### ISSUE TITLE
Add detection for popcnt

### ISSUE THREAD

**Issue by glinscott** [glinscott/fishtest#1]
Re-enable x86-64-modern builds, but need to detect popcnt on clients.

**Comment by niklasf** [comment]
This is what we use for the Stockfish cluster on lichess: https://gist.github.com/niklasf/a33a7405f88fbc7a27f0bd6f33a73678 (excerpt from https://github.com/niklasf/fishnet)

**Comment by linrock** [comment]
`x86-64-modern` is enabled for 64-bit systems by default by now:
https://github.com/glinscott/fishtest/blob/master/worker/games.py#L45

Maybe there's value in detecting whether `x86-64-bmi2` can be used?

**Comment by ppigazzini** [comment]
The worker setup scripts write the fitting `custom_make.txt`, so this is a low priority issue
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Linux
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows

```bash
# find the CPU architecture
# CPU without popcnt and bmi2 instructions (e.g. older than Intel Sandy Bridge)
arch_cpu=x86-64
# CPU with bmi2 instruction (e.g. Intel Haswell or newer)
if [ "$(g++ -Q -march=native --help=target | grep mbmi2 | grep enabled)" ] ; then
  # CPU AMD zen
  if [ "$(g++ -Q -march=native --help=target | grep march | grep 'znver[12]')" ] ; then
    arch_cpu=x86-64-modern
  else
    arch_cpu=x86-64-bmi2
  fi
# CPU with popcnt instruction (e.g. Intel Sandy Bridge)
elif [ "$(g++ -Q -march=native --help=target | grep mpopcnt | grep enabled)" ] ; then
  arch_cpu=x86-64-modern
fi
echo "make -j profile-build ARCH=${arch_cpu} COMP=mingw" > ${fish_path}/worker/custom_make.txt
```

**Comment by ppigazzini** [comment]
Closing because the worker now detects the CPU architecture, see
https://github.com/glinscott/fishtest/pull/738
