### ISSUE TITLE
Wrong bench

### ISSUE THREAD

**Issue by SFisGOD** [glinscott/fishtest#1006]
![image](https://user-images.githubusercontent.com/38142170/131214889-48c5f3f3-794c-478a-8bc1-a16fe45e965b.png)
![image](https://user-images.githubusercontent.com/38142170/131215122-89b4ebf3-08df-4209-9392-c84995c2c128.png)
![image](https://user-images.githubusercontent.com/38142170/131215134-58d0f289-cc13-4b04-9b13-9548011cd956.png)

Tests get stopped when tvijlbrief worker is assigned to a test
@ppigazzini

**Comment by tomtor** [comment]
My worker looks ok bit I will stop it if there is a real issue.

Op za 28 aug. 2021 12:26 schreef Jonathan D. ***@***.***>:

**Comment by Sopel97** [comment]
what cpu arch is the worker

**Comment by SFisGOD** [comment]
![image](https://user-images.githubusercontent.com/38142170/131225913-e4827e86-c699-488d-9050-6f5a7002a3f5.png)

**Comment by Sopel97** [comment]
So we can rule out the NNUE related code as it's the same as for the the BMI2 workers and they are fine. Possibly a hardware issue?

**Comment by tomtor** [comment]
I have a ryzen 1700 and 3950 worker

Op za 28 aug. 2021 19:41 schreef Tomasz Sobczyk ***@***.***>:

**Comment by tomtor** [comment]
14 cores is the 1700

Op za 28 aug. 2021 22:14 schreef Tom Vijlbrief ***@***.***>:
