### ISSUE TITLE
When no games have been played WDL statistics are shown on main test page

### ISSUE THREAD

**Issue by QuackQuackBlah** [glinscott/fishtest#1015]
<img width="1268" alt="Screen Shot 2021-09-05 at 2 24 31 PM" src="https://user-images.githubusercontent.com/77398316/132142117-eca6a39f-18e2-4a8c-b343-5e89c485fce7.png">

I believe the way to fix this (if it is indeed a real issue) can be found in a [branch](https://github.com/glinscott/fishtest/commit/38452ee2f90f9dbb94b9402d450a1d013254e276) I just made (I can create PR for it if needed)

**Comment by vdbergh** [comment]
I just fixed this (the reason for this cosmetic issue is that when pentanomial statistics were introduced the worker update was broken, so the switch to pentanomial was initiated by the worker, not the server). I will make a PR later.
