### ISSUE TITLE
Exception from calling heartbeat

### ISSUE THREAD

**Issue by Dark42ed** [glinscott/fishtest#1023]
So I recently popped up fishtest on my Linux machine and saw this:
```
Exception from calling heartbeat:
Expecting value: line 1 column 1 (char 0)
```
Fishtest continues to do games, and after the error appears 3 times, it says it successfully made a heartbeat 3 times in a row.
My code to run fishtest is just cloning the repo and running `python3 fishtest/worker/worker.py [username] "[password]" --use_all_cores True`, so I don't know what could be wrong. [Here](https://pastebin.com/cPpDwqSY) is the full log if you need it. It's using worker version 107 (as stated in the logs)

**Comment by Dark42ed** [comment]
Hmmm, seems like after it got a new task the error stopped popping up.

**Comment by ppigazzini** [comment]
That exception is raised only by this simple code, should be a temporary networking problem. Keep monitored a bit your worker and post some update.

https://github.com/glinscott/fishtest/blob/ee165e865139e94ed93b02296d18192ce2f7d357/worker/worker.py#L147-L158

**Comment by Dark42ed** [comment]
Thanks! Closing this as it isn't a problem (and is fixed).
