### ISSUE TITLE
Sometimes tasks get many more cores than they seem entitled to.

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1027]
The fishtest algorithm tries to keep  `cores/itp` constant over all runs, by assigning a new task to the run with the lowest value for `cores/itp`. (`itp` is initialized by `throughput` and then adjusted according to the type of test, tc, llr and threads but this is not important here).

 Unfortunately sometimes tasks get many more cores than they seem entitled to by this algorithm, e.g.

![cores](https://user-images.githubusercontent.com/6613103/133055172-a6c69f1c-ebd7-43d9-bb2a-da3d9886682f.png)

The screenshot does not show the itp values, but the for the second and third task they are ~ 100. So the second task certainly has too many cores.

Perhaps there is something about the algorithm that I do not understand? 

EDIT. I thought that perhaps the 3d task is hit by the core limit `40000 / math.sqrt(len(run["args"]["spsa"]["params"]))` but AFAICS this is not the case.

**Comment by ppigazzini** [comment]
Ongoing discussion here #1026

**Comment by vdbergh** [comment]
Why doesn't this 10+0.1 tune at priority 400 get any noob workers?

https://tests.stockfishchess.org/tests/view/61438983171fa5e08b4ec554

**Comment by ppigazzini** [comment]
> Why doesn't this 10+0.1 tune at priority 400 get any noob workers?
> 
> https://tests.stockfishchess.org/tests/view/61438983171fa5e08b4ec554

If I'm not worng noob workers have a memory problem and that test has "Hash=128"

**Comment by ppigazzini** [comment]
Yes, noob's workers should be still memory bounded, see
https://discord.com/channels/435943710472011776/813919248455827515/886505544691621899
https://discord.com/channels/435943710472011776/813919248455827515/886516465816174612

**Comment by vdbergh** [comment]
> > Why doesn't this 10+0.1 tune at priority 400 get any noob workers?
> > https://tests.stockfishchess.org/tests/view/61438983171fa5e08b4ec554
> 
> If I'm not wrong noob's workers have a memory problem and that test has "Hash=128"

Ah ok. Thanks!
