### ISSUE TITLE
free/malloc like algorithm for openings...

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1030]
Here is  a programming challenge...

Currently every task gets assigned a segment in the sequence of openings. If the task is not completed then part of this segment is wasted (since the task no longer migrates to a new worker).

A more sophisticated algorithm should be able to reclaim a lot of this wasted space by fitting new segments in the holes that are left by uncompleted tasks.

The free/malloc analogy is not perfect, but the problem feels similar.

**Comment by vondele** [comment]
I don't think we should really care about the wasted segments, most workers complete the task, and in almost all cases we have enough openings in the book

**Comment by vdbergh** [comment]
Well if I counted correctly then in this test there are 12 empty 464 games tasks.

https://tests.stockfishchess.org/tests/view/613f18edc02e4d540b78d71b

I agree that with the current huge book this is not a problem, but still it seems wasteful. And currently we have no control over how much space is wasted (it could easily be more). 

Anyway I agree it is not urgent but it would be nice to have and someone might find it fun to program it.
