### ISSUE TITLE
Test page no longer highlights active workers

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#1052]
The rows of the active workers of a test used to be highlighted in blue in each test page. 

This no longer seems to be the case, for instance:
https://tests.stockfishchess.org/tests/view/6154029150986fceb8bd015b

**Comment by ppigazzini** [comment]
Bug in light theme, dark theme works fine for me.

**Comment by ppigazzini** [comment]
Applied #1053 as temporary fix to PROD, hoping it's not terribly wrong, please @linrock at your convenience have a check :)

**Comment by ppigazzini** [comment]
boostrap 2.3.2 - table - optional row classes: `<tr class="info">`
https://getbootstrap.com/2.3.2/base-css.html#code

bootstrap 5.1.1 - table - variants - on row: `<tr class="table-info">...</tr>`
https://getbootstrap.com/docs/5.1/content/tables/

**Comment by snicolet** [comment]
Thanks :)

**Comment by linrock** [comment]
> PROD updated with #1053 as temporary fix (copied from theme.dark.css), hoping it's not terribly wrong, please @linrock at your convenience have a check :)

lgtm!

**Comment by ppigazzini** [comment]
Fixed by #1053, thank you @linrock :)
