### ISSUE TITLE
Some workers getting "SSL: CERTIFICATE_VERIFY_FAILED" message

### ISSUE THREAD

**Issue by crossbr** [glinscott/fishtest#1056]
Some workers getting "SSL: CERTIFICATE_VERIFY_FAILED" message. See [here](https://groups.google.com/g/fishcooking/c/9PtMh93Us6w/m/Ug1uBEE7AwAJ) in Fishcooking.

**Comment by vondele** [comment]
I wonder if this is related https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/

**Comment by vondele** [comment]
so, it is almost certainly related and it looks like this needs to be solved on the client side, i.e. clients need to be updated to trust the new ISRG Root X1 ? 

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

It's not clear to me how these clients can make this happen?

**Comment by d3vv** [comment]
`./worker.sh
Worker started in /home/dew/fishtest/worker ...

Memory: 25271816192
Found g++ version 10.2
Worker version 108 connecting to https://tests.stockfishchess.org:443
UUID: 2d9337c5-6db7-4fdf-b3ea-a66ec740a53f
Start heartbeat
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'resource': 'core', 'reset': 1633052045, 'used': 0}
Exception accessing host:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'resource': 'core', 'reset': 1633052070, 'used': 0}
Exception accessing host:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
Exception from calling heartbeat:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
  Send heartbeat for 2d9337c5-6db7-4fdf-b3ea-a66ec740a53f ... Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'resource': 'core', 'reset': 1633052157, 'used': 0}
Exception accessing host:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
Exception from calling heartbeat:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
Exception from calling heartbeat:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
  Send heartbeat for 2d9337c5-6db7-4fdf-b3ea-a66ec740a53f ...   Send heartbeat for 2d9337c5-6db7-4fdf-b3ea-a66ec740a53f ... Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'resource': 'core', 'reset': 1633052236, 'used': 0}
Exception accessing host:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
Exception from calling heartbeat:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)`

**Comment by ppigazzini** [comment]
@d3vv if you are not able to update some of your linux distribution then you can run the worker with http:
```
${virtual_env}/bin/python3 worker.py <your_user_name> <your_password> --protocol http --host tests.stockfishchess.org --port 80 --concurrency <number_of_thhreads>
```

**Comment by gvreuls** [comment]
Perhaps get a real SSL provider who doesn't demonstrate they only care about browser traffic? Demanding of people to rip out a vital part of their cryptography/security infrastructure and replace it  to access websites is a major no-go and the people who wrote such stupid and dangerous advise should get fired on the spot.

**Comment by ppigazzini** [comment]
> Perhaps get a real SSL provider who doesn't demonstrate they only care about browser traffic? Demanding of people to rip out a vital part of their cryptography/security infrastructure and replace it to access websites is a major no-go and the people who wrote such stupid and dangerous advise should get fired on the spot.

People that don't care to keep up to date old OS don't care at all about security :D

**Comment by ppigazzini** [comment]
https://en.wikipedia.org/wiki/Let%27s_Encrypt

The damn tech noobies sponsoring Let's Encrypt :D

```
Let's Encrypt is a non-profit certificate authority run by Internet Security Research Group (ISRG) that provides X.509 certificates for Transport Layer Security (TLS) encryption at no charge. It is the world's largest certificate authority,[2] used by more than 265 million websites,[3] with the goal of all websites being secure and using HTTPS. The Internet Security Research Group (ISRG), the provider of the service, is a public benefit organization.[4] Major sponsors include the Electronic Frontier Foundation (EFF), the Mozilla Foundation, OVH, Cisco Systems, Facebook, Google Chrome, Internet Society, AWS, NGINX, and Bill and Melinda Gates Foundation.[5] Other partners include the certificate authority IdenTrust,[6] the University of Michigan (U-M),[7] and the Linux Foundation.[8].

Overview

The mission for the organization is to create a more secure and privacy-respecting World-Wide Web by promoting the widespread adoption of HTTPS.[9] 
```

**Comment by ppigazzini** [comment]
@gvreuls my post here on GitHub was to @d3vv that know what is SSL, this is the post in the forum for non tech people.
https://groups.google.com/g/fishcooking/c/9PtMh93Us6w/m/xka_VfprAwAJ

> For the users not able to update the OS there is the possibility to run the worker without SSL, please mind that the data will be not encrypted.

**Comment by gvreuls** [comment]
> > Perhaps get a real SSL provider who doesn't demonstrate they only care about browser traffic? Demanding of people to rip out a vital part of their cryptography/security infrastructure and replace it to access websites is a major no-go and the people who wrote such stupid and dangerous advise should get fired on the spot.
> 
> People that don't care to keep up to date old OS don't care at all about security :D

@ppigazzini I'm running Fedora Core 33 which was released less than a year ago (October 20, 2020) and is still fully supported, when was your favorite OS released? ;)

**Comment by ppigazzini** [comment]
> > People that don't care to keep up to date old OS don't care at all about security :D
> 
> @ppigazzini I'm running Fedora Core 33 which was released less than a year ago (October 20, 2020) and is still fully supported, when was your favorite OS released? ;)

You are right!
People that don't care to run an upstream distribution don't care at all about security too :D

Just joking: I'm hoping that Fedora Core 33 hasn't this OpenSSL problem too.

**Comment by ppigazzini** [comment]
@vondele I reproduces the problem on WSL2 Ubuntu 20.04, the problem seems due to the very old "requests" package shipped by fishtest
https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

On "true" Ubuntu 20.04 this not happen.

Some days ago I triggered the workers update with #1017 PR that:
 - try to import the system "requests" package
 - in case of failure use the new "requests" package shipped in the "packages" directory

The old "requests" package is still there ("requests" directory) because I'm testing a safe update process.

To make a long story short, the simple solution could be to ask the affected user to rename the "requests" directory to "_requests". If this solves the problem that directory can be deleted.

**Comment by ppigazzini** [comment]
@d3vv please rename the "worker/requests" directory (eg "worker/_requests") and report here if the worker runs fine on https

**Comment by d3vv** [comment]
@ppigazzini Thank You for suggestions.. I'm Under Pressure and have no time.. Maybe after weekend :(

**Comment by ppigazzini** [comment]
No problem :)

**Comment by gvreuls** [comment]
> @d3vv please rename the "worker/requests" directory (eg "worker/_requests") and report here if the worker runs fine on https

@ppigazzini I'm not @d3vv but I can confirm that this works (and not just for Ubuntu as I'm running Fedora Core).

Thanks!

**Comment by ppigazzini** [comment]
> @ppigazzini I'm not @d3vv but I can confirm that this works (and not just for Ubuntu as I'm running Fedora Core).
> 
> Thanks!

It turns out that was a fishtest problem :)

**Comment by ppigazzini** [comment]
172 workers running without the old "requests" packages :)

**Comment by gvreuls** [comment]
@ppigazzini You see now why "rip out your SSL package and update it manually" is such bad advice? Usually it's another problem and once you have removed your SSL package you now have two problems.instead of solving one ;)

**Comment by ppigazzini** [comment]
@gvreuls I'm wondering how asking people to update the OS can be interpreted as "rip out your SSL package"...

The 99% of the workers were problem free (I wasn't able to reproduce the problem on Ubuntu 20.04) so IMO the old "requests" package was able to read the updated root certificates from the system.

Feel free to contribute PRs to improve fishtest :)

**Comment by ppigazzini** [comment]
@gvreuls IMO the proper way to run the worker is with a python virtual environment. In this way the user can update from time to time the "requests" packages group with `env/bin/python3 - pip install --upgrade requests`

The new "requests" package shipped with fishtest is the second last, but the last one can't work with python older than 3.5 because requires "typing" module, so not easy to kept it up to date.

**Comment by gvreuls** [comment]
> @gvreuls I'm wondering how asking people to update the OS can be interpreted as "rip out your SSL package"...

@ppigazzini I'm not criticizing you, I'm having an issue with the good folks at Let's Encrypt for putting up the advice to upgrade OpenSSL if their new root certificate gets rejected. While technically correct, it might encourage normal users with not enough know-how to attempt manually upgrading a vital security package like OpenSSL.
