### ISSUE TITLE
show memory limit for machines.

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#1131]
Maybe the machine overview could show the memory limit ? 

Right now we know noob's workers can't run LTC tests because of that, but it would be nice to see the actual amount of mem available.

**Comment by ppigazzini** [comment]
ChessDBCN | 8 | 79f2292d | 1.05 | os: Linux 3.10.0-1160.45.1.el7.x86_64; ram: 1834 | 124:3.6.8 | cnCaptExt1 | seconds ago
-- | -- | -- | -- | -- | -- | -- | --
ChessDBCN | 16 | ad5146a3 | 1.21 | os: Linux 3.10.0-1160.45.1.el7.x86_64; ram: 3072 | 124:3.6.8 | cnCaptExt1 | seconds ago
