### ISSUE TITLE
Wrong architecture for raspberry PI?

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1144]
From the current action log:
```
failed task: task_id: 41, worker: Malarksist-1cores-1cddbb4d, reason: 'Executing make COMP=gcc ARCH=x86-64 -j 1 profile-build failed. Error: ['g++: error: unrecognized command line option ‘-m64’\n', 'g++: error: unrecognized command line option ‘-msse’\n', 'g++: error: unrecognized command line option ‘-msse2’\n', 'g++: error'
```
The machine is a raspberry PI. See https://github.com/Level/leveldown/issues/359 .

**Comment by vondele** [comment]
OK, RPI is not supported, only x86. One reason is the cutechess-cli binary. 

That should be something we catch earlier.

**Comment by vdbergh** [comment]
Ok. Thanks. It seems that the check for `cutechess_cli` is done after building SF. That is indeed weird.

**Comment by vondele** [comment]
well we download cutechess-cli from the books repo, but there are no binaries for RPI. At this point, I think we should detect we're not on x86 and stop in that case. Unless we have a good reason to maintain other architectures (mac ARM, RPI come up from time to time, but realistically, there won't be significant resources contributed in this way, I think).

**Comment by vdbergh** [comment]
I meant that in the worker we could just as well do the check for a working `cutechess_cli` before building SF. I am testing this.

**Comment by vdbergh** [comment]
Mitigated by d161f65c27f3da933b34fadbffbd98414ef238fa .
