### ISSUE TITLE
Failed to find cutechess version info

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1151]
This error happens regularly. E.g.

https://tests.stockfishchess.org/actions?count=1&before=1636124444.511

What could be the cause?

**Comment by vondele** [comment]
this would mean a non-zero return code from running cutechess-cli. Unclear to me how that could happen.

**Comment by ppigazzini** [comment]
- first event
https://tests.stockfishchess.org/actions?count=1&before=1636121271.003
https://tests.stockfishchess.org/tests/view/6184f198d7a085ad008eef75

Idx | Worker | Info | Last Updated | Played | Pentanomial [0‑2] | Crashes | Time | Residual
-- | -- | -- | -- | -- | -- | -- | -- | --
190 | technologov-12cores-0dd676a5 | os: Windows 10; ram: 32724MiB; gcc: 11.2.0; arch: ? | 2021-11-05 14:07:50 | 000 / 352 | [0, 0, 0, 0, 0] | - | - | -

- second event
https://tests.stockfishchess.org/actions?count=1&before=1636124444.511
https://tests.stockfishchess.org/tests/view/61847a52d7a085ad008eef48

Idx | Worker | Info | Last Updated | Played | Pentanomial [0‑2] | Crashes | Time | Residual
-- | -- | -- | -- | -- | -- | -- | -- | --
923 | technologov-12cores-5da95637 | os: Windows 10; ram: 32724MiB; gcc: 11.2.0; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2021-11-05 14:51:33 | 056 / 056 | [0, 13, 7, 8, 0] | 0 | 0 | 3.229
949 | technologov-12cores-5da95637 | os: Windows 10; ram: 32724MiB; gcc: 11.2.0; arch: ? | 2021-11-05 15:00:43 | 000 / 056 | [0, 0, 0, 0, 0] | - | - | 3.229

**Comment by vdbergh** [comment]
Perhaps it is due to a missing dll?

**Comment by ppigazzini** [comment]
`cutechess-cli.exe` on Windows is a static build, in the second event finished the first task at 14:51:33 and failed the second task at 15:00:43 , 9 minutes seem to be disappeared, but I don't know the "Last Updated" event though.

Deleting the `testing` folder while the worker is running doesn't trigger an error.

**Comment by vdbergh** [comment]
Well I made a PR. Perhaps the error messages will clarify things. 

> Deleting the testing folder while the worker is running doesn't trigger an error.

I guess this is an unrelated comment? Is this on Windows or Linux? On Linux I would not be terribly surprised by this since you can delete files that are in use.

**Comment by ppigazzini** [comment]
I'm testing a msys2 windows worker, like the problematic one (it's a msys2 up to date), at the moment it's inactive.

**Comment by kotenok2000** [comment]
My cutechess crashes
[CrashDumps.zip](https://github.com/glinscott/fishtest/files/7556094/CrashDumps.zip)

**Comment by ppigazzini** [comment]
The files in the archive have .exe extension, so I suppose you are using the windows worker installed with the official setup.
In this case I suggest to:
 - update msys2 downloading the latest setup script and running `04_update_msys2_choco_admin.cmd` as administrator, see https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows#windows-10-and-windows-8-instructions 
 - delete the `worker\testing\cutechess.exe`, the worker will download the latest version
 - start the worker

**Comment by kotenok2000** [comment]
Turns out i had ansicon iinstalled and cutechess didn't agree with it
https://github.com/adoxa/ansicon
