### ISSUE TITLE
profile corruption

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1154]
In this build we see profile corruption

https://tests.stockfishchess.org/actions?count=1&before=1636295582.974

Perhaps this is caused by the multithreaded build? See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88608 .

The suggested fix seems to be `-fprofile-update=atomic` .

**Comment by vondele** [comment]
even if the build is multi-threaded the search runs single-threaded. These two are unrelated.

However we do have more than 1 thread always (uci and search threads). I've never ever seen corruption though.

**Comment by vondele** [comment]
```
-fprofile-update=method

    Alter the update method for an application instrumented for profile feedback based optimization. The method argument should be one of ‘single’, ‘atomic’ or ‘prefer-atomic’. The first one is useful for single-threaded applications, while the second one prevents profile corruption by emitting thread-safe code.

    Warning: When an application does not properly join all threads (or creates an detached thread), a profile file can be still corrupted.

    Using ‘prefer-atomic’ would be transformed either to ‘atomic’, when supported by a target, or to ‘single’ otherwise. The GCC driver automatically selects ‘prefer-atomic’ when -pthread is present in the command line.
```
so it seems (recent?) gcc automatically uses prefer-atomic if pthread is on the command line (which we have depending on OS).  

Can we figure out which gcc/OS this worker has?

**Comment by vdbergh** [comment]
> Can we figure out which gcc/OS this worker has?

Yes by looking at the corresponding task: gcc: 10.3.1 . Seems recent enough.  I guess this is another one of these mysterious non-reproducible build failures.

**Comment by vdbergh** [comment]
The os is Linux 5.14.15-100.fc33.x86_64 (Fedora Core 33 I assume). Also pretty vanilla.

**Comment by vondele** [comment]
so, -fprofile-update=prefer-atomic is available since gcc 7.5 at least, so I think we could add it. However, it should be the default for gcc 10.3 on fedora: https://gcc.gnu.org/onlinedocs/gcc-10.3.0/gcc/Instrumentation-Options.html#Instrumentation-Options so it won't matter.

**Comment by vdbergh** [comment]
Another one: https://tests.stockfishchess.org/actions?count=1&before=1636320509.289  os: Linux 4.19.0-17-amd64; gcc: 8.3.0.

**Comment by vdbergh** [comment]
I wonder if these strange errors are not caused by killing the worker in some unfortunate way. I don’t really see it but…
