### ISSUE TITLE
Update fishtest code to use pymongo 4.x

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#1176]
`pymongo 4.x` drop all the APIs already deprecated in `pymongo 3.x`
References:
https://pymongo.readthedocs.io/en/stable/changelog.html
https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html
https://www.mongodb.com/docs/drivers/pymongo/

**Comment by ppigazzini** [comment]
Errors found on DEV with `pymongo 4.x`:
1.
```
File "/home/usr00/fishtest/server/fishtest/userdb.py", line 77, in add_user_group
    self.users.save(user)
  File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pymongo/collection.py", line 2584, in __call__
    raise TypeError("'Collection' object is not callable. If you meant to "
TypeError: 'Collection' object is not callable. If you meant to call the 'save' method on a 'Collection' object it is failing because no such method exists.
```
2.
```
File "/home/usr00/fishtest/server/fishtest/rundb.py", line 470, in get_finished_runs
    count = c.count()
AttributeError: 'Cursor' object has no attribute 'count'
```

**Comment by ppigazzini** [comment]
Tentative solutions:
1.
https://github.com/glinscott/fishtest/blob/593c3d4004a190ee6bd75bf0b2de5c0be309f2d9/server/fishtest/userdb.py#L74-L77

```python
        self.users.replace_one({'_id': user['_id']}, user)
```

2.
https://github.com/glinscott/fishtest/blob/593c3d4004a190ee6bd75bf0b2de5c0be309f2d9/server/fishtest/rundb.py#L480-L485
```python
 else: 
     # Otherwise, the count is slow 
     count = self.runs.count_documents(q)
```

**Comment by vdbergh** [comment]
Both seems fine. Luckily soon the counting of runs will no longer be necessary.

**Comment by ppigazzini** [comment]
I need to review the `delta_update_users.py` changes in #902
