### ISSUE TITLE
g++ version issue

### ISSUE THREAD

**Issue by mahdi** [glinscott/fishtest#1180]
Hi,

I'm trying to run the fishtest on my Mac but keep receiving the following error:

Found g++ version 4.2.1
Please update to g++ version 7.3 or later

Tried to update gcc using brew and developer tools are updated too. 

Any idea how to resolve this issue?

**Comment by ppigazzini** [comment]
I'm not a Mac user, this is the wiki page to setup a recent gcc:
https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-macOS

To run fishtest then you need also a recent `cutechess-cli`, you can try these instructions to build yourself:
https://github.com/glinscott/fishtest/issues/13

fishtest could need some update to run easily on Mac, but we need the collaboration of some Mac users to test the development.

**Comment by vdbergh** [comment]
If you do `g++ --version` in the terminal, what do you get?

**Comment by ppigazzini** [comment]
@mahdi we have updated fishtest to setup the worker and run it smoothly on macOS with either Intel CPU or Apple CPU. You can use either `clang++` from Apple Xcode or `g++` from brew. I updated the macOS wiki page (but I have not a mac, so I'm not able to test the instructions).
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-macOS

**Comment by mahdi** [comment]
Thank you! I'll give it a try 👍
