### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by crossbr** [glinscott/fishtest#1193]
I'm getting "504 Gateway Time-out" on fishtest.

**Comment by vdbergh** [comment]
There should be some way to protect Fishtest from (unintentional) DOSing. I wonder if this can be done at the nginx level?

**Comment by vondele** [comment]
as discussed on discord, a possible issue was a python upgrade on the server yesterday, that seemingly lead to high load on one of the server processes. This has now been reverted.
