### ISSUE TITLE
gcc 7.5.0 no longer sufficient?

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1199]
See https://tests.stockfishchess.org/actions?action=&user=&before=1639803678.375&count=100 .

**Comment by vondele** [comment]
seemingly that functionality is not available in g++-7 nor g++-8, it is a recent feature https://en.cppreference.com/w/cpp/algorithm/for_each_n 
Now, I don't think we should drop support for g++-8 and probably not for g++-7

**Comment by mstembera** [comment]
std::for_each_n() can always be easily replaced with std::for_each() w/ only a minor change to parameters so agree it shouldn't be a reason to drop g++ 7 or 8.
