### ISSUE TITLE
Replacing cutechess-cli on macOS with Linux binaries

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#1209]
```
Exception running games:
Unable to run cutechess-cl. Error: [Errno 8] Exec format error: './cutechess-cli'
Informing the server
Heartbeat stopped
Post request https://tests.stockfishchess.org:443/api/failed_task handled in 0.941408s (server: 0.115966s)
Task exited
Waiting for the heartbeat thread to finish...
Deleting lock file /Users/prepper/fishtest/worker/worker.lock
```

Could it possible to avoid rewriting Cute Chess with Linux binaries for Darwin kernel?

**Comment by ppigazzini** [comment]
We need collaboration from a MacOS user:
 - information to detect the MacOS system: if I recall correctly in ARCH there is the string "darwin"
 - a copy of MacOS's `cutechess-cli` (hopefully adding the the build instruction to the wiki)

The update process however rename the `testing` folder to enable the update of book, cutechess-cli, and to preserve custom `cutechess-cli` build:
https://github.com/glinscott/fishtest/blob/e2f28925950c0e7210f08bc3a8df0e808d417fd1/worker/updater.py#L60-L62

**Comment by d3vv** [comment]
@ppigazzini I don't know about ARCH, but:

**Comment by d3vv** [comment]
As for simple Instruction:
Install macports from https://www.macports.org/

sudo port install gcc11
sudo port install qt5
sudo port install gcc_select 

```
% port select --list gcc
Available versions for gcc:
	mp-gcc11 (active)
	none
sudo port select --set gcc mp-gcc11
```

Then compile cutechess project as usually

**Comment by ppigazzini** [comment]
#1211 should solve the issue, tested with a linux worker. It will start working after the next worker update, though.

**Comment by ppigazzini** [comment]
PROD updated, with worker version >= 143 you shouldn't babysitting anymore your MacOS worker, finger crossed.

**Comment by vdbergh** [comment]
Could we maybe upload d3vv cutechess' binary to the repository, so that this can be handled in the normal way?

**Comment by vdbergh** [comment]
I don't know how portable MacOS binaries are. I guess it should preferably be a statically compiled binary.

**Comment by ppigazzini** [comment]
Solved by:
https://github.com/official-stockfish/books/pull/26
https://github.com/glinscott/fishtest/pull/1251
