### ISSUE TITLE
Https connection problem on Proxied internet Windows 10

### ISSUE THREAD

**Issue by jobs-git** [glinscott/fishtest#123]
As the title implies, i get connection timed out even when proxy is assigned to paths.

Here is the error message:

```
Exception running games:
Traceback (most recent call last):
  File "worker\worker.py", line 88, in worker
  File "C:\fishtest-master\worker\games.py", line 383, in run_games
    setup_engine(new_engine, binaries_url, worker_dir, run['args']['resolved_new'], repo_url, worker_info['concurrency'])
  File "C:\fishtest-master\worker\games.py", line 152, in setup_engine
    build(worker_dir, sha, repo_url, destination, concurrency)
  File "C:\fishtest-master\worker\games.py", line 115, in build
    f.write(requests.get(github_api(repo_url) + '/zipball/' + sha, timeout=HTTP_TIMEOUT).content)
  File "C:\fishtest-master\worker\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\fishtest-master\worker\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\fishtest-master\worker\requests\sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "C:\fishtest-master\worker\requests\sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "C:\fishtest-master\worker\requests\adapters.py", line 215, in send
    raise Timeout(e)
Timeout: HTTPSConnectionPool(host='api.github.com', port=443): Request timed out. (timeout=5.0)
Task exited
```

**Comment by jobs-git** [comment]
I Solved it now! The issue was that fishtest needs recompiling from master! In case other encouter the same problem, here is what I did to solve it.

1. Install Python 2.7 32-bit.
2. Download Fishtest master
3. Download Fishtest portable, just google it
4. Extract both archives.
5. Add paths for Python and MingGW (From fishtest portable)
6. Inside the worker folder of fishtest master, add a text file named: custom_make.txt
7. Inside the cutom_make.txt add: make profile-build ARCH=x86-64-bmi2 COMP=mingw
8. Then run: python worker.py --concurrency 1 username password
9. The fishtest will recompile, after compilation just delete the custom_make.txt so it wont recompile again.

**Comment by ppigazzini** [comment]
From the log your worker had simply a connection problem: the worker started to work again when the connection was re established.
Your second post is not the solution of the problem and has a wrong step: MinGW-w64 is used to compile the engines for all the tests, so you need **to keep the file custom_make.txt**.  Check the [wiki instruction](https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows) to make a proper manual installation/configuration on Windows.
