### ISSUE TITLE
NUMA workers often are red for fish-tests

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#1238]
But.. Why?
All I see is that very often one NUMA node is heavy loaded more than another from the start.

**Comment by d3vv** [comment]
It looks like:

![image](https://user-images.githubusercontent.com/32866346/148998687-1aaed5cb-c6d1-482c-9119-8564ec1cc66b.png)

And nothing changes if I greatly reduce the number of workers (less than real cores w/o hyper threading)

**Comment by d3vv** [comment]
And this is an absolutely typical situation during tests:

![image](https://user-images.githubusercontent.com/32866346/149000754-a1aecff2-33f2-43a7-b19d-041205ee2a0e.png)

**Comment by Technologov** [comment]
Is this problem Windows-only, or does it also occur on Linux and Mac ?

**Comment by vondele** [comment]
as far as I know this is not something that happens on Linux.

**Comment by d3vv** [comment]
> as far as I know this is not something that happens on Linux.

it's all about windows threads philosophy and NUMA ideology realization

**Comment by ppigazzini** [comment]
On my workstation (Windows 11 WIP) fishtest has a Numa balanced load with msys2 and an unbalanced one with WSL:
- msys2

![Untitled-msys2-2](https://user-images.githubusercontent.com/15718418/151798795-073f77a1-4d13-49e7-8c58-4f49ca486d21.jpg)
![Untitled-msys2](https://user-images.githubusercontent.com/15718418/151798799-f1c15c29-b423-4526-9558-5c06c8b4aad9.jpg)


- WSL:

![Untitled-wsl](https://user-images.githubusercontent.com/15718418/151798505-193b4ee6-7534-4085-bc8c-6db88ea24feb.jpg)
![Untitled-wsl-2](https://user-images.githubusercontent.com/15718418/151798517-8f2de4c9-446e-4642-b989-ff4818746712.jpg)
