### ISSUE TITLE
completed test not finished

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#1247]
This simpDraw test is not flagged as completed despite an LLR that is -3.81.

![image](https://user-images.githubusercontent.com/4202567/149638012-03571102-5aab-4e7c-bf79-8662080169d3.png)

![image](https://user-images.githubusercontent.com/4202567/149638030-e5e95c36-8061-475b-91c9-f16b863670de.png)

**Comment by vdbergh** [comment]
Looks like a bug to me… Purging is a mess. Various things should be refactored.

**Comment by vdbergh** [comment]
I found it. The test was stopped manually after purging. Then the state is currently not updated. The code assumes that the test will be rescheduled and then update_task takes care of it.

Not so obvious how to handle this cleanly.

**Comment by vondele** [comment]
I stopped it manually after making the screenshots, and I got the job from its paused state (prio -1) to active by rescheduling

**Comment by vdbergh** [comment]
> I stopped it manually after making the screenshots, and I got the job from its paused state (prio -1) to active by rescheduling

Yes but I do not think it received any update_task before it was stopped.

BTW I checked that purge_run clears the sprt state, regardless of the LLR. I understand why that’s done, but it is not the right thing.

**Comment by vdbergh** [comment]
The issue with current code is that sometimes you want purge_run to call stop_run. But stop_run may itself call purge_run. That would create a messy spaghetti.

**Comment by vdbergh** [comment]
Hmm that’s not right. Purge_run can only be called when a run is already finished.

**Comment by vdbergh** [comment]
To test the hypothesis that it is due to the manual stop before `update_task()` had the time to look at it, you could revive the run with modify and let it evolve normally.

I know that relying on `update_task()` for stopping the purged run is rather ugly but with the current implementation of purging it seems to be the most elegant solution actually...

**Comment by vdbergh** [comment]
Ok I think I see how to fix it properly.
