### ISSUE TITLE
Fishtest server 504 

### ISSUE THREAD

**Issue by Def9Infinite** [glinscott/fishtest#1249]
Fishtest server seems to be down, receiving a 504 error constantly
![image](https://user-images.githubusercontent.com/34544962/149660408-38c896e9-f2b0-413a-bf18-1b95383b8abf.png)

**Comment by ppigazzini** [comment]
Already restarted mongodb some minutes ago, I suppose OOM kill during the DB backup, need to investigate.

**Comment by Def9Infinite** [comment]
Yep server is back available but the speed seems to be very slow

**Comment by dav1312** [comment]
> Yep server is back available but the speed seems to be very slow

![image](https://user-images.githubusercontent.com/63931154/149661413-340f686b-d56f-4da1-8a1f-0106dceb4d6c.png)

**Comment by ppigazzini** [comment]
Strange CPU load for pserve on port 6544, I rebooted the VPS:
```
  589 www-data  20      148872  11624   3624 S   0.4  0.2  25:30.52      `- nginx: worker process
 7108 fishtest  20     1109956 420432   5544 R  99.6  8.0  18:49.28  `- /home/fishtest/fishtest/server/env/bin/python3 /home/fishtest/fishtest/server/env/bin/pserve production.ini http_port=6544
 7130 fishtest  20     1576208 755368   6104 R  99.6 14.4 236:59.16  `- /home/fishtest/fishtest/server/env/bin/python3 /home/fishtest/fishtest/server/env/bin/pserve production.ini http_port=6543
13687 mongodb   20     3189860 1.311g  50096 S   2.5 26.2   0:22.54  `- /usr/bin/mongod --config /etc/mongod.conf
```

**Comment by ppigazzini** [comment]
Load now seems ok, thank you @Def9Infinite @dav1312 for the fast alerts.
