### ISSUE TITLE
fishtest can't be run on linux with /tmp noexec mount option

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#125]
$ mount|grep "/tmp"
shm on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime)

/tmp/tmpGOdCbf/locutus2-Stockfish-c5bcbd4/src $ ./stockfish
-bash: ./stockfish: Permission denied

**Comment by d3vv** [comment]
UPD. If /tmp is out of space or mounted with noexec option you could to use:

export TMPDIR=</path/to/my/temp/dir>

**Comment by Stefano80** [comment]
Is this a fishtest or a stockfish problem?

**Comment by d3vv** [comment]
Fishtest if fishtest-program try to compile sources and execute pgo into /tmp by default

**Comment by vondele** [comment]
The fishtest worker (games.py) uses ```tmp_dir = tempfile.mkdtemp()```

The python docs state that
```
 tempfile.mkdtemp([suffix=''[, prefix='tmp'[, dir=None]]])

    Creates a temporary directory in the most secure manner possible. There are no race conditions in the directory’s creation. The directory is readable, writable, and searchable only by the creating user ID.
```
There indeed no guarantee we can execute stuff there. We could do the build in 'fishtest/worker/testing' which we anyway need to be executable.

**Comment by tomtor** [comment]
This can be closed now?

**Comment by ppigazzini** [comment]
Yes
