### ISSUE TITLE
Windows msys2 workers - Error: "make: the '-j' option requires a positive integer argument"

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#1255]
Some Windows msys2 workers are showing this error.
https://tests.stockfishchess.org/actions?count=1&before=1642671548.51

```
Failed task: task_id: 76, worker: rpngn-5cores-9bd86a33, reason: 'Executing make COMP=mingw ARCH=x86-64-bmi2 -j 5 profile-build failed. Error: ["make: the '-j' option requires a positive integer argument\n", 'Usage: make [options] [target] ...\n', 'Options:\n', ' -b, -m Ignored for compatibility.\n', ' -B, --always-make Unconditionally make all targets.\n', ' -C DIRECTORY, --directory=DIRECTORY\n', ' Change to DIRECTORY before doing anything.\n', ' -d Print lots of debugging information.\n', ' --debug[=FLAGS] Print various types of debugging information.\n', ' -e, --environment-overrides\n', ' Environment variables override makefiles.\n', ' -E STRING, --eval=STRING Evaluate STRING as a makefile statement.\n', ' -f FILE, --file=FILE, --makefile=FILE\n', ' Read FILE as a makefile.\n', ' -h, --help Print this message and exit.\n', ' -i, --ignore-errors Ignore errors from recipes.\n', ' '
```

Information:
 - we have just merged this Windows workers PR https://github.com/official-stockfish/Stockfish/pull/3891 that adds also these improvements:
   1. enable the LTO build for mingw-w64 g++ compiler
   2. set `lto=auto` to use the make's job server, if available, or otherwise to fall back to autodetection of the number of CPU threads . BTW `lto=auto` didn't speedu
 - the affected workers seems to share a little outdated msys2 setup (gcc: 10.2.0; python: 3.8.9) wrt the up to date one  (gcc: 11.2.0; python: 3.9.7)
 - msys2 is a rolling distribution, not easy to have that msys2 setup to debug the issue
 - tested linking options on msys2:
   - `-flto=auto` : no speedup in linking time
   - `-flto=jobserver` : no speedup in linking time and `make -j 4` shows always the warning `lto-wrapper.exe: warning: jobserver is not available: '--jobserver-auth=' is not present in 'MAKEFLAGS'`
   - `-flto=N` : speedup in linking time (PGO build time from 66s to 50s with N=4 and to 40s with N=48 on a 48 threads CPU)
 
Solutions:
 - the Windows worker installer has a script to update msys2, instructions on the wiki:
   https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows#msys2

> 5. from time to time (suggested monthly) update Chocolatey and the MSYS2 packages:
>    1. download the up to date [worker setup archive](https://github.com/ppigazzini/worker-setup/archive/master.zip)
>    2. stop the worker
>    3. right click on `04_update_msys2_choco_admin.cmd`, select `Run as administrator`, approve if asked for. This requires a couple of minutes in a system updated regularly
>    4. start the worker
 - switch from `-flto=auto` to `-flto`

**Comment by vondele** [comment]
we also have this issue https://github.com/official-stockfish/Stockfish/issues/3897 which could indicate another issue

**Comment by ppigazzini** [comment]
I tested the `-flto=auto` with the Ubuntu 18.04 outdated mingw 7.3, anyway I'm fine to switch from `-flto=auto` to `-flto`

**Comment by ppigazzini** [comment]
Fixed by https://github.com/vondele/Stockfish/commit/77cf5704b6deda52171dafeb2fae370273ebd797
