### ISSUE TITLE
[feature] Add ability to setup CPU cores as a percentage of total (i.e. 50pct)

### ISSUE THREAD

**Issue by Technologov** [glinscott/fishtest#1265]
[fishtest-worker-CPU-pct.patch.txt](https://github.com/glinscott/fishtest/files/7962859/fishtest-worker-CPU-pct.patch.txt)

This is particulary useful for cloud usage, where one user could have a lot of different servers to manage with different capabilities.

**Comment by vdbergh** [comment]
A slightly more generic solution would be to allow expressions. E.g. `max-1`. For this one needs an expression parser. This one seems to work https://github.com/lhelwerd/expression-parser. This could also be used for memory. E.g. `max-memory=max/2`.

**Comment by vdbergh** [comment]
With #1266 one could write `--concurrency=0.75*max`. But also for example `--concurrency=max-3`.

**Comment by ppigazzini** [comment]
@Technologov done, you can use elaborated expression for concurrency and memory like:
```bash
env/bin/python3 worker.py --concurrency=max*0.75+1 --max_memory=max*0.53+1024
```
