### ISSUE TITLE
Allow more than 100 results in "Events" log

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#1284]

**Comment by vdbergh** [comment]
The event log is flooded by nps too low messages. It would be nice if this were resolved.

**Comment by vdbergh** [comment]
https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1649518086.6&count=100

I wonder if noob has been contacted about this? This is appears to be a case of a badly configured machine (since his machines usually get around 1Mnps). 

This flooding of the event log makes it unusable.

**Comment by ppigazzini** [comment]
cc @noobpwnftw

**Comment by vdbergh** [comment]
@noobpwnftw It is getting worse and worse. Often the entire event log is filled by “machine too slow messages” by ChessDBCN… https://tests.stockfishchess.org/actions?action=&user=&before=1649836779.341&count=100

**Comment by vdbergh** [comment]
A possible solution might be to change the meaning of `--fleet` slightly. I.e. let `--fleet` quit the worker only if there is no task available. 

Currently `--fleet` also quits the worker when there is an error. If the worker runs in a loop then it immediately restarts, possibly leading to flooding.

**Comment by ppigazzini** [comment]
Smart suggestion.

**Comment by dav1312** [comment]
Can't we use pagination here too?

**Comment by vdbergh** [comment]
> Can't we use pagination here too?

Yep!

**Comment by vdbergh** [comment]
Something I was also planning to implement is a free text search on the comment field (that would be very useful to search for errors of a specific type). This needs a text index on the comment field. I am currently very busy so if somebody else wants to do it... :)
