### ISSUE TITLE
Slow/Fast switch

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#129]
A common usage scenario is to run a STC test, and if it is green, 
a) user will reschedule the test
b) Click the Slow button
c) Submit

However step b) always overwrite the "sprt elo0" and "sprt elo1" to [0, 5]
which is unexpected behaviour if there were already some values
(especially if former STC test was a [0,4] or [3,1])

I think it would make more sense to move the Slow/Fast buttons at the right of the time control,
and have those two buttons only change the time control, and nothing else.

**Comment by ianfab** [comment]
@Rocky640 You are lucky: #116 was merged yesterday. The position can also be changed if that is preferred. I think that the hash should still automatically be changed, not only the time control.

**Comment by Rocky640** [comment]
Changing the hash is indeed a good thing for "SPRT" tests or "numgames" tests.

https://github.com/glinscott/fishtest/wiki/Creating-my-first-test
For SPSA tests, I would hide the slow/fast button since the time control would depend if the user goes with the "nodestime" method or not.
Also, for SPSA, most people use hash=128 for both STC and LTC

**Comment by ianfab** [comment]
I just tried out the changes and the change of the position of the buttons indeed makes usage more intuitive to me. However, hiding the buttons for SPSA can be annoying in some cases. E.g., I clicked on LTC, then switched to SPSA, and then wanted to change back to STC, but the buttons had disappeared, so I had to change it manually or switch back to SPRT first. Maybe not a very common case, but might still be a reason not to hide them.

**Comment by Rocky640** [comment]
OK.

**Comment by Stefano80** [comment]
May I close this rocky?

**Comment by Rocky640** [comment]
Sure, and congrats to you @ppigazzini and @ianfab for your work

**Comment by Stefano80** [comment]
Thanks!
