### ISSUE TITLE
Reset Fishtest Password

### ISSUE THREAD

**Issue by adyavanapalli** [glinscott/fishtest#1293]
# Summary

I've forgotten my fishtest password. Is there anyway to reset it?

Related issues: #675

**Comment by ppigazzini** [comment]
Let me know your username on fishtest, I can send you the password:
1. to the email written during the registration to fishtest
2. to a pm on our discord server (I'm @ppigazzini)
https://discord.gg/nv8gDtt

**Comment by adyavanapalli** [comment]
@ppigazzini Can you email it to me? My username is also `adyavanapalli` on Fishtest.

**Comment by ppigazzini** [comment]
Done.
