### ISSUE TITLE
ddos with test and strange behavior.

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#1299]
just summarizing some observations made in discord. The following test:
https://tests.stockfishchess.org/tests/view/620b4522170fcff54b33a7bf
behaves strangely:
* When it runs, the server is essentially ddos'ed . 
* Modifications to the state do not appear in the event log but happen (like stopping it, changing auto-purge, number of games)
* These modifications can lead to a server internal error

The test is similar to another one that doesn't show that behavior:
https://tests.stockfishchess.org/tests/view/61fc7a6ed508ec6a1c9f4b7d

One difference between those two tests could be the number of tasks. The bad test has 21k+ tasks the good one 'only' 4k+. Any quadratic behavior in the number of tasks could explain the ddos effect, but not necessarily the other things (that could be related timeouts however).

**Comment by ppigazzini** [comment]
document too large:
```
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]: 2022-03-16 20:11:20,996 ERROR [waitress][waitress-0] Exception while serving /tests/modify
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]: Traceback (most recent call last):
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/pyramid/tweens.py", line 13, in _error_handler
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]:     response = request.invoke_exception_view(exc_info)
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/pyramid/view.py", line 786, in invoke_exception_view
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]:     raise HTTPNotFound
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]: During handling of the above exception, another exception occurred:
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]: Traceback (most recent call last):
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/waitress/channel.py", line 426, in service
Mar 16 20:11:20 tests.stockfishchess.org pserve[316]:     task.service()
...
...
Mar 16 20:15:53 tests.stockfishchess.org pserve[316]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/pymongo/message.py", line 1140, in _raise_document_too_large
Mar 16 20:15:53 tests.stockfishchess.org pserve[316]:     raise DocumentTooLarge("%r command document too large" % (operation,))
Mar 16 20:15:53 tests.stockfishchess.org pserve[316]: pymongo.errors.DocumentTooLarge: 'update' command document too large
```

**Comment by vondele** [comment]
that seems a hard limit. I assume that this document includes a list of tasks?

If so, we might have to change the way we compute the number of games per task, to keep it below a certain limit.

**Comment by ppigazzini** [comment]
I started the pyramid debug console, chose "Renderers" to view the run of the Viz's SPSA
http://185.83.217.134:6542/_debug_toolbar/313339383133353239303434323536#

**Comment by ppigazzini** [comment]
Please mind that it's the Viz's 20+0.2 SPSA, not the 180+1.8 SPSA

**Comment by vondele** [comment]
OK, that makes sense, that's the smaller one, so not yet hitting the 16MB limit.

**Comment by vondele** [comment]
I'm fine with deleting that record, if restore is easy, yes, otherwise not essential IMO.

**Comment by ppigazzini** [comment]
Ok.
I restored the backup of March 3, 2022 and set the priority to -10.
https://tests.stockfishchess.org/tests/view/620b4522170fcff54b33a7bf

**Comment by ppigazzini** [comment]
When i got the invalid token I refresh the browser and logout - login.

**Comment by ppigazzini** [comment]
The ddos should due only to the bug number of tasks.
The SPSA param history has a nice upper bound for a big number of games to be played (~10k param saved), the only problem is that the param history contains param for max 500k games.
#1304 cleans up a couple of magic numbers and computes the sampling delta using the SPSA number of games to be played.

**Comment by ppigazzini** [comment]
@vondele open the huge SPSA from the first post :)

**Comment by vondele** [comment]
btw, can we have by default the git diff as open on test pages, that's useful for quick approval

**Comment by ppigazzini** [comment]
The diff is closed if has more than X lines. Of course we can remove that function and set a cookie.

**Comment by ppigazzini** [comment]
X = 49 at the moment.
https://github.com/glinscott/fishtest/blob/6d628770dafaf183cde8dc97d6cecb61c796be64/server/fishtest/templates/tests_view.mak#L392-L401

**Comment by vondele** [comment]
which sounds good..thanks!
