### ISSUE TITLE
Compile cutechess-cli for mac

### ISSUE THREAD

**Issue by glinscott** [glinscott/fishtest#13]

**Comment by thomasahle** [comment]
Adding the `spec` and `config` parameters to `qmake` gave me the error `Project ERROR: failed to parse default search paths from compiler output`. However simply running `qmake` with no parameters worked well.

**Comment by ppigazzini** [comment]
Instruction to compile for macOS `cutechess-cli` with Qt5 static:
https://github.com/glinscott/fishtest/wiki/Build-cutechess-with-Qt5-static#macos
