### ISSUE TITLE
MSYS2 installed in C:\tools\msys64 requirement

### ISSUE THREAD

**Issue by mstembera** [glinscott/fishtest#1301]
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows says:
"If you have already installed MSYS2, please uninstall it: the fishtest worker is expecting to have MSYS2 installed in C:\tools\msys64"
This is a bit unreasonable as MSYS2 can be used by many things and moving it would break whatever was already installed.
Would ```mklink /D C:\tools\msys64  <Original_Install_Location>\msys64``` be a reasonable solution?

**Comment by ppigazzini** [comment]
The `mklink` works on windows 10 with:
1. open `cmd` as admin (eg open `ps` as admin and start `cmd`)
2. `mkdir C:\tools`
3. `mklink /D C:\tools\msys64 <Original_Install_Location>\msys64`
4. start `02_install_worker.cmd`

The wiki instructions are meant for a non skilled user, should be easy easily for a skilled user to set the right path in `02_install_worker.cmd` and `02_install_worker.sh` scripts.

**Comment by mstembera** [comment]
Thanks for replying.  I'm fine using the link solution.  Feel free to close this as you see fit.
