### ISSUE TITLE
worker authentication error with "%" in password

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#1302]
```
raise ValueError("invalid interpolation sintax in %r at ")
ValueError: invalid interpolation sintax in "%aaaaa%bbbbb" at position 0
```
Here is the screenshot:

![Screenshot_2022-03-27_171604](https://user-images.githubusercontent.com/15718418/160288867-4bb31119-f967-407c-a99a-1e07504b6e83.png)

**Comment by zungur** [comment]
Relevant issue #79
