### ISSUE TITLE
Error of compiling sf

### ISSUE THREAD

**Issue by HeroRebor** [glinscott/fishtest#1344]
[Here](https://github.com/ppigazzini/fishtest/wiki/Building-stockfish-on-Windows#building-stockfish-with-gcc)
It's written using the favourite text editor so do we have to type
`cd stockfish/src` then after that we have to create make fish.sh and paste those thing plz tell if not so then what to do with make fish.sh urgent reply plz

**Comment by ppigazzini** [comment]
![image](https://user-images.githubusercontent.com/15718418/166142227-33f7f200-13c1-42e9-b2d7-798f8f356dc9.png)

Here is the script:

```bash
#!/bin/bash
# makefish.sh

# install packages if not already installed
pacman -S --noconfirm --needed unzip make mingw-w64-x86_64-gcc

# download the Stockfish source code
wget -O master.zip https://github.com/official-stockfish/Stockfish/archive/master.zip
unzip -o master.zip
cd Stockfish-master/src
file_nnue=$(grep 'define.*EvalFileDefaultName' evaluate.h | grep -Ewo 'nn-[a-z0-9]{12}.nnue')
ls *.nnue | grep -v ${file_nnue} | xargs -d '\n' -r rm --

# find the CPU architecture
gcc_enabled=$(g++ -Q -march=native --help=target | grep "\[enabled\]")
gcc_arch=$(g++ -Q -march=native --help=target | grep "march")

if [[ "${gcc_enabled}" =~ "-mavx512vnni " && "${gcc_enabled}" =~ "-mavx512dq " && "${gcc_enabled}" =~ "-mavx512f " && "${gcc_enabled}" =~ "-mavx512bw " && "${gcc_enabled}" =~ "-mavx512vl " ]] ; then
  arch_cpu="x86-64-vnni256"
elif [[ "${gcc_enabled}" =~ "-mavx512f " && "${gcc_enabled}" =~ "-mavx512bw " ]] ; then
  arch_cpu="x86-64-avx512"
elif [[ "${gcc_enabled}" =~ "-mbmi2 " && ! "${gcc_arch}" =~ "znver1" && ! "${gcc_arch}" =~ "znver2" ]] ; then
  arch_cpu="x86-64-bmi2"
elif [[ "${gcc_enabled}" =~ "-mavx2 " ]] ; then
  arch_cpu="x86-64-avx2"
elif [[ "${gcc_enabled}" =~ "-mpopcnt " && "${gcc_enabled}" =~ "-msse4.1 " ]] ; then
  arch_cpu="x86-64-modern"
elif [[ "${gcc_enabled}" =~ "-mssse3 " ]] ; then
  arch_cpu="x86-64-ssse3"
elif [[ "${gcc_enabled}" =~ "-mpopcnt " && "${gcc_enabled}" =~ "-msse3 " ]] ; then
  arch_cpu="x86-64-sse3-popcnt"
else
  arch_cpu="x86-64"
fi

# build the fastest Stockfish executable
make -j profile-build ARCH=${arch_cpu} COMP=mingw
make strip
mv stockfish.exe ../../stockfish_${arch_cpu}.exe
make clean
cd
```

**Comment by ppigazzini** [comment]
Obviously if you are downloading the source with `git` you need to change:
```bash
#!/bin/bash
# makefish.sh

# install packages if not already installed
pacman -S --noconfirm --needed make mingw-w64-x86_64-gcc

# download the Stockfish source code
git clone https://github.com/official-stockfish/Stockfish.git
cd Stockfish/src
```

**Comment by ppigazzini** [comment]
Be sure that you are writing `makefish.sh` and not `makefish.sh.txt`

![image](https://user-images.githubusercontent.com/15718418/166142739-775c49f3-78f9-4404-99da-1b06b3a8b34f.png)

**Comment by HeroRebor** [comment]
I am using git so
`#!/bin/bash
# makefish.sh

# install packages if not already installed
pacman -S --noconfirm --needed git make mingw-w64-x86_64-gcc

# download the Stockfish source code
git clone https://github.com/official-stockfish/Stockfish.git
cd Stockfish/src
cd Stockfish-master/src
file_nnue=$(grep 'define.*EvalFileDefaultName' evaluate.h | grep -Ewo 'nn-[a-z0-9]{12}.nnue')
ls *.nnue | grep -v ${file_nnue} | xargs -d '\n' -r rm --

# find the CPU architecture
gcc_enabled=$(g++ -Q -march=native --help=target | grep "\[enabled\]")
gcc_arch=$(g++ -Q -march=native --help=target | grep "march")

if [[ "${gcc_enabled}" =~ "-mavx512vnni " && "${gcc_enabled}" =~ "-mavx512dq " && "${gcc_enabled}" =~ "-mavx512f " && "${gcc_enabled}" =~ "-mavx512bw " && "${gcc_enabled}" =~ "-mavx512vl " ]] ; then
  arch_cpu="x86-64-vnni256"
elif [[ "${gcc_enabled}" =~ "-mavx512f " && "${gcc_enabled}" =~ "-mavx512bw " ]] ; then
  arch_cpu="x86-64-avx512"
elif [[ "${gcc_enabled}" =~ "-mbmi2 " && ! "${gcc_arch}" =~ "znver1" && ! "${gcc_arch}" =~ "znver2" ]] ; then
  arch_cpu="x86-64-bmi2"
elif [[ "${gcc_enabled}" =~ "-mavx2 " ]] ; then
  arch_cpu="x86-64-avx2"
elif [[ "${gcc_enabled}" =~ "-mpopcnt " && "${gcc_enabled}" =~ "-msse4.1 " ]] ; then
  arch_cpu="x86-64-modern"
elif [[ "${gcc_enabled}" =~ "-mssse3 " ]] ; then
  arch_cpu="x86-64-ssse3"
elif [[ "${gcc_enabled}" =~ "-mpopcnt " && "${gcc_enabled}" =~ "-msse3 " ]] ; then
  arch_cpu="x86-64-sse3-popcnt"
else
  arch_cpu="x86-64"
fi

# build the fastest Stockfish executable
make -j profile-build ARCH=${arch_cpu} COMP=mingw
make strip
mv stockfish.exe ../../stockfish_${arch_cpu}.exe
make strip
mv stockfish.exe ../../stockfish_${arch_cpu}.exe
make clean
cd`
Mean I have to create folder and then  paste this ok
And  mv stockfish.exe ../../stockfish_3901020
make clean
cd
Will it be save as stockfish_3901020
If not how to save like that name 
And I want when I type !name it show it running stockfish_3901020
How can I do that 
Urgent reply plz
I need to make this awsome sf soon

**Comment by HeroRebor** [comment]
`#!/bin/bash

makefish.sh
install packages if not already installed
pacman -S --noconfirm --needed git make mingw-w64-x86_64-gcc

download the Stockfish source code
git clone https://github.com/official-stockfish/Stockfish.git
cd Stockfish/src
cd Stockfish-master/src
file_nnue=$(grep 'define.*EvalFileDefaultName' evaluate.h | grep -Ewo 'nn-[a-z0-9]{12}.nnue')
ls *.nnue | grep -v ${file_nnue} | xargs -d '\n' -r rm --

find the CPU architecture
gcc_enabled=$(g++ -Q -march=native --help=target | grep "[enabled]")
gcc_arch=$(g++ -Q -march=native --help=target | grep "march")

if [[ "${gcc_enabled}" =~ "-mavx512vnni " && "${gcc_enabled}" =~ "-mavx512dq " && "${gcc_enabled}" =~ "-mavx512f " && "${gcc_enabled}" =~ "-mavx512bw " && "${gcc_enabled}" =~ "-mavx512vl " ]] ; then
arch_cpu="x86-64-vnni256"
elif [[ "${gcc_enabled}" =~ "-mavx512f " && "${gcc_enabled}" =~ "-mavx512bw " ]] ; then
arch_cpu="x86-64-avx512"
elif [[ "${gcc_enabled}" =~ "-mbmi2 " && ! "${gcc_arch}" =~ "znver1" && ! "${gcc_arch}" =~ "znver2" ]] ; then
arch_cpu="x86-64-bmi2"
elif [[ "${gcc_enabled}" =~ "-mavx2 " ]] ; then
arch_cpu="x86-64-avx2"
elif [[ "${gcc_enabled}" =~ "-mpopcnt " && "${gcc_enabled}" =~ "-msse4.1 " ]] ; then
arch_cpu="x86-64-modern"
elif [[ "${gcc_enabled}" =~ "-mssse3 " ]] ; then
arch_cpu="x86-64-ssse3"
elif [[ "${gcc_enabled}" =~ "-mpopcnt " && "${gcc_enabled}" =~ "-msse3 " ]] ; then
arch_cpu="x86-64-sse3-popcnt"
else
arch_cpu="x86-64"
fi

build the fastest Stockfish executable
make -j profile-build ARCH=${arch_cpu} COMP=mingw
make strip
mv stockfish.exe ../../stockfish_${arch_cpu}.exe
make strip
mv stockfish.exe ../../stockfish_${arch_cpu}.exe
make clean
cd`

**Comment by HeroRebor** [comment]
Mean I have to create folder and then  paste this ok
And  mv stockfish.exe ../../stockfish_3901020
make clean
cd

Will it be save as stockfish_3901020
If not how to save like that name 
And I want when I type !name it show it running stockfish_3901020
How can I do that 
Urgent reply plz
I need to make this awsome sf soon

**Comment by ppigazzini** [comment]
Simply change the last part of the script in:
```bash
# build the fastest Stockfish executable
make -j profile-build ARCH=${arch_cpu} COMP=mingw
make strip
mv stockfish.exe ../../stockfish_3901020.exe
make clean
cd
```

**Comment by HeroRebor** [comment]
Is it the best way to compile?

**Comment by HeroRebor** [comment]
If we type name will it show our sf name urgent reply

**Comment by ppigazzini** [comment]
Frankly I don't understand what are you asking about.
In bash `!name` simply executes the last command line in history starting with "name".
In powershell/cmd `!name` seem to not have a meaning.

**Comment by HeroRebor** [comment]
I mean sf name

**Comment by HeroRebor** [comment]
Btw is it possible to add the make fish.sh and then add docker file and add commands
And run it to heroku
Will it be compile itself?

**Comment by ppigazzini** [comment]
It's possible to automate every process, I'm not an expert on docker and I don't know heroku cloud platform.
I'm closing this issue because in the Stockfish community we don't have expertise in those processes: we rely on Abrok (a third party) for the developments builds.
