### ISSUE TITLE
How to compile stockfish in android pls tell

### ISSUE THREAD

**Issue by HeroRebor** [glinscott/fishtest#1346]

**Comment by ppigazzini** [comment]
This GitHub Issue section is dedicated to the fishtest development.

Please read the wiki for information before asking questions:
https://github.com/glinscott/fishtest/wiki/Cross-compiling-Stockfish-for-Android-on-Windows-and-Linux

Then ask for help on the discord server (#help channel)
https://discord.gg/awnh2qZfTT

**Comment by HeroRebor** [comment]
I need to make in android not in pc

**Comment by ppigazzini** [comment]
Install Termux on an Android smartphone, then install the usual packages (make, gcc, git) and build Stockfish as on a linux pc.
https://termux.com/

**Comment by HeroRebor** [comment]
Give me all commands what ti install 
And I dont have pc so I cant do any pc work

**Comment by HeroRebor** [comment]
Where to post then I just asking the command then I wont ask anything and its really issue for me

**Comment by ppigazzini** [comment]
Read the first post:
Otherwise ask for help on the Stockfish discord server (#help channel)
https://discord.gg/awnh2qZfTT

**Comment by HeroRebor** [comment]
Sir on 1st u told 

> This GitHub Issue section is dedicated to the fishtest development.
> 
> Please read the wiki for information before asking questions: https://github.com/glinscott/fishtest/wiki/Cross-compiling-Stockfish-for-Android-on-Windows-and-Linux
> 
> Otherwise ask for help on the Stockfish discord server (#help channel) https://discord.gg/awnh2qZfTT
There we have to compile sf for android by window I dont have window
And your 2nd reply 



> Install Termux on an Android smartphone, then install the usual packages (make, gcc, git) and build Stockfish as on a linux pc. https://termux.com/

Nowadays gcc cant be install by termux u can try it by yourself that's why I asking the commands

**Comment by ppigazzini** [comment]
Done, 10 seconds Google search "how to compile c++ on termux"

https://medium.com/@basudev_18233/how-to-compile-c-c-programming-on-mobile-91e062bc7c52

**Comment by HeroRebor** [comment]
Will it install gcc?

**Comment by ppigazzini** [comment]
clang.
simply build Stockfish with:
`make -j profile-build ARCH=armv8 COMP=clang`
![Screenshot_20220502_154853_com termux](https://user-images.githubusercontent.com/15718418/166247966-3f359e64-0ec7-4f29-ae1f-960d24687d83.jpg)

**Comment by HeroRebor** [comment]
Thank you sir it worked btw will it be strong?

**Comment by ppigazzini** [comment]
Compiling form time to time the up to date development version you will get some improvements. Not a night and day difference with respect to the official release, I fear.
