### ISSUE TITLE
Only update cutechess-cli conditionally

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1368]
The updater does not update cutechess-cli on MacOS since we don’t have a MacOS binary.

This could be made more generic by testing if the downloaded cutechess-cli works. The code for this already exists in the worker.

Edit: I this way it would be less dangerous to try out new cutechess-cli binaries. We would not risk breaking existing setups.

**Comment by vondele** [comment]
probably needs to be able to check the version and act somehow if the version doesn't match the requirements. Now we can update the version, even if the installed one 'works'.

**Comment by vondele** [comment]
The cutechess version check is there, but it triggers and exception.

**Comment by vdbergh** [comment]
It seems this has to be done in worker and not in the updater. The updater should save a backup copy of the existing cutechess-cli. The worker then should use that as a fallback if the downloaded cutechess-cli does not work.

**Comment by vondele** [comment]
that's an idea.

**Comment by ppigazzini** [comment]
> The updater does not update cutechess-cli on MacOS since we don’t have a MacOS binary.

We do have a cutechess-cli binary:
https://github.com/official-stockfish/books/blob/master/cutechess-cli-macos-64bit.zip

https://github.com/glinscott/fishtest/blob/5f9824621f4d587f0fac531686b0d9aa925a58e3/worker/games.py#L1170-L1180

Perhaps we could drop the `cutechess-cli` restore for MacOS:
https://github.com/glinscott/fishtest/blob/5f9824621f4d587f0fac531686b0d9aa925a58e3/worker/updater.py#L71-L74

> The updater should save a backup copy of the existing cutechess-cli.

The updater already backups `cutechess-cli` :)

https://github.com/glinscott/fishtest/blob/5f9824621f4d587f0fac531686b0d9aa925a58e3/worker/updater.py#L61-L63

**Comment by vdbergh** [comment]
See #1369
