### ISSUE TITLE
SPSA tests required "ck" "rk" values

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#138]
If I look at a SPSA test which is "finished" from any author,
there is currently no way to see what ck and rk values were initially used for each parameter.
Maybe a switch initial/final could be useful.

There is however an undocumented workaround,
which is to "Reschedule", then change the test to SPSA, 
and the spsa box would contain the original values.

**Comment by Stefano80** [comment]
Sounds interesting, let us keep it open for some time.
