### ISSUE TITLE
tests.stockfishchess.org is down

### ISSUE THREAD

**Issue by RickyGrassmuck** [glinscott/fishtest#1385]
Just a heads up, tests.stockfishchess.org does not appear to be responding to requests right now. Not sure if this is the right place to report (apologies if not) but figured I'd let y'all know in case y'all weren't aware.

**Comment by vondele** [comment]
thanks yes, it is known, we probably need a VPS restart @glinscott

**Comment by ppigazzini** [comment]
Fans failure, see https://status.iniz.com/incident/103776

**Comment by vdbergh** [comment]
This can be closed now....
