### ISSUE TITLE
Cann't start worker.py with Raspberry Pi

### ISSUE THREAD

**Issue by D1visionbyZero** [glinscott/fishtest#1390]
Wanted to deploy my Raspberry Pi, but unfortunately the worker could not be run. The following error message came up: Unable to run cutechess-cli. Error: 
[Errno 8] Exec format error: '/root/fishtest/worker/testing/cutechess-cli'.
The downloaded cutechess-cli is not working. Trying to restore a backup copy ...
My current system is: Raspbian GNU/Linux 10 (buster)

**Comment by ppigazzini** [comment]
At the moment the fishtest worker supports ARM CPU only for Apple silicon. It has not at example a cutechess-cli built for ARM CPU.

**Comment by D1visionbyZero** [comment]
Oh okay, i see. Thanks for the information.
