### ISSUE TITLE
Save the PGN files of the workers on a server

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#140]
Fishtest is probably the entity which plays the most high quality games per day, with at least one of the players being at top level. 

In the long run it will prove useful to save the PGN files somewhere to constitute a giant database of such high quality games, if only to tune the eval in new fashions.

**Comment by Stefano80** [comment]
We should preliminarily estimate how much space we actually would need. I think this could rapidly escalate. I would to it only for LTC sprt tests, in order to guarantee a basics quality.

**Comment by snicolet** [comment]
When I was working on another open-source project (Gnugo) they used to have a clever logarithmic scheme for the site backups:

• each day, the new games of the day are consolidated (level 0)
• each week, the new files of level 0 are consolidated (level 1)
• each second week, the new files of level 1 are consolidated (level 2)
• each month, the new files of level 2 are consolidated (level 3)
• each trimester, the new files of level 3 are consolidated (level 4)
• each semester, the new files of level 4 are consolidated (level 5)
• each year, the new files of level 5 are consolidated (level 6)
• each leap year, the new files of level 6 are consolidated (level 7)

This way, the daily database are kept small, and the bigger and bigger databases are only manipulated very rarely, which means we don't have performance problems.

All this could be handled in a separate server, maybe there are free plans with database and python?

**Comment by candirufish** [comment]
They did it with lczero, I wonder why pgn aren't saved on fishtest. It is almost 700 million games wasted, we can do some interesting data mining/analysis on those. With batch sizes smaller now, 250, it should be easier to upload them from client's machine for every time a batch finishes and maybe even fast zip it so it can be smaller probably the file probably will only be around 100-300kb.

And maybe we can setup a community fund for the hosting servers? It probably won't costs that much though. s3 only cost 4 cents a gig per month and amazon glacier only 0.6 cents a gig a month. An entire 1 billion games db compressed won't probably be a terabyte big. Or we can make the game sharing peer to peer, we can have willing contributors who have lots of bandwidth/space host them.
