### ISSUE TITLE
Specific users corrupt regression tests results

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#141]
Basically title.
There are currently 2 users that produce heavily corrupted results in regression tests - one is anst (4 cores), and the other one is mgrabiak (3 cores).
First one produces results that are heavily favourite towards master, second one produces results that are heavily against master like there http://tests.stockfishchess.org/tests/view/5a7defef0ebc5902971a9c00.
Both of them are getting autopurged every regression test. Idk what is wrong with them but in every other test their result is fine.
Maybe they should be prohibited from participating in regression tests till fix of their issues is found? (since it's bad for both fishtest and them, fishtest achieves bad results and people are just wasting their CPU times).
You can also find topic on fishcooking about this.
https://groups.google.com/forum/#!topic/fishcooking/qZRlHCqHpLc

**Comment by Vizvezdenec** [comment]
This problem still exists, some machines of new chinese worker also produce strange results with really high residuals:
http://tests.stockfishchess.org/tests/view/5a96cfdb0ebc590297cc8d2b 

24 | Thanar-3cores-1478 | seconds ago | 949 / 1000 | 136 | 48 | 765 | 0 | 2 | 6.798
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

(it was chinese pool worker before)

I have a feeling that it's connecter to this issue 
https://github.com/glinscott/fishtest/issues/145

**Comment by Vizvezdenec** [comment]
Maybe we should do the same thing as we did in crashing issue - launch artificial tests and let @noobpwnftw see, what is wrong on machine that produces residual 7?

**Comment by noobpwnftw** [comment]
I have checked this, two problems:

1. Related to https://github.com/glinscott/fishtest/issues/145 there is indeed one worker that had a 0 sized book 8moves_v3.pgn. I manually put 2moves_v1.pgn on all workers but this one is new.

2. There is one race condition in fishtest/rundb.py `
    run = self.runs.find_and_modify(**q)
    if run == None:
      return {'task_waiting': False}

    # Find the task we have just activated: the one with the highest 'last_updated'
    latest_time = datetime.min
    for idx, task in enumerate(run['tasks']):
      if 'last_updated' in task and task['last_updated'] > latest_time:
        latest_time = task['last_updated']
        task_id = idx`
Now you have a busy database and imagine if another "update_task" gets executed at the same moment("last_updated" is the same), then server would handed out wrong task_id. 

I have seen one time only 99 of my machines are on your active workers list but 100 of them are actually  running during this test: http://tests.stockfishchess.org/tests/view/5a95c0830ebc590297cc8c47.
One of the workers had the same task_id with another worker for a long time, magically not guarded from '    # Guard against incorrect results
    count_games = lambda d: d['wins'] + d['losses'] + d['draws']
    num_games = count_games(stats)
    old_num_games = count_games(task['stats']) if 'stats' in task else num_games
    spsa_games = count_games(spsa) if 'spsa' in run['args'] else 0
    if num_games < old_num_games \
            or (spsa_games > 0 and num_games <= 0) \
            or (spsa_games > 0 and 'stats' in task and num_games <= old_num_games):
      return {'task_alive': False}'

Maybe change the check into 'num_games < old_num_games'?

**Comment by Stefano80** [comment]
@Vizvezdenec I think [this](https://github.com/glinscott/fishtest/pull/217) gives us a simple workflow to solve the problem. Closing.
