### ISSUE TITLE
Impossible to create/modify/stop tests on Safari (Mac and IPhone)

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#1412]
Hi,

Since a couple of days, I encounter a problem when trying to either create/modify/stop any test on Safari (Mac or IPhone), or even trying to login in fishtest. I suspect that it may be related to password checking: has anything changed in the recent days?

Steps to reproduce:

1) launch Safari
2) try to create/modify/stop any of my tests

==>  I get a blank page with an `check_csrf_token(): Invalid token` error message

**Comment by Disservin** [comment]
I cannot recreate this, I just successfully modified a test of yours and everything worked fine on safari. I have iOS 15.6.1

**Comment by snicolet** [comment]
I can make a video stream of my screen if you wish to see the bug in action: https://discord.gg/4r4C8x65

**Comment by snicolet** [comment]
I managed to change my password, but now even the logout link is broken:

```
404 Not Found
The resource could not be found.
predicate mismatch for view logout (request_method = POST)
```

**Comment by peregrineshahin** [comment]
What OS version do you have?
This is because of the use of using JavaScript ES6 (2015) syntax
The arrow functions, let, const instead of using normal functions and var
Your browser seems not to support these new syntactic sugar from ES6 because it's maybe old

**Comment by peregrineshahin** [comment]
Well I even think it's because of the optional chaining introduced in (ES2020) specifically
Not the ES6 (2015) features

I think the script running on your device is stopping way before password checking
Not allowing the script to continue and check login

Can you confirm where the script is failing by checking your browser console?
