### ISSUE TITLE
machine limit and stress on API

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#142]
I have recently deployed 100*16-core machines with fishtest worker, however, there is a limit on machines which only 4 of them would get jobs. Even so, it seems that the API(tests.stockfishchess.org:80 would fail with connection timeout and sometimes HTTP 503).
My side of the network should have no problem with this number of concurrency, and username I'm using is ChessDB_CN_WorkerPool.

**Comment by Stefano80** [comment]
Hi @noobpwnftw , first of all thank you for the tremendous contribution. I will investigate about the origin of these problems.

**Comment by ianfab** [comment]
That is a default limit to perhaps protect against attacks/misuse or unintentional issues caused by a single user: https://github.com/glinscott/fishtest/blob/712250c57b2ea4e22523364a92ac20d4a7ddef1c/fishtest/fishtest/userdb.py#L56-L60
If you want to connect more than 4 machines, an admin needs to increase your machine limit in the database.

**Comment by Stefano80** [comment]
So, the general machine limit is set to 4 [here](https://github.com/glinscott/fishtest/blob/712250c57b2ea4e22523364a92ac20d4a7ddef1c/fishtest/fishtest/userdb.py#L58).

But I see that @ianfab already answered this.

**Comment by Stefano80** [comment]
@noobpwnftw : are you planning to do this more often? If yes we should increase your number gradually and solve the problems as they present themselve, I don't know whether the server can handle this.

**Comment by noobpwnftw** [comment]
Another minor problem occurred to me is that when I encountered failed API requests after getting a task, it would then skip the task and overwrite "run_id.txt" after retry. I can see the old task remains there until expire and takes a place in the machine concurrency limit.

This 1600 cores will be dedicated to fishtest for a good while. My other projects now demand less processing power so the extra ones are moved here.

**Comment by Stefano80** [comment]
@ianfab : I have no experience in administrating mongo databases. I assume that I have to start the mongo shell locally on the fisthtest server and there I can change the appropriate document (must find out how). I am right so far?

**Comment by Stefano80** [comment]
@noobpwnftw : then we will solve this in a short time.
@ppigazzini : I assume you are more skilled than me in this. Could you increase the number of machines for the user to some higher value where we have some confidence it will not break anything. Maybe 20? I will try to learn this as fast as possible, but I need some time.

**Comment by Stefano80** [comment]
Is [this](https://docs.mongodb.com/getting-started/shell/update/#update-specific-fields) the right instruction to get this done without breaking anything?

**Comment by Stefano80** [comment]
This is similar to the issue [here](https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/Fabian$20FIchter%7Csort:date/fishcooking/2mirJpCVMvk/XcSLTnmQAgAJ), so I assume this is solvable.

**Comment by noobpwnftw** [comment]
@Stefano80 Please be aware when doing so since by changing the limit to 20 it would almost double your current server load for 1 threaded jobs.

**Comment by Stefano80** [comment]
@noobpwnftw : thank you for the remark. I have already seen the server running at >1000 Mnps, so this should be ok. But better be safe than sorry: we could start with 10.

**Comment by noobpwnftw** [comment]
@Stefano80 Ok, thanks. Now all the workers has been configured and running(or waiting). Please let me know when this issue should be closed.

**Comment by ppigazzini** [comment]
@noobpwnftw limit updated to 40

**Comment by noobpwnftw** [comment]
@ppigazzini 40 jobs assigned, now I'm observing more connection failures to github than the fishtest API...

**Comment by noobpwnftw** [comment]
Changes in worker/requests/adapters.py:
DEFAULT_RETRIES = 0 => DEFAULT_RETRIES = 3
and in worker/games.py & worker/worker.py:
HTTP_TIMEOUT = 5.0 => HTTP_TIMEOUT = 10.0

Fixed most of the connection problems.

**Comment by ppigazzini** [comment]
@noobpwnftw thank you for the debug and, obviously, for the CPU contribution. Limit updated to 100.

**Comment by noobpwnftw** [comment]
Thank you all for helping, now all my workers are running. Closing issue.

**Comment by Stefano80** [comment]
@noobpwnftw @ppigazzini please check this https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/T4AZOFF7Z1E out

**Comment by ppigazzini** [comment]
@Stefano80 I think that all is ok, right?

**Comment by Stefano80** [comment]
Yes, this is ok

**Comment by noobpwnftw** [comment]
@Stefano80 Is it possible to raise my machine limit to 200? I might actually run that many but just in case.

**Comment by Stefano80** [comment]
I can do this in the evening.

**Comment by ppigazzini** [comment]
@noobpwnftw @Stefano80 limit updated to 200.
