### ISSUE TITLE
worker connection problem

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#143]
@Stefano80 the user @noobpwnftw in this thread 
https://github.com/glinscott/fishtest/issues/142#issuecomment-368258652 used these changes to solve the connection problem with his 100 workers
```
Changes in worker/requests/adapters.py:
DEFAULT_RETRIES = 0 => DEFAULT_RETRIES = 3
and in worker/games.py & worker/worker.py:
HTTP_TIMEOUT = 5.0 => HTTP_TIMEOUT = 10.0
```
If this is a good idea we should commit the change to fishtest.

**Comment by Stefano80** [comment]
Yes I wanted to propose this too

**Comment by ppigazzini** [comment]
I posted a message in this [fishcoocking thread](https://groups.google.com/d/msg/fishcooking/GgsALC0GOxs/J2aYxP0yBQAJ) to collect opinions and ideas

**Comment by ppigazzini** [comment]
The worker connection problem seems to be triggered by tuning sessions. We could try to limit the number of contemporary tuning sessions.

**Comment by marrco** [comment]
> HTTP_TIMEOUT = 5.0 => HTTP_TIMEOUT = 10.0

what about a random time between 8 and 12 minutes, just to be sure there are not too many concurrent retries in case of a problem kicking out many workers at the same time?

BTW, I sometimes have to restart my workers (portable win setup) when there are large tuning sessions.

**Comment by noobpwnftw** [comment]
This fix does not solve the logic problem with task fetching because the request might still succeed on the server side. Workers will do retry but they won't get the tasks again, they will become idle until task scavenging 60 minutes later. This might be what happened with tuning sessions.

I also encountered a problem where the same task gets assigned to two different workers, but they show up as if they are from the same machine and produced a high residual.
http://tests.stockfishchess.org/tests/view/5a927adb0ebc590297cc882b

**Comment by ppigazzini** [comment]
@noobpwnftw on fishtest server `~/fishtest/fishtest/utils/scavenge.py` is scheduled every 5 minutes

**Comment by noobpwnftw** [comment]
@ppigazzini Yes, but with this [commit](https://github.com/glinscott/fishtest/commit/878b4bf23e09685912ed37f6c99952133e4e63ef) it would only clean up dead tasks > 60 minutes.

**Comment by ppigazzini** [comment]
Correct, Gary changed the delta value from 5 minutes to 60 minutes with the commit https://github.com/glinscott/fishtest/commit/878b4bf23e09685912ed37f6c99952133e4e63ef to solve a worker timeout problem, view this [thread](https://groups.google.com/forum/#!topic/fishcooking/UG5k_ifOHeA).

**Comment by noobpwnftw** [comment]
https://github.com/glinscott/fishtest/blob/e81663bda8c06cb826fa028318241b4accc26ed7/worker/games.py#L288
This request without a try block can fail and cause the entire tuning task bail out. This might be what happened with worker hangs.

**Comment by noobpwnftw** [comment]
Now I have set up a reverse proxy for tests.stockfishchess.org so that my workers does not suffer from connectivity issues with the origin server.

**Comment by noobpwnftw** [comment]
Ongoing turning session caused significant delays in fishtest HTTP API and workers suffered from timeouts.

**Comment by Stefano80** [comment]
Can it be that this is because they always ask the server for new value after very small batches? Maybe we must just increase the size of the batches to a standard number like 100 instead of how we do it today

**Comment by noobpwnftw** [comment]
I turned off 80 of my workers or the site won't open and you lost most of other workers too. I will now gradually add more.
I wonder how this could cause performance issues, I have a similar deployment that handled 4000 workers...

**Comment by Stefano80** [comment]
I think this is solved and subsided by [this](https://github.com/glinscott/fishtest/issues/159).
