### ISSUE TITLE
Sanity checks for downloaded book files

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#145]
I have seen cases that there exists 0-sized book files and they are never re-downloaded.
Then the worker will use no book and will produce incorrect results.

**Comment by Rocky640** [comment]
Also, ideally, make sure that
a) no scripture is changed in the holy books throughout the test
b) the exes are not changed throughout the test

**Comment by Stefano80** [comment]
Ok, this is meaningful issue. What do exactly want to do, if something happen? Stop the worker? Wait and retry? Write a log message?

Any idea?

**Comment by noobpwnftw** [comment]
For the book check maybe we can hash check on the file and re-download if they don't match.

**Comment by noobpwnftw** [comment]
This is very important because once the 0-sized book file is there, unless the user noticed and manually fix it, all following tests will run with no book.

**Comment by Stefano80** [comment]
Ok. I am definitely going to look into this issue.

**Comment by Stefano80** [comment]
Hi, so the code use the requests package to retrieve files from github. Are anybody familiar with the package?

For instance, does anybody have any idea if the [status code](http://docs.python-requests.org/en/master/user/quickstart/#response-status-codes) of the request will be ok or not for empty book files?

**Comment by Stefano80** [comment]
Hi @noobpwnftw , may I ask you for your support? I am thinking on the following lines. Yes, we could after downloading check the hashes and if they dont match, we download it again. This should be easy to implement and reasonably fail safe. I will start working on this immediately (and try to reduce my dynamic contempt activities).

My preferred solution, however, would be that we get the information from the request that something has gone wrong, so we would avoid spurious hash checking code. So my first question is: could you change your local fishtest and somehow check whether we get a surprising status code from the request when we download a 0-size book? I would do it locally, but with my concurrency 3 machine it would take ages until such a case is triggered.

**Comment by noobpwnftw** [comment]
@Stefano80 I'm not a Python guy, however, it looks like when connection failed, this requests package will throw an error, thus no file is created. However, if it connected successfully but failed the actual HTTP request, the requests package will not throw an error but proceed to returning this code and an empty response. We should handle it like this:
https://github.com/glinscott/fishtest/blob/712250c57b2ea4e22523364a92ac20d4a7ddef1c/worker/games.py#L142
You probably can reproduce it by downloading an non-existing file from Github server(HTTP code 404) and see what happens.

For the damage already done, we need a way to force the workers to re-download corrupted books.

**Comment by Stefano80** [comment]
Hi @noobpwnftw ,

thank you for the hints. I have a [primitive fix for the issue](https://github.com/glinscott/fishtest/compare/master...Stefano80:emptyBook), maybe you and @ppigazzini and whoever is interested can check it.

If at least you both agree that is more or less sensible, I will polish it and open a PR.

For what you suggested to do, I did not find a way to connect to http, but have it fail with status code 200. Do you have any idea? I would like to reproduce the error locally before committing any solution.

I tried:
- getting a non existing file: it just causes the setup function to exit with the exception
- to disconnect internet during the process: it will raise a HTTP exception

**Comment by noobpwnftw** [comment]
Hi @Stefano80 ,
Your patch logic looks fine to me, might consider adding delays between retries.

I don't think it is possible to have HTTP requests fail with status code 200, but I'm not sure under what circumstances it will result in no exception thrown with the original code if you tried on non-existing file, which is effectively a status code 404.

**Comment by Stefano80** [comment]
Ok, let us wait for the feedback by @ppigazzini to the two PRs and we see how to go on.

By the way, with "fail with status code 200" I actually mean "download a 0-size file but return status code 200 nevertheless"
