### ISSUE TITLE
How to build Stockfish by using Intel c++ compiler

### ISSUE THREAD

**Issue by BudiKusasi** [glinscott/fishtest#146]
How to build Stockfish by using Intel c++ compiler, either on cygwin or msys2, or another successful sensible environment

**Comment by ppigazzini** [comment]
Read [Building Stockfish on Windows](https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows) on Stockfish wiki. For any question about Stoskfish please write on the [FishCooking group](https://groups.google.com/forum/?fromgroups=#!forum/fishcooking)
