### ISSUE TITLE
Error when reaching 2nd phase of Stockfish profile build

### ISSUE THREAD

**Issue by BudiKusasi** [glinscott/fishtest#147]
I tried to build SF engine as PGO under cygwin use mingw64, but at 2nd phase errror 139;
...
```
Step 2/4. Running benchmark for pgo-build ...
./stockfish bench > /dev/null
/bin/sh: line 1:  8228 Segmentation fault      ./stockfish bench > /dev/null
make: *** [Makefile:417: profile-build] Error 139

$
```
used to be able to build it easily on the same environment, but suddenly get such condition... any useful guide to help me out?

**Comment by ppigazzini** [comment]
Try to build Stockfish with msys2 following the [Stockfish wiki](https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows).

Anyway this is the fishtest repo so I'm closing this issue.
Post you problem to the [FishCooking forum](https://groups.google.com/forum/?fromgroups=#!forum/fishcooking).
