### ISSUE TITLE
Failed FishTest Error

### ISSUE THREAD

**Issue by FishChess** [glinscott/fishtest#1475]
Hi, I created a fishtest but it failed, how can find reason of error?

![image](https://user-images.githubusercontent.com/118218359/206838347-20ae2195-8fa6-4e72-830d-264ea8e6202c.png)

my commit links

https://tests.stockfishchess.org/tests/view/63942b1988432ad6ae39d4d1

thanks

**Comment by vondele** [comment]
wrong bench. Please don't file issues for that.

**Comment by XInTheDark** [comment]
You provided the wrong bench. You filled the bench as `112358` (which is ridiculously low), while in reality it is `3636253`. If you wish to rerun the test, submit it with the correct bench. 

You can get the bench by running the compiled binary file and typing `bench` into it. The bench is the number under "Nodes searched".

Also, it is unwise to change classical eval parameters, such as piece values, as they don't affect the engine by much with NNUE enabled.

**Comment by FishChess** [comment]
> Also, it is unwise to change classical eval parameters, such as piece values, as they don't affect the engine by much with NNUE enabled.

I want to test higher knight value perhaps stockfish could be stronger, for affect can disable nnue 

> You provided the wrong bench. You filled the bench as 112358 (which is ridiculously low), while in reality it is 3636253. If you wish to rerun the test, submit it with the correct bench.

can fill bench 3636253 as default for all bench?

**Comment by vdbergh** [comment]
> can fill bench 3636253 as default for all bench?

Please stop trolling.

**Comment by FishChess** [comment]
@vdbergh, this was my first fishtest , not trolling 

I filled bench 3467381, I wish to return good test 

thanks

**Comment by FishChess** [comment]
https://tests.stockfishchess.org/tests/view/63943d7388432ad6ae39d840

failed again, why failed my fishtest again?

**Comment by vondele** [comment]
stopped because you disabled NNUE, which first of all doesn't do what you want, and second we don't tune classical eval with NNUE disabled.

**Comment by FishChess** [comment]
I want to test higher knight value perhaps stockfish could be stronger

**Comment by vondele** [comment]
you do realize that with NNUE these parameters have essentially no impact?

**Comment by XInTheDark** [comment]
> https://tests.stockfishchess.org/tests/view/63943d7388432ad6ae39d840
> 
> failed again, why failed my fishtest again?

You failed because your bench was wrong again.

I have already mentioned earlier that the correct bench is 3636253.

**Comment by XInTheDark** [comment]
Please do stop trolling with unnecessary and obviously indecent changes like this.

**Comment by zungur** [comment]
Help on how to configure tests is available on Discord channels and our wiki page

**Comment by FishChess** [comment]
OK, I Report This Issues to Black Reward Team

**Comment by FishChess** [comment]
I just wanted to increase the knight value to see LTC & STC but for disagree viewpoints it ignored
I will give you an example, which one is correct?
## 1 + 2 + 3 + 4 + 5 + ... = ∞
## 1 + 2 + 3 + 4 + 5 + ... = -1/12

**Comment by XInTheDark** [comment]
> I just wanted to increase the knight value to see LTC & STC but for disagree viewpoints it ignored I will give you an example, which one is correct?
> 
> ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> ## 1 + 2 + 3 + 4 + 5 + ... = -1/12

@atumanian this just proves that he's trolling.

**Comment by peregrineshahin** [comment]
> I just wanted to increase the knight value to see LTC & STC but for disagree viewpoints it ignored I will give you an example, which one is correct?
> 
> ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> ## 1 + 2 + 3 + 4 + 5 + ... = -1/12

Imagine going from a knight value tweak to a Ramanujan's summation in one shot, might as well just quote special relativity and say all opinions are valid and relatively true from another perspective just to prove your opinion is of any worth (worst logic ever)..
Okay, that's enough of you.. just try to touch the grass and STFU!

**Comment by XInTheDark** [comment]
> I just wanted to increase the knight value to see LTC & STC but for disagree viewpoints it ignored I will give you an example, which one is correct?
> 
> ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> ## 1 + 2 + 3 + 4 + 5 + ... = -1/12

@FishChess Yeah, yeah, right. So 1 + 2 + 3 + 4 + 5 + ... can be both infinity and -1/12 at the same time. That's very convenient, isn't it? No need to choose between the two, we can just have both! 

Maybe we can also have 1 + 2 + 3 + 4 + 5 + ... equal to the square root of -1 while we're at it. Because why not, right?

**Comment by atumanian** [comment]
> I just wanted to increase the knight value to see LTC & STC but for disagree viewpoints it ignored I will give you an example, which one is correct?

@FishChess 
I see nothing wrong in testing a version with an increased knight value. You still have to set `Use NNUE=true` because this is the default value and the engine is much weaker otherwise. Even if NNUE is enabled, the classical evaluation is selected conditionally by the line (evaluation.cpp:1059):

```
 bool useClassical = !useNNUE || (pos.count<ALL_PIECES>() > 7 && abs(psq) > 1760);
```
Moreover, `pos.non_pawn_material()`, which depends on the piece values, is used in nnue/evaluate_nnue.cpp:146. Therefore, I don't agree the piece values have no impact with NNUE.

> ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> ## 1 + 2 + 3 + 4 + 5 + ... = -1/12

The first one is correct. But how is it related to our topic?

**Comment by vdbergh** [comment]
Although the second one is not correct according to the standard definition of series, one may guess that the author wants to interpret the left hand side as &zeta;(-1) which is indeed equal to -1/12. 
![24958692_10155082936826198_2618396015967072706_o](https://user-images.githubusercontent.com/6613103/208061929-cf2b7d19-9b30-42bb-9b40-d95cef91f88e.jpg)

**Comment by OfekShochat** [comment]
> (Christmas decoration in the beautiful city of Ljubljana).
oh thats amazing I have to say

**Comment by atumanian** [comment]
> Although the second one is not correct according to the standard definition of summing series, one may guess that the author wants to interpret the left hand side as ζ(-1) which is indeed equal to -1/12.
> ![24958692_10155082936826198_2618396015967072706_o](https://user-images.githubusercontent.com/6613103/208061929-cf2b7d19-9b30-42bb-9b40-d95cef91f88e.jpg)
> (Christmas decoration in the beautiful city of Ljubljana).

It's interesting but a bit off-topic, in my opinion.
There's a good rule in Wikipedia: "[Assume good faith](https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith)" I wish the same rule was followed here. If you, @vdbergh and @XInTheDark , call a person a troll you must prove your accusation.

**Comment by XInTheDark** [comment]
> > Although the second one is not correct according to the standard definition of summing series, one may guess that the author wants to interpret the left hand side as ζ(-1) which is indeed equal to -1/12.
> > ![24958692_10155082936826198_2618396015967072706_o](https://user-images.githubusercontent.com/6613103/208061929-cf2b7d19-9b30-42bb-9b40-d95cef91f88e.jpg)
> > (Christmas decoration in the beautiful city of Ljubljana).
> 
> It's interesting but a bit off-topic, in my opinion. There's a good rule in Wikipedia: "[Assume good faith](https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith)" I wish the same rule was followed here. If you, @vdbergh and @XInTheDark , call a person a troll you must prove your accusation.

@atumanian We have "assumed good faith" in our conversations of course, but they have proven on multiple occasions that they are trolling. At the very least, they keep bringing up unrelated topics and insisting on illogical arguments in our discussions. There is too much proof for this: just look at any issue/PR created by them in this repository or in fishtest.

**Comment by XInTheDark** [comment]
As this issue is closed, it's unwise to keep on arguing about irrelevant stuff here, isn't it?
