### ISSUE TITLE
Enhancements for web page displayed informations

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#148]
Three small enhancements suggestions:

- on the test submission page, instead of labeling the button 'fast|slow' what about 'short|long' or even the canonical 'STC|LTC'

- on the individual test view... display a line summarizing the number of active workers and cores for this particular test.

- on the individual test view ... I'd love to see the 'system' information next to each worker name (as is available on the overview)

**Comment by Stefano80** [comment]
Hi @vondele , thank you for making these points. To make changes in the display of the pages is really not that difficult, it only needs some time until you get it right (and setup a dev server, which I still have to do). [Here](https://github.com/glinscott/fishtest/pull/121) you can have an example by @ianfab.

I am wondering if we want to use the issues page for feature requests. Your opinion on that?

**Comment by Stefano80** [comment]
If anybody wants to give a try, [here](https://github.com/glinscott/fishtest/pull/121) a source of inspiration.

**Comment by tomtor** [comment]
@snicolet See https://github.com/glinscott/fishtest/pull/220

**Comment by tomtor** [comment]
@vondele #220 should take care of your wishes too

**Comment by vondele** [comment]
@tomtor thanks... I guess that's what I suggested. No so easy for me to map from the code to the expected result, I'm sure it will look good once it is live.

**Comment by vondele** [comment]
I think all things mentioned have been implemented. I'm closing the issue.
