### ISSUE TITLE
Use local time zone instead of UTC time

### ISSUE THREAD

**Issue by XInTheDark** [glinscott/fishtest#1498]
Right now, the time zone used on fishtest is UTC time; can we change it to display the local time instead?

**Comment by dubslow** [comment]
Eh, screwing with timezones only ever ends in pain

**Comment by XInTheDark** [comment]
The time can just be changed locally though, not server-side?

**Comment by noobpwnftw** [comment]
Eh, screwing with timezones only ever ends in pain. But GMT is a time zone and UTC is a time standard.
