### ISSUE TITLE
Consider caching web output

### ISSUE THREAD

**Issue by xoto10** [glinscott/fishtest#152]
Tom Vji... has suggested caching some of the web output in [fishcooking](https://groups.google.com/d/msg/fishcooking/kA28W9fyCGQ/K39_bEIzBAAJ).

A lot of fishtest is transactional so I guess can't be cached, but the main page could probably be cached without causing many problems. It looks like this can be handled by pyramid with relatively little change to the code, see [here](https://docs.pylonsproject.org/projects/pylons-webframework/en/latest/caching.html).

It looks like we add a \@cache_region line to the relevant function (tests_view in views.py?) and that does most of the work, combined with setting options for beaker in the ini file.

**Comment by tomtor** [comment]
See

https://github.com/glinscott/fishtest/pull/153

**Comment by Stefano80** [comment]
Closing, this is not an issue but a suggestion which is being actively followed up.
