### ISSUE TITLE
NNUE uploading is broken

### ISSUE THREAD

**Issue by linrock** [glinscott/fishtest#1546]
Always fails with `Post request failed: other HTTP error` for me as of yesterday.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/208617/213487991-d995eee4-e985-4569-870e-5ff361e58bf0.png">

**Comment by ppigazzini** [comment]
The net server uses a different endpoint path respect to the wiki setup script, I forgot to change the path in the fastapi script as well. Updated the TODO list in the original PR https://github.com/glinscott/fishtest/pull/1540#issuecomment-1382229438
