### ISSUE TITLE
Add LLR graph

### ISSUE THREAD

**Issue by XInTheDark** [glinscott/fishtest#1556]
Adding a LLR graph to show the overall trend of the LLR might be useful data?

**Comment by dubslow** [comment]
No it's not, since the LLR by definition incorporates all test data into its current value. Such a graph would effectively be just taking arbitrary samples of the data, which given our human biases would be worse than useless -- much like the LOS is.

**Comment by vdbergh** [comment]
> Adding a LLR graph to show the overall trend of the LLR might be useful data?

The pentanomial frequencies are a _sufficient statistic_ https://en.wikipedia.org/wiki/Sufficient_statistic for the pentanomial probabilities. So the graph would yield no extra information.

**Comment by silversolver1** [comment]
So does this mean that there is no point in following the trends at https://stockfish.dev/chart/index.php ? Just curious

**Comment by dubslow** [comment]
Pretty much yea. The elo is all-inclusive at any given instant, so the history of the elo is irrelevant, just an arbitrary subsample. No point to watching it.

**Comment by silversolver1** [comment]
Thanks for your reply. I was actually referring more to trend of W-L as elo gaining patches do seem to have a particular trend to me. Could it be said that the history of W-L trend matters or no?

**Comment by ppigazzini** [comment]
https://github.com/glinscott/fishtest/wiki/Fishtest-mathematics

> To calculate Elo estimates from the results of GSPRT tests, Fishtest uses the formula (6.1) in this [document](https://hardy.uhasselt.be/Fishtest/brownian_approximation.pdf). To model a GSPRT as a random walk, we use the formula (2.1) of this [document](https://hardy.uhasselt.be/Fishtest/GSPRT_approximation.pdf) which essentially shows that a GSPRT may be approximated by an SPRT for the drift of a Brownian motion where the infinitesimal variance is estimated from the sample.

Suppose to have two SPRT tests:
- the first fails very fast going down to -2.94 LLR
- the second raises fast and oscillates for 1000 times in [2.80-2.90] LLR before failing after much time

The very different trend information does not influence the final state: fail.

**Comment by silversolver1** [comment]
Ok thank you, I see what you're saying. It's just a bit hard to let go of the idea that a test that seems to be on average doing more well is not more likely to succeed. But i guess for things like this you can only know the final state after it has already been achieved and not before... I mean it's very tempting to say but yes, I see. Thanks for the clarification
