### ISSUE TITLE
Last updated shown is incorrect and API is not robust

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#159]
While running a huge SPSA job

A strange effect is that the main page shows my worker as active seconds ago and the next time I look (a few seconds later) as 11 minutes ago while the upload after each game is OK, my worker is happy sending its spsa results and receiving new parameters every 14 games. We'll have to investigate that.

Currently: 

tvijlbrief | 7 | 0.00 | Linux 4.4.0-109-generic | 62 | tune_imbalance3 | 35 minutes ago
-- | -- | -- | -- | -- | -- | --

Also 0.00 NPS and it sends about every 15 seconds its game result without issues?

What is also strange is that /api/request_spsa is called without issues (this call returns a lot of data and its done every 14 games for my machine),
but the /api/request_task (much less data and called once every 1000 games) often times out.

**I assume the cause for the latter is that the version and task call are executed back-to-back without delay and that traffic caused by a Worker version update made things worse. Some extra delay between these steps would be good, at least until the server has threading.**

**Comment by Stefano80** [comment]
Thx, can you post the error you got locally in the beginning?

**Comment by tomtor** [comment]
`Will fetch task soon...
Exception accessing host:
Traceback (most recent call last):
  File "worker.py", line 59, in worker
    req = requests.post(remote + '/api/request_version', data=json.dumps(payload), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT)
  File "/home/stockfish/fishtest/worker/requests/api.py", line 87, in post
    return request('post', url, data=data, **kwargs)
  File "/home/stockfish/fishtest/worker/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/stockfish/fishtest/worker/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/home/stockfish/fishtest/worker/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/home/stockfish/fishtest/worker/requests/adapters.py", line 215, in send
    raise Timeout(e)
Timeout: HTTPConnectionPool(host='tests.stockfishchess.org', port=80): Request timed out. (timeout=5.0)
Will fetch task soon...
`

repeated 4 times, after which the job started

**Comment by Stefano80** [comment]
This is exactly the same as mine, thx. I have it repeated already ~10 times.

**Comment by tomtor** [comment]
Also Nr of active machines is effected, allthough contributing they are not counted, this is probably the same issue.

Machine | Cores | MNps | System | Version | Running on | Last updated
-- | -- | -- | -- | -- | -- | --
tvijlbrief | 3 | 2.11 | Linux 4.4.0-104-generic | 62 | OutpostRanks | seconds ago
robal | 5 | 2.08 | Darwin 17.4.0 | 62 | OutpostRanks | seconds ago
leszek | 7 | 1.04 | Windows 7 | 62 | OutpostRanks | 14 minutes ago
mibere | 7 | 1.40 | Linux 4.9.0-6-amd64 | 62 | OutpostRanks | seconds ago
ElbertoOne | 6 | 1.73 | Windows 10 | 62 | OutpostRanks | seconds ago
biffhero | 1 | 0.78 | Linux 3.16.0-4-amd64 | 62 | OutpostRanks | seconds ago
IgorLeMasson | 2 | 0.97 | Windows 10 | 62 | OutpostRanks | seconds ago
sunu | 2 | 1.37 | Linux 4.14.0-4.slh.2-aptosid-amd64 | 62 | timeManagement | seconds ago
biffhero | 1 | 0.87 | Linux 3.16.0-4-amd64 | 61 | probcut3 | seconds ago
dew | 1 | 1.17 | Linux 3.4.2-hardened | 61 | probcut3 | seconds ago
gri | 1 | 2.29 | Linux 3.16.0-5-amd64 | 61 | probcut3 | seconds ago
dew | 1 | 1.21 | Linux 4.9.76-gentoo-r1 | 61 | probcut3 | seconds ago
drabel | 1 | 1.32 | Windows 10 | 61 | probcut3 | seconds ago
Bobo1239 | 1 | 1.69 | Linux 4.13.12-1-ARCH | 61 | BishopOutpost | seconds ago
ChessDB_CN_WorkerPool | 8 | 1.59 | Linux 3.10.0-693.17.1.el7.x86_64 | 61 | master | seconds ago
basepi | 1 | 0.00 | Linux 4.4.0-87-generic | 62 | tune_imbalance3 | seconds ago
Patrick_G | 3 | 0.00 | Linux 4.10.0-38-generic | 62 | tune_imbalance3 | 2 minutes ago
velislav | 1 | 0.00 | Linux 4.4.0-112-generic | 62 | tune_imbalance3 | 3 minutes ago
mhoram | 3 | 0.00 | Linux 4.9.0-6-amd64 | 62 | tune_imbalance3 | 12 minutes ago
basepi | 1 | 0.00 | Linux 4.4.0-87-generic | 62 | tune_imbalance3 | 13 minutes ago
leszek | 7 | 1.89 | Windows 7 | 62 | tune_imbalance3 | seconds ago
velislav | 1 | 0.00 | Linux 4.4.0-112-generic | 62 | tune_imbalance3 | 14 minutes ago
Flopzee | 7 | 1.91 | Windows 8.1 | 62 | tune_imbalance3 | 7 minutes ago
Patrick_G | 3 | 0.00 | Linux 4.10.0-38-generic | 62 | tune_imbalance3 | 21 minutes ago
Thanar | 3 | 0.00 | Windows 7 | 62 | tune_imbalance3 | 28 minutes ago
bigpen0r | 6 | 0.00 | Linux 3.13.0-135-generic | 62 | tune_imbalance3 | 31 minutes ago
racerschmacer | 1 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 33 minutes ago
racerschmacer | 5 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 34 minutes ago
mgrabiak | 3 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 34 minutes ago
horst.prack | 1 | 0.00 | Linux 4.15.0-1-amd64 | 62 | tune_imbalance3 | 35 minutes ago
bigpen0r | 15 | 0.00 | Linux 3.13.0-135-generic | 62 | tune_imbalance3 | 36 minutes ago
bigpen0r | 15 | 0.00 | Linux 3.13.0-135-generic | 62 | tune_imbalance3 | 36 minutes ago
bigpen0r | 6 | 0.00 | Linux 3.13.0-135-generic | 62 | tune_imbalance3 | 36 minutes ago
JojoM | 2 | 1.76 | Linux 4.4.0-43-Microsoft | 62 | tune_imbalance3 | 27 minutes ago
sqrt2 | 3 | 2.25 | Linux 3.16.0-5-amd64 | 62 | tune_imbalance3 | seconds ago
brabos | 7 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 38 minutes ago
eastorwest | 4 | 0.00 | Linux 4.4.0-116-generic | 62 | tune_imbalance3 | 39 minutes ago
racerschmacer | 1 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 39 minutes ago
Thanar | 3 | 0.00 | Windows 7 | 62 | tune_imbalance3 | 39 minutes ago
joster | 2 | 0.00 | Linux 4.13.0-36-generic | 62 | tune_imbalance3 | 40 minutes ago
Flopzee | 7 | 0.00 | Windows 8.1 | 62 | tune_imbalance3 | 44 minutes ago
brabos | 7 | 1.92 | Windows 10 | 62 | tune_imbalance3 | seconds ago
JojoM | 7 | 0.00 | Linux 3.16.0-4-amd64 | 62 | tune_imbalance3 | 44 minutes ago
racerschmacer | 5 | 2.24 | Windows 10 | 62 | tune_imbalance3 | seconds ago
JojoM | 7 | 0.00 | Linux 3.16.0-4-amd64 | 62 | tune_imbalance3 | 45 minutes ago
tvijlbrief | 7 | 0.00 | Linux 4.4.0-109-generic | 62 | tune_imbalance3 | 45 minutes ago
Flopzee | 7 | 1.24 | Windows 8.1 | 62 | tune_imbalance3 | 32 minutes ago
horst.prack | 1 | 0.00 | Linux 4.15.0-1-amd64 | 62 | tune_imbalance3 | 50 minutes ago
drabel | 1 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 50 minutes ago
velislav | 2 | 0.00 | Linux 3.10.0-123.8.1.el7.x86_64 | 62 | tune_imbalance3 | 50 minutes ago
tvijlbrief | 7 | 2.40 | Linux 4.4.0-109-generic | 62 | tune_imbalance3 | seconds ago
leszek | 3 | 1.36 | Windows 7 | 62 | tune_imbalance3 | 2 minutes ago
xoto | 12 | 1.36 | Linux 4.13.0-36-generic | 62 | tune_imbalance3 | seconds ago
leszek | 3 | 0.00 | Windows 7 | 62 | tune_imbalance3 | 54 minutes ago
horst.prack | 1 | 0.00 | Linux 4.15.0-1-amd64 | 62 | tune_imbalance3 | 54 minutes ago
Thanar | 3 | 1.28 | Windows 7 | 62 | tune_imbalance3 | seconds ago
sven500 | 1 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 55 minutes ago
JojoM | 7 | 0.00 | Linux 3.16.0-4-amd64 | 62 | tune_imbalance3 | 56 minutes ago
velislav | 2 | 0.00 | Linux 3.10.0-123.8.1.el7.x86_64 | 62 | tune_imbalance3 | 56 minutes ago
ronaldjerum | 3 | 0.00 | Linux 4.4.0-108-generic | 62 | tune_imbalance3 | 56 minutes ago
mhoram | 3 | 0.00 | Linux 4.9.0-6-amd64 | 62 | tune_imbalance3 | 6 minutes ago
Allonautilus | 3 | 0.00 | Linux 3.19.8-100.fc20.x86_64 | 62 | tune_imbalance3 | 56 minutes ago
marrco | 7 | 0.00 | Windows 8.1 | 62 | tune_imbalance3 | 56 minutes ago
mgrabiak | 3 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 56 minutes ago
dex | 7 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 57 minutes ago
racerschmacer | 1 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 21 minutes ago
geoffeg | 1 | 0.00 | Linux 3.10.102 | 62 | tune_imbalance3 | 57 minutes ago
sven500 | 1 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 57 minutes ago
bigpen0r | 15 | 0.00 | Linux 3.13.0-135-generic | 62 | tune_imbalance3 | 57 minutes ago
Thanar | 3 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 57 minutes ago
mgrabiak | 3 | 1.87 | Windows 7 | 62 | tune_imbalance3 | seconds ago
JojoM | 7 | 0.00 | Linux 3.16.0-4-amd64 | 62 | tune_imbalance3 | 58 minutes ago
rkl | 2 | 0.00 | Linux 4.15.7-1.el7.elrepo.x86_64 | 62 | tune_imbalance3 | 58 minutes ago
solarlight | 3 | 0.00 | Windows 10 | 62 | tune_imbalance3 | 58 minutes ago
CSU_Dynasty | 11 | 0.00 | Windows 7 | 62 | tune_imbalance3 | 61 minutes ago
CSU_Dynasty | 11 | 2.28 | Windows 7 | 62 | tune_imbalance3 | seconds ago
velislav | 2 | 1.59 | Linux 3.10.0-123.8.1.el7.x86_64 | 62 | tune_imbalance3 | 3 minutes ago
drabel | 1 | 1.92 | Windows 10 | 62 | tune_imbalance3 | seconds ago
JojoM | 2 | 1.82 | Linux 4.4.0-43-Microsoft | 62 | tune_imbalance3 | 7 minutes ago
bcross | 3 | 1.37 | Windows 10 | 62 | tune_imbalance3 | seconds ago
ronaldjerum | 3 | 2.09 | Linux 4.4.0-108-generic | 62 | tune_imbalance3 | seconds ago
marrco | 7 | 1.54 | Windows 8.1 | 62 | tune_imbalance3 | seconds ago
dex | 7 | 1.50 | Windows 10 | 62 | tune_imbalance3 | seconds ago
Thanar | 3 | 0.75 | Windows 7 | 62 | tune_imbalance3 | 3 minutes ago
Vizvezdenec | 1 | 2.17 | Windows 8.1 | 62 | tune_imbalance3 | 4 minutes ago
basepi | 1 | 0.00 | Linux 4.4.0-87-generic | 62 | tune_imbalance3 | 19 minutes ago
JojoM | 7 | 0.00 | Linux 3.16.0-4-amd64 | 62 | tune_imbalance3 | seconds ago
Thanar | 3 | 1.29 | Windows 10 | 62 | tune_imbalance3 | seconds ago
ronaldjerum | 11 | 0.00 | Linux 4.4.0-112-generic | 62 | tune_imbalance3 | seconds ago
JojoM | 7 | 1.20 | Linux 3.16.0-4-amd64 | 62 | tune_imbalance3 | seconds ago
Allonautilus | 3 | 1.08 | Linux 3.19.8-100.fc20.x86_64 | 62 | tune_imbalance3 | seconds ago
davar | 3 | 2.04 | Windows 8.1 | 62 | tune_imbalance3 | seconds ago
ronaldjerum | 3 | 2.64 | Darwin 17.3.0 | 62 | tune_imbalance3 | seconds ago
rkl | 2 | 2.14 | Linux 4.15.7-1.el7.elrepo.x86_64 | 62 | tune_imbalance3 | 3 minutes ago
solarlight | 3 | 2.83 | Windows 10 | 62 | tune_imbalance3 | seconds ago
velislav | 3 | 2.13 | Linux 4.13.0-36-generic | 62 | tune_imbalance3 | seconds ago

**Comment by tomtor** [comment]
@Stefano80 After 2 hours the situation normalises (see also first comment). Could it be related to the server restart?

**Comment by ppigazzini** [comment]
@tomtor server RAM and CPU are OK, these are the jobs scheduled (btw the last one is not operative)

```
fishtest@tests:~$ crontab -l
# Backup mongodb database every hour and upload to s3
2 * * * * ~/fishtest/fishtest/utils/backup.sh

# Remove clients that are not updating any more
*/5 * * * * ~/fishtest/fishtest/utils/scavenge.py

# Update the users table
*/29 * * * * ~/fishtest/fishtest/utils/update_users.py

# Restart server every six hours
20 */6 * * * ./start.sh
```

**Comment by tomtor** [comment]
@Stefano80 Note that we also have the old problem that running tasks are sometimes not shown in the Overview, but present on the next refresh. Might be related.

**Comment by tomtor** [comment]
@ppigazzini What is the cpu load that top shows? Can you paste a top output? 

How many (virtual) cores has this server and any idea of the over-commit ratio of the provider?

**Comment by ppigazzini** [comment]
@tomtor I don't have information on the ISP, these the information retrieved:
- VM: Virtuozzo
- CPU: 3 cores Intel(R) Xeon(R) X5675 @ 3.07GHz
- RAM: 3 GB
- Disk: 54 GB
-  OS: CentOS 6.8

```
top - 17:03:45 up  3:43,  1 user,  load average: 1.53, 1.71, 1.38
Tasks:  27 total,   1 running,  26 sleeping,   0 stopped,   0 zombie
Cpu(s):  1.0%us,  3.5%sy, 31.6%ni, 63.9%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  3145728k used,        0k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  2413516k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  663 fishtest  25   5  914m 492m 2844 S 87.9 16.0 102:49.97 python
  637 fishtest  25   5 8919m 725m 572m S 17.3 23.6  68:25.74 mongod
 1677 fishtest  20   0  108m  12m 4308 S  6.3  0.4   0:02.09 s3put
    1 root      20   0 19232  752  512 S  0.0  0.0   0:00.01 init
    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd/1988
    3 root      20   0     0    0    0 S  0.0  0.0   0:00.00 khelper/1988
```

```
~$ free
             total       used       free     shared    buffers     cached
Mem:       3145728    3036540     109188       3076          0    2118352
-/+ buffers/cache:     918188    2227540
Swap:            0          0          0
```

```
~$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/simfs      52428800 14669428  37759372  28% /
none             1572864        4   1572860   1% /dev
none             1572864        0   1572864   0% /dev/shm
```

**Comment by xoto10** [comment]
"but the /api/request_task (much less data and called once every 1000 games) often times out"

I suspect this is because the request is slow. I assume there are thousands of tasks and there is no index on that collection. My patch to create two indexes should improve this a lot.

**Comment by xoto10** [comment]
On the inconsistent output, runs are updated in 2 or 3 stages in parts of rundb.py instead of waiting until all the processing is finished and then doing the update. I intend to look at this at some point, there is a chance this will improve some of the inconsistent outputs we are seeing. One example, sometimes when a test finishes it shows up twice in the finished tests list.

**Comment by tomtor** [comment]
@xoto10 Thanks, any suggestions on the occasional not shown task?

I have no mongodb experience, can queries retrieve incomplete results in our simple setup?

**Comment by xoto10** [comment]
I don't know. I assume the updates are atomic when they get done, so the
staged updates that update some fields/other data, then some more, then
some more ... are the main candidate for causing problems. But I'm not
certain. Maybe it's some other issue I haven't considered, my day job is
with relational DBs so I'm not familiar with products like MongoDB.

We seem to have a few routes for improving things, so the obvious approach
seems to be to do the simplest ones and then reassess ...
e.g. the multi-threading idea sounds attractive, but I'm not sure it's
required for our transaction numbers. Nothing wrong with doing the easy
steps towards a multi-threaded server, but I wouldn't expect to need to
implement it.

**Comment by Stefano80** [comment]
Hi @tomtor , I noticed one point. At the moment, the `updater.py` downloads the full github zip locally. I am wondering whether this is sensible. Could'nt we just download the `worker.py` and be done with it? This would avoid overloading the github repository.

**Comment by Stefano80** [comment]
I also do not agree completely with your analysis. For instance, the traffic for worker update is directed to github, whereas the task requests are directed to our server, so why should they collide?

I think this has been a very transient problem of all workers wanting to update the version at once, maybe we just should add a random time of up to 5 min when the worker must be updated. This would avoid the effect that many workers going on a LTC simplification started before a worker update want to update simultaneously upon finishing the patch. This effectively launch a small DOS against our own repository! Maybe github even reduce bandwidth in the case of too many concurrent requests.

**Comment by tomtor** [comment]
@Stefano80 @xoto10 I did some reading and it appears that waitress which is configured in `production.ini` IS a threading webserver.
The fact that fishtest works without applying https://github.com/glinscott/fishtest/pull/157 with waitress and needs https://github.com/glinscott/fishtest/pull/157 with gunicorn hints that waitress synchronizes access to a specific API. Concurrent access to different APIs is allowed.

This explains the garbled status output, it is simply caused by concurrent execution of updates and queries. This could be solved by adding some additional synchronization to https://github.com/glinscott/fishtest/pull/157. If this has a significant performance impact on the frequent executed Overview page then we should apply https://github.com/glinscott/fishtest/pull/153

I will first try to locally reproduce the garbled status display and test if this can be fixed with additional synchronization and what the performance implication are without applying https://github.com/glinscott/fishtest/pull/153

It would be good to research if applying https://github.com/glinscott/fishtest/pull/153 is possible on the current running server with its older framework/python version. Perhaps install pyramid_beaker by hand and drop the pyramid_make references. At some time we really should do a clean install.

**Comment by tomtor** [comment]
@ppigazzini What do you think about the software upgrade options/strategy, see previous comment.

**Comment by tomtor** [comment]
@xoto10 @Stefano80 I see now that request_version has the timeout, not request_task. Weird, request_version should be a very efficient call.

Regarding updating the worker,  I agree with @Stefano80  that we could add an addional random delay before downloading the zip, but note that we already have the random delay before request_version, which will also effect the zip download.

**Comment by Stefano80** [comment]
@tomtor : well not that weird if the server is busy sending spsa parameters all over the place. 

> but note that we already have the random delay before request_version, which will also effect the zip download

By reading this, I though about following scenario: everybody have asked for spsa parameters, the server needs time to satisfy those. In the meanwhile, a lot of requests for the new version have been issued. As the last spsa json file is sent over the network, the server just satisfy the version requests very quickly after the other, sending everybody to the github server almost simultaneously where they start downloading the full repo. Are HTTP requests queued, stacked or just answered in some random fashion? If they are queued, then I think the above scenario is well possible and could have been happened as I merged, stopped everything and restarted Stefan's patch: because we had simultaneously a lot of reqs for a new worker as well as a lot of reqs for spsa parameters.

**Comment by tomtor** [comment]
@Stefano80 @ppigazzini  I don't think it is related to SPSA. About one hour ago the same problem, request_task() failed this time, request_version() now was OK and no SPSA running.

It's a mystery to me, we should try gunicorn at a later time at the server, if the ThreadSafe PR gets merged. Just starting it from the command-line, should have minimal impact if it does or does not work. Just restart the normal pserve if fishtest misbehaves. Perhaps making a MongoDb backup first to be safe.

**Comment by ppigazzini** [comment]
@tomtor 
- new server: I and @Stefano80 already discussed to switch to a new server. I'm not confident to update the official server because I don't have access to the ISP control panel
- MongoDB backup: it's very easy but we should check if a DB restore with running workers can result in a polluted DB

**Comment by glinscott** [comment]
The DB is already backed up every day into the `~/backups` folder.  I wouldn't trust mongo to restore while users were connected though, so it might be a little downtime.

@ppigazzini RE: access to control panel - I don't see a nice way to do access to only one server there unfortunately, otherwise I'd be more than happy to give you access.  Thinking of upgrading the OS?  If so, I'd be happy to help.

**Comment by xoto10** [comment]
I think it's a bit early to be thinking about a new server. We've made some changes which appear to have helped and we have some more to make. We should make the easy fixes to the software before doing more radical stuff.

On the timeouts, I've coded some print changes in worker.py to flush the output and output some times, see [this commit](https://github.com/xoto10/fishtest/commit/5b3495eeadaf141c58a03a35d70c0bc3faa9b557). My home fishtest blew up again just as I was getting ready to push the changes and create a PR but I've pushed the change so you can see it. The flush() is useful because otherwise the timing of the output is confusing, and it also outputs the time taken for the version request and task request.

**Comment by ppigazzini** [comment]
@glinscott should be very useful to have the official server running with latest CentOS and packages. In that way we could test the patches on a development server before committing to the official. I sent at your personal mail a script to install and setup a fishtest server, let me know.

**Comment by marrco** [comment]
@snicolet I just received an answer from a friend working at a large cloud provider about sponsorship. If Stephan contacts me privately (marrco (at) gmail) maybe we could try getting some more resources for fishtest.

**Comment by tomtor** [comment]
@Stefano80 @xoto10 @ppigazzini 

See https://github.com/glinscott/fishtest/pull/163 which explains why a cheap request_version call fails with the current large number of workers.

**Comment by tomtor** [comment]
Most of this issue has been solved by adding some locks/semaphores but occasionally active workers are not shown.

This is caused by a MongoDb index combined with a search:

    def get_unfinished_runs(self):
        return self.runs.find({'finished': False},
                          sort=[('last_updated', DESCENDING), ('start_time', DESCENDING)])

which skips some entries while being updated, see:
 https://blog.meteor.com/mongodb-queries-dont-always-return-all-matching-documents-654b6594a827

Probably not worth fixing, but a possible solution would be to share the lock between update_task and get_unfinished_runs

**Comment by tomtor** [comment]
@Stefano80 @ppigazzini I think that this can be closed now. The last cosmetic issue is that after a completed sprt run, the test is shortly listed twice in completed. Perhaps we should open a new issue for that...
