### ISSUE TITLE
Remaining time calculation is incorrect

### ISSUE THREAD

**Issue by maximmasiutin** [glinscott/fishtest#1593]
The "Time remaining" value is calculated incorrect. For example, there is one LTC SMP test (117160 games played so far) and 2670 cores connected and active. The number of cores does not change. The overview page says "Time remaining: 1.5h". However after one hour and a half, there is still "Time remaining: 1.5h". The number of games in the test increases as the time passes, but the "Time remaining" does not decrease. This can be also reproduced with an STC game; the "Time remaining" decreases, but very slowly; i.e. it tells time remaining 4.1 hours, but after 4 hours it tells time remaining 3.5 hours.

![calculation](https://user-images.githubusercontent.com/25011752/231099143-c2189b1d-0973-4e9f-92cb-1799a07f3aed.png)

**Comment by ppigazzini** [comment]
There are few open PRs to improve the estimate (too much of a good thing), and a proposal to write a statistical sound estimate, see https://github.com/glinscott/fishtest/pull/1545 https://github.com/glinscott/fishtest/pull/1567 https://github.com/glinscott/fishtest/pull/1568

**Comment by maximmasiutin** [comment]
OK, thank you. BTW, one hour passed, there are 137352 games passed in that test already (vs 117160 a hour ago) but the estimate is still 1.5h.

![one-hour-passed](https://user-images.githubusercontent.com/25011752/231120044-dd336d3b-e73a-4257-bcce-d53894365a35.png)

**Comment by dubslow** [comment]
The obvious root issue is that we don't know, a priori, how many games a SPRT test will have. That's the core issue.
