### ISSUE TITLE
Tests take a long time to finish

### ISSUE THREAD

**Issue by xoto10** [glinscott/fishtest#1602]
We have a very powerful test rig, and yet tests seem to take a long time to finish. This seems like a problem to me. It's frustrating for devs - it discourages waiting for a test result and encourages starting several variations of the same test at the same time. Which makes tests take even longer. Recent work on performance has also highlighted how having a higher number of unfinished tests loads the server more, increasing the risk of wastage, or even crashes.

It seems to me that if we have ~5000 cores, the total throughput is roughly fixed, but we can choose whether to run 80 tests at a time and have them take 24 hours each on average, or run 40 at a time and have them take 12 hours on average. (Made up numbers, but not miles out, I think they give the general idea.)

Q. Personally, I would prefer to see fishtest running 30-40 tests at a time, rather than the recent 60/70 or even more. What do others think?

Q. I think we should implement some kind of restriction on the width of the test queue. We could use priority or itp to achieve this, but there are probably other ways too. What do people think?

To be clear, I am not suggesting stopping devs from submitting tests, I am suggesting we e.g. only run 40 at most at a time, and later tests queue up with no cores until some of the earlier ones finish. This would help tests finish faster (once they start, ofc) and reduces load on the server, helping it stay stable when the number of machines connected is a lot higher than usual.

Edited for clarity. 23/04/17

**Comment by dubslow** [comment]
If the "equal-spread" priority isn't good enough, then we can certainly adjust the itp weight to include a weight-by-test-duration term. Frankly the weight-by-games-played is already sorta close to this, but not quite the same.

Keep in mind the reason for the current system: any given test may take only a couple thousand games or may take 800k, and most near the average. Adjusting itp to reduce the *spread* of the latency would have the effect of increasing the latency of short tests, but then again that may be worth the trade off of reducing long tests.

**Comment by dubslow** [comment]
If want you meant was "make another stage between pending approval and active", where submitted tests are queued but not yet receiving games, then I'd be ~okay with that, altho it would take more effort than tweaking itp.

**Comment by xoto10** [comment]
> Restricting submissions would only worsen submitter morale. Believe me my submitter morale is already fairly low, but I did a lot over winter so I'm trying to let others have their shot.

No, I am not thinking of restricting submissions, just altering how they (sprt tests) run.

A manual approach using priority could be:
- change the default prio to be -1 when sprts are created
- let approvers change prio to 0 when there are < X active tests
(devs would use -9 or something to pause tests)

Tests would run quicker, and there would be a steady stream of stcs finishing, allowing queued up jobs to start regularly.
It wouldn't be a big deal if the number of jobs was (X+1) or (X-10) at times when approvers are missing or whatever, the general idea is still achieved.

**Comment by pb00068** [comment]
>>What do people think?

My opinion is, that we should provide a more equal distribution of cores.
This by restricting the bandwith per submitter, when queue is long (= remaining hours is big.)
This regardless how 'successful' or not a submitter is/was.
For instance:
- no restriction in bandwith for a submitter when overall remaining hours  < 24 or one of his tests has prio > 0
- otherwise limit the assigned cores per submitter to the percentage of active users.
  maxCoresPerSubmitter =   cores / activeUsers
  Example: 40 active tests submitted by 10 different users, 5000 cores available.
  maxCoresPerSubmitter = 500
  
  For instance this would now in the moment reduce the amout of cores used by the most taxing submitter from 1317 to 534.

**Comment by xoto10** [comment]
Interesting.

An upside of this approach is that it gives control to the user. If they want all their allocation on one test, they can just run one test and get many cores on that test instead of most of them going to other devs. If they want to run several tests at once (with fewer cores per test) they can do that instead.

**Comment by dubslow** [comment]
That idea would not work, as LTCs require more work than STCs. You'd want to adjust on a per-test level, to achieve the sort of balancing you desire. But on a per-test basis, I *might* be okay with it.

And we have a long history of not weighting by submitter, as we argued to atumanian over and over again. 

And it would certainly lead to oddball scenarios where a submitter with only one STC has their test going much faster than the average STC on the server. I'm like -0.5 on this idea overall.

**Comment by xoto10** [comment]
To try and understand the code better, I've attempted some code for rundb.py that would add a timer to update runs from prio -1 to prio 0, assuming tests are initially set to prio -1 and we don't want more than 40 active runs:
```
[ after start_timer() ]
    def start_new_test_timer(self):
        self.new_test_timer = threading.Timer(60, self.check_new_tests)
        self.new_test_timer.start()

[ in buffer() ]
            if self.new_test_timer is None:
                self.start_new_test_timer()

[ after flush_buffers() ]
    def check_new_tests(self):
        if self.new_test_timer is None:
            return

        with self.run_lock:
            n = len(self.active_runs)

        if n < 40:
            with self.run_cache_write_lock:
                runs_to_start = self.runs.find(
                    {"finished": False, "args.priority": -1}, {"_id": 1},
                    sort=[("results.draws", DESCENDING), ("last_updated", ASCENDING)]
                    # really want to sort by w+l+d, not just draws
                )

            if runs_to_start:
                try:
                    self.run_cache_lock.acquire()

                    for r in runs_to_start:
                        if n >= 40:
                            break
                        run = self.get_run(r["_id"])
                        run["args"]["priority"] = 0
                        self.buffer(run, False)
                        n = n + 1
                except:
                    print("Check new tests exception", flush=True)
                finally:
                    # Restart timer:
                    self.run_cache_lock.release()
                    self.start_new_test_timer()
```
