### ISSUE TITLE
Unneccessary get_machines query to db

### ISSUE THREAD

**Issue by peregrineshahin** [glinscott/fishtest#1620]
Duplicate logic (queries) exists in getting homepage results.
There is no need to call get_machines in getting homepage results because we can already obtain the information after calling `aggregate_unfinished_runs` that call `get_unfinished_runs` which has the information about all tasks and workers with up-to-date values from the cache_lock.

Fixing this redundant query would remove an essential slowdown in building the home page.

**Comment by peregrineshahin** [comment]
so just to visualize it

```
get_machines() => queries A from DB
aggregate_unfinished_runs() => get_unfinished_runs() => queries A
```
instead, the logic should be
```
result = get_unfinished_runs() => queries A
get_machines(result)
aggregate_unfinished_runs(result)
```
This will leave us with 1 call over query A, but not sure I can get it right with Python.

**Comment by vdbergh** [comment]
Seems indeed trivial to implement. Nice catch.

**Comment by vondele** [comment]
not unrelated to https://github.com/glinscott/fishtest/pull/1596

**Comment by vondele** [comment]
we could get down from 3 calls to 1 call, IIUC

**Comment by vdbergh** [comment]
> we could get down from 3 calls to 1 call, IIUC

Yes. Get the unfinished runs once and move from there.

**Comment by vdbergh** [comment]
So who will do it?

**Comment by vdbergh** [comment]
I can do it tonight.

**Comment by vdbergh** [comment]
I just did it but I need to test it tonight.

**Comment by peregrineshahin** [comment]
Fixed with https://github.com/glinscott/fishtest/pull/1621
