### ISSUE TITLE
Implement a cutechess-cli test at startup

### ISSUE THREAD

**Issue by maximmasiutin** [glinscott/fishtest#1622]
Implement a cutechess-cli test at startup of a worker to make sure that cutechess-cli is working correctly and a failure of cutechess-cli should not be attributed to a failure of the patch being tested. It may be tested against a predefined position and the result should be compared, e.g. a position of https://syzygy-tables.info/?fen=2nbk3/8/8/8/8/8/4P3/4K3_w_-_-_0_1 

This test should be run after compiling the engines but before the first "real" run on the two engines. If this test between the two "master" engines completes successfully, the worker may further proceed with playing games got from the server. Another option is not to run on a predefined game, but that if a first ever cutechess-cli run since worker startup fails, it does not affect the tested patch but disqualifies the worker.

**Comment by vdbergh** [comment]
cutechess-cli is already checked before start up ( `--version`).

**Comment by maximmasiutin** [comment]
> cutechess-cli is already checked before start up ( `--version`).

By test I meant conducting a game by engines; the `--version` command line does not involve a game.

**Comment by vdbergh** [comment]
It seems highly unlikely that `cutechess --version` works but that an error would appear later.
