### ISSUE TITLE
Server is not accessible

### ISSUE THREAD

**Issue by Def9Infinite** [glinscott/fishtest#1642]
```
Worker version 201 connecting to https://tests.stockfishchess.org:443
Confirming supplied credentials with https://tests.stockfishchess.org:443
Exception in requests.post():
HTTPSConnectionPool(host='tests.stockfishchess.org', port=443): Read timed out. (read timeout=30.0)
```

Seems like server is down again? Able to access the gui but workers are not able to access it. (CPU usage looks anomaly from monitoring)
![image](https://user-images.githubusercontent.com/34544962/235224197-85b5537e-cc53-412b-b300-976c17d10a54.png)

**Comment by ppigazzini** [comment]
We have restarted the server, try now.

**Comment by Def9Infinite** [comment]
Ah I see. Server seems to be back now (workers are working right now), will follow up if occurs again
