### ISSUE TITLE
Batch size calculation can blow up due to task count

### ISSUE THREAD

**Issue by Sopel97** [glinscott/fishtest#1661]
https://github.com/glinscott/fishtest/blob/68faa547232ad9a99f4a8d5acf13f216a744f0c3/server/fishtest/rundb.py#L668

It doesn't make much sense for this to depend on the number of tasks, because the number of tasks does not reflect the length of a test, and in extreme cases, for example here https://tests.stockfishchess.org/tests/view/642df05c77ff3301150e87f2, it can result in huge overestimates.

**Comment by vondele** [comment]
current code is different 
https://github.com/glinscott/fishtest/commit/473c40b81224e48d93d0704ac42c6d817f473de5
