### ISSUE TITLE
api_active_runs does extra unnecessary stuff.

### ISSUE THREAD

**Issue by peregrineshahin** [glinscott/fishtest#1672]
Now that get_unfinished_runs always queries stuff from the db, it makes no sense to query all fields from db and then strip the data to only wanted fields, rather the logic should be to no stripping runs and query only the stuff we want to show from the first place.

**Comment by peregrineshahin** [comment]
(Should be trivial to implement also).

**Comment by vdbergh** [comment]
I wonder if Mongodb is actually smart enough to optimize this. Or will it simply fetch the documents from the db and then throw away the unwanted stuff?

**Comment by vondele** [comment]
if it can do this in the bson format, it would still be a significant win (i.e. before it is converted to native python), also if done in mongo and not it the pserve, it would probably be threaded and not be GIL bound.
