### ISSUE TITLE
Multiple changes that I made seems to improve worker stability

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#169]
https://github.com/glinscott/fishtest/blob/2b73ca009cdae1fb9b0dffeb960a661892fb0f46/worker/games.py#L152

In case of source code download timed out, exception is raised and assigned job got stuck on server and can only wait for scavenging.

This can be fixed by giving a number of retries and then properly report failure to server in order to get job reassigned.

**Comment by noobpwnftw** [comment]
In
https://github.com/glinscott/fishtest/blob/ba14d0bfc890c495226d0b3495ef43f509e28629/worker/requests/adapters.py#L28-L29

change to pool less connections per worker seems to have direct effect in reducing the number of connections to the server, and using the built-in retry functionality may helped to reduce the number of workers getting stuck at 0.00.

**Comment by vondele** [comment]
@noobpwnftw what about making two pull requests for these two changes. It is not really an issue, you seem to have the solutions essentially ready. Will be more visible for the devs to judge an comment on this.

**Comment by noobpwnftw** [comment]
Well, they are just workarounds for cases that not supposed to happen. So I'd rather make one like a FYI thread instead of an "update".
