### ISSUE TITLE
Problem when modifying an SPSA tune

### ISSUE THREAD

**Issue by cj5716** [glinscott/fishtest#1714]
When changing the number of games in an SPSA tune (ie in the modify column) the number of iterations will not change. This will result in a) more games being played than `2 * iterations` or that there are not enough games being played. 

Suggested course of action:
when number of games in an SPSA tune is modified, also change the number of iterations within the system automatically.

**Comment by vondele** [comment]
I think there was some agreement that modifying a SPSA tune is not possible.Not sure if this has changed meanwhile.

**Comment by ppigazzini** [comment]
The SPSA parameters are computed only once when submitting the SPSA run with the form:
https://github.com/glinscott/fishtest/blob/604e74f70db2d0e21fd46c5f37b97fd5fc49a0ab/server/fishtest/views.py#L823-L824
https://github.com/glinscott/fishtest/blob/604e74f70db2d0e21fd46c5f37b97fd5fc49a0ab/server/fishtest/views.py#L613-L634

Then the parameters are used here:
https://github.com/glinscott/fishtest/blob/604e74f70db2d0e21fd46c5f37b97fd5fc49a0ab/server/fishtest/rundb.py#L1461-L1489

A little change in number of games/iterations could be theoretically wrong but practically not harmful, but a big change could create nonsensical parameters values (to be checked).

**Comment by vdbergh** [comment]
I have a bit forgotten how classical SPSA works, but I think that the learning rate schedule is set at the beginning and depends on the length of the test. So letting it run longer than foreseen would not be harmful but it would perhaps be less optimal than when the length was correctly given at the beginning. But I think it does not matter much.

**Comment by ppigazzini** [comment]
By the way our SPSA parallel implementation still have a problem when many workers get the same first parameters values. Without the noise they contribute the same vector displacement, over pushing the searching point. After some iterations the framework distributes the parameter with more serialization. To make a long story short, we should distribute the same SPSA 
parameters a Max number.
