### ISSUE TITLE
SF crash

### ISSUE THREAD

**Issue by threeCheck** [glinscott/fishtest#1731]
Hi there!

Recently I created an issue in Official_Stockfish but my issue is missing now and I can't create it again.

My issue details is:

```
Stockfish 15 by the Stockfish developers (see AUTHORS file)
position fen 2r3rk/6p1/3pPpqp/pp1N1P2/3b1P1R/Pp3Q1K/7P/8 w - - 0 42
go depth 33
```

Can anyone help me?

**Comment by ppigazzini** [comment]
fishtest is the testing framework in python.
Please submit your question to the Discord server in the "support" channel
https://discord.com/invite/awnh2qZfTT

**Comment by threeChecks** [comment]
@ppigazzini Thanks for Guidance but I'm not join in Discord. 

![_woochess](https://github.com/glinscott/fishtest/assets/136655730/653ee48d-3761-4d84-b217-e5148ee0221b)

**Fishtest means Stockfish test , So if SF crash then fishtest maybe crash**

1-Open Stockfish 15
2-position fen 2r3rk/6p1/3pPpqp/pp1N1P2/3b1P1R/Pp3Q1K/7P/8 w - - 0 42
3-go depth 33

You or @vdbergh can do this simple test , Please reopen this issue if Sf crashed else send info depth 33 and bestmove here.

Best Regards

**Comment by noobpwnftw** [comment]
No troll, you just messed up with your alts.

**Comment by ChessNoob** [comment]
@threeCheck your issue is not missing but Official_Stockfish Admins Blocked you and deleted your issue. 
You can report this  to Marco Costalba.

mcostalba@gmail.com
