### ISSUE TITLE
Is 'tests.stockfish.org' down?

### ISSUE THREAD

**Issue by LunaticBFF57** [glinscott/fishtest#1734]
Hello, I was attempting to run the Stockfish worker on my laptop and kept getting this error saying that I can't connect to the server.
This is the error message that I get:
```
Current time is 2023-06-18 13:43:23.804244 UTC (local offset: +10:00)
Verify worker version...
Exception in requests.post():
HTTPSConnectionPool(host='tests.stockfishchess.org', port=443): Max retries exceeded with url: /api/request_version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001d8c9673250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Waiting 900.0 seconds before retrying
```
I tried to access the page via Firefox, and then Chrome, but even the website cannot be loaded. Is this an issue on my end or is everyone else getting the same errors?

Edit: Checked my existing workers and they also spit out similar errors as well.

**Comment by ppigazzini** [comment]
The nginx admin fixed the issue with nginx version.
