### ISSUE TITLE
Is Fishtest Elo result reproducable from Pentanomial distribution or WDL?

### ISSUE THREAD

**Issue by peregrineshahin** [glinscott/fishtest#1737]
This is not necessarily an issue, I want to ask the math specialists in Fishtest (especially @vdbergh if he may) if the get_elo function in live elo can be reproduced only knowing WDL or Pentanomial distribution.

If not, how could we explain failing Red with positive Elo and failing Yellow with negative Elo?

**Comment by dav1312** [comment]
> If not, how could we explain failing Red with positive Elo and failing Yellow with negative Elo?

Examples?

**Comment by peregrineshahin** [comment]
Red with positive Elo https://tests.stockfishchess.org/tests/view/63541343fa69565f265c308d
Blue with W > L and negative Elo: https://tests.stockfishchess.org/tests/view/640fb39965775d3b539d2a78

**Comment by peregrineshahin** [comment]
Closing as per this

```
from stats.stat_util import SPRT_elo

results = {"losses" : 51917, "draws": 89164, "wins":51959, "pentanomial": [93, 18711, 58877, 18739, 100] }
alpha = 0.05
beta = 0.05
elo0 = -1.75
elo1 = 0.25
elo_model = "normalized"
a = SPRT_elo(
                results,
                alpha=alpha,
                beta=beta,
                elo0=elo0,
                elo1=elo1,
                elo_model=elo_model,
            )
print(a)

// output
{'a': -2.9444389791664403, 'b': 2.9444389791664403, 'elo': -0.06778116713881258, 'ci': [-0.8466362878788467, 0.6601080796952428], 'LOS': 0.4287935384362421, 'LLR': 2.9420974720708513}

https://tests.stockfishchess.org/tests/live_elo/640fb39965775d3b539d2a78
```
