### ISSUE TITLE
Enable the discussion section 

### ISSUE THREAD

**Issue by ChessOverflow** [glinscott/fishtest#1751]
@ppigazzini 
Hi, Pasquale!

The importance of the Fishtest repository is not less than the Stockfish repository, maybe more.

Newcomers may want to ask questions or share ideas with you.

- [x] General

- [ ] Ideas

- [ ] Polls

- [ ] Question & Answer

- [ ] Show & Tell

For this purpose, I request you to enable the discussion section in this forum.
Thank you ❤️

**Comment by ppigazzini** [comment]
I have only the collaborator role for the repository, no access to the repository configuration.

**Comment by ChessOverflow** [comment]
I request @glinscott to enable the discussion section for Fishtest. I hope this option will be activated as soon as possible.

**Comment by ppigazzini** [comment]
Feel free to open issues here about fishtest (server and worker).
I'm active on the Stockfish server on Discord as well, I usually help there on compilers, but I'm not a Stockfish developer.

**Comment by ChessOverflow** [comment]
Thank you so much, I am glad to see you 🥰

Asking my questions in the issue section may not be professional.

I will wait until the discussion section is enabled and then I will ask my questions.

**Comment by ChessOverflow** [comment]
To solve this issue, I have created @official-fishtest. I invite @ppigazzini to join this organization as an owner role.
With the help of other members, this organization will grow and become as strong as @official-stockfish in the future.

**Comment by ChessOverflow** [comment]
@ppigazzini Would you allow me to activate the discussion section?

**Comment by ChessOverflow** [comment]
It seems that fishtest admins are not interested in building @official-fishtest, my goal was to build a  better organization where **honesty** and **freedom** come first.
