### ISSUE TITLE
I can't perform action on the stockfish repository.

### ISSUE THREAD

**Issue by KasparovChess** [glinscott/fishtest#1752]
Hello dear administrator @ppigazzini ,I recently created a PR that you and a few others(@ddobbelaere) posted on.

- https://github.com/official-stockfish/Stockfish/pull/4720

But now when I want to post a comment, I can't and I have the following error message:

![image](https://github.com/glinscott/fishtest/assets/121145620/a7a14a79-556f-4f43-acff-4a2a880691a1)

Who made this restriction(@snicolet?) and how should I fix it?

Thanks

**Comment by ppigazzini** [comment]
<https://github.com/googleads/googleads-mobile-unity/issues/397>

It could be a random problem with Github. Try to logoff, clear the browser cache (CRTL + F5), and login.

**Comment by KasparovChess** [comment]
> considering how the regex only detects illegal fens and all the fens in `bench` command is legal
> 
> _Originally posted by @cj5716 in https://github.com/official-stockfish/Stockfish/issues/4720#issuecomment-1666445556_

@mhouppin Do you deny that this account is related with you?

**Comment by ppigazzini** [comment]
We know that the fishtest repo is not the appropriate place to argue about Stockfish and/or with other people.
Please consider that the maintainer role is taxing.

**Comment by mhouppin** [comment]
> > _Originally posted by @cj5716 in [official-stockfish/Stockfish#4720 (comment)](https://github.com/official-stockfish/Stockfish/pull/4720#issuecomment-1666445556)_
> 
> @mhouppin Do you deny that this account is related with you?

I don't see how this is related to me interacting with you. I'm not responsible for what a contributor to Stash writes on other repositories. Please refrain from pinging me here.
