### ISSUE TITLE
No tasks available at this time, waiting...

### ISSUE THREAD

**Issue by mstembera** [glinscott/fishtest#185]
I regularly get the below:
```
No tasks available at this time, waiting...
Will fetch task soon...
```
This is while the web page is showing several tests running in the que as well as other approved tests waiting.  After some wait this message repeats again over and over.  My machine goes largely unutilized as a result.

**Comment by Stefano80** [comment]
Do you still have the problem?

**Comment by mstembera** [comment]
@Stefano80 
Not in the last day.  I will reopen if it returns.  Thanks.
