### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by MJZ1977** [glinscott/fishtest#189]
Hello Everyone,

I'am new to fishtest and to this community but i'a eager to participate to stockfish as chess player and developper. So sorry if my first issue is a beginner one...
So I followed steps described for first test and I have a problem in the last step
command : git push origin my_branch
remote: Permission to official-stockfish/Stockfish.git denied to MJZ1977

Can you please help me ? how can I have permission?

Thank you in advance
MJ

**Comment by ppigazzini** [comment]
@MJZ1977 welcome to Stockfish and fishtest projects. In this place we keep only the issues about fishtest code, please post your request to the [Stockfish forum](https://groups.google.com/forum/#!forum/fishcooking) where you will find help from others contributors. Have a nice day.
