### ISSUE TITLE
Using hyperthreaded cores

### ISSUE THREAD

**Issue by 4616** [glinscott/fishtest#20]
The README states that: "Option concurrency refers to the number of available cores in your system (not including Hyperthreaded cores!), leaving one core for the OS." I have 4 cores x 2 threads per core on Windows 7. When I set concurrency to 7, it simulates 7 games at a time with no problem and seems to run faster than if I just use concurrency 4. In the task manager concurrency 4 runs at 50% CPU while concurrency 7 is at roughly 90%. What am I missing?

**Comment by sachess** [comment]
yes, I also want to know the details like this:


LLR: -2.96 (-2.94,2.94) [0.00,6.00]

(second line is easy to read )

**Comment by Stefano80** [comment]
I close this as this is not really an issue.
