### ISSUE TITLE
Auto purge and test restart

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#216]
Today I had the following test turn green
http://tests.stockfishchess.org/tests/view/5ac2c15f0ebc591746423fa3
then some high residuals workers were purged, and my test ended up in the Finished section.
But the LLR was only 2.63. 
Usually in such cases, the test reappear automatically in the Pending section.

I was able to click Modify, the test appeared in the Pending section, and after a while, new workers took care of the test.

_Maybe we should not stop all the workers when the residual clean up is done, 
(only the bad residual ones...) and only if LLR > 2.96 the test can be "stopped"..._

It just happened again

EDIT: OK, the exaplnation is simple. It turned out that a worker reported a wrong bench and stopped the test...2 times ! (and stopped three other tests too !)
https://groups.google.com/d/msg/fishcooking/YxEgBcdnaH8/9Wk3g6ySAgAJ

It would be great if approvers had power to block problematic workers until their owner is contacted.

I will close the issue tomorrow.

**Comment by tomtor** [comment]
@ppigazzini @Stefano80 I intend to write a block/unblock function (some users are blocked now directly in the fishtest source code :/ ) and show the eMail address of users to approvers. 

IMO we should not implement https://github.com/glinscott/fishtest/issues/100 but just block those users, because I cannot think of a technical reason why those workers give wrong bench numbers, aside from having the worker installed in a very strange way.

**Comment by Stefano80** [comment]
Hi @tomtor, I think your solution would be better than this one. I also feel we should understand what is going on with those users.

**Comment by Vizvezdenec** [comment]
Yeah, just saying that users like biffhero also participate in wrong bench blocking of tests and yet he is top-30 contributor, same with mgrabiak. Looking at their usual amount of games/hour my guess that they were donating their CPUs since early fishtest days.

**Comment by ppigazzini** [comment]
@tomtor now the users are classified using the 'groups' field (field values: 'approvers', 'admin', 'stats'). A solution could be to add a couple of new values, the first one for a temporary suspension, the second one for a perpetual ban.
