### ISSUE TITLE
Autoapproval?

### ISSUE THREAD

**Issue by Stefano80** [glinscott/fishtest#229]
It happened to me three times to day that my patch became active automatically without need for approval. This is bad.

Do we have some autoapproval mechanism no one was aware of, which were exposed by recent commits? Any ideas?

**Comment by tomtor** [comment]
Yes that is the auto approval code which was hardwired to Marco, Joona, Gary and Lucas but now to every approver after the cleanup commit #220

**Comment by ppigazzini** [comment]
Solved by https://github.com/glinscott/fishtest/pull/232
