### ISSUE TITLE
Old fishtest branches: clean up?

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#238]
The Fishtest repo has few branches alongside the master, all very old. IMO we should delete the branches that are not useful anymore.

**Comment by Stefano80** [comment]
Yes, agree.

**Comment by ppigazzini** [comment]
After a review IMO all the branches could be deleted:
* [clop_ec2](https://github.com/glinscott/fishtest/tree/clop_ec2)
* [no_profile_build](https://github.com/glinscott/fishtest/tree/no_profile_build)
* [spsa](https://github.com/glinscott/fishtest/tree/spsa)
* [worker](https://github.com/glinscott/fishtest/tree/worker)

I would like to have the opinion of @glinscott
