### ISSUE TITLE
Wrong message

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#247]
Until recently, if I submit a new test and the branch had not been pushed to the remote, 
I would get  a message similar to  "Unable to find branch" 

Now, the message only says "commit"
![image](https://user-images.githubusercontent.com/8949638/39142543-000a64bc-46f9-11e8-850d-b7bf60809623.png)

**Comment by tomtor** [comment]
I get "Cannot find branch in developer repository" in #248 but this issue probably IS present in the current master. Thanks for reporting.
