### ISSUE TITLE
Unable to create new test

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#259]
At the moment I am unable to access the page to create a new test:
http://tests.stockfishchess.org/tests/run

This gives me the following error in the browser:
````
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)
````

I have tried two different browsers (Safari and Chrome), and also to logout and login back, to no avail.

Anybody having the same problem?

EDIT: here is my test history for the day, showing that I had been able to create a couple of test a couple of hours ago
http://tests.stockfishchess.org/tests/user/snicolet

**Comment by ppigazzini** [comment]
@snicolet try now, I reverted the python packages

**Comment by snicolet** [comment]
@ppigazzini 
Yes it works, thanks! :-)

May I help you somehow to bisect the package set, to figure out which package is at fault?

**Comment by ppigazzini** [comment]
@snicolet it make no sense to try to update the production server with CentOS 6.x ... On the dev-server (CentOS 7.x) it's so easy to update on the fly the fishtest server with this script

```
#!/bin/bash
# to update a fishtest server simply run:
# sudo -H bash update-fishtest.sh 2>&1 | tee update-fishtest.sh.log
#
# to use fishtest open a browser and connect to:
# http://<ip-address>

STAMP=$(date +%Y%m%d%H%M%S --utc -d '1 hour')

systemctl stop fishtest

# download and prepare fishtest
sudo -i -u fishtest << EOF
tar -czvf fishtest.$STAMP.tgz fishtest
rm -rf fishtest
git clone https://github.com/glinscott/fishtest.git

cd fishtest
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

# add here the upstream branch to be tested
#git remote add new-upstream https://github.com/tomtor/fishtest
#git pull --no-edit new-upstream CleanUsers
# add here the PR to be tested
#git pull --no-edit origin pull/254/head
#git pull --no-edit origin pull/256/head


# pull some mandatory PRs for an up to date installation
# comment out if a PR will be committed upstream
# https://github.com/glinscott/fishtest/pull/43
# https://github.com/glinscott/fishtest/pull/106
git pull --no-edit origin pull/43/head
git pull --no-edit origin pull/106/head

# setup fishtest
cd /home/fishtest/fishtest/fishtest
python setup.py develop --user
EOF

echo "repo sync finished, start the server with:"
echo "sudo systemctl start fishtest"
```

**Comment by tomtor** [comment]
@ppigazzini Could you log the error message generated on the server? I would like to know why only test creation failed with pypy.

**Comment by ppigazzini** [comment]
@tomtor sotty, my message was too much short. The installation of pypy finished with several error messages, I never started fishtest with pypy. I update a couple of python packages and this immediately broke the fishtest server, so I stopped and reverted the packages. I will stick to my plan to install a dev server w/ CentOS 6.x before try anything on the production server but it's frustrating to waste so much time baby sitting a not maintained server when a fresh install could be on line in half an hour...

**Comment by tomtor** [comment]
@ppigazzini Ah, clear. Yes, that is frustrating...
