### ISSUE TITLE
GUI and Windows Installer

### ISSUE THREAD

**Issue by 4616** [glinscott/fishtest#29]
Stockfish has a massive user base, but there are only 34 active machines currently running fishnet. A huge barrier to contributing to the project is the lack of windows installer and GUI. If there is interest in incorporating a GUI into the project, I would be willing to help work on it with some help.

**Comment by ppigazzini** [comment]
Closing because now there is a decent worker setup script for windows, see
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows
