### ISSUE TITLE
fishtest hits github api limit ?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#290]
on submitting tests:  Unable to find branch! 
also
Base signature: None

**Comment by snicolet** [comment]
I also have these error messages at the moment (22th of May, 12:46 UTC+2)

**Comment by tomtor** [comment]
These are just transient github.com errors because hitting the api limit will result in failed calls for an extended period (eg > 15 minutes).

**Comment by ppigazzini** [comment]
I keep open the newer issue https://github.com/glinscott/fishtest/issues/385 because has more information.
