### ISSUE TITLE
highlight your machines and show limit info when logging on fishtest

### ISSUE THREAD

**Issue by candirufish** [glinscott/fishtest#293]
It is quite a hassle if you run many machines on fishtest and searching yours in the list and seeing if it is running ok. I suggest highlight all of them when user is logged and put them on top of the list together with info "total machines running", "total CPUs" etc...

Another thing is if you're a newbie, you might not know there is a limit imposed on the number of machines you can put on fishtest and might think it is some error or fishtest is broken and might thwart that contributor from putting more cpus. I guess displaying this limit info when logging in is better with a button messaging admin to raise it.

**Comment by tomtor** [comment]
We show machine-limit on the user profile page for approvers. I agree that it makes sense to show that info for all users.

The overview is shared/cached between all users, but a sort button is possible.
