### ISSUE TITLE
Python code error in games.py

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#296]
https://github.com/glinscott/fishtest/blob/fab0fe8996d0d731bad2a3da484cf497823cb041/worker/games.py#L121

@Stefano80 This will give a runtime error, but the line is not reached in the happy flow, it should be 

    time.sleep(HTTP_TIMEOUT)

**Comment by tomtor** [comment]
@Stefano80 The original code was

    sleep(5)

introduced in a commit from you, so it would be best if you rechecked this code and made a PR, cq merged a fix.

**Comment by tomtor** [comment]
The idea was to prevent playing with a 0-sized book (resulting from a failed download), but setup('book') will not be called when a zero sized file exists:

https://github.com/glinscott/fishtest/blob/fab0fe8996d0d731bad2a3da484cf497823cb041/worker/games.py#L419

II really think the current code/logic is broken...

**Comment by Stefano80** [comment]
Your logic seems more robust than my (seemingly broken) fix. I will happily merge, let me test it locally first.

**Comment by Stefano80** [comment]
Just tested locally, works fine.
