### ISSUE TITLE
Unexpected behaviour in automatic submit message

### ISSUE THREAD

**Issue by Stefano80** [glinscott/fishtest#297]
I just noticed that the prefix "LTC:" is always used for non STC, even in the case in which the time control is shorter, see http://tests.stockfishchess.org/tests/view/5afdd81d0ebc591fdf408f2d

**Comment by tomtor** [comment]
Ah, good catch!

https://github.com/glinscott/fishtest/blob/fab0fe8996d0d731bad2a3da484cf497823cb041/fishtest/fishtest/views.py#L352

I will write a PR tomorrow, thanks.
