### ISSUE TITLE
More detailed worker sanity checks

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#301]
Here I face two problems:
1. Currently the worker does not check for hash memory size availability, if I run a worker that has 4GB of memory with concurrency=8, and there is a job that is asking for 256MB of Hash on 1 thread, then it will likely to have TT on swap if not failing the allocations(2*256MB*8=4GB).
2. There is a number of engines per cutechess-cli process can handle, if I have a worker that has concurrency=128, it will end up with many timeouts, this is tricky because sometimes we may need to run particular tests on very high thread concurrency, then I have to stop the worker in time or it will pollute other tests with timeouts. Maybe we should introduce a hard concurrency cap within the worker for how many engines to run in parallel.

**Comment by tomtor** [comment]
It is not hard to add some additional optional parameters to the fishtest.cfg file.

I will have a look at it.

**Comment by ppigazzini** [comment]
@noobpwnftw I merged the PR #311 and updated the production server. You should update your worker by hand. Thank you for opening this issue.
@tomtor thank you to solve it.
