### ISSUE TITLE
username 2 letters

### ISSUE THREAD

**Issue by mrobaczyk** [glinscott/fishtest#304]
Just a quick question: Is there any reason we are displaying only 2 letters of an username on overview page?

Cheers 
Mike

**Comment by tomtor** [comment]
To safe display space. Those two letters where fine when there were only a few workers and testers. I agree it is a bit restricting now and  some contributors share the same two letter prefix.

**Comment by mrobaczyk** [comment]
Yes, some testers have the same prefix, so maybe it's time to reorganize the space a little bit and expand username column :) 
Mike

**Comment by tomtor** [comment]
Expand it to 4 or even 8 characters? I suggest 4 and a mouse-over which shows full name. I will write a PR for this in the near future unless someone has a better proposal.

**Comment by tomtor** [comment]
I tried 4 but found that visually not pleasing, so I changed it to 3. Combined with the mouse-over that should be sufficient.

**Comment by mrobaczyk** [comment]
Don't we have space for entire user name? They usually are not so long :) This would be the easiest solution :)

**Comment by ppigazzini** [comment]
@mrobaczyk the PR #306 shows the complete username with a mouse-over popup
