### ISSUE TITLE
Warnings!!

### ISSUE THREAD

**Issue by ik4u** [glinscott/fishtest#307]
thread.c: In function 'thread_create':
thread.c:146:42: warning: cast between incompatible function types from 'void * (*)(void *)' to 'DWORD (*)(void *)' {aka 'long unsigned int (*)(void *)'} [-Wcast-function-type]
   HANDLE *thread = CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)thread_init, (void *)(intptr_t)idx, 0 , NULL);
                                          ^
numa.c: In function 'numa_init':
numa.c:202:17: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'BOOL (*)(LOGICAL_PROCESSOR_RELATIONSHIP,  struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *, DWORD *)' {aka 'int (*)(enum _LOGICAL_PROCESSOR_RELATIONSHIP,  struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *, long unsigned int *)'} [-Wcast-function-type]
                 (GLPIEX)GetProcAddress(GetModuleHandle("kernel32.dll"),
                 ^
numa.c:205:17: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'BOOL (*)(void *, const GROUP_AFFINITY *, struct _GROUP_AFFINITY *)' {aka 'int (*)(void *, const struct _GROUP_AFFINITY *, struct _GROUP_AFFINITY *)'} [-Wcast-function-type]
                 (STGA)GetProcAddress(GetModuleHandle("kernel32.dll"),
                 ^
numa.c:209:17: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'void * (*)(void *, void *, SIZE_T,  DWORD,  DWORD,  DWORD)' {aka 'void * (*)(void *, void *, long long unsigned int,  long unsigned int,  long unsigned int,  long unsigned int)'} [-Wcast-function-type]
                 (VAEN)GetProcAddress(GetModuleHandle("kernel32.dll"),
                 ^

**Comment by tomtor** [comment]
These are not fishtest errors. You probably want to report this in the Stockfish repo: https://github.com/official-stockfish/Stockfish
