### ISSUE TITLE
Games uploaded contain illegal FENs

### ISSUE THREAD

**Issue by Stefano80** [glinscott/fishtest#313]
I just noticed that the FENs in the games uploaded do not contain plies and move information. They are thus non compliant and cannot, e.g., be imported in python-chess.

The reason is of course that the FENs in 2moves_v1.pgn are themselves illegal. What do we do?

**Comment by ppigazzini** [comment]
[bookgen](https://github.com/ianfab/bookgen) from @ianfab uses the process described by [Dariusz Orzechowski](https://groups.google.com/forum/#!msg/fishcooking/pt9MBSQMZs0/omErNOzyxesJ) to make 2moves_v1.pgn .

**Comment by Stefano80** [comment]
The solution of the problem is quite simple, we have to replace the 2moves_v1.pgn with one containing the information.
I was wondering if we want to fix this, in which case we have to restart the old activities about porting everything from @mcostalba fishcooking to this repository. 
Any thoughts?

**Comment by ppigazzini** [comment]
Already tested with https://github.com/glinscott/fishtest/pull/240.
IMO better to use a different/new repository for opening books and cutechess-cli binaries.

**Comment by Stefano80** [comment]
You mean a different from @mcostalba fishcooking or a different from this one? I just created a branch https://github.com/Stefano80/fishtest/tree/openingBooks_v2 where I added the opening books and the cutechess binaries and libs. Could you give a look and check whether this is all what we need?

**Comment by Stefano80** [comment]
I reread #240 and now I understand. Would [git lfs](https://git-lfs.github.com/) be a solution?

**Comment by ppigazzini** [comment]
With #240 the setup of the dev-server and test workers was very slow. To avoid leftovers I test new patches deleting the fishtest folder and cloning the official fishtest repository.
I don't know [git lfs](https://git-lfs.github.com/), a new github repository should be sufficient.

**Comment by Stefano80** [comment]
Ok. My proposal would be to have an official-stockfish/resources repositories for this kind of stuff. Maybe @snicolet can give his opinion.

**Comment by ppigazzini** [comment]
Official repo for binaries and books used by fishtest
https://github.com/official-stockfish/books

**Comment by KasparovChess** [comment]
@zungur Who are you? Are you @vdbergh? Please stop the closing correct issues. It is disrespectful.

https://web.archive.org/web/20230808180623/https://github.com/official-stockfish/Stockfish/pull/4720

**Comment by ppigazzini** [comment]
https://github.com/official-stockfish/Stockfish/wiki/Governance-and-responsibilities#fishtest
He is one of the fishtest maintainers, he has simply closed old issues dedicating his spare time contributing to the project.

It was my fault to not have properly written the status of the Issue during my review.

- The issue is solved (courtesy of `cutechess-cli` I suppose), the pgn uploaded by the workers have complete FENs, see
```
[Event "Batch 0: prevBonusSE3 vs master"]
[Site "https://tests.stockfishchess.org/tests/view/64d3efdc5b17f7c21c0e185b"]
[Date "2023.08.09"]
[Round "1"]
[White "New-ba40e766ce"]
[Black "Base-5c2111cc30"]
[Result "1/2-1/2"]
[FEN "2rqkbnr/3b1ppp/p1n1p3/1pppP3/3P4/P1P2N2/1P1NBPPP/R1BQK2R w KQk - 0 1"]
```

- the books still have broken FENs, but this is not an issue regarding fishtest
```
2rqkbnr/3b1ppp/p1n1p3/1pppP3/3P4/P1P2N2/1P1NBPPP/R1BQK2R w KQk b6
```

I want to thank you for helping me improve the status of this issue. I wonder if I can ask you to edit your post, it is not up to your usual standard held on fishtest, to be honest. Little slips happen to everyone :)

**Comment by KasparovChess** [comment]
> He is one of the fishtest maintainers, he has simply closed old issues dedicating his spare time contributing to the project.

My thread and this thread were both closed within the same hour, should I believe It was completely random?!

> I want to thank you for helping me improve the status of this issue.

I also thank you for helping me in the Stockfish repository❤

> I wonder if I can ask you to edit your post, it is not up to your usual standard held on fishtest, to be honest.

I can't edit my post in fishtest repo because my comment was marked as abuse by @zungur.

![image](https://github.com/glinscott/fishtest/assets/121145620/5649b623-dfe8-4d3e-9273-0644fdf4bfee)

**Comment by KasparovChess** [comment]
To be honest from my opinion there is no real person named Onur Zungur , at least in Russia.

> In 24 minutes he closed these issues:
> #1569, #1751, #1498, #969, #1474, #1391, #1238, #313, #238, #1634, #1575, #1624, #1752, #1622, #1556, #1264

Maybe he is a robot!

> If you agree with me, I would like to edit your previous post dropping the unnecessary reference to one of our longtime contributor (vdbergh) and the link to the issue of an external repository,

I neither agree nor disagree. If there is a real person named @Zungur, why does he appear only to close the thread or block member?!

**Comment by ppigazzini** [comment]
He updated his PR just after closing all these issues, then disappeared https://github.com/glinscott/fishtest/pull/1375
I don't argue with other admin actions, I do know that they are volunteering their spare time and he seems to have very little spare time after February 2019.

I updated the previous post about the Issue status.
fishtest has switched to EPD opening books. The "halfmove clock" and "full move counter", obligatory in FEN, are replaced by optional "hmvc" and "fmvn" operations, with 0, 1 as their default values.
https://www.chessprogramming.org/Extended_Position_Description
https://en.wikipedia.org/wiki/Extended_Position_Description

`cutechess-cli` loads the EPD book, convert the position in FEN and pass the FEN to Stockfish.

Have a nice night.

**Comment by KasparovChess** [comment]
> He updated his PR just after closing all these issues, then disappeared #1375

@zungur is probably a mathematician like [Alan Turing](https://en.wikipedia.org/wiki/Alan_Turing)

> I updated the previous post about the Issue status.
> fishtest has switched to EPD opening books. The "halfmove clock" and "full move counter", obligatory in FEN, are replaced by optional "hmvc" and "fmvn" operations, with 0, 1 as their default values.

I thank you very much and I appreciate it. **If you are interested in chess, you can join our master class:**

https://github.com/glinscott/fishtest/assets/121145620/b23435ee-7016-44aa-9c00-14f1d7040b52

Good Luck.
