### ISSUE TITLE
Question about the updater

### ISSUE THREAD

**Issue by RensDeVries** [glinscott/fishtest#318]
Dear all,

I might have missed it, because I remember there were some posts on FishCooking on this topic, but the worker updater seems not to be working. Both on Linux and Windows. All my workers are running on the 66:2 version at this moment.

Is this a bug in the script, and is a manual upgrade at this moment the only way to fix this issue?

-TueRens

**Comment by ppigazzini** [comment]
@RensDeVries on version 63 the updater is broken and can be done only a manual update. We are testing the version 67 and the server stability with the PGN upload before enforcing the update for all the contributors.
The worker now supports python 2.x and python 3.x. With the latter you will have 66:3.

**Comment by RensDeVries** [comment]
@ppigazzini thanks for your quick response, Good luck with the testing and I am looking forward to the stable PGN update.
