### ISSUE TITLE
VPS seems down

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#319]
@Stefano80 I'm not able to connect via ssh to the production server.

@glinscott could you check the ISP control panel, please?

[Edit] the ISP has suspended the VPS because was exceeded the bandwidth allocated.

**Comment by ppigazzini** [comment]
@noobpwnftw I'm commuting now. I will be home in 90 minutes.

**Comment by ppigazzini** [comment]
@noobpwnftw this is the public key used for the production and dev server
[public.txt](https://github.com/glinscott/fishtest/files/2105593/public.txt)

**Comment by ppigazzini** [comment]
@glinscott @mcostalba Switching the production server requires an update of the DNS. Do you know who has registered the domain stockfishchess.org ?

I add at this thread also @snicolet @tomtor

**Comment by noobpwnftw** [comment]
Ok, here are the server info:
2 VMs of 4C/8G/1TB CentOS7.5
112.73.74.72(192.168.1.101)
112.73.74.73(192.168.1.102)
Private IPs are connected with a dedicated VLAN so you are free to change them.

I have added your keys, please change all root passwords as you log in.

You must not provide any web service on port 80 or point your DNS to above IPs, unless you have a Chinese ICP license for the domain, instead, please point them to the bridge:
69.172.90.171, now it runs a reverse proxy of 112.73.74.72 at port 81 for tests.stockfishchess.org.

**Comment by noobpwnftw** [comment]
I have configured the reverse proxy at 69.172.90.171 like following:

```
upstream fishtest {
    keepalive 32;
    server 112.73.74.72:81;
}
server {
    server_name tests.stockfishchess.org;
    listen 80;
    include /etc/nginx/default.d/*.conf;
    client_max_body_size 10m;
    location / {
        proxy_pass http://fishtest;
        proxy_redirect          http://112.73.74.72/ /;
        proxy_set_header        Host            112.73.74.72;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout   60;
        proxy_send_timeout      60;
        proxy_read_timeout      60;
        proxy_http_version      1.1;
        proxy_set_header        Connection "";
    }
    error_page 404 /404.html;
        location = /40x.html {
    }
    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
}
```
I have tested by setting my local hosts file for tests.stockfishchess.org pointing to 69.172.90.171, and it appears to be working correctly.

**Comment by ppigazzini** [comment]
@noobpwnftw fist server installed, check port 81, the second is on the way.
A little problem with the mongodb installation (the mongodb mirrors are very slow, few kB/s).
I changed sshd_config: forbidding root login, enforcing the key login and adding an AllowUsers directive.

**Comment by noobpwnftw** [comment]
@ppigazzini Yup, for those repositories that does not have many mirrors, it will be slow to install packages from them.
For workers, there are two ways to connect to the new server, either use server IP address and port 81 in .cfg file, or connect via proxy by changing DNS pointing to the proxy. One potential problem for the latter is the necessity of parsing HTTP headers from the reverse proxy to retrieve real IP addresses and correctly show country flags, probably by adding the following into .ini file, according to guide here https://stackoverflow.com/questions/9380088/how-to-get-the-real-ip-of-a-client-in-a-pyramid-server-behind-a-nginx-proxy:
```
###
# pipeline configuration
###

[filter:paste_prefix]
use = egg:PasteDeploy#prefix

[pipeline:main]
pipeline =
    paste_prefix
    fishtest_server
```

**Comment by noobpwnftw** [comment]
@ppigazzini Yup, for those repositories that do not have many mirrors, it will be slow to install packages from them.
For workers, there are two ways to connect to the new server, either use server IP address and port 81 in .cfg file, or connect via proxy by changing DNS pointing to the proxy. One potential problem for the latter is the necessity of parsing HTTP headers from the reverse proxy to retrieve real IP addresses and correctly show country flags, probably by adding the following into .ini file, according to guide here https://stackoverflow.com/questions/9380088/how-to-get-the-real-ip-of-a-client-in-a-pyramid-server-behind-a-nginx-proxy:
```
###
# pipeline configuration
###

[filter:paste_prefix]
use = egg:PasteDeploy#prefix

[pipeline:main]
pipeline =
    paste_prefix
    fishtest_server
```

**Comment by ppigazzini** [comment]
@noobpwnftw second server up and running.
In the week end I can complete the configuration.

**Comment by noobpwnftw** [comment]
I can provide one more public IP and a number of VMs inside the same private network in case of need.
Hope this solves your hosting problems.

**Comment by ppigazzini** [comment]
@noobpwnftw thank you.
I'm for a switch to a new VM, anyway I wait the opinion of other people.

**Comment by ppigazzini** [comment]
The production server now has:
  - 4 cores
  - 5 GB RAM
  - 100 GB HD

Thank you @glinscott

**Comment by Stefano80** [comment]
Yes, thank you Gary and Pasquale!

**Comment by Stefano80** [comment]
I also started noticing again tests disappearing although they still are active.

**Comment by noobpwnftw** [comment]
@Stefano80 I know why those disappearing appear: when building the list in the process via a MongoDB iterator(cursor), another update operation may cause the iterator to skip records, it is a documented behavior. Search https://docs.mongodb.com/manual/faq/concurrency/ for "Reads may miss matching documents that are updated during the course of the read operation."

**Comment by noobpwnftw** [comment]
@tomtor Is it possible to see the waterfall graph on the live server? Now I can see it timeouts on workers quite often again.
@ppigazzini

**Comment by snicolet** [comment]
> Le 1 juil. 2018 à 08:33, noobpwnftw <notifications@github.com> a écrit :
> @tomtor Is it possible to see the waterfall graph on the live server? Now I can see it timeouts on workers quite often again.
> @ppigazzini


I agree that the waterfall graph would be nice.

Meanwhile, as a temporary measure, wouldn't it be possible to just disable
the saving of parameters to construct the graph for big tuning patches?

I am sure sure that nobody look at these graphs when there are more than 
ten parameters to tune, so it is just wasting ressources and killing the
server for nothing :-)

Stéphane

**Comment by tomtor** [comment]
The main issue is >1000000 tasks in the pre allocated task list. The graph code adjusts for a large number of parameters (lowers log frequency) so that maintaining it uses a constant amount of resources.

**Comment by noobpwnftw** [comment]
Right, and maybe a separate server for such low priority tasks. Minimum changes to the worker can allow one swapping among multiple task queues.

**Comment by Stefano80** [comment]
Hi @tomtor, thank you for your insight!

Let us dig a bit deeper. Do you happen to know, what is the problem exactly? The rendering, keeping the list in memory? 

If you know it, could you point to the area of the code where the problems arise?

**Comment by tomtor** [comment]
Fishtest preallocates all tasks in a list: 1000000 game limit > 4000 tasks of 250 games each. You don't see these tasks on the test display page until they have been active, but each slot is inspected to see if a line must be added to the test display page.

Also in some other places in the fishtest code this list is used in a lineair scan.

I don't think the issue is memory usage, but @ppigazzini can make sure by inspecting the current state with `top`
