### ISSUE TITLE
SPSA reports always the same 'c' across all iterations

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#324]
The problem is explained here
https://groups.google.com/d/msg/fishcooking/X6yCuH55AHY/G5nEcZW2BwAJ

A fix would be to change the way that view.py "prints" the report
https://groups.google.com/d/msg/fishcooking/X6yCuH55AHY/a4Suhsi8BwAJ

This way, fishtest will report the results similarly as the spsa.pl of Joona

**Comment by tomtor** [comment]
@Rocky640 Thanks for the investigation. I allready had a quick look yesterday at the code, glad to hear that it is not a recently introduced bug.
