### ISSUE TITLE
Long-running workers eventually cause OS issues

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#326]
After running tests for a while on my worker, it shows the following:
```
Indexing opening suite...
Started game 2 of 23 (Base-a6fa6a9 vs New-a6fa6a9)
Started game 1 of 23 (New-a6fa6a9 vs Base-a6fa6a9)
Started game 3 of 23 (New-a6fa6a9 vs Base-a6fa6a9)
Started game 4 of 23 (Base-a6fa6a9 vs New-a6fa6a9)
Started game 6 of 23 (Base-a6fa6a9 vs New-a6fa6a9)
Warning: Player New-a6fa6a9 has no side
Engine New-a6fa6a9 failed to respond to ping
```
There isn't anything else running on the machine, but if I issue
"echo 3 > /proc/sys/vm/drop_caches" when this happens, problem is gone.

I wonder if there is anything I can do to prevent this from happening, looks like it occurs related to accumulated memory usage, but my machine has very large RAM, some cleanup mechanisms must have failed.

**Comment by Stefano80** [comment]
Could you try locally whether setting restart='on' in the engine options solves the problem? See, here https://github.com/cutechess/cutechess/blob/master/projects/cli/res/doc/help.txt

**Comment by noobpwnftw** [comment]
@Stefano80 Setting restart to "on" makes the problem happen even more frequently.

**Comment by Stefano80** [comment]
Fascinating. Could be some garbage collection problem with python? We have a python 3 version in the PR, could you try that?

**Comment by noobpwnftw** [comment]
I think it is the large RAM size broke OS page table GC... That seems to be why manually drop caches worked.

**Comment by noobpwnftw** [comment]
So my proposal is we may have this done in the worker, before starting each game, and be friendly about slow engine initializations (if we are to test large TT cases, engine startup is going to take a while).

**Comment by noobpwnftw** [comment]
Looks like it is non-trivial to do anything on the worker side since they usually run without root permissions.
Closing.
