### ISSUE TITLE
Fishtest password lifespan is too short

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#329]
I would suggest to increase the session delay (using cookies or https session or whatever) to 15 months instead of 15 minutes, because the approver job is really painful at the moment.

**Comment by Stefano80** [comment]
Strange, I don't have this problem. I have to check.

**Comment by ppigazzini** [comment]
@snicolet do you still have this problem?

**Comment by snicolet** [comment]
Yes, I have to re-type password several times a day :-)

**Comment by tomtor** [comment]
Strange, I do not have that issue. I guess it expires for me after 14 days not using fishtest.

It is related to the browser/anti-virus software you are using.

**Comment by ppigazzini** [comment]
@snicolet please test the https server, your account should work (or use "user00/user00")
https://dfts-0.pigazzini.it/tests

**Comment by ppigazzini** [comment]
@tomtor antivirus?!? IIRC @snicolet is OSX addicted :)

**Comment by tomtor** [comment]
Safari/OSX has Intelligent Tracking Prevention (ITP) which is very aggressive regarding cookie expiry...

**Comment by snicolet** [comment]
@ppigazzini 
Indeed I am on a Mac :-p 
I have approved two tests on the https server, if there are some more to approve in a couple of hours (say 6 hours) I will try again, and report. Thanks for taking care of this :-)

**Comment by ppigazzini** [comment]
@snicolet I created a new test to be approved by you in a couple of hours. If https doesn't fix it, you are writing the password the wrong way :)

**Comment by snicolet** [comment]
Yes, it worked and the https server remembered my password (9 hours later)!
