### ISSUE TITLE
limitations?

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#331]
Why some of my workers has no tasks for a long while we have a huge pending queue?

-- 
Cheers,
\dew

**Comment by d3vv** [comment]
Anybody home?
It seems fishtest has limits per ip.. Could it possible to fix it at least?

**Comment by ianfab** [comment]
No, it has limits per user. The default is 4 if I remember correctly, so if you want to connect more workers, please inform @ppigazzini about how many workers you plan to run, since the limit needs to be updated in the database per user.

**Comment by d3vv** [comment]
@ianfab I hear about per user. But almost it has limit per ip - most workers from the same nat-gateway waiting task (has a rest), but i have no problem run a bit more workers from other gateways with the same user-login.

**Comment by ppigazzini** [comment]
@d3vv please give me your fishtest username and the workers number.

**Comment by d3vv** [comment]
@ppigazzini 

username: dew
about 25 workers now

And I'am about a workers from the same ip at prev. message

**Comment by d3vv** [comment]
```
Fetch task...
Worker version checked successfully in 0.14213s
Task requested in 0.127234s
No tasks available at this time, waiting...
```

...

```
Fetch task...
Worker version checked successfully in 0.108736s
Task requested in 0.125273s
No tasks available at this time, waiting...
```

**Comment by ppigazzini** [comment]
@d3vv limit raised

**Comment by d3vv** [comment]
@ppigazzini thank you in advanced
but could you suggest - what is current limit number?

**Comment by ppigazzini** [comment]
@d3vv 4 default, 40 your new limit.

**Comment by d3vv** [comment]
@ppigazzini My pleasure..
Tomorrow I will check and close an issue if everything will be good
