### ISSUE TITLE
public mongodb dump

### ISSUE THREAD

**Issue by sethtroisi** [glinscott/fishtest#334]
I'm trying to do some development on the site's front-end.

I'd like to load some test data (or real data) into mongo so that the frontend isn't empty.
SETUP suggests `Use boto "fetch_file s3://fishtest/backup/archive/20130623/dump.tar.gz -o dump.tar.gz""`
I was unable to get boto to find that file (or any newer dump.tar.gz).

I've also tried with `clone_fish.py` but that doesn't appear very fast (and I don't seem to see partial results if I should be)

Can you point me at a publically readable s3 url or other file?
Thanks

**Comment by ppigazzini** [comment]
Hi @sethtroisi , thank you for your effort about fishtest.
The data are not encrypted, it's impossible to release a copy of the official db.

Fortunately following the [wiki](https://github.com/glinscott/fishtest/wiki) it's very simple to to setup a development framework and populate in very short time the db:
1. setup a [fishtest server](https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup). The setup script creates 2 default users, add more users if necessary;
2. setup some [workers](https://github.com/glinscott/fishtest/wiki/Running-the-worker), keep them in separate folders;
3. run some tests with very very short time controls to populate the db (copy the test parameters from the official tests queue)

Simply ask for more help.

-pp

**Comment by sethtroisi** [comment]
Thanks pp. I'll try playing some 1+1 games and see if I can get reasonable amounts of data that way.
