### ISSUE TITLE
Change default TT size for STC to 8MB

### ISSUE THREAD

**Issue by CoffeeOne** [glinscott/fishtest#336]
see test:
http://tests.stockfishchess.org/tests/view/5c0652900ebc5902bcee542b
I tested also doubling one more time from 8 => 16.
http://tests.stockfishchess.org/tests/view/5c065ac10ebc5902bcee5561
That failed, so 8 MB seems fine.

**Comment by Vizvezdenec** [comment]
maybe we should do the same LTC test (maybe with partial hash since sf supports sizes like 96 mb?)?

**Comment by CoffeeOne** [comment]
I tested also LTC 128MB which failed:
http://tests.stockfishchess.org/tests/view/5c069ae30ebc5902bcee5b97

**Comment by Vizvezdenec** [comment]
@snicolet @mcostalba

**Comment by Chess13234** [comment]
@CoffeeOne 128MB is possibly adding latency. Smaller hashes have more L2/L1 cache hits(cache is much faster).
8MB+ is the size of cache on most quadcores.

**Comment by xoto10** [comment]
See #341

**Comment by CoffeeOne** [comment]
+1
