### ISSUE TITLE
fishtest down... Again :(

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#337]
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

**Comment by ppigazzini** [comment]
Thank you for the alarm.

@tomtor : the pserve log report this error, I start googling to find a solution.
```
Starting subprocess with monitor parent
Starting server in PID 699.
serving on http://0.0.0.0:6543
Overview exception: BSON document too large (16777392 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
Overview exception: BSON document too large (16777392 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
Overview exception: BSON document too large (16777392 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.```

**Comment by ppigazzini** [comment]
@tomtor this is the size of the mongodump
```
[fishtest@tests fishtest_new]$ ls -lah
total 13G
drwxrwxr-x 2 fishtest fishtest 4.0K Dec  9 22:22 .
drwxrwxr-x 5 fishtest fishtest 4.0K Dec  9 22:21 ..
-rw-rw-r-- 1 fishtest fishtest 5.2G Dec  9 22:22 actions.bson
-rw-rw-r-- 1 fishtest fishtest  102 Dec  9 22:22 actions.metadata.json
-rw-rw-r-- 1 fishtest fishtest  22K Dec  9 22:22 clop.bson
-rw-rw-r-- 1 fishtest fishtest   99 Dec  9 22:22 clop.metadata.json
-rw-rw-r-- 1 fishtest fishtest 1.6M Dec  9 22:22 flag_cache.bson
-rw-rw-r-- 1 fishtest fishtest  105 Dec  9 22:22 flag_cache.metadata.json
-rw-rw-r-- 1 fishtest fishtest 164M Dec  9 22:22 old_runs.bson
-rw-rw-r-- 1 fishtest fishtest  103 Dec  9 22:22 old_runs.metadata.json
-rw-rw-r-- 1 fishtest fishtest  77K Dec  9 22:22 old_user_cache.bson
-rw-rw-r-- 1 fishtest fishtest  109 Dec  9 22:22 old_user_cache.metadata.json
-rw-rw-r-- 1 fishtest fishtest 5.0G Dec  9 22:22 pgns.bson
-rw-rw-r-- 1 fishtest fishtest  187 Dec  9 22:22 pgns.metadata.json
-rw-rw-r-- 1 fishtest fishtest  75K Dec  9 22:21 regression_data.bson
-rw-rw-r-- 1 fishtest fishtest  110 Dec  9 22:21 regression_data.metadata.json
-rw-rw-r-- 1 fishtest fishtest 1.8G Dec  9 22:22 runs.bson
-rw-rw-r-- 1 fishtest fishtest 1.3K Dec  9 22:22 runs.metadata.json
-rw-rw-r-- 1 fishtest fishtest 2.0K Dec  9 22:21 system.indexes.bson
-rw-rw-r-- 1 fishtest fishtest  19K Dec  9 22:22 top_month.bson
-rw-rw-r-- 1 fishtest fishtest  104 Dec  9 22:22 top_month.metadata.json
-rw-rw-r-- 1 fishtest fishtest 197K Dec  9 22:22 user_cache.bson
-rw-rw-r-- 1 fishtest fishtest  105 Dec  9 22:22 user_cache.metadata.json
-rw-rw-r-- 1 fishtest fishtest 227K Dec  9 22:22 users.bson
-rw-rw-r-- 1 fishtest fishtest  210 Dec  9 22:22 users.metadata.json
```

**Comment by Anzadii** [comment]
BSON Document Size

The maximum BSON document size is 16 megabytes.

The maximum document size helps ensure that a single document cannot use excessive amount of RAM or, during transmission, excessive amount of bandwidth. To store documents larger than the maximum size, MongoDB provides the GridFS API. See mongofiles and the documentation for your driver for more information about GridFS.

**Comment by ppigazzini** [comment]
@tomtor still same error message after dropping the pgns collection with `create_pgndb.py` (backup saved).

**Comment by noobpwnftw** [comment]
I think it has something to do with that SPSA tuning.
The limit there is for a single document to not exceed 16MB in size, you might want to find out which document is that large and remove it for the moment.

**Comment by ppigazzini** [comment]
@noobpwnftw unfortunately I'm not so skilled with mongodb. Anyway I copied the db on the dev servers to experiment some solutions. The problem is obviously present also with mongodb 4.0.4 (CentoOS  7.6.1810 and CentOS 6.10).

**Comment by xoto10** [comment]
There's a command line tool for looking at mongodb databases, that would be the way (I don't remember what it's called).

Alternatively, does the error happen when engines are processing tests? If engines can be prevented from connecting perhaps the normal web interface can be used to stop one or more of the tests currently running? (Presumably one of them is very large?) 
I assume most tests can still run without problem (if not, we have a real issue!)

**Comment by Chess13234** [comment]
If its because of SPSA data generated, maybe there should be a limit on number of tuned variables? I don't see a point in tuning tons of variables at once when the accuracy of that tuning is very shallow and unpredictable vs tuning a few parameters.

**Comment by ppigazzini** [comment]
@xoto10 the shell is `mongo`, the problem is that I don't know the data structure of fishtest.
I'm trying to reload the latest automatic backup in the dev server.

**Comment by ppigazzini** [comment]
@tomtor @glinscott @vondele A possible simple solution should be to load the backup of the previous day (08/12/2018), losing the last 20 hours of tests, and then stopping the SPSA run. I'm not sure of possible problems with the workers, though. Any idea?

**Comment by Vizvezdenec** [comment]
I actually think this is okay - we had only 1 test from all tests yesterday that passed STC and it already passed STC (apart from one simplification).
Guess we will lose 10k of it LTC games, but it's not that big of a deal.

**Comment by ppigazzini** [comment]
@vondele I just restored the backup of the previous day. IMO losing 20 hours of computation is a better solution than losing 4-5 days of computation. Anyway I have the backup of the db at the time of the crash. I already lowered the priority of the [SPSA test](http://dfts-11.pigazzini.it:6543/tests/view/5c0bf34d0ebc5902bceecd3e).
Anyway the pages seem a bit slow.

**Comment by Vizvezdenec** [comment]
We wouldn't lose 20 hours of computation since I killed tests that I 100% remember failing.
So we are losing much less :)

**Comment by noobpwnftw** [comment]
1. Load the point of time DB of crash,
2. Run mongo shell like mongo fishtest_new
3. db.runs.deleteOne({'_id': 5c0bf34d0ebc5902bceecd3e})
4. profit?!

**Comment by ppigazzini** [comment]
@noobpwnftw I start testing your suggestion on the development server.

**Comment by Chess13234** [comment]
Tests page randomly shows Internal Server Error and also feels much slow loading when it doesn't have the error.

**Comment by ppigazzini** [comment]
@noobpwnftw result of your suggestion
* with this python:
```python
#!/usr/bin/env python
from pymongo import MongoClient, ASCENDING, DESCENDING
conn = MongoClient('localhost')
db = conn['fishtest_new']
db.runs.deleteOne({'_id': 5c0bf34d0ebc5902bceecd3e})
```
```
$ python remove_run.py
  File "remove_run.py", line 9
    db.runs.deleteOne({'_id': 5c0bf34d0ebc5902bceecd3e})
                                                     ^
SyntaxError: invalid syntax
```

* with the mongo shell:

```
$ mongo
MongoDB shell version: 2.4.4
connecting to: test
> use fishtest_new
switched to db fishtest_new
> show collections
actions
clop
flag_cache
old_runs
old_user_cache
pgns
regression_data
runs
system.indexes
top_month
user_cache
users
> db.runs.deleteOne({'_id': 5c0bf34d0ebc5902bceecd3e})
Mon Dec 10 14:34:42.529 JavaScript execution failed: SyntaxError: Unexpected tok                      en ILLEGAL
>
```

**Comment by noobpwnftw** [comment]
@ppigazzini try quoting like this in mongo shell?
b.runs.deleteOne({'_id': ObjectId('5c0bf34d0ebc5902bceecd3e')})

**Comment by ppigazzini** [comment]
@noobpwnftw 
* mongo shell:
```
> db.runs.deleteOne({'_id': ObjectId('5c0bf34d0ebc5902bceecd3e')})
Mon Dec 10 14:56:51.376 JavaScript execution failed: TypeError: Property 'deleteOne' of object fishtest_new.runs is not a function
```

* python script
```
$ python remove_run.py
Traceback (most recent call last):
  File "remove_run.py", line 10, in <module>
    db.runs.deleteOne({'_id': ObjectId('5c0bf34d0ebc5902bceecd3e')})
NameError: name 'ObjectId' is not defined
```

Anyway I'm more confident loading a db backup than deleting a document.

**Comment by ppigazzini** [comment]
@Chess13234 @xoto10 @noobpwnftw what are your feeling about the fastness of the fishtest page with the db backup?

**Comment by Chess13234** [comment]
@ppigazzini The individual test pages load fast. The main tests page is slow, but not as slow as before(taking 5-8 seconds)

**Comment by noobpwnftw** [comment]
@ppigazzini Speed seems fine to me.
Maybe `db.runs.remove({'_id': ObjectId('5c0bf34d0ebc5902bceecd3e')})` ?

We now stuck at syntax :)

**Comment by ppigazzini** [comment]
@noobpwnftw  the last command ran without error in the mongo shell.
Anyway the dev server still shows the same error

```
Starting subprocess with monitor parent
Starting server in PID 21227.
serving on http://0.0.0.0:6543
Overview exception: BSON document too large (16777392 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2018-12-10 15:27:19,145 ERROR [waitress][Dummy-2] Exception when serving /tests
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/waitress/channel.py", line 332, in service
    task.service()
  File "/usr/lib/python2.6/site-packages/waitress/task.py", line 174, in service
    self.execute()
  File "/usr/lib/python2.6/site-packages/waitress/task.py", line 382, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/usr/lib/python2.6/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/usr/lib/python2.6/site-packages/pyramid/config/views.py", line 369, in rendered_view
    context)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 531, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 561, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 557, in render
    result = renderer(value, system_values)
  File "/usr/lib/python2.6/site-packages/pyramid/mako_templating.py", line 227, in __call__
    raise ValueError('renderer was passed non-dictionary as value')
ValueError: renderer was passed non-dictionary as value
```

**Comment by noobpwnftw** [comment]
@ppigazzini OK! That test wasn't the cause after all. From your new logs I think the problem is the result of the test history is too big. Let me see what I can do to it.

**Comment by Rocky640** [comment]
I don't think my SPSA test was the culprit. There was 128 variables, and 
an almost identical run http://tests.stockfishchess.org/tests/view/5c0b308a0ebc5902bceebb7d
completed correctly just 2-3 days ago.

**Comment by ppigazzini** [comment]
@noobpwnftw The official server has only 10% free RAM, with python/pervse using 80% RAM.
In my notes of 8 months ago the server usually had the 75% of free RAM.

**Comment by noobpwnftw** [comment]
@ppigazzini I read some documents and found that it is the limitation caused by our finished task pagination.
We are now using skip & limit, which is unable to use any index, and when the dataset is large it will fail and not to mention slow.

Let's just try for once if we delete all finished tasks in the database:
`db.runs.remove({'finished': true})`

And then see if it crashes?

**Comment by ppigazzini** [comment]
@noobpwnftw here is the CentOS 7.6 mongodb 4.0.4:

```
> use fishtest_new
switched to db fishtest_new
> db.runs.remove({'finished': true})
WriteResult({ "nRemoved" : 39292 })
>
```

Log:
```
Dec 10 17:23:52 dfts-0 systemd[1]: Started Fishtest Server: connect to port 6543.
Dec 10 17:26:09 dfts-0 pserve[26646]: 2018-12-10 17:26:09,881 ERROR [waitress][waitress] Exception whe
Dec 10 17:26:09 dfts-0 pserve[26646]: Traceback (most recent call last):
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/waitress/channel.py", lin
Dec 10 17:26:09 dfts-0 pserve[26646]: task.service()
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/waitress/task.py", line 1
Dec 10 17:26:09 dfts-0 pserve[26646]: self.execute()
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/waitress/task.py", line 3
Dec 10 17:26:09 dfts-0 pserve[26646]: app_iter = self.channel.server.application(env, start_response)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/router.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: response = self.execution_policy(environ, self)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/router.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: return request.invoke_exception_view(reraise=True)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 76
Dec 10 17:26:09 dfts-0 pserve[26646]: reraise_(*exc_info)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/router.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: return router.invoke_request(request)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/router.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: response = handle_request(request)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: response = _error_handler(request, exc)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: reraise(*exc_info)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: response = handler(request)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/router.py", line
Dec 10 17:26:09 dfts-0 pserve[26646]: registry, request, context, context_iface, view_name
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 65
Dec 10 17:26:09 dfts-0 pserve[26646]: response = view_callable(context, request)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py",
Dec 10 17:26:09 dfts-0 pserve[26646]: request, result, view_inst, context
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/renderers.py", li
Dec 10 17:26:09 dfts-0 pserve[26646]: return self.render_to_response(response, system, request=request
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/renderers.py", li
Dec 10 17:26:09 dfts-0 pserve[26646]: result = self.render(value, system_values, request=request)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/usr/lib/python2.7/site-packages/pyramid/renderers.py", li
Dec 10 17:26:09 dfts-0 pserve[26646]: result = renderer(value, system_values)
Dec 10 17:26:09 dfts-0 pserve[26646]: File "/home/fishtest/.local/lib/python2.7/site-packages/pyramid_
Dec 10 17:26:09 dfts-0 pserve[26646]: raise ValueError('renderer was passed non-dictionary as value')
```

**Comment by noobpwnftw** [comment]
@ppigazzini  That's weird, can you then try the following?
Clear database one by one, and see which was the one that caused the crash?
`db.[dbname].remove({})`
where `dbname` in this order, one at a time.

```
pgns
actions
flag_cache
old_user_cache
user_cache
old_runs
runs
clop
regression_data
top_month
users
```

**Comment by ppigazzini** [comment]
@noobpwnftw I loaded on the dev servers the working db and applied your delete recipe. Fishtest is still slow in my opinion, even though the finished tests list has now 7130 entries vs. the 40000 of the official.
I will try to load an old backup (8 months ago) to be sure.

**Comment by noobpwnftw** [comment]
@ppigazzini If there are still 7130 entries then they must be in `old_runs` db. Try to clear that too.

**Comment by xoto10** [comment]
I used to run a script to regularly test how long the main web page takes to load. I started it up again:
```
2018-09-10_20:22  real	0m2.232s
2018-09-10_20:37  real	0m1.854s
2018-09-10_20:52  real	0m0.266s
2018-09-10_21:07  real	0m2.415s
2018-09-10_21:22  real	0m2.253s
2018-09-10_21:37  real	0m0.274s
2018-09-10_21:52  real	0m2.298s
2018-09-10_22:07  real	0m0.256s
2018-09-10_22:22  real	0m2.039s
2018-09-10_22:37  real	0m0.285s
2018-09-10_22:52  real	0m2.788s
2018-09-10_23:07  real	0m1.944s
2018-09-10_23:22  real	0m2.334s
2018-09-10_23:37  real	0m2.121s
2018-09-10_23:52  real	0m3.006s

2018-12-10_16:37  real	0m10.112s
2018-12-10_16:52  real	0m9.125s
2018-12-10_17:07  real	0m4.104s
2018-12-10_17:22  real	0m0.649s
2018-12-10_17:37  real	0m9.871s
```
As you can see it is often taking 9-10s to load at the moment, which matches what I have seen in the browser today, where it was taking 0-3s in September. (Although a couple of those logged times in the last hour are 4s and <1s so it is not consistently bad.)

@ppigazzini Can you run utils/current.py on the production server? It may not be useful, but it might give us some idea which current queries are taking a long time to run. (Perhaps run it a few times to see if the results are consistent?)

**Comment by ppigazzini** [comment]
@noobpwnftw ok, my memory was correct. Tests with old backups on the dev server CentOS 7.6 mongodb 4.0.4:
 - 01/03/2018 (Finished - 24450 tests) fishtest is loading fast
 - 01/08/2018 (Finished - 32474 tests) fishtest takes 2-3s to load

Now I start with your tests.

**Comment by ppigazzini** [comment]
@noobpwnftw:
dev server CentOS 6.10 mongodb 2.4.4, db backup 09/12/2018 (the db with problems), already without `pgns` (too big to transfer) but fishtest  doesn't start.

` mongo fishtest_new --eval 'db.actions.remove({'finished': true})'` and fishtest seems to work fine

**Comment by ppigazzini** [comment]
I start commuting, I will be home in 2 hours.

**Comment by noobpwnftw** [comment]
Now it is confusing, `db.actions.remove({'finished': true})` should not remove any document there because the documents there do not have a field of `finished`. If you executed `db.actions.remove()` then it makes sense.

Then if that is the cause of the crash then it would only crash after you view the "Actions" page, if that is the case then we should lower the number of 100 here https://github.com/glinscott/fishtest/blob/39e9b57da535b5a1229063e5a6c120fcc7488ab4/fishtest/fishtest/views.py#L173 to 50, maybe?

**Comment by ppigazzini** [comment]
@noobpwnftw I was in hurry and I typed the wrong commands and unfortunately I also tested the wrong dev server in the browser. Sorry for the fuss. I repeat the tests with calm.

**Comment by ppigazzini** [comment]
@noobpwnftw test repeated, reloading the db and using these commands in the mongodb shell to have a feedback from mongodb 2.4.4

```
> db.[collectionName].find({})
> db.[collectionName].remove({})
> db.[collectionName].find({})
```

The bad collection is 'runs'. After deleting all the documents from 'runs' fishtest is very reactive (Finished - 7130 tests).

I repeated also the test with `db.runs.remove({'finished': true})`,  error with `Overview exception: BSON document too large (16777392 bytes)`

**Comment by ppigazzini** [comment]
@noobpwnftw test repeated reloading the db from the backup, `db.runs.remove({'finished': false})`, fishtest works.

**Comment by noobpwnftw** [comment]
So... was it a data corruption? Let's find out.
Load the runs database, try to run:
`db.runs.find({'finished': false})`
And it shall fail, then:
`db.runs.ensure_index({'finished': 1,}, {sparse: true})`
This should build you an index over 'finished' field, there should already be a compound index covering this field but just to be sure.
Now run this again:
`db.runs.find({'finished': false})`
If it fails again, then we need to go though the data by hand(I wonder how is it possible that such a document could have survived a mongodump/mongorestore cycle, since they also use BSON format), if it succeeded, then we know that the compound index did not work, and we can fix it by adding another sparse index over `finished` field.

**Comment by ppigazzini** [comment]
@noobpwnftw test executed loading a fresh db backup.

*  `db.runs.find({'finished': false})`
Runs without errors. The output runs, then hangs for 5 seconds, then runs until the finish.

Here the output when the command hangs for 5 seconds:
```
 "last_updated" : ISODate("0001-01-01T00:00:00Z"),       "pending" : true },     {       "worker_key" : "-",     "num_games" : 250,    "residual" : 0,  "residual_color" : "#44EB44",   "active" : false,       "last_updated" : ISODate("0001-01-01T00:00:00Z"),       "pending" : true },     {       "worker_key" : "-",     "num_games" : 250,    "residual" : 0,  "residual_color" : "#44EB44",   "active" : false,       "last_updated" : ISODate("0001-01-01T00:00:00Z"),       "pending" : true },     {       "worker_key" : "-",     "num_games" : 250,    "residual" : 0,  "residual_color" : "#44EB44",   "active" : false,       "last_updated" : ISODate("0001-01-01T00:00:00Z"),       "pending" : true } ], "last_updated" : ISODate("2018-12-08T21:18:02.358Z"), "results_stale" : false, "start_time" : ISODate("2018-12-08T19:35:03.886Z"), "args" : { "book_depth" : "8", "internal_priority" : -1544365203, "new_signature" : "3523396", "auto_purge" : true, "tests_repo" : "https://github.com/SFisGOD/Stockfish", "new_tag" : "tuned_BRpsqt", "sprt" : { "alpha" : 0.05, "beta" : 0.05, "drawelo" : 240, "elo0" : 0, "elo1" : 4 }, "priority" : -1, "base_signature" : "3773021", "book" : "2moves_v1.pgn", "tc" : "10+0.1", "username" : "SFisGOD", "base_tag" : "master", "msg_base" : "Revert \"pseudo_legal() and MOVE_NONE\"", "new_options" : "Hash=4", "resolved_new" : "7bba8fe8afcbea29045de80c8a12cb4ac5df7f62", "threads" : 1, "resolved_base" : "5c2fbcd09b43bd6867780a3ace303ffb1e09d763", "base_options" : "Hash=4", "info" : "try the raw values first", "num_games" : 250000, "msg_new" : "Tweak Bishop and Rook PSQT. Bench: 3523396", "throughput" : 1000 }, "results" : { "time_losses" : 5, "wins" : 4367, "losses" : 4392, "draws" : 10991, "crashes" : 0 }, "approver" : "Vizvezdenec", "finished" : false, "approved" : true }
```

here the successive output:
```
{ "_id" : ObjectId("5c0b7ebe0ebc5902bceec141"), "results_info" : { "info" : [  "Pending..." ], "style" : "" }, "tasks" : [ 	{ 	"last_updated" : ISODate("2018-12-08T08:22:03.816Z"), 	"num_games" : 250, 	"worker_info" : { 	"username" : "ChessDBCN", 	"country_code" : "HK", 	"unique_key" : "ec3758f7-8904-4c79-bd87-3d561db0885f", 
```


* ` db.runs.ensureIndex({'finished': 1}, {sparse: true})`
Runs fine but this don't change the output/behavior of  `db.runs.find({'finished': false})`

* this is the pserve.log after the commands
```
Starting subprocess with monitor parent
Starting server in PID 9279.
serving on http://0.0.0.0:6543
Overview exception: BSON document too large (16777392 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2018-12-11 11:29:19,593 ERROR [waitress][Dummy-2] Exception when serving /tests
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/waitress/channel.py", line 332, in service
    task.service()
  File "/usr/lib/python2.6/site-packages/waitress/task.py", line 174, in service
    self.execute()
  File "/usr/lib/python2.6/site-packages/waitress/task.py", line 382, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/usr/lib/python2.6/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/usr/lib/python2.6/site-packages/pyramid/config/views.py", line 369, in rendered_view
    context)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 531, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 561, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 557, in render
    result = renderer(value, system_values)
  File "/usr/lib/python2.6/site-packages/pyramid/mako_templating.py", line 227, in __call__
    raise ValueError('renderer was passed non-dictionary as value')
ValueError: renderer was passed non-dictionary as value
```

**Comment by ppigazzini** [comment]
@noobpwnftw test executed loading a fresh db backup.
`db.runs.remove({ "_id" : ObjectId("5c0b7ebe0ebc5902bceec141")})`
Fishtest works fine.
ps: to take the log of the mongo shell

```
mongo | tee  mongo-`date +%Y%m%d%H%M%S`.log
```

**Comment by ppigazzini** [comment]
The bad test should be [this](http://tests.stockfishchess.org/tests/view/5c0b7ebe0ebc5902bceec141)

The num_games is set to zero, could be the problem?

**Comment by Chess13234** [comment]
@ppigazzini  I've set to stop the test because it had an error in cutNode && && (which i copied to &&, i use github editor). Is it wrong ?

**Comment by Chess13234** [comment]
I've set it back to 250K

**Comment by noobpwnftw** [comment]
@ppigazzini 
I do not know the details for now but if that test has a very big database document in runs, then it may be caused by it, maybe the counter overflowed when generating tasks or something.

@Chess13234 
Page should at least guard against those values. To stop a test just click stop and change nothing else for the moment.

**Comment by Chess13234** [comment]
@noobpwnftw I recall when i tried to stop the test there was some loading error and instead i set it to -10 priority and 0 games, which would prevent it from running.

**Comment by ppigazzini** [comment]
@Chess13234 you have found a very bad fishtest bug :)

**Comment by vondele** [comment]
well, it *did* prevent his test from running.... with unexpected collateral damage :-) 

good debugging @ppigazzini

**Comment by ppigazzini** [comment]
@Chess13234  I was not able to replicate the bug on the dev server following your steps, so perhaps the bug was triggered by a not so banal combination of factors. Can you explain a bit your actions, please?

```
18-12-08 08:34:16 | Chess13234 | ImprovingNonCutNodeIID | stop run: User stop
18-12-08 08:33:56 | Chess13234 | ImprovingNonCutNodeIID | modify: games changed from 250000 to 0
18-12-08 08:32:16 | Chess13234 | ImprovingNonCutNodeIIDf | new run
18-12-08 08:30:05 | Chess13234 | ImprovingNonCutNodeIID | modify: priority changed from 0 to -10
18-12-08 08:27:33 | Chess13234 | ImprovingNonCutNodeIID | delete run
18-12-08 08:27:29 | Chess13234 | ImprovingNonCutNodeIID | delete run
18-12-08 08:27:03 | Chess13234 | ImprovingNonCutNodeIID | new run
18-12-08 08:24:15 | Chess13234 | ImprovingNonCutNodeIID | stop run: User stop
18-12-08 08:22:16 | Chess13234 | ImprovingNonCutNodeIID | stop run: User stop
18-12-08 08:22:05 | Chess13234 | ImprovingNonCutNodeIID | stop run: User stop
18-12-08 08:20:14 | Chess13234 | ImprovingNonCutNodeIID | new run
```

@noobpwnftw the json of ObjectId("5c0b7ebe0ebc5902bceec141") weighted 12MB the 08/12/2018 and 24MB the 09/12/2018. The json of all the finished runs is 3.7 MB.

Thebigger json of ObjectId("5c0b7ebe0ebc5902bceec141") is a long repetition (over 900k lines) of this element (there are also other usernames):
```
                {
                        "last_updated" : ISODate("2018-12-08T08:22:03.816Z"),
                        "num_games" : 250,
                        "worker_info" : {
                                "username" : "ChessDBCN",
                                "concurrency" : 8,
                                "remote_addr" : "xxx.xxx.xxx.xxx",
                                "unique_key" : "ec3758f7-8904-4c79-bd87-3d561db0885f",
                                "uname" : "Linux 3.10.0-862.14.4.el7.x86_64",
                                "version" : "66:2",
                                "architecture" : [
                                        "64bit",
                                        "ELF"
                                ],
                                "country_code" : "xx"
                        },
                        "residual" : 0,
                        "residual_color" : "#44EB44",
                        "active" : false,
                        "pending" : false
                },
```

ps: thank you to all of you for the support. The biggest thank you to @noobpwnftw , obviously.

ps2: @xoto10 I think to be able to update at mongodb 4.0.4 the official server.

**Comment by ppigazzini** [comment]
@Chess13234 thank you for your time. Please remember than I'm not a stockfish developer and a fishtest approver, so some of my questions could appear dumb.
Were there some workers running the test when you tried to stop it?
Do you viewed some strange results from the workers?
How have you got the "new run" action for the same test after having stopped it?
How have you got the "delete run" action?

ps: yes, I leaved "ImprovingNonCutNodeIIDf" to not break the sequence of actions

**Comment by ppigazzini** [comment]
@Chess13234 ok, the workers were not able to build the executable and in a couple of minutes the Object was already hogging the server. Strange that the Object had kept increasing the size.
Thank you.

**Comment by Rocky640** [comment]
@ppigazzini: can I set my priority back to 0 now ?

**Comment by noobpwnftw** [comment]
It was a combination of 0 num_games + unable to compile causing infinite loop on repeating the task?

@Rocky640 It seems unrelated to your test, sorry for confusion.

**Comment by ppigazzini** [comment]
@Rocky640 yes

@noobpwnftw I'm not able yet to replicate the bug on the dev server. I confirm that the code does not compile and the workers keep retrying. Anyway after stopping the test the workers switch to another test, so I don't understand why the Object became so big (and apparently in a couple of minutes to make the server nearly irresponsive).

**Comment by noobpwnftw** [comment]
@ppigazzini If you set num_games to 0 at some point after it started and that is the only test to run, will the workers keep trying and growing the document?
