### ISSUE TITLE
Stockfish 10 needs more depth than version 8 to find the correct move

### ISSUE THREAD

**Issue by ofsham** [glinscott/fishtest#343]
In many cases, Stockfish 8 finds the best move faster than version 10.  I first noticed that as in different cites the evaluation histogram of the moves bacame unstable changing drastically even when the move played was the best (according to Stockfish 10). Here is one example among many:
In this position (7k/p2qQ1p1/P1pP1r1p/1p3p2/4p3/2P4P/5PP1/3R2K1 b - - 2 2) Stockfish 10, depth=14 (single thread) approves 2…QxQ and it needs go further to prefer 2…Rf7 while Stockfish 8 gets the correct answer in lower depth.
Even worse, White’s answer to 2…Rf7 (7k/p2qQrp1/P1pP3p/1p3p2/4p3/2P4P/5PP1/3R2K1 w - - 3 3) by version 10, depth=12 is 3.Qe5?? while version 8 has no problem finding the correct move 3.QxR.

**Comment by Hanamuke** [comment]
This is the wrong repository for this issue. It should have been on https://github.com/official-stockfish/Stockfish. To answer your concern, the right question is not how much depth is needed to find the right move, but how much time, and this should have improved.
