### ISSUE TITLE
fishtest qt4core cutechess-cli edition for Linux

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#344]
Some modern Linux distributions has qt5core support only
Cause qt4 is obsolete, deprecated, etc..
Moreover current cutechess is qt5 based only too..

Could it possible to implement running fishtest with cutechess-cli static build or from sources?

BTW using qmake static builds for Windows(native/mingw/msys/cygwin) also is good idea against duty hack suggestions like:

https://github.com/glinscott/fishtest/issues/126

**Comment by ppigazzini** [comment]
@d3vv I built cutechess with QT static for Multivariant Fishtest, here the [repo](https://github.com/ianfab/FishCooking). On the wiki you find the [scripts](https://github.com/glinscott/fishtest/wiki/Build-cutechess-with-Qt5-static) for linux and windows.
Unfortunately today the Linux script triggers a gcc bug in Ubuntu 14.04.

**Comment by d3vv** [comment]
@ppigazzini So, if I try to port cutechess-cli w/o QT framework.. Does it interesting?

**Comment by ppigazzini** [comment]
@d3vv I'm closing this. The new binaries with QT5 static are ready and will be uploaded as soon as we decided the new repo location for books and binaries, read https://github.com/glinscott/fishtest/issues/376

**Comment by ppigazzini** [comment]
@d3vv new repo updated https://github.com/official-stockfish/books , the fishtest PR is ready to be merged https://github.com/glinscott/fishtest/pull/471 

> @ppigazzini So, if I try to port cutechess-cli w/o QT framework.. Does it interesting?

I prefer to use SW from project with active status to be able to upgrade in case of bugs. Thank you for your offer :)

**Comment by ppigazzini** [comment]
@d3vv on linux is impossible to have a true static build (and we could have some GNU license problem too), the best solution is to build on a older distro to improve the compatibility with the system libs.
I tried just now to make a cutechess-cli build (w/ Qt5 static) on Ubuntu 12.04 to improve the compatibility w/ very old distros, but Qt5 requires a c++11 compiler.
So 14.04 is the older version of Ubuntu that we can use out of the box to build cutechess-cli for fishtest.
