### ISSUE TITLE
Games in a game pair are highly correlated

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#348]
Following some reports by Kai Laskos on talkchess I decided to test for myself the correctness of the standard simplifying assumption that games in a game pair are independent. So I downloaded the pgns of some `150` LTC tests on fishtest and computed the correlation coefficient between the scores for white and for black. Lo and behold the correlation coefficient is usually around `-0.15` which is much too high (in absolute value) to be compatible with the null hypothesis that there is no correlation (`p-value=0`).

Now correlation is not actually a bad thing since it means in this case that the correct pentanomial variance is about `15%` smaller than the naive trinomial variance (see the section on Statistical Analysis in https://www.chessprogramming.org/Match_Statistics). This may not seem much but it literally means we could use `15%` fewer games during testing. To cash in on this opportunity the worker should send the result of each game pair to the server (there are 9 possible outcomes), which can easily be done in a backward compatible way, and the server should use this information to compute the correct LLR in the case of SPRT tests (e.g.  using the function `LLR_logistic` in [LLRcalc.py](http://hardy.uhasselt.be/Toga/LLRcalc.py)).

![reduction](http://hardy.uhasselt.be/Toga/reduction.png)

EDIT: The script to compute the variance ratios (as well as lots of other statistical information) is here:
[compute_stats](https://github.com/vdbergh/compute_stats/).

**Comment by vdbergh** [comment]
I changed my client to also send the pentanomial frequencies to the server.
```
{'username': 'vdbergh', 'stats': {'draws': 34, 'crashes': 0, 'wins': 16, 'losses': 11, 'pentanomial': [1, 4, 16, 8, 1], 'time_losses': 0}, 'task_id': 43, 'run_id': '5c3a2c4f0ebc596a450cb1cc', 'password': '**********', 'nps': 1305769.0}
```
I will make a pull request soon.

**Comment by vondele** [comment]
@vdbergh naive question .. if this just affects the variance, this means we could decide earlier in SPRT runs, but alternatively, one could say that  we have right now implicitly a higher confidence level ?

**Comment by vdbergh** [comment]
@vondele Yes I believe that's right. The actual LLR is about `18%` higher than the one we compute naively. 
This follows from the formula (2.1) http://hardy.uhasselt.be/Toga/GSPRT_approximation.pdf . The numerator remains the same but currently we overestimate the denominator. 

If we could be sure about this `18%` then we could just multiply the LLR by `1.18` but this would be quite dangerous I think since the ratio may depend on the time control and may also change over time.

Incidentally there is a simple theoretical formula for the ratio between the pentanomial and trinomial variance. It is function of the average bias and standard deviation of the book (expressed in `expected score-0.5`). The formula is
```
(sigma^2-sigma^2_book)/(sigma^2+mu^2_book)

where sigma^2=(1-d)/4
```
For the 2moves book at LTC we have `sigma_book=0.103 (+-72elo)` and `mu_book=0.041 (+-28elo)` (this was independently verified by Kai and me). For LTC we have `d=0.67` yielding a ratio of `0.852` which agrees with the observations.

**Comment by vdbergh** [comment]
I just made the pull request #351 with the required worker changes.

**Comment by xoto10** [comment]
Does the code change alter the variance of the test? I can imagine some code changes making fairly steady elo gains (perhaps a code speedup?) whereas some would increase the variance compared to "average" but still make elo gains in the long run (perhaps a term in evaluate() choosing more aggressive play?).

If this is the case then maybe analysing the consistency of the test while it runs would be useful? A test showing consistent gains could finish earlier, and a test showing big swings could be made to run for longer to get more confidence in the result.
I agree that using pentanomial is probably better than trinomial, but if the variance changes between tests then maybe it's less important to get the "right" distribution?

**Comment by vdbergh** [comment]
PR #352 is the next installment in the project.

**Comment by vdbergh** [comment]
One more: PR #354.

**Comment by Stefano80** [comment]
This is good @vdbergh, thank you. And the follow-up too...

**Comment by vdbergh** [comment]
#355 does fixed length tests.

The real challenge of course is SPRT. This will take a bit of time. The steps are as follows.

1. Create a simulator with realistic pentanomial frequencies that shows that the pentanomial LLR, computed as in http://hardy.uhasselt.be/Toga/LLRcalc.py does indeed behave correctly (I have done this before but now I understand better how to create realistic pentanomial frequencies starting from `(elo,draw_ratio,book_bias,book_variance)`). 

2. Update the SPRT routines on the server to use the pentanomial LLR.

3. Update the math behind the live_elo page using the Brownian approximation starting from (2.1) in http://hardy.uhasselt.be/Toga/GSPRT_approximation.pdf.

4. Rather than using the complicated chain `python-(hand translation)->C++-(emscripten)->javascript` I will import the python source on the server and provide the elo estimates via an api call.

**Comment by vdbergh** [comment]
I guess it is much too early to think about this but still...  I see that on the official fishtest site many people still use quite old clients. 

I wonder if there is a policy with regard to forcing client upgrades? Or do we just ask people nicely?

The use of old clients has the following consequences. 

1. If a client with version<68 is assigned a new task in a run then the pentanomial frequencies of the whole run will be invalidated which is wasteful. 

2. Currently it is even a bit worse. If such a client is assigned an old task which already has pentanomial frequencies then the client will not update them. As a result the pentanomial frequencies of the run will not be invalidated but they will be based on fewer than the available games, thus degrading the statistics derived from them.

Luckily this last issue can be solved on the server side by deleting existing pentanomial frequencies of a task if the client does not send them. However the first issue obviously cannot.

**Comment by ppigazzini** [comment]
@vdbergh the worker update v63 broke the updater code. This was fixed with #267 with the worker v64 https://github.com/glinscott/fishtest/pull/273. At the moment there are only 11 workers v63.

We can use the old plane https://github.com/glinscott/fishtest/pull/267#issuecomment-385422318 to enforce the workers update.

**Comment by ppigazzini** [comment]
@noobpwnftw tomorrow at 02:00 PM CET I would like to enforce the update of the workers to the latest version on GitHub (v68). Please check your workers update or update by hand.

**Comment by vdbergh** [comment]
Blogging... PR #358 implements a discrete time correction (since in general the LLR will overshoot the boundaries). This is based on a well-know procedure invented by Siegmund which is however not entirely correct since it is based on normally distributed jumps which is not true in our case (and this really makes a difference, even asymptotically).

I now found a simple and completely exact method of doing overshoot correction by using a randomized stopping rule, which kicks in once you are close to the boundary of the continuation region. So I plan to update PR #358 accordingly after suitable testing.

**Comment by vdbergh** [comment]
PR #361 introduces a new api call "get_elo" and uses it to render the live_elo page. The emscripten generated javascript code is no longer used.

**Comment by vdbergh** [comment]
I am still working on this but my main laptop with all my development stuff broke down, causing some delays. I am currently running some simulations to see if the pentanomial elo estimate and the corresponding confidence interval are accurate.

**Comment by vdbergh** [comment]
PR #372 uses the pentanomial frequencies for elo estimation for SPRT tests.

**Comment by vdbergh** [comment]
PR #373 add a page with raw statistics.
