### ISSUE TITLE
Unable to approve run! 

### ISSUE THREAD

**Issue by praveentml** [glinscott/fishtest#374]
Unable to approve run message popping up when trying to run test on my local fishtest server. Any help ?

**Comment by ianfab** [comment]
@praveentml To my knowledge there are basically two possible reasons: Either your user does not have approver rights, or you are approving a test of the same user. If you want to enable self-approving on your local server, you can comment out https://github.com/glinscott/fishtest/blob/aef93ec8f86777e830e57ba2b35f040e23b574e6/fishtest/fishtest/rundb.py#L499-L501

**Comment by praveentml** [comment]
Thank you .. It's approved but I see "Active - 0 machines 0 cores 0.00M nps "even though my worker is up and serving other games

**Comment by praveentml** [comment]
resolved one my own. ignore

**Comment by ianfab** [comment]
So I guess this can be closed?
