### ISSUE TITLE
Switching default opening book for testing to 2moves_v2

### ISSUE THREAD

**Issue by Alayan-stk-2** [glinscott/fishtest#376]
See this issue for discussion of the new opening book : https://github.com/official-stockfish/Stockfish/issues/1853

The 2moves_v2 pgn book by @dorzechowski with 12092 positions can be downloaded in this fishcooking thread : https://groups.google.com/forum/#!topic/fishcooking/cO5bF2_a6Ow

This is almost the same as the version which was tested on the test server and showed similar sensitivity to the current book with saner positions. The only difference is the removal of additional openings which end up with a wasted white tempo on the 3rd move (for example bishop on a6 which has to be retreated).

Marco said he is fine with the change.

> It looks good to me. I'm ok in changing the book.

@snicolet Could you also confirm this is good for you ?

**Comment by vondele** [comment]
I would be fine with this, and @mcostalba also agreed on this. What needs to be done to make this happen?

**Comment by ppigazzini** [comment]
From the code POV should be required only these steps:
1. copy the book into the [Marco's FishCooking repo](https://github.com/mcostalba/FishCooking/tree/setup), here the reference in the calling code
https://github.com/glinscott/fishtest/blob/master/worker/games.py#L44
2. update any reference to "2moves_v1.pgn" in fishtest code; I found only this line
https://github.com/glinscott/fishtest/blob/master/fishtest/fishtest/templates/tests_run.mak#L150

I don't know if it's required a calibration of some thresholds.

**Comment by vondele** [comment]
@mcostalba given the above, can you put the file in your repo ?

**Comment by mcostalba** [comment]
@vondele @ppigazzini doesn't it make more sense to take advantage of this opportunity and just copy the new book in fishtest repo? Eventually into a separate branch form master so that it does not get downloaded with the sources.

**Comment by vondele** [comment]
@mcostalba  I agree that we should migrate that that repo to main fishtest. 

However, that would likely be more work for @ppigazzini , and I'm not sure he has the time to do so. If he has, very good, but otherwise, I would moving forward with the book first, and make an issue to move the repo. So, @ppigazzini do you have a preference?

**Comment by ppigazzini** [comment]
I will try tomorrow adding a branch in my fishtest repo and testing with the development server. One year ago this slowed down the workflow of the development server (clone of the repo with books and engines binaries).

**Comment by mcostalba** [comment]
@ppigazzini Thanks! I'd suggest you add the book here in github (for instance create a branch called book), not on your local repo or on the fishtest server.

**Comment by ppigazzini** [comment]
@mcostalba I will test on my repo, if successful I will do the work on the official fishtest :)

**Comment by ppigazzini** [comment]
@mcostalba your "setup" branch is used also for the cutechess binaries.

**Comment by Alayan-stk-2** [comment]
What's the testing's status ? I'd like to run a tune with the new book.

**Comment by MJZ1977** [comment]
What is the status of this patch please ?

**Comment by Alayan-stk-2** [comment]
Any news ?

**Comment by MJZ1977** [comment]
Same request 👍

**Comment by Vizvezdenec** [comment]
Bump :)

**Comment by ppigazzini** [comment]
Sorry guys, I restarted to work on fishtest after dealing for 6 months w/ a family-related problem.

After some tests I think that the @mcostalba suggestion (to create a 'book' branch on fishtest repo) is not optimal.

For each fishtest PR I clone the fishtest repo on the dev server to be sure to have not leftovers. I already updated my scripts w/ `git clone -b master --single-branch` to minimize the download, but if other people should clone routinely the repo I fear that we can hit some GitHub bandwidth limits (I have not investigated about this subject). In this moment the FishCooking setup branch has a git objects db size of 29 MB, each update of the cutechess-cli binaries will add 7 MB.

A better solution is to create a new repo for the books and for the cutechess-cli binaries (the real problem).

**Comment by vondele** [comment]
@ppigazzini good to read you're back, I hope all worked out well.

Concerning cutechess binaries, maybe one can use the release feature of git for which the is no bandwidth limit https://help.github.com/en/articles/distributing-large-binaries

However, sizes you mention seem small, repos up to 1Gb seem rather standard, the hard limit is 100Gb. https://help.github.com/en/articles/what-is-my-disk-quota#file-and-repository-size-limitations

**Comment by ppigazzini** [comment]
@vondele thank you for the wishes...

fishtest is hosted into the Gary's account, I haven't visibility of quota/settings and I don't want to hit some bandwidth limits.

I build cutechess binaries w/ clean virtual machines and test for virus/false positive w/ virustotal (e.g. https://github.com/ianfab/FishCooking/commit/5046bb974b41129cf2cb2cdbae0e59749882ec1f).

However I'm not happy in spreading in stealth mode the binaries: all my colleagues thought that git clone only the master SHAs.

IMO the books&binaries repo could be created on https://github.com/official-stockfish, no problem to be a maintainer.

**Comment by ppigazzini** [comment]
Fabian wrote https://github.com/ianfab/bookgen to create books with several filtering strategies, there is also the recipe used for the 2moves_v1.pgn

**Comment by ppigazzini** [comment]
@snicolet @mcostalba have you the possibility to fork a new books&binaries repo on https://github.com/official-stockfish ?

**Comment by snicolet** [comment]
@ppigazzini 

Sorry, I don't have the credentials on https://github.com/official-stockfish to create a new repository for storing the books and the cutechess binaries.

In the Stockfish team, @glinscott , @zamar and @mcostalba are marked as "owners" of github.com/official-stockfish, so probably only them can create such a repo. That would indeed be a good idea :-)

**Comment by noobpwnftw** [comment]
Don't you think I should just host those books and test repos?
They can be in the same network as 90% of the workers and saves all the trouble of downloading from Github.

**Comment by glinscott** [comment]
I'm happy to create a new archive there as well if needed.  Just let me know the name(s).

**Comment by ppigazzini** [comment]
@glinscott with a flight of fancy I propose FishCooking, like the Marco's repo, so we should change only the user name here:
https://github.com/glinscott/fishtest/blob/2b4c830d1ab01fc5b9d5fca5f4a752a4c060c141/worker/games.py#L44
and the branch name here:
https://github.com/glinscott/fishtest/blob/2b4c830d1ab01fc5b9d5fca5f4a752a4c060c141/worker/games.py#L98

**Comment by ppigazzini** [comment]
@snicolet after fixing the fishtest server stability/speed, we should close now the books&binaries issues (I lost the count :) ).
Let me know if you want to use:
* the new repo https://github.com/official-stockfish/books
* clone https://github.com/mcostalba/FishCooking/tree/setup or  https://github.com/ianfab/FishCooking to keep the history

I must:
* open a PR with the cutechess-cli binaries. I will uses the well tested versions built for http://www.variantfishtest.org:6543/tests --  https://github.com/ianfab/FishCooking
* open a PR with the worker patch

**Comment by ppigazzini** [comment]
@snicolet @vondele @Alayan-stk-2 I opened the PRs to usethe  new book and the up to date cutechess-cli:
https://github.com/official-stockfish/books/pull/1
https://github.com/official-stockfish/books/pull/2
https://github.com/glinscott/fishtest/pull/471
https://github.com/glinscott/fishtest/pull/472
