### ISSUE TITLE
Search or calculation gets wrong position/branch

### ISSUE THREAD

**Issue by illuminat281090** [glinscott/fishtest#377]
I use this online resource https://www.365chess.com/analysis_board.php and it claims SF is used here.

i looked on this position (black's move)
![image](https://user-images.githubusercontent.com/24498981/57030095-5885f880-6c4c-11e9-829f-0dd341df32e3.png) 
(FEN: k7/1p5p/p4p2/8/4K1P1/1B6/Pr6/8 b - - 1 41)
Engine analyzing it more than 15 minutes and shows Kb8 with mark '-7.75' or so in depth 32.
But i dislike it. I want to move Rb3.
Once i moved so, in a few seconds i got '-12' in depth 27, in 1 minute it shows '-63' in depth 35.

As of mine, there is smth wrong with forward pruning algorithm which ignores some subbranches.
Please review ASAP.

**Comment by ppigazzini** [comment]
@illuminat281090 this is the fishtest repo, the framework that tests the Stockfish patches. If not already done, please report the problem on [FishCooking](https://groups.google.com/forum/?fromgroups=#!forum/fishcooking), the Stockfish forum.
