### ISSUE TITLE
[FishTest 2019 Games Not Saving Bug Issue] Result in Weaker Stockfish Conversion to NN Form (-30 Elo)

### ISSUE THREAD

**Issue by Cscuile** [glinscott/fishtest#379]
There is a project of mine called BetaOne in which attempts to essentially convert Stockfish into an NN form engine.

Currently 2019 games are not saving resulting in an overall 30 Elo or so weaker performance.

Is there anyway I can assist in saving the FishTest games from 2019?

Thanks to my college, I have unlimited drive space so if anyone is willing to help get me setup please feel free to contact me here or on discord Cscuile #0 0 4 4.

Thank you!

**Comment by fun8** [comment]
You can use your unlimited drive space for web server, like fishtest. And disributively generate own games.

**Comment by fun8** [comment]
Also you can modify fishtest executable for sending games  on your

**Comment by ppigazzini** [comment]
The official server stopped saving PGN after a reload of the mongo db. The code is working fine on the development server.
The official server runs on a dated CentOS6, uses dated MongoDB/git/python version and the python packages were installed in a mixed mode (using yum, by hand, through pip).
We are ready to setup a new official server w/ Ubuntu 18.04 LTS and up to date SW packages (installed in a proper way). I'm waiting the answer of the person who has access to the VPS control panel.

**Comment by MJZ1977** [comment]
Please, can we correct this issue because it is annoying to see patchs falling without having PGN to analyse the reasons.

**Comment by glinscott** [comment]
Oop, sorry, is this waiting on me?  Sorry, I didn't see the email.  Happy to update it.

**Comment by Cscuile** [comment]
Don't worry, BetaOne is long dead due to college and no free time. 

Don't feel any pressure to update FT. 😃

**Comment by ppigazzini** [comment]
@Cscuile @glinscott PGNs saving should restart working after the upgrade to Ubuntu 18.04. I'm closing this issue.

**Comment by MJZ1977** [comment]
Just for information : PGN saves are still not working.

**Comment by tomtor** [comment]
> Just for information : PGN saves are still not working.

@MJZ1977 That is because the system is not upgraded yet... If all goes well that will be completed around 1800 UTC October 5th

**Comment by ppigazzini** [comment]
The latest db extraordinary maintenance (db dump, mongodb clean install, db restore) seems to have solved the PGN saving.
