### ISSUE TITLE
PGN files no more saved on server

### ISSUE THREAD

**Issue by MJZ1977** [glinscott/fishtest#380]
We cannot download PGN files since several months from fishtest server. It was a important feature to understand how patchs are working and how to improve them. Is there a plan to make this feature working again ?

Thank you

**Comment by Cscuile** [comment]
Yes, this is a big issue. The strongest games are not being saved.

**Comment by ppigazzini** [comment]
Duplicate https://github.com/glinscott/fishtest/issues/379
