### ISSUE TITLE
SMP tests: add "Standard STC SMP" and "Standard LTC SMP" buttons

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#384]
Currently we have 2 buttons - standart STC and standart LTC which set TC and hash accordingly.
But we have no standart STC SMP and standart LTC SMP which are actually more or less standart but not having them can create quite a mess.
I propose to create this 2 buttons (at test submitting page), stc should set TC to 5+0.05, threads to 8 and hash to 32, LTC should set TC to 20+0.2, threads to 8 and hash to 128.
@vondele what do you think about it? :)

**Comment by tomtor** [comment]
I agree that adding those options is a good suggestion.

**Comment by vondele** [comment]
yes, that's a good idea, as long as the 8 core machines dominate fishtest.

**Comment by Vizvezdenec** [comment]
So, will this be done?
Whenever I try to do SMP tests I ALWAYS fuck up TC/hash/whatever at least once because I click to standart buttons and forget either to set threads/hash/bounds/tc at least once in series test.
Like there.
https://tests.stockfishchess.org/tests/view/5e87a3694411759d9d0986ca
:) Hash for STC should be 64 now (I think) and for LTC probably 256 or smth like this.

**Comment by ppigazzini** [comment]
@Vizvezdenec merged, I will update PROD as soon as it will be on line.
