### ISSUE TITLE
Add CSRF security

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#386]
See https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#checking-csrf-tokens-automatically

Could be done after the server infrastructure upgrade when https is active and the software stack up-to-date (requires pyramid >= 1.7)

**Comment by ppigazzini** [comment]
If I'm not wrong this could be added now.

**Comment by tomtor** [comment]
@ppigazzini Yes, I think it can be added now. I will have a look at it.

**Comment by tomtor** [comment]
@linrock I had a quick look at this, but if you have experience with this and find it interesting, please have a look.

**Comment by linrock** [comment]
sounds good, i'll take a look at this
