### ISSUE TITLE
Fishtest in an infinite loop

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#395]
The Fishtest site is not working at the moment.

From what I can see or infer from the state just before the pages stop responding,
this may be due to the test "KingAndPawnEvaluator" not compiling properly on some
workers. 

This happens sometimes, tests which cannot compile suck the workers but never
release them. These tests show that they have many active workers but no games.

The problem today is that it seems impossible to stop this test...

**Comment by ppigazzini** [comment]
@snicolet the Fishtest site seems working fine in this moment, no action by me on the vps.

**Comment by tomtor** [comment]
I assume it needs a similar change as #390.

**Comment by ppigazzini** [comment]
@snicolet fixed, thank you for the alert.

**Comment by snicolet** [comment]
Thanks to both!
