### ISSUE TITLE
LTC button

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#405]
Maybe i'm the only one who gets caught with this but...

When we reschedule a STC test, and press LTC, time and hash are changed correctly,
but sprt stays the same which is unexpected behaviour.

if sprt was 0.5...4.5 (STC) it should change to 0....3.5 (LTC)

**Comment by tomtor** [comment]
@Rocky640 Sounds like something that could happen to me ;-)

**Comment by Rocky640** [comment]
nice job ! txs
