### ISSUE TITLE
Decrease maximum number of games for long runs

### ISSUE THREAD

**Issue by MJZ1977** [glinscott/fishtest#410]
The issue is that for very long TC and/or multiple threads each run takes too much time to finish the job for 250 games. Sometimes it can takes several hours to free workers for other new runs.

I propose that we lower the limit to  100 or even 50 for these runs. Approvers can choose or automatic, the easiest option to add.

**Comment by tomtor** [comment]
Lowering this number results in a much larger memory consumption for the server for equal max number of games. 

It was originally 1000 and lowered to 250 as a compromise for the reasons you mention.

**Comment by MJZ1977** [comment]
Yes, I understand and remember the 1000 to 250 change.

If the change affects only very long runs (superior to LTC), can this lead to a memory problems ?

Another alternative in this case is to have an option to limit maximum core use per run.

**Comment by tomtor** [comment]
Currently we reserve 1000 slots, so default max nr games is 250000. If task size is reduced to eg 100, then the max would be 100000 which results in the same memory consumption. So if we lower max games simultaneously when lowering the task size, then there should be no memory issue and 100000 games would be sufficient for VLTC tests.

So it is possible, but it has a low priority IMO.

**Comment by ppigazzini** [comment]
Solved by #1021
