### ISSUE TITLE
Gracefully decommissioning workers

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#412]
I wonder what is the best way to decommission a large number of workers, say after they finish their current task and not to request the next one.
How can I reduce disruption of running tests when I need to turn off some workers without either aborting their tasks or waiting for fishtest to recycle their task slots?

**Comment by tomtor** [comment]
Would require eg a file flag (simple and portable) or implementing an Unix SIGHUP handler for the worker.

I will put it on my to-do list, but for now I suggest not to worry about it.
