### ISSUE TITLE
Regression test links produce internal server error

### ISSUE THREAD

**Issue by gvreuls** [glinscott/fishtest#425]
On the server, links to completed regression tests fail and produce an internal server error.

This is easily reproducible by clicking a "master" link on the [Greens](http://tests.stockfishchess.org/tests?success_only=1) pages.

Direct failing links:
[Single core 9-10-18](http://tests.stockfishchess.org/tests/view/5da9d8470ebc597ba8edbb52)
[Multi core 19-10-06](http://tests.stockfishchess.org/tests/view/5d9932830ebc5902b6cef9fc)
[Single core 19-10-06](http://tests.stockfishchess.org/tests/view/5d99322f0ebc5902b6cef9fa)
[Multi core 19-09-17 ](http://tests.stockfishchess.org/tests/view/5d80d2240ebc5971531d1e46)
[Single core 19-09-17](http://tests.stockfishchess.org/tests/view/5d809d540ebc5971531d0b66)

Note that links to [-3,1] master tests work fine:
[Testing the 8MB stack size patch 19-09-17](http://tests.stockfishchess.org/tests/view/5d80a9860ebc5971531d10ff)

**Comment by tomtor** [comment]
Hmm, probably a side effect of the blue patch?
@ppigazzini Can you give me a copy of the stacktrace?

**Comment by tomtor** [comment]
@ppigazzini No need for stacktrace....
