### ISSUE TITLE
Worker with lots of time losses in the framework

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#427]
Hi everybody,

the worker "mgrabiak-6cores-49" seems to generate lots of losses on time
in the framework at the moment, impacting the precision of some SPRT tests:

a) this is worker #40 with 232 LOT out of 250 games in this test:
http://tests.stockfishchess.org/tests/view/5dbb24020ebc5925b64edef6

b) and worker #203 here with already 6 LOT out of 45 games:
http://tests.stockfishchess.org/tests/view/5dbab3f90ebc5925b64ed70b

What is strange is that nowadays the buggy slots of 250 games are no longer
purged when we stop a test. But they used to be auto-purged, so that the tests
could renter the loop without wasting all the correct workers games?

Stéphane

**Comment by tomtor** [comment]
@snicolet That is related to your observation in https://github.com/glinscott/fishtest/issues/395

So now stopping tests by hand is immediately effective and does no longer depend on completing an auto-purge. So auto-purge is only done when a test ends normally. If you hit 'stop' then you should purge by hand.
