### ISSUE TITLE
Missing number of active tests

### ISSUE THREAD

**Issue by mrobaczyk** [glinscott/fishtest#450]
On the main page we have:
Pending - X tests
Finished - X tests
but Active has no such counter - it displays machines and cores info though.

I looked in the code and there is something that I dont understand:
```
%else:
 <h3>Active - ${len(runs['active'])} tests</h3>
%endif
```
It should be displayed when 'show_machines' is false but it doesn't change when I hide machines list.

@tomtor if you think that adding active tests counter is a nice improvement, could you please look at the code?
Thanks :)

**Comment by tomtor** [comment]
@mrobaczyk That code is executed when you show tests by a user by selecting a user name (click on a blue username on the main page).

The active line is already a bit long, but adding the tests counter is ok for me. Perhaps we should remove the nps info or show it somewhere else.

Can you create a PR?

**Comment by mrobaczyk** [comment]
Yes maybe we should remove the average nps, but leave cores and total nps. But I don't think I'm the right person to make such decisions. :)

**Comment by xoto10** [comment]
I guess this is a separate suggestion:
I think the games/minute is a theoretical calculation rather than actually counting how many games are being played each minute. It would be nice to display the actual throughput rather than a theoretical throughput.
