### ISSUE TITLE
Clean up MongoDb indices

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#452]
I intend to drop these unused indices:

    db['runs'].drop_index('last_updated_-1_start_time_-1')      # 0 usage                                                                                        
    db['runs'].drop_index('tasks.pending_1')                            # 0 usage                                                                                
    db['runs'].drop_index('deleted_1_finished_1')                     # Used once???

**Comment by tomtor** [comment]
@xoto10 @ppigazzini Ideas? Especially regarding `deleted_1_finished_1` which is used once?

**Comment by ppigazzini** [comment]
@tomtor I can drop the indexes by hand on DEV and bench with my curl script.

**Comment by xoto10** [comment]
Looks good to me. 

I suggest we drop one index per week from that list, in that order, and keep an eye on perceived performance and that load average graph. That keeps the admin load minimal, and makes it trivial to see if there are any good/bad effects. This sounds slow, but even dropping one index is useful progress, no need to risk confusing ourselves by making more than one change at a time.

Can we run the updated test_queries.py to see what the output is as a current benchmark? The main page certainly looks quick now.

**Comment by xoto10** [comment]
[ My suggestion of dropping one index at a time is for Prod, for Dev feel free to start by dropping all 3 and see what happens ... ]

**Comment by ppigazzini** [comment]
tomtor benches running `$ time bash curl_tests.sh`

* all indexes
```
real    2m3.240s
user    0m4.297s
sys     0m9.578s
```
* all indexes loading mongo also with `curl_loop.sh`
```
real    2m47.738s
user    0m4.563s
sys     0m9.125s
```

* dropped 3 indexes
```
real    1m50.347s
user    0m4.391s
sys     0m9.313s
```
* dropped 3 indexes loading mongo also with `curl_loop.sh`
```
real    2m51.468s
user    0m4.266s
sys     0m9.344s
```

```
 > db.runs.stats()
...
       "nindexes" : 5,
        "indexBuilds" : [ ],
        "totalIndexSize" : 679936,
        "indexSizes" : {
                "_id_" : 188416,
                "finished_1_last_updated_-1" : 126976,
                "finished_1_last_updated_-1_start_time_-1" : 200704,
                "deleted_1" : 81920,
                "args.username_1" : 81920
        },
        "scaleFactor" : 1,
        "ok" : 1
}
```

**Comment by xoto10** [comment]
@tomtor @ppigazzini 
> Ideas? Especially regarding `deleted_1_finished_1` which is used once?

I don't think this should be needed. There is another index on `deleted` and that will only have a relatively small number of rows, so that can be used whenever a query on `deleted: true` is required. No need for finished in the index as well. 

Perhaps the one use was from one of you guys doing something manually? Even if it was from legitimate use of fishtest it's obviously extremely rare, so I don't think it justifies having an index - especially given my 1st thought above.

**Comment by ppigazzini** [comment]
@xoto10 the first server setup in 2013 was made mostly by hand.
I and @tomtor are trying to keep documented the whole server configuration. At the moment only sshd_config and mongod.conf are configured by hand, but I will add the latter to the setup script.

**Comment by xoto10** [comment]
@tomtor @ppigazzini 
See #453 for a script to (re-)create the indexes.

**Comment by snicolet** [comment]
@tomtor @ppigazzini @xoto10 

You three guys have made fabulous work during the last weeks, thank you so much!

**Comment by ppigazzini** [comment]
Thank you @snicolet !
