### ISSUE TITLE
auto-purge is broken

### ISSUE THREAD

**Issue by lucasart** [glinscott/fishtest#47]
The chi-square test indicator is the pvalue, not the max residual.

Using the max residual isn't equivalent, and it's dangerously biased towards over-purging tests with many workers.

With the current purge based on max residual > 2.7, you're purging far too much. I don't know if it's possible to see on the server side in the logs, but I bet half the tests are purged.

**Comment by lucasart** [comment]
Auto-purge is still wrong. Purging means removing the offending worker, which is the one with the highest residual, not every worker with a large residual. THis is very different, and many good workers have large residual because bad workers pollute the global stats. You need to purge one worker, then *recalculate* the chi-square test, and *re-test* the p-value condition, and purge the one offending worker, until the p-value is good (or everything is purged).

For example, looking at the auto-purge code, I think it will purge the entire tasks in this test: http://tests.stockfishchess.org/tests/view/54a463920ebc5938eaa8b0e0

    Idx 	Worker 	Last Updated 	Played 	Wins 	Losses 	Draws 	Crashes 	Time 	Residual
    0 	BRAVONE-23cores 	1 days ago 	1000 / 1000 	198 	191 	611 	0 	0 	4.072
    1 	glinscott-16cores 	1 days ago 	1000 / 1000 	171 	170 	659 	0 	0 	4.962
    2 	CoffeeOne-23cores 	1 days ago 	1000 / 1000 	212 	175 	613 	0 	11 	8.000
    3 	glinscott-16cores 	20 hours ago 	1000 / 1000 	186 	183 	631 	0 	13 	8.000
    4 	glinscott-16cores 	9 hours ago 	1000 / 1000 	167 	162 	671 	0 	1 	8.000
    5 	glinscott-16cores 	21 hours ago 	1000 / 1000 	166 	168 	666 	0 	0 	4.962
    6 	BRAVONE-23cores 	19 hours ago 	1000 / 1000 	195 	202 	603 	0 	0 	4.072
    7 	BRAVONE-23cores 	6 hours ago 	1000 / 1000 	201 	197 	602 	0 	0 	4.072
    8 	glinscott-16cores 	seconds ago 	856 / 1000 	143 	133 	580 	0 	0 	4.962
    9 	BRAVONE-23cores 	seconds ago 	454 / 1000 	81 	81 	292 	0 	0 	4.072

Instead you should purge the `CoffeeOne-23cores` tasks (highest residual 8). Recompute the whole chi2 test, and see if if still needs purging (maybe it doesn't) etc.

**Comment by glinscott** [comment]
Ok, agreed, I've set it to only purge the worst now - 319e9cdb2b652dce87225d6e729a902469ca5cc7
