### ISSUE TITLE
Scale batch size with time control

### ISSUE THREAD

**Issue by ghost** [glinscott/fishtest#482]
Could something be changed to use smaller batches for LTC and VLTC tests? they seem to occupy workers regardless of throughput or priority.

**Comment by tomtor** [comment]
A (better?) alternative would be to (automaticly) stop/restart a test when priority is lowered.

**Comment by tomtor** [comment]
See also #410 (duplicate)

**Comment by Chess13234** [comment]
If fishtest could handle variable size batches, the better solution would be assigning batches based on number of cores multiplied by time control - no games wasted and workers will get freed at predictable time(unlike e.g. LTC 1 core worker being assigned 250 games).
example:
STC, 1 core - 16 games.(x16 cores)
LTC 1 core - 4 games(x4 cores)
VLTC 1 core - 2 games(x2 cores)
STC 8 Core - 128 games
LTC 8 core - 32 games
VLTC 8 core - 16 games.

**Comment by Alayan-stk-2** [comment]
1 core workers taking forever to finish on regression tests are extremely annoying.

**Comment by ppigazzini** [comment]
Solved by #1021
