### ISSUE TITLE
Leave an audit trail that a test has been purged.

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#489]
Currently the only indication that a test has been purged is I think a (possibly) strange LLR value like in this test  http://tests.stockfishchess.org/tests/view/5e10428db48e44a99a9bb599 .

This is a bit frustrating since such a strange LLR value could conceivably also be the result of a bug.
So some other systematic indication of purging would be nice. I can implement this myself but perhaps someone else can do it quicker.

**Comment by vondele** [comment]
I agree that this would be useful. I.e. kept in the list, but e.g the color field dark red.

There is a very hidden trail... the batch IDs have gaps. 

There has been some discussion on completely removing auto-purge https://github.com/glinscott/fishtest/pull/394#issuecomment-535840239

**Comment by vdbergh** [comment]
Thanks. I had missed that discussion. I feel that purging should either be done automatically or never. Now auto purging is done - I think - if p<0.01. The idea is that p<0.01 is an indicator that something _might_ be wrong with some workers. But it will also happen by itself in 1% of the tests. By doing auto purging one avoids introducing bias for those fluke cases.

In any case 0.01 is probably too high for the volume of tests on Fishtest.  Perhaps p<0.001 would be a better precondition.

**Comment by Chess13234** [comment]
@vdbergh  more of these tests with strange LLR:
http://tests.stockfishchess.org/tests/view/5e0e94ffe97ea42ea89da9d6 -3.45
http://tests.stockfishchess.org/tests/view/5e08bfa59d3fbe26f672d36b -3.61
http://tests.stockfishchess.org/tests/view/5e013c0ac13ac2425c4a9a81 -3.41
http://tests.stockfishchess.org/tests/view/5df7dab16932658fe9b45268 -3.27
http://tests.stockfishchess.org/tests/view/5dea97aecaa7c610e4d186cc -3.40
http://tests.stockfishchess.org/tests/view/5dea92b6caa7c610e4d186c4 -3.19
http://tests.stockfishchess.org/tests/view/5dea9734caa7c610e4d186ca -3.01
http://tests.stockfishchess.org/tests/view/5dea98accaa7c610e4d186d0 -4.67
http://tests.stockfishchess.org/tests/view/5dea69d6caa7c610e4d186a4 -3.79
http://tests.stockfishchess.org/tests/view/5dea88dacaa7c610e4d186b7 -3.34
http://tests.stockfishchess.org/tests/view/5dea6cc6caa7c610e4d186ac -3.59
http://tests.stockfishchess.org/tests/view/5dea6859caa7c610e4d1869b -3.40
http://tests.stockfishchess.org/tests/view/5dea5c59caa7c610e4d18698 -3.47
http://tests.stockfishchess.org/tests/view/5de57773b407ee7bfda68a3e -3.07
http://tests.stockfishchess.org/tests/view/5ddab668e75c0005326d2103 -3.04
http://tests.stockfishchess.org/tests/view/5dd4d5a3f531e81cf278eaae -3.83
http://tests.stockfishchess.org/tests/view/5dcbb47f0ebc590256924190 -3.05
http://tests.stockfishchess.org/tests/view/5dbccd070ebc5925b64ef751 -3.06
http://tests.stockfishchess.org/tests/view/5dbc7f9b0ebc5925b64ef261 -3.56
http://tests.stockfishchess.org/tests/view/5dbb13da0ebc5925b64edec8 -3.12
http://tests.stockfishchess.org/tests/view/5db1b7e60ebc590812750874 -3.22
http://tests.stockfishchess.org/tests/view/5daa24670ebc590de13a17f2 -3.01
http://tests.stockfishchess.org/tests/view/5da00d5d0ebc597ba8ed0d39 -3.08
http://tests.stockfishchess.org/tests/view/5d9c21b60ebc5902b6d0661b -3.01

http://tests.stockfishchess.org/tests/view/5ddc6b485a23bc8a4083316a +3.45

http://tests.stockfishchess.org/tests/view/5d9784e60ebc590c21aa7013 +3.15
http://tests.stockfishchess.org/tests/view/5d82f6600ebc5971531d385c +3.04
http://tests.stockfishchess.org/tests/view/5cef595d0ebc5925cf082441 +3.70
http://tests.stockfishchess.org/tests/view/5c9c25780ebc5925cfffa2c0 +3.16
http://tests.stockfishchess.org/tests/view/5c4bcfba0ebc593af5d49ea8 +3.40
http://tests.stockfishchess.org/tests/view/5c45bf610ebc5902bb5d5d62 +3.19 
http://tests.stockfishchess.org/tests/view/5c3491d30ebc596a450c4e8e +3.18
http://tests.stockfishchess.org/tests/view/5c2f176f0ebc596a450bdfb3 +3.15
http://tests.stockfishchess.org/tests/view/5c1aa8d50ebc5902ba127ad0 +3.12

**Comment by ppigazzini** [comment]
Problematic workers are rare now. I prefer to avoid purging and use chi2 test and residual analysis only for a post mortem analysis.
@vdbergh @lantonov in case of evident workers problems I'm wondering what is more statistically sound between purging the outliers or redoing the test.

**Comment by vdbergh** [comment]
I guess redoing the test would be the safest, but I think that purging is also fine and it saves (often a lot of) resources (sorry that I do not know a more definite answer).

What would definitely be bad is to factor the outcome of the test in the decision of pruning/redoing. That's why I think pruning/redoing should be automatic if it is done at all.

Concerning the issue of ill configured/malicious clients. If we don't prune then they will be detected because they will repeatedly show high residuals in the test outcomes. But of course someone needs to do the inspection. In the beginning this was easy since there were a lot of such clients, but now as you say they are rare.

**Comment by Chess13234** [comment]
Could autopurge work, but just leave the batch as is, i.e. only alter the statistics not delete PGNs and test table entries?

**Comment by ppigazzini** [comment]
The framework is often half empty with multiple little variants of the same idea (often all passing STC with the new relaxed bounds...), so I'm for to lower the p-value (e.g. 0.001) and auto rescheduling only once the test (e.g. adding a tag to the test description). Without "mad workers" out there we should raise the framework load of the 0.001.

**Comment by vdbergh** [comment]
@ppigazzini This sounds reasonable to me and might be worth a try. p=0.01 is too high for the Fishtest load. And for an event that happens once in a thousand tests I guess one could even accept a manual restart. The bias risk would be minuscule (if significant p-values would happen more often then that would be a sign that something is wrong and some manual intervention would be necessary anyway).

**Comment by ppigazzini** [comment]
I opened #502 to lower the p-value to 0.001
This should limit cases like the #501

**Comment by ppigazzini** [comment]
#502 merged.

**Comment by ppigazzini** [comment]
@vdbergh some thoughts on our chi2/residuals filter:
- if chi2 < p we drop the games played by some outlier workers
- chi2 < p is expected with probability p for a framework without problems  
- after autopurge we continue the test keeping the new games played by the outlier workers
- to trigger the autopurge on DEV I simply set a VSTC (usually 1+0.01) and join my workers, so chi2/residuals have some dependency at least on TC

IMO:
- never drop data
- if we want filter the data:
  - save the filter parameters in the test data (so changing the default values will not change the result of finished tests)
  - always compute the SPRT values using the 1-p games according the residuals distribution (so never use the outliers games, never use chi2 as a trigger):
    - compute the games batches residuals (not the worker one)
    - order the residuals
    - uses the next batch of games while n_games/tot_games <= 1-p (with n_games+=n_games_next_batch)

**Comment by ppigazzini** [comment]
@vdbergh I'm closing the Issue because the request is fulfilled.
Anyway you can view in this [purged test on DEV](https://dfts-0.pigazzini.it/tests/view/5e22f71ed8df75bc5cca5326) one of the reasons why I think that the purge process as defined today is not statistically sound (the filter process is workers based, but we have either purged and accepted games from purged workers).
Anyway using a lower p-value #502 and keeping all data #509 are an improvement.

**Comment by vdbergh** [comment]
@ppigazzini  @tomtor  Thanks for fixing this so swiftly!

Concerning the soundness of purging. I think throwing away data (or adding data for that matter) is generally ok as long as there is no  connection between the selection of the data and the result one wants to obtain. I think this is the case with purging but I agree we cannot be sure.
