### ISSUE TITLE
Fix the geo location resolve by using another API endpoint

### ISSUE THREAD

**Issue by NoTeefy** [glinscott/fishtest#498]
I was wondering why some subnets/ip addresses don't receive proper flags in the testing framework. Turns out the API you guys and gals use is considered deprecated and no longer operates. 
Here's an example GET request to that API endpoint:
```json
curl -L http://geoip.nekudo.com/api/

{
  "0": "#################################################################################################################################",
  "1": "#                                                                                                                               #",
  "2": "# IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                                                                   #",
  "3": "#                                                                                                                               #",
  "4": "# This API endpoint is deprecated and has now been shut down. To keep using the Free Geolocation API, please update             #",
  "5": "# your integration to use the new ipapi API endpoint, designed as a simple drop-in replacement.                                 #",
  "6": "# You will be required to create an account at https://ipapi.com and obtain an API access key.                                  #",
  "7": "#                                                                                                                               #",
  "8": "# For more information on how to upgrade please visit our Github page at: https://github.com/nekudocom/shiny_geoip#readme       #",
  "9": "#                                                                                                                               #",
  "a": "#################################################################################################################################",
  "country": ""
}
```

https://github.com/glinscott/fishtest/blob/481591d6aa28fed433c6d773b6c10f0d3150c266/fishtest/fishtest/api.py#L8 would be the place where a logic rehaul is needed.

I know that it's just a style fix and nothing major but I think it would look better if all runners would be represented by their locations. I could provide an own patch for it if nobody feels interested in it, but I am not too familiar with your framework yet and want to respect all of your coding/contribution guidelines before providing patches.

**Comment by ppigazzini** [comment]
@NoTeefy feel free to open a PR, every contribution is welcomed :)

**Comment by NoTeefy** [comment]
Gonna give it a shot then. I need to know certain things though: Is there any service mail I could register such an account on? Like a technical user for that token we need with the new API?
And how would you guys provide such a token. Are you using environment variables/files for your deploys on the official Fishtest server?
I wouldn't put a token into public code 😄

**Comment by ppigazzini** [comment]
@NoTeefy we use 2 files with secrets (recaptha, github) and a couple of variables (aws s3). You can develop and test locally the patch using your email and then providing the instruction when opening the PR.

In this [wiki page](https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup) you find the scripts: to setup a fishtest server in a vm w/ Ubuntu 18.04, to update the server with a github branch/PR, to update a worker with a github branch/PRs.

**Comment by NoTeefy** [comment]
@ppigazzini thanks a bunch for your fast response and input. I made a little PR with the tiny fix. I've tested it locally and on one of my servers with the installation guides provided by the wiki page.
It would be good to know if we're okay with the fact that we send ip addresses to a third-party service and don't know if they collect them or not.
