### ISSUE TITLE
Weird HTML conversion

### ISSUE THREAD

**Issue by Chess13234** [glinscott/fishtest#511]
test description is partially converted to html
This is how it should be:
 BestMovesChanges_LTrootDepth15_16
bestMoveChanges total <rootDepth*15/16.
Bench:4489366
It appears that only " BestMovesChanges_LTrootDepth15_16
bestMoveChanges total " is retained and rest is invisible.
http://tests.stockfishchess.org/tests/view/5e22aa8b346e35ac603b7dba (see info)

**Comment by tomtor** [comment]
Fixed in #512

**Comment by tomtor** [comment]
@ppigazzini pserv restarted

**Comment by tomtor** [comment]
@ppigazzini The fix is for Python >= 3.2, so we are no longer Python 2 compatible, but that should be no issue.
