### ISSUE TITLE
Iterations do not increase

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#515]
https://tests.stockfishchess.org/tests/view/5e20bac0346e35ac603b7c75

**Comment by tomtor** [comment]
@xoto10 do you have a suggestion?

**Comment by xoto10** [comment]
Ah, I don't know. I saw it had been parked at -10 and just assumed someone
thought it was using too much resource or something.
I had noticed that the graph wouldn't display, but didn't have any idea why
that was.
Afk at the moment but will think about it and have a look later today.
(ah, just looked at the test, I see what you mean, I hadn't noticed the
really low iterations number! :-(  )

**Comment by Chess13234** [comment]
I've stopped tuning runs because of no progress(to not waste LTC time after 10k games it returned to start values), what kind of problems are there?
Could it be some bug that stops iterating when updating too variables at once? I only used one single parameter and it didn't stop updating iterations.

**Comment by xoto10** [comment]
Yes, that's what I've tried to change, see last commit in link above https://github.com/xoto10/stockfish-xoto10/commit/97f0e73e88b3d53643e89336d5ccd27b864b706d
Not convinced that's a real problem though - Let's see how my test tune goes ...
There have been some commits to fishtest around the spsa code about a week ago, but I think you've had this problem before then?

**Comment by Chess13234** [comment]
Added a fix for stockfish to use lowercase version.
https://github.com/official-stockfish/Stockfish/pull/2507
Reading the recent commits to fishtest, there was nothing touching SPSA handling recently.

**Comment by Chess13234** [comment]
@xoto10 I usually don't notice the number of iterations, they seem to be roughly 1/2 of games in most tests. 
Here is a test from Jan 6 which seems to be fine. 
https://tests.stockfishchess.org/tests/view/5e12e3f0aaa74b7dfee121b4

**Comment by Chess13234** [comment]
The tests seem to have tons of crashes, could this be the case for missing iterations?

**Comment by Chess13234** [comment]
Last successful test with lots of tuned variables was this(started 2020-01-09):
http://tests.stockfishchess.org/tests/view/5e16ac760ac9162cdd5f39f0

**Comment by tomtor** [comment]
@xoto10 Current https://tests.stockfishchess.org/tests/view/5e26f9a2c3b97aa0d75bc117 and recent  https://tests.stockfishchess.org/tests/view/5e25eccfc3b97aa0d75bc01f are also fine but your new test https://tests.stockfishchess.org/tests/view/5e2712c5c3b97aa0d75bc13b is crashing again...

So it is specific to your test

**Comment by tomtor** [comment]
Closing this because it is test specific

**Comment by xoto10** [comment]
Ah, a simple divide by zero problem?! My apologies!
