### ISSUE TITLE
Invisible machines

### ISSUE THREAD

**Issue by ghost** [glinscott/fishtest#518]
They only show up in machine list.
dew 	
3 	0.00 	Linux 3.4.2-hardened 	71:2 	TL_LE_BMC_LT13_2 	46 minutes ago
dew 	
3 	0.00 	Linux 3.18.7-gentoo 	71:3 	TL_LE_BMC_LT13_2 	47 minutes
http://tests.stockfishchess.org/tests/view/5e289a9ac3b97aa0d75bc29a (2 early batches seem corrupt, seem to be related)
Edit:both 2 batches seem to be replaced by ChessDBCN games now.
Davar 3 cores.
http://tests.stockfishchess.org/tests/view/5e2893d7c3b97aa0d75bc286 (batch 10 corrupt)
Edit: batch10 is now replaced by gvreuls games, but batch 18 is absent now.
Edit:Batch 18 was replaced by ChessDBCN games.

**Comment by Chess13234** [comment]
fkraiem 	
1 	0.00 	Linux 5.3.0-24-generic 	71:2 	TL_LE_BMC_LT13
Also doesn't show up in test page.

**Comment by Chess13234** [comment]
Machines of dew generally don't show up in test pages except when its 1core.

**Comment by Chess13234** [comment]
Manap 0.00 mnps also absent from its test page.
several ChessDBCN workers with 0.00 also seem to exhibit the same pattern.
davar seems to be joining and leaving random tests, but much slower than fkraiem, the machine seems absent most of time.

**Comment by Chess13234** [comment]
The common factor here being they all have 0.00 mnps, and version 71:2 is heavily overrepresented.

**Comment by Chess13234** [comment]
A recent test with 3 absent batchs and 
grandphish2 	
5 	0.00 	Windows 10 	71:2 	TL_LE_AlphaSelDepth1_4
http://tests.stockfishchess.org/tests/view/5e29245a4744cfa4d6af414f

Could version 71:2 be causing this?

**Comment by ppigazzini** [comment]
@Chess13234 IMO they have the old cutechess-cli not able to load the new *.epd book, so the worker is joining a test but it not able to use the book. This should be solved after implementing #488

The 71:2 workers are still using python2 and this should be fine at the moment, but in the next months we will enforce the switch to python3 also client side to simplify the testing work and to improve/clean the worker code.

I will keep on eye on this problem, thank you for the report :)

**Comment by ppigazzini** [comment]
With #1021 now a misconfigured worker is reported in the test page.
