### ISSUE TITLE
I think there is something wrong.

### ISSUE THREAD

**Issue by kotenok2000** [glinscott/fishtest#525]
Step 4/4. Deleting profile data ...
make ARCH=x86-64-modern COMP=mingw profileclean
make[1]: Entering directory `/c/Users/frolo/Desktop/Fishtest-Worker-Portable/fishtest/worker-CPU0/tmpfsscru/Rocky640-Stockfish-d6ab17e/src'
make[1]: Leaving directory `/c/Users/frolo/Desktop/Fishtest-Worker-Portable/fishtest/worker-CPU0/tmpfsscru/Rocky640-Stockfish-d6ab17e/src'
Downloading noob_3moves.epd.zip ...
Verifying signature of stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39.exe ...
Verifying signature of stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39.exe ...
CPU factor : 1.973160 - tc adjusted to 39.46+0.39
Running TuneEvalComponents vs TuneEvalComponents
Fetched SPSA parameters successfully in 0.241s
['C:\\Users\\frolo\\Desktop\\Fishtest-Worker-Portable\\fishtest\\worker-CPU0\\testing\\cutechess-cli.exe', '-repeat', '-rounds', '2', '-tournament', 'gauntlet', '-site', u'https://tests.stockfishchess.org/tests/view/5e2d25b2ab2d69d58394fb16', '-event', u'Batch 146: TuneEvalComponents vs TuneEvalComponents', '-srand', '1634984006', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '1', '-openings', u'file=noob_3moves.epd', u'format=epd', 'order=random', 'plies=16', '-engine', u'name=New-d6ab17e', u'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', u'option.Hash=128', u'option.nodestime=600', u'option.factors[0]=49', u'option.factors[1]=72', u'option.factors[2]=57', u'option.factors[3]=56', u'option.factors[4]=74', u'option.factors[5]=58', u'option.factors[6]=52', u'option.factors[7]=58', u'option.factors[8]=26', u'option.factors[9]=67', u'option.factors[10]=73', u'option.factors[11]=39', '-engine', u'name=Base-d6ab17e', u'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', u'option.Hash=128', u'option.nodestime=600', u'option.factors[0]=63', u'option.factors[1]=58', u'option.factors[2]=71', u'option.factors[3]=69', u'option.factors[4]=60', u'option.factors[5]=72', u'option.factors[6]=65', u'option.factors[7]=44', u'option.factors[8]=39', u'option.factors[9]=53', u'option.factors[10]=60', u'option.factors[11]=25', '-each', 'proto=uci', 'tc=39.46+0.39', 'timemargin=10000', 'option.Threads=1']
TC limit 789.264035951 End time: 2020-01-26 16:50:15.776036
Qt: Untested Windows version 6.2 detected!
Indexing opening suite...
2020-01-26 16:50:16.719000 is past end time 2020-01-26 16:50:15.776036
Успешно: Процесс, с идентификатором 4780, дочерний процесса 12680, был завершен.
Fetched SPSA parameters successfully in 0.25s
['C:\\Users\\frolo\\Desktop\\Fishtest-Worker-Portable\\fishtest\\worker-CPU0\\testing\\cutechess-cli.exe', '-repeat', '-rounds', '2', '-tournament', 'gauntlet', '-site', u'https://tests.stockfishchess.org/tests/view/5e2d25b2ab2d69d58394fb16', '-event', u'Batch 146: TuneEvalComponents vs TuneEvalComponents', '-srand', '1771150082', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '1', '-openings', u'file=noob_3moves.epd', u'format=epd', 'order=random', 'plies=16', '-engine', u'name=New-d6ab17e', u'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', u'option.Hash=128', u'option.nodestime=600', u'option.factors[0]=49', u'option.factors[1]=71', u'option.factors[2]=57', u'option.factors[3]=56', u'option.factors[4]=60', u'option.factors[5]=58', u'option.factors[6]=51', u'option.factors[7]=44', u'option.factors[8]=39', u'option.factors[9]=67', u'option.factors[10]=61', u'option.factors[11]=25', '-engine', u'name=Base-d6ab17e', u'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', u'option.Hash=128', u'option.nodestime=600', u'option.factors[0]=62', u'option.factors[1]=58', u'option.factors[2]=71', u'option.factors[3]=69', u'option.factors[4]=74', u'option.factors[5]=71', u'option.factors[6]=65', u'option.factors[7]=58', u'option.factors[8]=26', u'option.factors[9]=53', u'option.factors[10]=74', u'option.factors[11]=39', '-each', 'proto=uci', 'tc=39.46+0.39', 'timemargin=10000', 'option.Threads=1']
Qt: Untested Windows version 6.2 detected!
TC limit 789.264035951 End time: 2020-01-26 17:03:27.772036
Indexing opening suite...
2020-01-26 17:03:28.081000 is past end time 2020-01-26 17:03:27.772036
Успешно: Процесс, с идентификатором 624, дочерний процесса 12680, был завершен.
Fetched SPSA parameters successfully in 0.271s
['C:\\Users\\frolo\\Desktop\\Fishtest-Worker-Portable\\fishtest\\worker-CPU0\\testing\\cutechess-cli.exe', '-repeat', '-rounds', '2', '-tournament', 'gauntlet', '-site', u'https://tests.stockfishchess.org/tests/view/5e2d25b2ab2d69d58394fb16', '-event', u'Batch 146: TuneEvalComponents vs TuneEvalComponents', '-srand', '2714840346', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '1', '-openings', u'file=noob_3moves.epd', u'format=epd', 'order=random', 'plies=16', '-engine', u'name=New-d6ab17e', u'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', u'option.Hash=128', u'option.nodestime=600', u'option.factors[0]=48', u'option.factors[1]=57', u'option.factors[2]=58', u'option.factors[3]=56', u'option.factors[4]=60', u'option.factors[5]=58', u'option.factors[6]=52', u'option.factors[7]=44', u'option.factors[8]=26', u'option.factors[9]=53', u'option.factors[10]=61', u'option.factors[11]=39', '-engine', u'name=Base-d6ab17e', u'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', u'option.Hash=128', u'option.nodestime=600', u'option.factors[0]=62', u'option.factors[1]=71', u'option.factors[2]=71', u'option.factors[3]=70', u'option.factors[4]=73', u'option.factors[5]=72', u'option.factors[6]=65', u'option.factors[7]=57', u'option.factors[8]=39', u'option.factors[9]=66', u'option.factors[10]=75', u'option.factors[11]=25', '-each', 'proto=uci', 'tc=39.46+0.39', 'timemargin=10000', 'option.Threads=1']
TQt: Untested Windows version 6.2 detected!
C limit 789.264035951 End time: 2020-01-26 17:16:38.977036
Indexing opening suite...

**Comment by ppigazzini** [comment]
@kotenok2000 you are using an old version of `cutechess-cli.exe` not able to load the opening books in epd format.

Simply delete the folders:
```
C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker-CPU0\testing
C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker\testing
```

and fishtest will download the new `cutechess-cli.exe` from the repo.

**Comment by kotenok2000** [comment]
I updated https://github.com/glinscott/fishtest/wiki/A-portable-fishtest-worker-for-Windows-64-bit#step-by-step-instructions page
