### ISSUE TITLE
Stockfish compile

### ISSUE THREAD

**Issue by Rakicc** [glinscott/fishtest#542]
The official stockfish compiles exe files can be run in any 32bit and 64bit windows Pc (win7,win8,win10), but whenever I compile using mingw, msys2 mingw , as instructed by on github, the exe file can't able to run on other pc, it wil only run on my pc which has msys2 and its lib. I don't know what is the problem and what are the difference between your compile and my compile.

**Comment by vondele** [comment]
no need to repeat the comment you made in the SF repository here...
