### ISSUE TITLE
I get stuck on worker  update.

### ISSUE THREAD

**Issue by kotenok2000** [glinscott/fishtest#544]
`Worker started in C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker-CPU0 ...

Memory: 8571244544
Worker version 71 connecting to https://tests.stockfishchess.org:443
Fetch task...
Updating worker version to 72
start_dir: C:\Users\frolo\Desktop\Fishtest-Worker-Portable
Worker started in C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker-CPU0 ...

Memory: 8571244544
Worker version 71 connecting to https://tests.stockfishchess.org:443
Fetch task...
Updating worker version to 72
start_dir: C:\Users\frolo\Desktop\Fishtest-Worker-Portable
Worker started in C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker-CPU0 ...

Memory: 8571244544
Worker version 71 connecting to https://tests.stockfishchess.org:443
Fetch task...
Updating worker version to 72
start_dir: C:\Users\frolo\Desktop\Fishtest-Worker-Portable
Worker started in C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker-CPU0 ...

Memory: 8571244544
Worker version 71 connecting to https://tests.stockfishchess.org:443
Fetch task...
Updating worker version to 72
start_dir: C:\Users\frolo\Desktop\Fishtest-Worker-Portable
Worker started in C:\Users\frolo\Desktop\Fishtest-Worker-Portable\fishtest\worker-CPU0 ...

Memory: 8571244544
Worker version 71 connecting to https://tests.stockfishchess.org:443
Fetch task...
Updating worker version to 72
`

**Comment by ppigazzini** [comment]
The update code works only if the folder is named "worker".
Simply rename "worker-CPU0" to "worker" and delete the "worker\testing" folder.
After the update you can rename the folder to "worker-CPU0".
Version 72 fix this bug and has other improvements.
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/V5j8UL5lSH4

**Comment by protonspring** [comment]
Can this be closed?  I can help a bit here, but I cant' tell which issues actually need attention.
