### ISSUE TITLE
Fishtest on cygwin uses the wrong cutechess-cli

### ISSUE THREAD

**Issue by protonspring** [glinscott/fishtest#546]
I setup fishtest on my cygwin machine.  When I run the worker it fails with an "OSError: exec format" something.

The worker script made a testing directory, but the cutechess-cli is a linux binary.  This will not work with cygwin.  I fixed mine by removing the linux binary and symlinking to the windows cutechess-cli.

The worker script should probably check if we're in cygwin or not and copy over the correct cutechess-cli binary executable.

**Comment by ppigazzini** [comment]
For windows we suggest or Windows Subsystem for Linux or msys2 or the Portable worker (we test any fishtest PR with the suggested workers)
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows

Check #126 for some hints to write a PR to fully support cygwin.

**Comment by protonspring** [comment]
Got it.  Thx.
