### ISSUE TITLE
Machines with more threads than memory are unable to get certain tasks

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#550]
I recently introduced 50 new machines which have 16C/4G, but they seem unable to get any LTC task.
It is probably due to the increased hash size in LTC tasks exceeding available RAM but I wonder if the worker code can be adjusted to run tasks with reduced threads other than sitting idle.

**Comment by vondele** [comment]
first, thanks for adding more resources!

Somewhat strange that we can't run at LTC @ 16C/4G.. I would expect 16 cores to run the LTC tests with ~64Mb * 16 * 2 = ~2048Mb. That should fit in principle. Do explicitly specify the memory, and if so what value do you use? I wonder if there is a 32bit int somewhere overflowing?

**Comment by vondele** [comment]
actually, if you do not specify --max-memory, it seems the worker code uses 1/2 of the available memory (as somehow parsed from `free -b`), so that could be a problem. Can you check launching the worker with --max-memory close to 4Gb?

**Comment by noobpwnftw** [comment]
It defaults to 1893 as I see from its config, is it safe to raise it above 1/2 of RAM size?

**Comment by ppigazzini** [comment]
My worker runs LTC @15C/4G, this my config

```
[parameters]
host = tests.stockfishchess.org
port = 443
concurrency = 15
max_memory = 1969
min_threads = 1
protocol = https
```

**Comment by vondele** [comment]
I think it is safe.. I think this was just done to keep some RAM free to have users use their PC while the worker was running. The memory usage calculation is a bit naive, it just looks for the hash, so the actual use will be a bit larger. Yet, I think you can safely use e.g 3Gb.

**Comment by noobpwnftw** [comment]
Changed to 3072.

**Comment by vondele** [comment]
OK, thanks.. should work. Locally a running LTC SF seems to need ~90Mb, so 2*16 (~2.8Gb) of those should fit.

**Comment by noobpwnftw** [comment]
It seems to be working now. Thanks.
