### ISSUE TITLE
Mistake in logic: bmi version will never be done.

### ISSUE THREAD

**Issue by pachnes** [glinscott/fishtest#551]
(EDIT_000: fence block code and syntax highlight)

```bash
arch_cpu=x86-64
# CPU with popcnt instruction (e.g. Intel Sandy Bridge)
if [ "$(g++ -Q -march=native --help=target | grep mpopcnt | grep enabled)" ] ; then
  arch_cpu=x86-64-modern
# CPU with bmi2 instruction (e.g. Intel Haswell or newer)
elif [ "$(g++ -Q -march=native --help=target | grep mbmi2 | grep enabled)" ] ; then
  arch_cpu=x86-64-bmi2
fi
```
must be:

```bash
arch_cpu=x86-64
# CPU with bmi2 instruction (e.g. Intel Haswell or newer)
if [ "$(g++ -Q -march=native --help=target | grep mbmi2 | grep enabled)" ] ; then
  arch_cpu=x86-64-bmi2
# CPU with popcnt instruction (e.g. Intel Sandy Bridge)
elif [ "$(g++ -Q -march=native --help=target | grep mpopcnt | grep enabled)" ] ; then
  arch_cpu=x86-64-modern
fi
```

**Comment by pachnes** [comment]
This is, why a bmi cpu can also popcnt. So it will never go to the elif command.

**Comment by ppigazzini** [comment]
You are right, thank you.
I'm fixing the wiki.

**Comment by pachnes** [comment]
or you keep ,it and make the elif statement a if statement. :)

**Comment by vondele** [comment]
not that enabling bmi2 by default as soon as the instruction is available, is not a good idea for AMD CPUs unfortunately. Probably one can diagnose this. I my case `g++ -Q -march=native --help=target` lists valid arguments for for '-march=...' and this includes znver1 znver2 (but that seems a feature of new gcc... 8.3 doesn't list this, while gcc 9.2 lists this).

**Comment by ppigazzini** [comment]
@vondele I don't have access to AMD CPUs to write/test an improved script. On Windows msys2 provides gcc 9.3, but Ubuntu 18.04 from Windows Subsystem for Linux provides gcc 7.5.0

**Comment by vondele** [comment]
This would work for the system with the modern gcc:
```bash
if [ "$(g++ -Q -march=native --help=target | grep mbmi2 | grep enabled)" ] ; then
  if [ "$(g++ -Q -march=native --help=target | grep znver[12])" ] ; then # gcc >= 9.1
     arch_cpu=x86-64-modern
  else
     arch_cpu=x86-64-bmi2
  fi
elif [ "$(g++ -Q -march=native --help=target | grep mpopcnt | grep enabled)" ] ; then
  arch_cpu=x86-64-modern
fi
```
it would default to bmi2 if the instruction is support, but switch to modern if a zen1/2 is detected. What I'm not sure, and can't test right now, is if a -march=zenv1 would be a valid arch flag on modern intel cpu as well. That would be bad, as it would switch to modern....

**Comment by vondele** [comment]
this should work regardless (as it relies of the output of gcc when compiling, i.e. really what the native architecture is):
```bash
if [ "$(g++ -Q -march=native --help=target | grep mbmi2 | grep enabled)" ] ; then
  if [ "$(g++ -march=native  - -E -v < /dev/null 2>&1 | grep 'march=znver[12]')" ] ; then
     arch_cpu=x86-64-modern
  else
     arch_cpu=x86-64-bmi2
  fi
elif [ "$(g++ -Q -march=native --help=target | grep mpopcnt | grep enabled)" ] ; then
  arch_cpu=x86-64-modern
fi
```

**Comment by ppigazzini** [comment]
@vondele gcc 7.5 hasn't `-march=znerv2` but has `-march=znerv1`

```
$ g++ -Q -march=znver2 --help=target | grep march
cc1: error: bad value (‘znver2’) for ‘-march=’ switch
cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 bonnell atom silvermont slm knl x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2; did you mean ‘znver1’?
  -march=                               znver2
```
So if I'm not wrong this code should be equivalent at your last proposition:
```
if [ "$(g++ -Q -march=native --help=target | grep mbmi2 | grep enabled)" ] ; then
  if [ "$(g++ -Q -march=native --help=target | grep znver[12] | grep enabled)" ] ;
     arch_cpu=x86-64-modern
  else
     arch_cpu=x86-64-bmi2
  fi
elif [ "$(g++ -Q -march=native --help=target | grep mpopcnt | grep enabled)" ] ; then
  arch_cpu=x86-64-modern
fi
```

By the way both code will work fine with gcc < 9.x only if a latest AMD CPU is recognized as `znver1`

**Comment by vondele** [comment]
@ppigazzini gcc < 9 will ouput -march=znver1 if the actual cpu is znver2, so are detected correctly with the latest snippet I posted. 

I don't think your snippet works. It needs to match '-march=                     		znver1' without the enabled, and it would be better if it doesn't match 'i386 i486 i586 pentium lakemont pentium-mmx winchip-c6 winchip2 c3 samuel-2 c3-2 nehemiah c7 esther i686 pentiumpro pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel geode k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native' or similar. (i.e. znver1 or znver2 must be selected as the actual -march=..... not be in the list of valid arguments for -march=...)

**Comment by ppigazzini** [comment]
@vondele if `g++ -march=native  - -E -v < /dev/null` uses `-march=znver1` I'm expecting `march=znver1  enabled` from `g++ -Q -march=native --help=target`

**Comment by vondele** [comment]
yes, except that the line is without 'enabled'. That's the relevant gcc-7 output:
``` 
 -march=                     		znver1
```
and that gcc-9
```
  -march=                     		znver2
```

**Comment by vondele** [comment]
The architecture appears 4 time in the output:
```
$ g++ -Q -march=native --help=target | grep znver2
  -march=                     		znver2
  -mtune=                     		znver2
    i386 i486 i586 pentium lakemont pentium-mmx winchip-c6 winchip2 c3 samuel-2 c3-2 nehemiah c7 esther i686 pentiumpro pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel geode k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    generic i386 i486 pentium lakemont pentiumpro pentium4 nocona core2 nehalem sandybridge haswell bonnell silvermont goldmont goldmont-plus tremont knl knm skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake intel geode k6 athlon k8 amdfam10 bdver1 bdver2 bdver3 bdver4 btver1 btver2 znver1 znver2
```
and we need to be sure to grep the right one (the fist line)

**Comment by ppigazzini** [comment]
Ok, then this should work fine
`g++ -Q -march=native --help=target | grep march | grep 'znver[12]'`

**Comment by vondele** [comment]
yep

**Comment by ppigazzini** [comment]
wiki pages updated
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Linux
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows
https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows

Thnak you @pachnes @vondele :)

**Comment by pachnes** [comment]
there is a "fi" missing in line 31 :)
