### ISSUE TITLE
Stats shallow copy in games.py

### ISSUE THREAD

**Issue by shooreek** [glinscott/fishtest#552]
We save stats to `old_stats` variable like this:

https://github.com/glinscott/fishtest/blob/0c076f225bd6f0e15f2d0ddd2de80e1dd5e206f4/worker/games.py#L570

`stats` defined like this:

https://github.com/glinscott/fishtest/blob/0c076f225bd6f0e15f2d0ddd2de80e1dd5e206f4/worker/games.py#L413

`result['stats']` won't be fully copied using `copy()` method because it does a shallow copy, list under `pentanomial` key will be just referenced. If the intention was to create a full/deep copy, then another copying methods should be used.

I'm not so familiar with the code and cannot tell if this really causes some problems, probably it is harmless due to the slicing:

https://github.com/glinscott/fishtest/blob/0c076f225bd6f0e15f2d0ddd2de80e1dd5e206f4/worker/games.py#L257

**Comment by linrock** [comment]
The shallow copy here doesn't look like it'll be an issue since `old_stats['pentanomial']` is only ever overwritten or read and its individual list elements are never modified.

**Comment by vdbergh** [comment]
Likewise the individual entries of result[‘pentanomial’] are never changed so that old_stats[‘pentanomial’] will not change inadvertently. Still, this code seems very fragile and deepcopy instead of copy would be more robust.

**Comment by vdbergh** [comment]
Using a global variable old_stats seems rather dangerous anyway. It would be nice to eliminate it altogether.

**Comment by vdbergh** [comment]
I am now slowly cleaning up the worker code. I have eliminated the ugly, dangerous and confusingly named global old_stats variable.

The code states that old_stats is global "because it is shared across all threads". But AFAICS the worker is not multi-threaded. All concurrency is handled by cutechess-cli. So I suspect the old_stats variable was a left over from times when the worker handled concurrency itself. @tomtor ?

**Comment by tomtor** [comment]
> So I suspect the old_stats variable was a left over from times when the worker handled concurrency itself.

I do not think that the worker has ever been multithreaded, but I and @ppigazzini did not work on it in the early fishtest years...

**Comment by vondele** [comment]
The comment was added long ago in 517559f0 and at that point there was threading in the worker it seems:
```
  th = []
  for idx in range(threads):
    th.append(threading.Thread(target=launch_cutechess, args=payload))
    th[idx].start()
```
this seem gone

**Comment by vdbergh** [comment]
@vondele Ah. There was an attempt once at implementing clop tuning but I recall it was unsuccessful.

**Comment by tomtor** [comment]
@vondele I just located the same commit https://github.com/glinscott/fishtest/commit/517559f05e1bfb217791f7371f2b8ed1c58d4bb2 

There has been an effort to add CLOP tuning as an alternative to SPSA. It might be that threading in the worker was part of that implementation effort. CLOP tuning code was never successfully implemented and removed at some moment.

**Comment by ppigazzini** [comment]
> I am now slowly cleaning up the worker code. I have eliminated the ugly, dangerous and confusingly named global old_stats variable.

Take a look at the nice clean up work by @AndyGrant

https://github.com/AndyGrant/OpenBench/blob/master/Client/Client.py

**Comment by vdbergh** [comment]
@ppigazzini  Starting from scratch is always tempting. However one should also keep this in mind

https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/

**Comment by ppigazzini** [comment]
> @ppigazzini Starting from scratch is always tempting.

@vdbergh If you have tempting thoughts to start from scratch, please cease and desist :)

**Comment by vdbergh** [comment]
This can be closed now I think.
