### ISSUE TITLE
Games per minute is calculated, not counted

### ISSUE THREAD

**Issue by xoto10** [glinscott/fishtest#554]
The main fishtest page displays a figure for number of games per minute, but it is calculated from the number of workers that fishtest thinks are connected.When fishtest is under heavy load, workers can disconnect and reconnect, and the worker "count" goes up. This then gives a false impression of how well the server is performing.

We should implement a count of how many games are actually stored in the database, and display that instead. If we then see that number falling, despite an apparently large number of workers, it would be a clear indication that perhaps fishtest is under too much load

**Comment by xoto10** [comment]
One way might be something like this [patch](https://github.com/glinscott/fishtest/compare/master...xoto10:gamesmin1).
My local fishtest appeared to be working earlier but is now broken, so either this patch needs work or I've done some other thing to break it, probably both! :(

**Comment by tomtor** [comment]
@xoto10 I agree, a real counted games/minute would be nice. 

Your patch looks also good and introduces a generic key/value store which could be handy also in other contexts, so why don't you create a PR with it so we can test/evaluate it?
