### ISSUE TITLE
# finished tests on Greens page is wrong

### ISSUE THREAD

**Issue by linrock** [glinscott/fishtest#569]
If you go to the `Greens` page, it shows a large number of finished tests. Over 73,000
https://tests.stockfishchess.org/tests?success_only=1

If you go to the last page, it takes forever to load, then shows there are only about 5,900
https://tests.stockfishchess.org/tests?page=1461&success_only=1

**Comment by ppigazzini** [comment]
If I recall correctly the delay for old run is by design, runs older than 100 days are moved in old_runs collection
https://github.com/glinscott/fishtest/pull/434

**Comment by tomtor** [comment]
See #563
