### ISSUE TITLE
main page hide/show pending

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#579]
@linrock one of the recent changes to the main page (couldn't find it back which one exactly), stored the state of the hide/show button for the pending tests. I recall it is supposed to store the state in a cookie, but in my browser (where I use an tab with an autoreload extension), it sometimes flips from one state to the other, hiding/showing these tests upon reload. I haven't been able to figure out a pattern, why/when this happens, it seems more or less random.

**Comment by tomtor** [comment]
@linrock @vondele This is caused by the caching of the main page.

People receive the main page of an earlier visitor. The page previously didn't have this behaviour without the cookie introduced by #571

**Comment by ppigazzini** [comment]
@vondele I got the random behavior on Chrome, Edge it's fine for me.. #581 solve the bug with Chrome for me (and Edge works always fine). Please try with your browser on DEV.

**Comment by vondele** [comment]
yes, dev seems to work fine in quick testing..
