### ISSUE TITLE
Error starting working

### ISSUE THREAD

**Issue by noobgame** [glinscott/fishtest#582]
Error, Unverified version of Windows 6.2 detected! Indexing start suite. on windows 10 pro
![Screenshot_278](https://user-images.githubusercontent.com/63532306/79064581-c76c2e00-7cb2-11ea-9bb4-f6c78d49f3f6.png)

**Comment by ppigazzini** [comment]
@noobgame delete the "testing" and restart fishtest. In your screenshot the path is truncated at "CPU", should be something like this: 
`C:\Users\Admin\Desktop\FISHTEST\Fishtest-Worker-Portable\fishtest\worker-CPU\testing`

**Comment by noobgame** [comment]
No same. i think Qtcore4.dll unsuported my Windows 10

**Comment by ppigazzini** [comment]
@noobgame ok, `ONE_CLICK_RUN.bat` uses `robocopy /mir`, simply delete this folder `C:\Users\Admin\Desktop\FISHTEST\Fishtest-Worker-Portable\fishtest\worker\testing`

**Comment by ppigazzini** [comment]
wiki instruction updated with the mandatory step to delete the `testing` folder by hand, see
https://github.com/glinscott/fishtest/wiki/A-portable-fishtest-worker-for-Windows-64-bit#setting-up-the-very-first-time-using-the-profiler
