### ISSUE TITLE
Sorting on machine headers fails when lazy-loaded

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#585]
@linrock #584 has a minor issue. When machines are hidden, pressing Show shows them, but you cannot sort on the headers. After a page reload all is fine.

**Comment by vondele** [comment]
and maybe the column on which is being sorted should be added to a cookie or so, since if one shows, and sorts, and afterwards reloads, the sorted column is forgotten.

**Comment by ppigazzini** [comment]
Funny, I discovered only now the possibility to sort on the headers :)

**Comment by ppigazzini** [comment]
@vondele the sorted column is forgotten for these pages:
 - "Home"
 - "Users"
 - "Top Month"
 - "Actions"

**Comment by tomtor** [comment]
> and maybe the column on which is being sorted should be added to a cookie or so, since if one shows, and sorts, and afterwards reloads, the sorted column is forgotten.

I generally only use sort to find a specific user worker(s) and reload to restore default ordering for tables (@vondele when sorting is remembered we also need a restore to default feature?). Perhaps it should sort on worker names by default on the main page? On individual test pages I also use sort for this, but on those pages the default order is probably the best.

Showing the machines for the logged-in user shown in a separate table (above the current machines table) on the main page would be nice.

**Comment by vondele** [comment]
maybe it is not so important on recall the sort order (I just need to switch off the autoreload feature for the main page if I like to look at the machines in sorted order, which I essentially never do).

**Comment by tomtor** [comment]
> Funny, I discovered only now the possibility to sort on the headers :)
 
@ppigazzini  #295 was merged by you ;-)

**Comment by ppigazzini** [comment]
> > Funny, I discovered only now the possibility to sort on the headers :)
> 
> @ppigazzini #295 was merged by you ;-)

@tomtor yes, and that conversation is the proof that I didn't understood what that PR did: I didn't test anything and I simply asked to you if the PR was ready to be merged :)

**Comment by linrock** [comment]
ah i'll fix this.. i forgot the machines table was sortable
