### ISSUE TITLE
quick test cherry pick

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#590]
This is a feature suggestion, not urgent and I'm not sure this is even the best way to do that. If a dev wants to base it work on the work of another dev, getting the changes in the local git repo is some copy and paste work. E.g. to cherry-pick the code on this page:

https://tests.stockfishchess.org/tests/view/5e901abb4ff721d0bce30eca

I would presumably do 
```
git fetch https://github.com/Vizvezdenec/Stockfish.git ttcaptUpdate4 && git cherry-pick 195a4fec6d6bd1f9e43f5b3e83a3dcf57dc73744..79f5132d665f1a82b78a80340cb5da60d05ed6c8
```
that command can be assembled from the information present on the test page, but takes multiple copy and pastes and some edits. Would be nice if the command would be displayed on the test page, possibly hidden under a  'copy to clipboard' button.

**Comment by linrock** [comment]
Would you prefer to cherry-pick the commits or apply the diff?

For example with:
https://tests.stockfishchess.org/tests/view/5e95bf25c2aaa99f75d1a154

Running this in a Stockfish repo applies the diff without making any commits:
`curl https://github.com/pb00068/Stockfish/compare/5c58f67...5431821.diff | git apply`

---
We could put a button by the diff section that lets you copy the command when the diff is visible:

![image](https://user-images.githubusercontent.com/208617/79258075-975e8f80-7e58-11ea-8cdd-8f8c93870d39.png)

**Comment by vondele** [comment]
I think, I would probably prefer to apply the diff... 
location of the button is good.
@linrock thanks again for your amazing work!

**Comment by vondele** [comment]
@linrock clicking the button leads to an error message (using firefox):

![image](https://user-images.githubusercontent.com/4202567/79313771-232bf680-7f01-11ea-8350-9a37cf915d33.png)

the content is copied to the clipboard, and the green message appears (which I can verify by going back in the browser history).

**Comment by ppigazzini** [comment]
javascipt?!?

**Comment by vondele** [comment]
that's the window that pops up... that's also what I see when I hover over the button with the mouse (which usually shows the url of the link).

**Comment by vondele** [comment]
ah! careful reading! I didn't even read it correctly when you typed it @ppigazzini
