### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by jhellis3** [glinscott/fishtest#599]
First, just want to thank everyone who works to keep fishtest improving; the progress has been truly remarkable.  

Second, if it is not too much trouble, I was wondering if someone could do a night/dark theme to help save our eyes after hours.  I could probably try to do something, but it really isn't my area of expertise.  It would probably take me a while, and the end result would likely be worse than someone who knows what they are doing.

**Comment by SFisGOD** [comment]
@linrock Thank you so much for your work in improving fishtest. If you have the time, we would be really grateful if you could implement something like in openbench. They have a nice dark theme there http://chess.grantnet.us/

**Comment by linrock** [comment]
i'll work on a night mode theme today and aim to get a PR ready for review by the end of the day!
