### ISSUE TITLE
Add checks to see if all required  libs are installed.

### ISSUE THREAD

**Issue by kjellkvinge** [glinscott/fishtest#60]
I started running the fishtest on a fresh installed virtual machine, running debian 8.0

I noticed that under testing, i got:

```
fishtest-master/worker/testing/cutechess-cli: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory
Task exited
```

After installing libqt4-core it seems to run fine.

I guess this should be handled somehow.

**Comment by kjellkvinge** [comment]
looks like i did not read the docs properly. This is not an issue if the steps in documentation is followed, but it is strange that the worker continues to work  when errors like this occur.

**Comment by Stefano80** [comment]
Not an issue, so closing.
