### ISSUE TITLE
Two pending tests not finishing

### ISSUE THREAD

**Issue by adentong** [glinscott/fishtest#602]
There are two pending tests right now that are not being run and it says 0 cores. What's going on?

**Comment by adentong** [comment]
Oh some cores came back. Not sure what happened there...

**Comment by noobpwnftw** [comment]
Too many workers, they timeout on updating.

**Comment by vondele** [comment]
@ppigazzini maybe this should be re-open. Right now 2 numgames tests:
https://tests.stockfishchess.org/tests/view/5e9692c6c2718dee3c82296f
https://tests.stockfishchess.org/tests/view/5e98b9e130be947a14e9db1b
remain in the pending state, however, clicking on the test page, it claims to have workers assigned, yet the number of played games do not increase, nor do they move to the active state. I think we have seen this mis-counting before. It could be related to having a timeout on updating.

**Comment by vondele** [comment]
@tomtor do you have an idea? 

I'll now stop the tests and try to modify them... see if this gets them started.

**Comment by vondele** [comment]
stop & modify did get them started properly, transferring to active, and games increasing.

**Comment by xoto10** [comment]
My understanding is that this happens when the workers have gone away for some reason, e.g. user reboots the PC, but fishtest takes quite a long while to time them out and then allocate new workers.
I was going to contact someone to suggest they restart their test a week or two ago when we had some issues, the test supposedly had 600+ workers but wasn't progressing. What happened was that the test fixed itself while I was still writing a message in github - it's possible someone else fixed it like Vondele did here, I don't remember checking for that, but my assumption at the time was that fishtest fixed itself, it just took a while for the timeouts to happen.

**Comment by tomtor** [comment]
Cron runs every 5 minutes after the whole hour the `scavenge.py` job which cleans up  worker slots which are idle for > 60 minutes. So worst case time for cleanup is 115 minutes.

Were the slots older than 115 minutes?

**Comment by vondele** [comment]
The OP didn't mention which jobs he saw, but if those were the same it was >5h. Between my first post and my 'stop & modify' post there are about ~2h. I think those jobs were in that state for >2h, but I'm not 100% sure. Some what more accurately : I stopped the job '20-04-17 07:14:25' so, almost certainly, the scavenge at 07:05 should have cleaned those.

**Comment by ppigazzini** [comment]
> So worst case time for cleanup is Edit: 120 minutes.

(disclaimer: I dont' know `scavenge.py` code) I would think 64, why 120?

**Comment by vondele** [comment]
start idling at 5:06, not cleaned at 6:05, cleaned at 7:05 -> 119 min ;-)

**Comment by ppigazzini** [comment]
```
# Remove clients that are not updating any more
*/5 * * * * ${VENV}/bin/python ${UPATH}/scavenge.py
```

`scavenge.py` run at every 5th minute... so start idling at 5:06, not cleaned at 6:05, cleaned at 6:10 -> 64 minutes.
I don't know how works `scavenge.py`, though.

**Comment by adentong** [comment]
The pending jobs were an ltc tune for time management and the regression test

**Comment by vondele** [comment]
@ppigazzini ah, but that's a different statement from what @tomtor made (5 past the hour, or every 5minutes). First time I see `*/5` so I checked the wiki, this is a non-posix extension.... does it work with our cron (or could the the line be ignored) ?

Thanks @adentong , those are the same jobs I saw and rescheduled, so they were pending for multiple hours.

**Comment by vondele** [comment]
actually, could scavenging every 5 minutes be a problem if the TC of a game is such that a game is >5min ? or even more so if we start batching ?

**Comment by ppigazzini** [comment]
@vondele yes it's work fine on PROD, see below the mails received after any job.
```
q:Quit  d:Del  u:Undel  s:Save  m:Mail  r:Reply  g:Group  ?:Help
 492 O + Apr 11 Cron Daemon     (4980) Cron <fishtest@tests> /usr/bin/cpulimit -l 50 -f -m -- sh ${UPATH}/backup.sh
 493 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 494 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 495 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 496 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 497 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 498 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 499 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 500 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 501 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 502 O + Apr 11 Cron Daemon     (5001) Cron <fishtest@tests> /usr/bin/cpulimit -l 50 -f -m -- sh ${UPATH}/backup.sh
 503 O + Apr 11 Cron Daemon     (   2) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 504 O + Apr 11 Cron Daemon     (   2) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 505 O + Apr 11 Cron Daemon     (   2) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 506 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 507 O + Apr 11 Cron Daemon     (   2) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 508 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 509 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 510 O + Apr 11 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 511 O + Apr 11 Cron Daemon     (   2) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 512 O + Apr 11 Cron Daemon     (   2) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 513 O + Apr 12 Cron Daemon     (   3) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 514 O + Apr 12 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 515 O + Apr 12 Cron Daemon     (   3) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/scavenge.py
 516 O + Apr 12 Cron Daemon     (   1) Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py
 517 O + Apr 12 Cron Daemon     (5016) Cron <fishtest@tests> /usr/bin/cpulimit -l 50 -f -m -- sh ${UPATH}/backup.sh
```

**Comment by tomtor** [comment]
Ah, missed that. So every 5 minutes the job is run. A server restart might have caused this, we had several recently and the code may not be robust in that situation.

**Comment by ppigazzini** [comment]
I stop cron when a PR requires a DB update, this PR https://github.com/glinscott/fishtest/pull/574#issuecomment-614247335 took nearly 2 hours to complete.
