### ISSUE TITLE
statistics on CPU hours ?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#605]
seems not to be updated anymore according to:
https://groups.google.com/d/msg/fishcooking/pGFcmUsNmAk/vIyTDRuiAAAJ

**Comment by ppigazzini** [comment]
Something is wrong, I loaded yesterday a fresh DB on DEV, and "user01" (used in my tests) should have the same information
- page "Users"

| Username | Last active | Games/Hour | CPU Hours | Games played | Tests submitted | Tests repository |
| - | - | - | - | - | - | - |
| user01 | 13 minutes ago | 30493 | 9 | 3292 | 2 | https://github.com/official-stockfish/Stockfish |

- page "Top Month"

| Username | Last active | Games/Hour | CPU Hours | Games played | Tests submitted | Tests repository |
| - | - | - | - | - | - | - |
| user01 | seconds ago | 30493 | 105 | 115970 | 14 | https://github.com/official-stockfish/Stockfish |

**Comment by tomtor** [comment]
@ppigazzini The MongoDb databases were processed on prod to patch fields. Could you try fully rebuilding the stats on prod?

**Comment by ppigazzini** [comment]
@tomtor I hope to have understood correctly, I ran `${VENV}/bin/python fishtest/fishtest/utils/delta_update_users.py all` on PROD and DEV.
On DEV pages "Users" and "Top Month" are still very different.

**Comment by ppigazzini** [comment]
@tomtor could be that "Users" is updated only after that a test is finished and "Top Month" is updated in real time?

**Comment by tomtor** [comment]
> could be that "Users" is updated only after that a test is finished and "Top Month" is updated in real time?
> By the way this doesn't explain the different numbers of tests submitted.

Yes, users is only updated when tests are finished and monthly on every update cron job. 

Monthly tests submitted is tests submitted last month. That is 0 for me and correct. Everything looks fine to me? I have not checked if numbers increase yet, but according to https://groups.google.com/d/msg/fishcooking/pGFcmUsNmAk/vIyTDRuiAAAJ they do?

**Comment by JojoM-sf** [comment]
Following Pasquale‘s measures, the numbers got updated picking up on the recent „delay“, but now they appear to be stuck again.

**Comment by tomtor** [comment]
@JojoM-sf I just checked, they incremented for me (tvijlbrief) compared to about 2 hours ago....

**Comment by JojoM-sf** [comment]
No, the value is constant: 312471

**Comment by tomtor** [comment]
@JojoM-sf But I do not see any active workers from you now?

Note that a few months ago the update implementation DID change. Only when a test is completely finished the user totals are now adjusted, but with the current number of workers that should not take very long.  The monthly figures should adapt every 15 minutes.

**Comment by JojoM-sf** [comment]
Excuse me, my bad. Logged all my workers back on. Let‘s observe the process over the coming hours.

However, my original observation (that the stats wouldn’t budge) was made over the last 2-3 days (when my workers were active).

**Comment by tomtor** [comment]
@JojoM-sf  at 9:02 UTC it should be updated from the old 312471 value

**Comment by tomtor** [comment]
@JojoM-sf  It did not move, but my totals did also not move. Might be rounding, I'll keep an eye on it.

**Comment by tomtor** [comment]
@JojoM-sf  Did you also make a note of games-played?

**Comment by ppigazzini** [comment]
@tomtor if you totals don't increase we could copy by hand the previous version of `delta_update_users.py` to be sure that #595 didn't break something.

**Comment by JojoM-sf** [comment]
As for #(games_played), I am not 100% certain, but it seems to be an equivalent behavior. I suspect there must be some sort of update „jam“ – cause after Pasquale‘s fix, figures made a leap of several hundred hours.

**Comment by tomtor** [comment]
@ppigazzini Not related but we have a MongoDb load of 300% now and 0 workers running!?

**Comment by ppigazzini** [comment]
@tomtor also both python processes are loaded, someone downloading pgns?

```
top - 12:21:49 up 13 days, 19:48,  2 users,  load average: 15.24, 12.61, 11.11
Tasks:  34 total,   3 running,  31 sleeping,   0 stopped,   0 zombie
%Cpu0  :  97.7/1.3    99[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ]
%Cpu1  :  95.7/1.3    97[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||   ]
%Cpu2  :  98.7/1.0   100[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||]
%Cpu3  :  94.0/2.0    96[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||    ]
KiB Mem : 58.4/5242880  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                          ]
KiB Swap:  0.0/0        [                                                                                                    ]

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20      224908   2592   1268 S        0.0   0:08.20 init -z
    2 root      20                           S                       `- [kthreadd/1988]
    3 root      20                           S                           `- [khelper]
   65 root      20      225564  43380  35192 S   1.7  0.8  10:41.96  `- /lib/systemd/systemd-journald
  167 root      20       42092    320    268 S        0.0   0:01.02  `- /lib/systemd/systemd-udevd
  170 systemd+  20       71848    316    252 S        0.0   0:01.22  `- /lib/systemd/systemd-networkd
  295 root      20       62100    900    728 S        0.0   0:01.64  `- /lib/systemd/systemd-logind
  296 message+  20       47724    740    408 S        0.0   0:00.64  `- /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  300 syslog    20      189016   1516    284 S   0.7  0.0   3:28.26  `- /usr/sbin/rsyslogd -n
  301 root      20      184296    308    272 S        0.0   0:00.11  `- /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
  305 mongodb   20     3448480 1.777g   5380 S 339.2 35.5   1627:47  `- /usr/bin/mongod --config /etc/mongod.conf
  314 root      20       72288    496    384 S        0.0   0:00.12  `- /usr/sbin/sshd -D
13714 root      20       97180    556    404 S        0.0                `- sshd: fishtest [priv]
13729 fishtest  20       97180    596    344 S        0.0   0:00.76          `- sshd: fishtest@pts/0
13730 fishtest  20       20480   1356    936 S        0.0   0:00.14              `- -bash
 1846 fishtest  20       54140   6648   3384 S        0.1   0:00.46                  `- vi fishtest/rundb.py
14474 root      20       97180   1476    532 S        0.0   0:00.05      `- sshd: fishtest [priv]
14517 fishtest  20       97180   1324    368 S        0.0   0:00.31          `- sshd: fishtest@pts/1
14519 fishtest  20       19660   2288    692 S        0.0   0:00.07              `- -bash
 1849 fishtest  20       36752   1988   1380 R        0.0   0:00.05                  `- top
  581 root      20       24176    280    276 S        0.0            `- /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive -inetd_compat -inetd_ipv6
  594 Debian-+  20       59184    488    376 S        0.0   0:01.20  `- /usr/sbin/exim4 -bd -q30m
  597 root      20      100972    260    232 S        0.0            `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  598 root      20      100972     28        S        0.0                `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  619 root      20      142520   2516   1044 S        0.0   0:00.03  `- nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
31264 www-data  20      147932   8984   2412 R   7.6  0.2 136:44.42      `- nginx: worker process
31265 www-data  20      143788   4596   2340 S   0.3  0.1   5:03.80      `- nginx: worker process
31266 www-data  20      143320   4080   2008 S        0.1   0:02.10      `- nginx: worker process
31267 www-data  20      142864   3680   1884 S        0.1   0:00.10      `- nginx: worker process
16839 root      20       28344    732    448 S        0.0   0:00.88  `- /usr/sbin/cron -f
28770 fishtest  20     1838784 357652   5152 S  12.3  6.8   3:03.78  `- /home/fishtest/fishtest/fishtest/env/bin/python3 /home/fishtest/fishtest/fishtest/env/bin/pserve production.ini http_port=6544
28771 fishtest  20     2186884 788064   6100 R  34.2 15.0  42:04.90  `- /home/fishtest/fishtest/fishtest/env/bin/python3 /home/fishtest/fishtest/fishtest/env/bin/pserve production.ini http_port=6543
 1791 root      20       13008    844    712 S        0.0            `- /sbin/agetty -o -p -- \u --noclear tty2 linux
 1792 root      20       13008    844    716 S        0.0            `- /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux

```

**Comment by ppigazzini** [comment]
@tomtor stopping nginx all went 0

**Comment by tomtor** [comment]
```
diff --git a/fishtest/fishtest/api.py b/fishtest/fishtest/api.py
index 40cf283..943a503 100644
--- a/fishtest/fishtest/api.py
+++ b/fishtest/fishtest/api.py
@@ -11,6 +11,7 @@ WORKER_VERSION = 73


 def get_flag(request):
+  return None
   ip = request.remote_addr
   result = request.userdb.flag_cache.find_one({'ip': ip})
   if result is not None:
```

Applied on prod fixed the load. The flag query is hitting MongoDb.

**Comment by tomtor** [comment]
@JojoM-sf  Back to the original topic, Our counts moved up! Compare to https://github.com/glinscott/fishtest/issues/605#issuecomment-616093666

**Comment by JojoM-sf** [comment]
@tomtor By a minuscule margin, yes. But presently, I seem to be unable to access the server anyway.

**Comment by tomtor** [comment]
@JojoM-sf @linrock @ppigazzini 
The stats are indeed incrementing too slowly. Looking at the cause in production now. Have manually reverted #595 for debugging.

**Comment by ppigazzini** [comment]
@tomtor I loaded on DEV the latest hourly (07:03am UTC) DB backup if this can be useful

**Comment by tomtor** [comment]
@ppigazzini Thanks. Monthly statistics look OK on prod, I'll have a look again tomorrow to see if they are really progressing slower and I have to look at some additional diagnostics.

@ppigazzini Could you on DEV test if the full scan option still works as expected with the current master version of `delta_update_users.py`?

**Comment by tomtor** [comment]
@ppigazzini No need to test something on DEV, its OK.

**Comment by linrock** [comment]
another thing that changed that might affect stats calculations was moving runs from `old_runs` back into the `runs` collection. after adding the old runs back in, the `_id` field in `runs` is no longer an accurate representation of how recently the run happened.

the `delta_update_users.py` script sorts by `_id` and iterates through runs. maybe there's an issue there? to iterate through runs by recency, it's more accurate to sort runs by `last_updated` now

> also note my tests submitted (530), which does not match the total when you click the 530 link (697). I am pretty sure these numbers used to match. The difference can be without/with deleted tests

yes, i think the difference is that 697 counts submitted+deleted tests, while 530 does not count the deleted tests. i can open a PR to fix that by updating some indexes on runs.

**Comment by ppigazzini** [comment]
@linrock the `_id` field seems to not change when moving documents between collection, see 
https://stackoverflow.com/questions/24741667/does-id-field-change-in-mongodb-when-copying-data-from-one-collection-to-anothe

**Comment by tomtor** [comment]
I am not 100% sure something is really broken, so no hurry to make changes (if any).

**Comment by tomtor** [comment]
@linrock @ppigazzini 

Not related to this issue but when running scan all I found that
run:  5144513ee4721c1c36a06a58 causes an error.

https://tests.stockfishchess.org/tests/view/5144513ee4721c1c36a06a58

```
Apr 21 08:43:06 tests pserve[2489]:   File "/home/fishtest/fishtest/fishtest/fishtest/templates/tests_view.mak", line 269, in render_body
Apr 21 08:43:06 tests pserve[2489]:     const apiUrlBase = "${run['args']['tests_repo']}".replace("//github.com/", "//api.github.com/repos/");
Apr 21 08:43:06 tests pserve[2489]: KeyError: 'tests_repo'
```

**Comment by tomtor** [comment]
@linrock @ppigazzini 

I found the root cause for the missing updates, the update script most sort descending on `last_updated`:
```
-    runs = list(rundb.runs.find(q, sort=[('_id', DESCENDING)], limit=step_size))
+    if clear_stats:
+      runs = list(rundb.runs.find(q, sort=[('_id', DESCENDING)], limit=step_size))
+    else:
+      runs = list(rundb.runs.find(q, sort=[('last_updated', DESCENDING)], limit=step_size))
```

This is however much slower than the original version.... (runs many minutes)

**Comment by ppigazzini** [comment]
@tomtor I changed by hand `delta_update_users.py` with your fix on DEV, here is the snippet:

```
git diff
diff --git a/fishtest/utils/delta_update_users.py b/fishtest/utils/delta_update_users.py
index fb4513c..d1fd356 100644
--- a/fishtest/utils/delta_update_users.py
+++ b/fishtest/utils/delta_update_users.py
@@ -125,7 +125,11 @@ def update_users():
     q = { 'finished': True }
     if last_run_id:
       q['_id'] = { '$lt': last_run_id }
-    runs = list(rundb.runs.find(q, sort=[('_id', DESCENDING)], limit=step_size))
+#    runs = list(rundb.runs.find(q, sort=[('_id', DESCENDING)], limit=step_size))
+    if clear_stats:
+      runs = list(rundb.runs.find(q, sort=[('_id', DESCENDING)], limit=step_size))
+    else:
+      runs = list(rundb.runs.find(q, sort=[('last_updated', DESCENDING)], limit=step_size))
     if len(runs) == 0:
       break
     for run in runs:
```

The script is still very fast on DEV wrt the previous code https://github.com/glinscott/fishtest/pull/595#issuecomment-614300588 :
```
$ time ${VENV}/bin/python delta_update_users.py all
scan all
...
not in info:  NachoSoto
Exception on run:  5144513ee4721c1c36a06a58
Successfully updated 1361 users

real    2m33.313s
user    2m21.309s
sys     0m4.730s
```

**Comment by tomtor** [comment]
@ppigazzini Without "all" it is slow....

**Comment by ppigazzini** [comment]
@tomtor 18 seconds
```
time ${VENV}/bin/python delta_update_users.py
Successfully updated 1361 users

real    0m18.270s
user    0m14.977s
sys     0m2.049s
```

**Comment by tomtor** [comment]
@ppigazzini For some reason it ran very slow on prod (tested two times), just after a scan "all". Not sure why.

**Comment by ppigazzini** [comment]
@tomtor true, but after a mongo restart now it's fast (I copied a new script, the original one has some debugging code)
```
 time ${VENV}/bin/python delta_update_users_my.py
Successfully updated 1361 users

real    0m25.604s
user    0m19.527s
sys     0m2.455s
```

**Comment by linrock** [comment]
ah i see, so we have to sort by `last_updated` instead of `_id` after all.

the script will be faster if we both query + sort by `last_updated` since then every batch of runs is fetched already-sorted using a sorted index.

querying by `_id` and sorting by `last_updated` will be slower since every batch needs to be sorted even though the batch is fetched using the index on `_id`.

**Comment by linrock** [comment]
see https://github.com/glinscott/fishtest/pull/618 for a possible fix that shouldn't incur a slowdown
