### ISSUE TITLE
Detect if two instance are running from same workstation

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#61]
Re: recent icewulf and JojoM case.

**Comment by Rocky640** [comment]
Here is some new input from user JojoM
https://groups.google.com/d/msg/fishcooking/TZDYHEW61Pw/SmwVobKOC-8J

**Comment by Rocky640** [comment]
Seems that JojoM found a solution.
https://groups.google.com/d/msg/fishcooking/yuustjto4Y4/RuaPVXz_BgAJ

**Comment by vondele** [comment]
if fishtest is on a shared filesystem, this is indeed a problem, i.e. two different running instances of the worker (on different machines) can overwrite each others files. A simple solution would be to add the hostname to the directories that are being created inside the fishtest tree.

**Comment by ppigazzini** [comment]
This could be closed after committing #258, correct?

**Comment by vondele** [comment]
We still shouldn't recommend doing this, but I think it is good enough in case users make mistakes. One issue in principle is that both workers could 'mv' the binary at the same time to the same name, which, I assume, would cause problems on certain systems where a mv is not atomic (not quite sure which/when this is problematic). Don't think we should care.

**Comment by ppigazzini** [comment]
Sure, multiple workers from the same workstation should be run within separate folders.
Anyway #258 is a good safety net against an user mistake, so we can close this issue.
Thank you @vondele for that PR :-)
