### ISSUE TITLE
Gateway timeout when submitting tests

### ISSUE THREAD

**Issue by linrock** [glinscott/fishtest#636]
Something I saw several times today:

- Try to submit a test. Loads for a long time, then 504 gateway timeout.
- Refresh to resubmit. Test submits successfully a second or two later.

Maybe the first request gets sent to a backed-up pserve? When this happens, I visit other pages to see if the site is down, but the site seems to be functioning normally.

**Comment by dav1312** [comment]
Is this still an issue?

**Comment by linrock** [comment]
I don't think so, closing this issue as it's likely stale and irrelevant by now
