### ISSUE TITLE
Some oddity in stat_util.py.

### ISSUE THREAD

**Issue by GeorgeMJ23** [glinscott/fishtest#637]
In https://github.com/glinscott/fishtest/blob/78c8e2345346eddc25e29ea3016884800369c607/fishtest/fishtest/stat_util.py#L45

While i don't know if this is used or not anymore, in the line 45:

mu_min = mu + phi_inv(0.025) * stdev
mu_max = mu + phi_inv(0.975) * stdev

It should have been:
mu_min = mu + phi_inv(0.025) * stdev/math.sqrt(N)
mu_max = mu + phi_inv(0.975) * stdev/math.sqrt(N)

As also in line 42 the:
 stdev = math.sqrt(w*(1-mu)**2 + l*(0-mu)**2 + d*(0.5-mu)**2) / math.sqrt(N)

Should have been:
 stdev = math.sqrt(w*(1-mu)**2 + l*(0-mu)**2 + d*(0.5-mu)**2) / math.sqrt(N-1)

**Comment by vdbergh** [comment]
The code you refer to is from the beginning days of Fishtest. Dividing by sqrt(N) was a (hacky) way to avoid division by zero when the test starts. Note that it is not so clear what would be the "best" denominator. See https://en.wikipedia.org/wiki/Standard_deviation#Sample_standard_deviation. But in fact this is completely irrelevant. This code is only used to calculate error bars for fixed length tests which are used to measure Elo differences. For those one only wants to have a rough estimate of the error (2 significant digits is more than enough).  Even for a test of 1000 games the different
possible denominators lead to differences in sizes of error bars which are  far too small to be measurable.

**Comment by vdbergh** [comment]
I think this can be closed now.
