### ISSUE TITLE
purge_pgn.py stopped working?

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#642]
@linrock @tomtor the script should delete the STC PGNs older than 2 days, but there are still the STC PGNs dated since 20-04-12 (14 days ago) , see at example
https://tests.stockfishchess.org/tests/view/5e92a136be6ede5b954bf237

The disk space on PROD is running low, only 11 GB free (after a hard housekeeping...), the "pgns" collection is inflated at 75 GB.

**Comment by tomtor** [comment]
@ppigazzini I am looking at it...

**Comment by tomtor** [comment]
Find order is changed, probably due to new indices. I have patched the script on prod and I am dropping old PGNs now. Will create a PR later...

**Comment by ppigazzini** [comment]
@tomtor `create_pgndb.py` created a capped collection `db.create_collection('pgns', capped=True, size=50000)`, but now the `pgns` collection isn't capped:
```
> db.pgns.stats()
{
        "ns" : "fishtest_new.pgns",
        "size" : 79297209417,
        "count" : 498640,
        "avgObjSize" : 159026,
        "storageSize" : 80386555904,
        "capped" : false,
        "wiredTiger" : {
                "metadata" : {
                        "formatVersion" : 1
                },
...
}
```

Questions:
1. Should we cap `pgns` collection?
2. `create_pgndb.py` is still useful?

**Comment by tomtor** [comment]
> Questions:
> 
> 1. Should we cap `pgns` collection?
> 2. `create_pgndb.py` is still useful?

@linrock @ppigazzini When `purge_pgn` script is run on regular intervals then IMO the answer is: No and No
