### ISSUE TITLE
Time Control Issue

### ISSUE THREAD

**Issue by protonspring** [glinscott/fishtest#653]
If someone enters "40/10" as a time control, everything dies.  This is a common format, but I'm not sure it's used much anymore.  Was there a choice to remove it?

Solution #1) Add it back in with a good parser that will error if there are errors.

Solution #2) Acknowledge that this type of TC is dead.  Change to two separate text fields.  One for start time in seconds and another for increment in seconds.  This is much easier to parse and it's more clear to a user that 40/10 is no longer supported.

**Comment by vondele** [comment]
will probably be fixed by https://github.com/glinscott/fishtest/pull/650

**Comment by ppigazzini** [comment]
Bug fixed, thank you @protonspring for the nice catch :)
