### ISSUE TITLE
problem auto-update

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#672]
There seems to be an issue with the auto updater:

https://groups.google.com/d/msg/fishcooking/bWR8rvtCLkg/sIzHpFtEAwAJ

maybe happens when the user has another process running in the testing directory or something else looking at the content there (just guessing)?

**Comment by ppigazzini** [comment]
We could keep the old "testing" dir if the move fails:  
https://github.com/glinscott/fishtest/blob/377b2884cf628f4793e1a5cd3d49f88bc34148eb/worker/updater.py#L59

But in this way we'll fail to update "cutechess-cli", books etc.

**Comment by vondele** [comment]
could we use 'versioning' for the testing directory, i.e. testing_workerid or so ?

**Comment by ppigazzini** [comment]
Fixed by #894
