### ISSUE TITLE
authentication worker / server

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#673]
I just played around with a .netrc file to try authenticated access with username and password, and got a notification about it being deprecated:

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

not sure if we are already using that or how to do that for a worker. We still have a couple of months for this.

**Comment by ppigazzini** [comment]
@vondele Here is the token creation page, I chose only "public_repo" scope
https://github.com/settings/tokens

Write the `.netrc` in this ways

```
machine api.github.com
login <personal-access-token>
password x-oauth-basic
```
or
```
machine api.github.com
login <username>
password <personal-access-token>
```

**Comment by ppigazzini** [comment]
Wiki updated
https://github.com/glinscott/fishtest/wiki/Running-the-worker:-overview#github-api-requests-rate-limit

**Comment by vondele** [comment]
so, I think I can close the issue.. right? If not reopen, thanks for the info and the docs.
