### ISSUE TITLE
reset of fishtest password

### ISSUE THREAD

**Issue by dorzechowski** [glinscott/fishtest#675]
I forgot my fishtest password. Is there any way to reset it?

**Comment by ppigazzini** [comment]
@dorzechowski Let me know your username.

**Comment by dorzechowski** [comment]
Username as here on github.

**Comment by ppigazzini** [comment]
@dorzechowski pwd "UtxpN6LgYLcf5Rp"
Please login asap and change the password.

**Comment by dorzechowski** [comment]
@ppigazzini Done, thanks!
