### ISSUE TITLE
Limits again?

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#680]
I saw this picture during more over hour with 19 active and 6 pending tests:

![ft_lol](https://user-images.githubusercontent.com/32866346/82710423-8260f180-9c8b-11ea-8222-2a68c3dab96c.jpg)

**Comment by ppigazzini** [comment]
@tomtor the first d3vv worker went idle at 11:18PM CEST the other workers some minutes after.

**Comment by d3vv** [comment]
@ppigazzini fresh screen - the same situation:

![lol2](https://user-images.githubusercontent.com/32866346/82711589-82aebc00-9c8e-11ea-862b-c9d59b448f9e.jpg)

**Comment by Vizvezdenec** [comment]
Yeah my LTC doesn't get workers. I'm trying workaround with 1 prio for now.

**Comment by d3vv** [comment]
@Vizvezdenec workers starts at least.. I will try to add some more..

**Comment by noobpwnftw** [comment]
Server is broken, adding new workers won't get any task.

**Comment by vondele** [comment]
@noobpwnftw this looks like it could be fixed by your https://github.com/glinscott/fishtest/pull/681 right?

**Comment by noobpwnftw** [comment]
@vondele I think so.

**Comment by tomtor** [comment]
See https://github.com/glinscott/fishtest/issues/677#issuecomment-633016311

**Comment by tomtor** [comment]
Discuss at #677, I am closing this one.
