### ISSUE TITLE
locale & pgn

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#685]
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/SOpgUxPYZa0

looks like depending on the locale the generated PGNs can not be uploaded. I'd like to keep the PGNs easy to parse, so enforcing ascii makes sense. Can we launch cutechess while setting the equivalent of export LC_ALL=C in the worker?

**Comment by d3vv** [comment]
Guess it's all about:

https://doc.qt.io/qt-5/qlocale.html

Sure need something like: `QLocale::setDefault(QLocale::C);`

But in a good way  if fishtest will abilities to parse unicode for date into info-string..

**Comment by d3vv** [comment]
In simple, just cut season and country field..

**Comment by tomtor** [comment]
See https://github.com/glinscott/fishtest/pull/686#issuecomment-633481723

**Comment by tomtor** [comment]
See google thread:

Quote:

Ah thanks, that (8bit codepage) explains the error and why it DOES work for some users.

The next question is why some Window users have Cyrillic and utf-8 and some have Cyrillic with an 8bit codepage.

I guess it depends on window version (7/8/10) and the cutechess binary used.

Anyway, handling 8bit encoded pgns by fishtest is not a real option, so IMO ignoring them (throwing exception) is correct.

**Comment by tomtor** [comment]
We could translate to ascii in the worker before upload when not utf-8. Not sure if that is worth the trouble.

**Comment by vondele** [comment]
I guess this pull should be closed, as it neither solves the problem nor is the preferred way to solve it. Right?

**Comment by tomtor** [comment]
@vondele Yes it can be closed...

**Comment by tomtor** [comment]
Should close the PR, not the issue

**Comment by tomtor** [comment]
command:

`chcp 65001`

in the command-prompt window of a fishtest worker should switch to utf-8 (untested)

**Comment by kotenok2000** [comment]
Do i have to put it in one_click_run.bat?

**Comment by tomtor** [comment]
Yes, please do.

Let me know if it works.

Op za 6 jun. 2020 06:03 schreef kotenok2000 <notifications@github.com>:

**Comment by kotenok2000** [comment]
No it didn’t

**Comment by tomtor** [comment]
Is fixed with #698
