### ISSUE TITLE
Resolved New / Base not reliable

### ISSUE THREAD

**Issue by xoto10** [glinscott/fishtest#688]
After the latest sf merges, patch diffs are not showing on github.

I think the problem is because we now only display and use the first 7 chars of the github commit reference. This is generally enough but in the case of current master it seems that it isn't (I assume there is a clash).
e.g. This diff doesn't display: https://github.com/vondele/Stockfish/compare/d40d04c...3140aa0
but this one does: https://github.com/vondele/Stockfish/compare/d40d04c1...3140aa0

Perhaps we should add a couple of characters to the commit refs to avoid this?

**Comment by ppigazzini** [comment]
Great catch @xoto10 :)
