### ISSUE TITLE
fishtest dead?

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#690]
I get 504 error when trying to refresh.

**Comment by ppigazzini** [comment]
Server rebooted. I will check the logs in my first coffee break.

**Comment by crossbr** [comment]
Again?

"Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)"

**Comment by vondele** [comment]
@ppigazzini did an update a little while ago. I assume he's aware.

**Comment by ppigazzini** [comment]
```
May 30 19:43:47 tests.stockfishchess.org pserve[24316]:   File "/home/fishtest/fishtest/fishtest/fishtest/util.py", line 255, in estimate_game_duration
May 30 19:43:47 tests.stockfishchess.org pserve[24316]:     time_tc = float(chunks[0])
May 30 19:43:47 tests.stockfishchess.org pserve[24316]: ValueError: could not convert string to float: '15Npsq'
```

**Comment by vondele** [comment]
@ppigazzini hmm bogus TC being passed to this function. Possibly a garbage test?

**Comment by vondele** [comment]
https://tests.stockfishchess.org/tests/user/fauzi2 doesn't display. I think it is one of his tests (psq tuning).

**Comment by vondele** [comment]
@ppigazzini https://github.com/glinscott/fishtest/pull/695 might be a workaround.

**Comment by ppigazzini** [comment]
@vondele correct, I deleted that test.
I was able to have fishtest up and running with:
```
  else:
    try:
      time_tc = float(chunks[0])
    except:
      time_tc = 666
```

Previously I restarted fishtest to raise the worker version to 79 server side.

**Comment by vondele** [comment]
Right the tc seems like a pasto : `15Npsq+0.15`

**Comment by crossbr** [comment]
500 Internal Server Error

**Comment by tomtor** [comment]
@ppigazzini 

Mongodb had crashed, did a restart of the mongod service

**Comment by Vizvezdenec** [comment]
bump

**Comment by ppigazzini** [comment]
@tomtor vps restarted 3 hours ago

**Comment by crossbr** [comment]
I'm getting "504 Gateway Time-out" and my worker is timing out.

**Comment by Vizvezdenec** [comment]
main page fails to refresh.

**Comment by crossbr** [comment]
@Vizvezdenec still up for me.

**Comment by Vizvezdenec** [comment]
it's up but main page was stuck on tests not updating it stats for tests for like 10 minutes (while you could click on individual tests and see their actual stats with 10k games diff from what main page shows) ~
Now it's refreshing again. Maybe there will be smth in the logs...

**Comment by Vizvezdenec** [comment]
It's still like this - I need to manually open every test page and refresh them by hand to get actual info because main page is really outdated.

**Comment by tomtor** [comment]
@ppigazzini I see you restarted fishtest. Root cause according to the log is an internal error in the mongodb python library....

**Comment by ppigazzini** [comment]
@tomtor let me know when can install the latest MongoDB updates on PROD.

**Comment by tomtor** [comment]
@ppigazzini After the TCEC final has started? So next saturday or later...

**Comment by ppigazzini** [comment]
@tomtor OK let's wait the SUFI start.
I keep DEV up to date with `sudo apt update && sudo apt full-upgrade -y` and today I noted updates for MondoDB.
I never had a problem with the MongoDB update but it requires a VPS reboot.

**Comment by vondele** [comment]
@ppigazzini I won't merge any new patches before the SUFI, so that should not be a concern.

**Comment by ppigazzini** [comment]
@vondele @tomtor PROD up and running with up to date MondoDB and up to date python packages.

**Comment by Vizvezdenec** [comment]
"504 gateway timeout" or simply opening for 20+ seconds on every single user page for me - everything else works fine. https://tests.stockfishchess.org/tests/user/Vizvezdenec for example.

**Comment by vondele** [comment]
yes, I've also noticed user pages have become very slow to open.

**Comment by vondele** [comment]
this is not very recent

**Comment by Vizvezdenec** [comment]
bump

**Comment by tomtor** [comment]
@ppigazzini Could you try increasing the mongodb cache size?

The root cause is new additional indices and old indices which are bigger due to the removal of `old_runs`.

**Comment by tomtor** [comment]
@ppigazzini So we need to reduce mongodb max memory usage, but increase the INDEX cache size (if possible at all).

**Comment by ppigazzini** [comment]
@tomtor I set `cacheSizeGB: 2.00` from 1.50 and restarted mongod.

**Comment by tomtor** [comment]
> @tomtor I set `cacheSizeGB: 2.00` from 1.50 and restarted mongod.

See https://github.com/glinscott/fishtest/issues/708#issuecomment-647097462

**Comment by tomtor** [comment]
@ppigazzini Until we know why MongoDb was killed (I have not seen the actual kernel kill message) it is safer to reduce the MongoDb cache size for now. The kernel IO buffer cache should cache most IO anyway.

I have not seen the option to specify INDEX cache size for MongoDb. User queries seem to perform quite good with the 1GB setting.

**Comment by tomtor** [comment]
@ppigazzini It looks as if MongoDb dump forces much of the cache out, so the first user queries will be slow? Not much we can do about that.

**Comment by tomtor** [comment]
@vondele @Vizvezdenec Is a reduction in pagesize acceptable to you?

Eg from 50 to 25 entries for user queries or perhaps even for all pages?

**Comment by vondele** [comment]
@tomtor sure, if that improves the performance, that's no big deal IMO. This could be for all pages consistently. 

However, this seems to indicate that we're close to the limit of what we can do with the current infrastructure.

**Comment by tomtor** [comment]
I changed it to 25 on prod to get a feel for it....

> However, this seems to indicate that we're close to the limit of what we can do with the current infrastructure.

IO speed is a bit low which impacts non frequent queries, but IMO in general there are sufficient resources.

**Comment by ppigazzini** [comment]
@tomtor usually MongoDB RAM usage raises to a steady max value after a `mongodump`. Perhaps the optimal `cacheSizeGB` value to run fishtest is lower than 1 GB.

**Comment by tomtor** [comment]
> usually MongoDB RAM usage raises to a steady max value after a `mongodump`. Perhaps the optimal `cacheSizeGB` value to run fishtest is lower than 1 GB.

Yes, that could be. But a dump will always access the whole DB which will remove all recently cached data from the caches. This could be considered a MongoDb dump issue.

**Comment by ppigazzini** [comment]
> Yes, that could be. But a dump will always access the whole DB which will remove all recently cached data from the caches.

But IMO if done rightly that should be the same clean state after a mongod restart.

**Comment by vondele** [comment]
> I changed it to 25 on prod to get a feel for it....

for me that's fine. It might require a few more clicks in the future searching for a patch, but that's not so important IMO.

**Comment by tomtor** [comment]
> But IMO if done rightly that should be the same clean state after a mongod restart.

Yes that is true for the mongodb cache, but a restart does not flush the kernel buffer cache. The dump does...

**Comment by tomtor** [comment]
@ppigazzini from the mongodb documentation:

mongodump can adversely affect performance of the mongod. If your data is larger than system memory, the mongodump will push the working set out of memory.

**Comment by tomtor** [comment]
@ppigazzini How about a dump every 12 hours instead of every hour?

**Comment by ppigazzini** [comment]
> @ppigazzini from the mongodb documentation:
> 
> mongodump can adversely affect performance of the mongod. If your data is larger than system memory, the mongodump will push the working set out of memory.
> 
> https://docs.mongodb.com/manual/reference/program/mongodump/

@tomtor until some months ago we ran `mongodump` on 4 collections in parallel, dumping also the huge pngs collection. The RAM stress from `mongodump` was bigger than now.

MongoDB RAM usage follow the `cacheSizeGB` value, I'm suspecting that the OOM problem could be triggered by a `pserve` increased RAM usage.

If the problem is really `mongodump`, perhaps should be better to dump only 1 collection each hour.

**Comment by tomtor** [comment]
> If the problem is really `mongodump`, perhaps should be better to dump only 1 collection each hour.

This issue is a mix of several issues. I hope that the current reduction of cache (to 1 GB) fixes the OOM issue.

I would like to reduce the dump impact to speed up the slow user queries. Best that I first look at #710, that would speedup the dump also.

I still think that just reducing the dump frequency makes sense. We have never needed to restore a dump due to an emergency. Dumping once every 12 hours should be sufficient and this would minimize impact on user query speed.

**Comment by tomtor** [comment]
@ppigazzini yesterday around 2330 fishtest had a 350% mongodb load and main view was unresponsive. Actions and nn-stats were responsive. No increase in  network downloads. Restart mongo did not help. Restart fishtest started with busy queue messages.

Now things are normal. Not clear what caused the load.

**Comment by Vizvezdenec** [comment]
Bump

**Comment by SFisGOD** [comment]
@ppigazzini Fishtest down

**Comment by ppigazzini** [comment]
@tomtor mongod down, restarted.
Thanks @SFisGOD

**Comment by Vizvezdenec** [comment]
main page lags in terms of updating tests for some minutes @ppigazzini @tomtor

**Comment by ppigazzini** [comment]
@Vizvezdenec restarted mongod and fishtest servers.

**Comment by Vizvezdenec** [comment]
Bump @ppigazzini @tomtor

**Comment by tomtor** [comment]
@ppigazzini The busy pserve is using 38% of memory and the mostly idle pserve 22%. I suggest testing with just a single pserve instance to see if the reduced memory usage fixes these issues.

**Comment by ppigazzini** [comment]
@tomtor done.

- [x] : /etc/nginx/sites-available/fishtest.conf
```
upstream backend_all {
    # server 127.0.0.1:6544;
    server 127.0.0.1:6543;
}
```
- [x] : `sudo systemctl reload nginx`
- [x] : `sudo systemctl stop fishtest@6544`
- [x] : `sudo systemctl disable fishtest@6544`

**Comment by ppigazzini** [comment]
@tomtor testing PROD w/ python 3.8.5 by pyenv to test if this help w/ RAM/CPU usage. DEV has been running fine from the switch some weeks ago.

**Comment by ppigazzini** [comment]
@tomtor the single pserve instance peaked at 49% RAM

Now I configured PROD to run 2 pserve instances:
 - pserve @ 6543 with production6543.ini (usual configuration, threads = 16 ; connection_limit = 500)
 - pserve @ 6544 with production6544.ini (threads = 4 ; connection_limit = 100)

systemctl commands unchanged to start/stop fishtest.

**Comment by ppigazzini** [comment]
@tomtor recent how to waitress works (pserve is a loader):
https://stackoverflow.com/questions/59838433/how-does-waitress-handle-concurrent-tasks

**Comment by tomtor** [comment]
> the single pserve instance peaked at 49% RAM

@ppigazzini The memory usage is strongly related to the number of active tests and the nr-of-games of these tests. 

Recent issues were related to `pserve` not being able to access `mongodb`. That can be caused by an issue on the python side or on the mongodb-server side.

You restarted mongodb https://github.com/glinscott/fishtest/issues/690#issuecomment-691588736
but I do not see any issues reported in the mongodb log:

```
2020-09-12T23:31:25.668+0000 I  COMMAND  [conn15430] command fishtest_new.runs command: count { coun
t: "runs", hint: "finished_runs", lsid: { id: UUID("0a4834d1-ff0c-4655-90f9-77e718d7d1b5") }, $db: "
fishtest_new", $readPreference: { mode: "primaryPreferred" } } planSummary: COUNT_SCAN { last_update
d: -1 } keysExamined:88180 docsExamined:0 numYields:689 reslen:45 locks:{ ReplicationStateTransition
: { acquireCount: { w: 690 } }, Global: { acquireCount: { r: 690 } }, Database: { acquireCount: { r:
 690 } }, Collection: { acquireCount: { r: 690 } }, Mutex: { acquireCount: { r: 1 } } } storage:{ da
ta: { bytesRead: 883318, timeReadingMicros: 103894 } } protocol:op_msg 171ms
2020-09-12T23:31:27.073+0000 I  COMMAND  [conn15873] command fishtest_new.runs command: find { find: "runs", filter: { finished: true, last_updated: { $lt: new Date(1599293220913) } }, sort: { last_updated: -1 }, limit: 100, lsid: { id: UUID("b0483906-665a-4bf1-9bc4-ae98ded84f60") }, $db: "fishtest_new", $readPreference: { mode: "primaryPreferred" } } planSummary: IXSCAN { last_updated: -1 } cursorid:1358209641852981721 keysExamined:85 docsExamined:85 numYields:21 nreturned:84 queryHash:1FEFA34D planCacheKey:56A3B9EE reslen:16658677 locks:{ ReplicationStateTransition: { acquireCount: { w: 22 } }, Global: { acquireCount: { r: 22 } }, Database: { acquireCount: { r: 22 } }, Collection: { acquireCount: { r: 22 } }, Mutex: { acquireCount: { r: 1 } } } storage:{ data: { bytesRead: 16868363, timeReadingMicros: 717739 } } protocol:op_msg 730ms
2020-09-13T01:30:40.205+0000 I  CONTROL  [main] ***** SERVER RESTARTED *****
```

It is not receiving queries according to the log. Can you remember if it was busy (as reported in https://github.com/glinscott/fishtest/issues/690#issuecomment-674692530)

**Comment by ppigazzini** [comment]
@tomtor from syslog fishtest was killed over and over (OOM killer?)
```
Sep 19 11:46:08 tests systemd[1]: fishtest@6543.service: Main process exited, code=killed, status=9/KILL
Sep 19 11:46:08 tests systemd[1]: fishtest@6543.service: Failed with result 'signal'.
```

In my tests in these two days the pserve memory usage seems to be strongly correlated to the number of threads.
At example yesterday night I configured the busy pserve with 12 threads, idle pserve with 4 threads, now RAM used is busy pserve 24.9%, idle pserve 7.9%.

Perhaps the optimization work (mongodb indexes, batching worker communication) has lowered the threads requirement.

By the way this is the PROD nginx status after 13 hours
```
Active connections: 29 
server accepts handled requests
 106971 106971 251123 
Reading: 0 Writing: 1 Waiting: 27 
```
So:
 - 2.28 connections/sec
 - 5.37 requests/sec

http://nginx.org/en/docs/http/ngx_http_stub_status_module.html

**Comment by tomtor** [comment]
@ppigazzini It is now at 28.5%. I am ok with testing lower max threads (try 4), to see if that reduces memory usage a lot.

**Comment by ppigazzini** [comment]
@tomtor Ops, I was wrong, fishtest was running with  busy `pserve` at 8 threads, idle `pserve `at 4 threads, I corrected my previous post.
Restarted with busy `pserve` at 4 threads, idle `pserve `at 2 threads, both with 100 connections.

Raised `mongod `cache to 1.75GB, restarted `nginx `at 10:41 UTC+2, see https://tests.stockfishchess.org/nginx_status

**Comment by ppigazzini** [comment]
@tomtor with 2152 machines and 17083 cores (no SPSA tests) the busy `pserve` oscillates between 30%-100% CPU load, these the connections measured (by hand) in 5 minutes intervals:
- both `pserve` at 4 threads 100 connections
```
Active connections: 57 
server accepts handled requests
 10687 10687 12114 
Reading: 0 Writing: 1 Waiting: 56 
```
- both `pserve` at 4 threads 500 connections
```
Active connections: 57 
server accepts handled requests
 12035 12035 12880 
Reading: 0 Writing: 6 Waiting: 51 
```
- both `pserve` at 16 threads 500 connections
```
Active connections: 91 
server accepts handled requests
 11182 11182 12310 
Reading: 0 Writing: 4 Waiting: 87 
```

**Comment by tomtor** [comment]
@ppigazzini It is not clear to me if any of these configs is significant different or better...

**Comment by ppigazzini** [comment]
@tomtor with 4 threads we are able to raise the mongodb cache from 1GB to 1.75GB and to avoid the OOM killer. I'm opening a PR.

**Comment by ppigazzini** [comment]
@tomtor yesterday I setup on PROD the recently released python 3.8.6 (courtesy of pyenv).
After half day the busy/idle `pserve` at 4 threads were using 14.9%/5.8% vs 23.1%/7.5% (python 3.8.5)
VPS memory usage was at 64.4% vs 73%.

I restarted the server raising the `mongod` cache to 2.25 GB, the VPS memory usage at the moment is still very low (64%), finger crossed.

https://docs.python.org/release/3.8.6/whatsnew/changelog.html#changelog

**Comment by crossbr** [comment]
502 Bad Gateway.

**Comment by ppigazzini** [comment]
fishtest down for MongoDB maintenance: started a script to compact the "pgns" collection.
Here the post on the forum:
https://groups.google.com/g/fishcooking/c/eiSAKmd2fqY

**Comment by ppigazzini** [comment]
fishtest restarted.

* before:
```
Filesystem        1K-blocks     Used Available Use% Mounted on
/dev/ploop36869p1 103078840 68980316  29783256  70% /
```
* after:
```
Filesystem        1K-blocks     Used Available Use% Mounted on
/dev/ploop36869p1 103078840 32656440  66107132  34% /
```

**Comment by SFisGOD** [comment]
@ppigazzini Fishtest down

**Comment by ppigazzini** [comment]
"Load average too high - VPS shutdown", see #799
