### ISSUE TITLE
fatal error: intrin.h: No such file or directory

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#700]
https://tests.stockfishchess.org/tests/view/5ede9659f29b40b0fc95ad0c

This test only works with Windows! Why it's running on Linux workers?

**Comment by ppigazzini** [comment]
@d3vv thank you for the alert, action taken, see
https://github.com/mstembera/Stockfish/commit/9ffb7d1f4833b428bd15f4c58b89fc2f00d3eb52#commitcomment-39773433
