### ISSUE TITLE
waiting for stackpath

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#701]
I've noticed that recently things became a bit slower again, in particular I see that loading the page often waits for 'stackpath.bootstrapcdn.com' ... is that something that can be avoided by caching or other?

**Comment by linrock** [comment]
if this is still happening, it could be fixed by going back to self-hosting the bootstrap CSS files or using a better CDN. it's unfortunate if this CDN is unreliable.

**Comment by vondele** [comment]
actually has become much better. Let me close the issue.
