### ISSUE TITLE
Lost options when changing TC in the test creation page

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#704]
Steps to reproduce:

1) open the following passed STC test, which correctly includes "Contempt=0" in the options for base and tested patch: https://tests.stockfishchess.org/tests/view/5ee7f27daae8aec816ab75db

2) click on "reschedule" : the options correctly include "Contempt=0" in the test creation page

3) click on "Long (LTC)": the page changes correctly the hash table settings, but clear all the other options. If the user doesn't notice and launch the test, then it is a surpise that the STC and the LTC tests do not use the same settings... https://tests.stockfishchess.org/tests/view/5ee84d41563bc7aa755ffb6d

Expected behavior: changing the time control should change the hash table size for the test, but leave all other options the same.

**Comment by nickolasreynolds** [comment]
I've found that most of the user-specified fields annoyingly fail to be persistent, e.g. when a test submission fails for whatever reason, all the stuff you just wrote gets blanked out.

**Comment by snicolet** [comment]
@nickolasreynolds when a submission fails, at least you can use the "back" button of your browser to recover the blanked options: that is a work-around.

The issue in this PR is a little bit different, because it is a surprise.

**Comment by tomtor** [comment]
We could add a new "shared options" field which is set by clicking the buttons.
The Base/Test options would be left unchanged when clicking.

Would that be OK?

**Comment by snicolet** [comment]
Hmm, that would complicate the interface quite a bit.

Probably better would be to decide on a clear subset of options pairs that are OK to change (via substring recognition) when going default STC -> default LTC, and leave all the other settings unchanged.

Examples of such pairs:
STC default: Hash=16
LTC default: Hash=64
STC default: Contempt=24
LTC default: Contempt=24

• if setting at STC: `Hash=16 Contempt=24`, change only the Hash=16 to Hash=64 part of the string
• if setting at STC: `Hash=10 Contempt=24`, do not change anything because Hash=10 is not the default, so user probably has something special in mind and it is better to let him decide
• if setting at STC: `Hash=16 Contempt=12`, change only the Hash=16 to Hash=64 part because Contempt=12 doe not match the STC default for contempt.

Algorithm:
```For each (STC_default, LTC_default) pair, if options.contains(STC_default) then options.replace(STC_default,LTC_default)```

**Comment by vondele** [comment]
I think adding Contempt to the list of options was a bit quick. It is like inviting people to do even more contempt tests. Adding additional options is something for like <1% of the tests... if things can be fixed quickly and without complications, why not, but otherwise I would just be careful as a user.

**Comment by snicolet** [comment]
> It is like inviting people to do even more contempt tests.

+1

**Comment by ppigazzini** [comment]
@vondele @snicolet feel free to ask for a #703 revert :)

**Comment by mstembera** [comment]
@ppigazzini 
This issue has already existed before https://github.com/glinscott/fishtest/pull/703 and is unrelated.  Contempt=0 would have still been removed when rescheduling and the internal SF contempt of 24 used instead of the original 0.
