### ISSUE TITLE
Windows ASLR breaks Fishtest portable worker

### ISSUE THREAD

**Issue by nickolasreynolds** [glinscott/fishtest#706]
Followup to: [https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/jmMr0B6SZWY](https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/jmMr0B6SZWY).

On some Windows systems, if Address Space Layout Randomization (ASLR) is enabled, various components of the Fishtest portable worker no longer function.

Here is some information about my system, for which I had to disable all forms of ASLR: [https://i.imgur.com/YJbaSCR.png](https://i.imgur.com/YJbaSCR.png).

**Comment by ppigazzini** [comment]
@nickolasreynolds thanks to document this obscure problem :) 

On all my Windows 7-8-10 systems msys2 works fine with the default "Windows Security" settings:
- "Force randomization for images (Mandatory ASLR)": off
- "Randomize memory allocations (Bottom-up ASLR)": on

Please mind that "MSYS2 MSYS" shell builds POSIX applications using the Cygwin layer, so you need "MSYS2 MinGW 64-bit" shell to build a Windows native application using the wiki script. See the fixed wiki page.
