### ISSUE TITLE
Making the Windows Portable Worker installation instructions clearer

### ISSUE THREAD

**Issue by Ricoh06** [glinscott/fishtest#707]
Hi All,

So I setup the Windows portable worker the other day, and found some of the instructions I found to be confusing and not orderly. In particular the "windows-step-by-step-installation.txt" file located in \Fishtest-Worker-Portable\fishtest is outdated and contains unneccessary steps.

For example, anyone reading that file has already downloaded it doesn't need further info on where to get the sources, as they already have it. It also doesn't mention about deleting the "testing" folder located in \Fishtest-Worker-Portable\fishtest\worker which is mentioned on the wiki. It also suggests to download Python 2.7.3 rather than the latest (and final 2.7.x) version which is 2.7.18 which suggests the file hasn't been updated in a number of years. It also has no mention of a link to the Fishtest wiki page for further information, which would be useful.

These steps named in the file aren't orderly with the wiki, which currently has much better steps but still misses some information that was needed from the installation file (mainly regarding installing Python). I propose that the wiki gets an update to mention installing Python (and its contents updated at bottom of page where mentions 2.7.12) and updating the installation text file in the Fishtest-Worker-Portable.exe download. I couldn't see this on Fishtest so don't know how to create a pull request for it.

I have created an updated version of the file to propose as a base for the changes. The steps in the new version should allow someone to successfully setup the worker from that file alone and makes the process much clearer.

[windows-step-by-step-installation-proposednewversion.txt](https://github.com/glinscott/fishtest/files/4797726/windows-step-by-step-installation-proposednewversion.txt)

[windows-step-by-step-installation-oldversion.txt](https://github.com/glinscott/fishtest/files/4797724/windows-step-by-step-installation-oldversion.txt)

**Comment by ppigazzini** [comment]
@Ricoh06  Thank you for pushing me to finish the new windows worker setup :)
