### ISSUE TITLE
Optimize action storage

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#710]
I wondered why MongoDb actions database is so big. The reason is that it stores a copy of the complete run with all empty task slots included. 

We should remove all the task slots to safe space.

Needs a change of the fishtest code and a script to adapt the current database. This will significantly shrink the database.

**Comment by ppigazzini** [comment]
@tomtor we should compact the "actions" collection after the cleaning, see https://github.com/glinscott/fishtest/pull/643#issuecomment-619536873
