### ISSUE TITLE
Better sanity checking for spsa tests. Is it possible?

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#712]
Right now it seems to be perfectly possible to create an spsa tune which tunes nothing. I did this locally by forgetting to update the branch used for the test on github.

In principle the worker can know this since cutechess warns when it is instructed to set an option that does not exist. But how can the worker communicate this information to the server?

Of course forgetting to update the branch can happen with other types of tests as well. But for spsa it seems extra bad since it may lead to the mistaken belief that some parameters are optimal while they are not.

**Comment by tomtor** [comment]
It could act like it acts on a signature failure and stop the test:

https://github.com/glinscott/fishtest/blob/190a05b3d5e7cfaf1c27325f7faf041b84671201/worker/games.py#L86

**Comment by vdbergh** [comment]
> It could act like it acts on a signature failure and stop the test:
> 
> https://github.com/glinscott/fishtest/blob/190a05b3d5e7cfaf1c27325f7faf041b84671201/worker/games.py#L86

Thanks! Good idea. I will look into that.
