### ISSUE TITLE
Bench signature cutoff

### ISSUE THREAD

**Issue by Chess13234** [glinscott/fishtest#714]
The current script doesn't handle the full number which is Bench: 20101877
while fishtest displays: Bench: 2010187
https://tests.stockfishchess.org/tests/view/5ef32cb2122d6514328d7866
Test where bench signature is manually set are not affected:
https://tests.stockfishchess.org/tests/view/5ef3200c122d6514328d785a

**Comment by vondele** [comment]
yes, I think there is an issue in the code that parses the git commit messages, assuming the bench will be 6 digits only.
