### ISSUE TITLE
Separate pages for different test types

### ISSUE THREAD

**Issue by ghost** [glinscott/fishtest#716]
Perhaps there should be more types of pages for different test types?
1.Unapproved tests(see https://github.com/official-stockfish/Stockfish/issues/2771 they're mixed with pending tests)
2.Tuning tests( to easily see all tunings)
3.ELO difference tests(to separate them from normal tests)

**Comment by silversolver1** [comment]
Alternatively multiple show/hide buttons: "Pending Approval", "Approved", "Active". 

Currently "Pending Approval" and "Approved" (but not active) are both grouped into "Pending". Separating them would help address this problem

**Comment by tomtor** [comment]
> Currently "Pending Approval" and "Approved" (but not active) are both grouped into "Pending". Separating them would help address this problem.

I would like that too so reopening
