### ISSUE TITLE
SPSA issues?

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#721]
https://groups.google.com/g/fishcooking/c/_4Q5gmTeLDw

https://tests.stockfishchess.org/tests/view/5efb8d4d59f6f03532893ff3

Could it be related to the recent SPSA related worker changes?

How can we check?

**Comment by ppigazzini** [comment]
I re started the SPSA on DEV with some workers.
https://dfts-0.pigazzini.it/tests/view/5f01be162a2da05b61f077e1

**Comment by tomtor** [comment]
@ppigazzini Have you tested what happens after a server restart?

**Comment by ppigazzini** [comment]
@tomtor yes. The fishtest server is restarted after every git update, I just rebooted DEV without problems.

I viewed that the server was restarted, perhaps the OOM killer.
```
Jun 15 05:33:36 tests.stockfishchess.org systemd[1]: fishtest@6543.service: Main process exited, code=exited, status=1/FAILURE
Jun 15 05:33:36 tests.stockfishchess.org systemd[1]: fishtest@6543.service: Failed with result 'exit-code'.
```

**Comment by tomtor** [comment]
> Jun 15 05:33:36

@ppigazzini June?

**Comment by ppigazzini** [comment]
> > Jun 15 05:33:36
> 
> @ppigazzini June?

Ops, I missed the out of order dates in the log :(

```
Jul 04 10:10:33 tests.stockfishchess.org pserve[9338]:     response = view(request)
Jul 04 10:10:33 tests.stockfishchess.org pserve[9338]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 899, in tests
Jul 04 10:10:33 tests.stockfishchess.org pserve[9338]:     if int(request.params.get('page', 1)) > 1:
Jul 04 10:10:33 tests.stockfishchess.org pserve[9338]: ValueError: invalid literal for int() with base 10: "4'A=0"
Jun 12 14:17:39 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 12 14:17:42 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jun 12 14:17:42 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jun 12 14:20:29 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 12 14:20:31 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jun 12 14:20:31 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jun 12 14:22:24 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 12 14:22:25 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jun 12 14:22:25 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jun 12 14:32:43 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 12 14:32:45 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jun 12 14:32:45 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jun 12 21:24:32 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 12 21:24:36 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jun 12 21:24:36 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jun 14 15:38:38 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 14 15:38:40 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jun 14 15:38:40 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jun 15 05:33:03 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jun 15 05:33:36 tests.stockfishchess.org systemd[1]: fishtest@6543.service: Main process exited, code=exited, status=1/FAILURE
Jun 15 05:33:36 tests.stockfishchess.org systemd[1]: fishtest@6543.service: Failed with result 'exit-code'.
```

**Comment by vdbergh** [comment]
I am not sure if restarting the test will answer the question why the behavior of the parameters suddenly appeared to change. The history is here

https://tests.stockfishchess.org/tests/view/5efb8d4d59f6f03532893ff3/spsa_history

**Comment by ppigazzini** [comment]
@vdbergh there are also the wrong starting parameters values (should be zero).

The SPSA on DEV is fine either with master and the new #722
https://dfts-0.pigazzini.it/tests/view/5f01be162a2da05b61f077e1

#720 fixed a worker IndexError exception with an empty string from STDERR that I observed with my two pipes code and with #722 , strangely I never observed it with #713 . By the way I don't view how this exception could have messed up that SPSA run and only that SPSA run.

**Comment by vdbergh** [comment]
Here again something strange 

https://tests.stockfishchess.org/tests/view/5f1048080640035f9d297919

After 3900 games the initial part of the graph is suddenly cut off.

It happened after I invoked https://tests.stockfishchess.org/api/get_run/5f1048080640035f9d297919 but this should not have any effect on the graph.

**Comment by vdbergh** [comment]
This is the history. It appears to have been truncated. https://tests.stockfishchess.org/tests/view/5f1048080640035f9d297919/spsa_history

**Comment by vdbergh** [comment]
It seems to be reproducible. Invoking  https://tests.stockfishchess.org/api/get_run/5f1048080640035f9d297919  truncates the spsa history.

**Comment by tomtor** [comment]
Did you forget to commit your changes in
https://tests.stockfishchess.org/tests/view/5f1048080640035f9d297919

It is identical to master? Prio set to -1

Op do 16 jul. 2020 16:59 schreef vdbergh <notifications@github.com>:

**Comment by tomtor** [comment]
It does indeed truncate the history, weird.

Op do 16 jul. 2020 16:59 schreef vdbergh <notifications@github.com>:

**Comment by tomtor** [comment]
https://github.com/glinscott/fishtest/blob/261d0874fb41b19cbc4ba7b7c51094b87b6030c2/fishtest/fishtest/api.py#L17

Should be a deep_copy!?

Op do 16 jul. 2020 21:56 schreef Tom Vijlbrief <tvijlbrief@gmail.com>:

**Comment by vdbergh** [comment]
Hmm I wonder why fc6291006 did not kick in....

**Comment by vdbergh** [comment]
> https://github.com/glinscott/fishtest/blob/261d0874fb41b19cbc4ba7b7c51094b87b6030c2/fishtest/fishtest/api.py#L17 Should be a deep_copy!? Op do 16 jul. 2020 21:56 schreef Tom Vijlbrief <tvijlbrief@gmail.com>:
> […](#)

I think so....

**Comment by tomtor** [comment]
> Hmm I wonder why [fc62910](https://github.com/glinscott/fishtest/commit/fc6291006f4ee315f5844b7448806d235a15d7d3) did not kick in....

Because the worker has not been force pushed yet? @ppigazzini

**Comment by tomtor** [comment]
> > Hmm I wonder why [fc62910](https://github.com/glinscott/fishtest/commit/fc6291006f4ee315f5844b7448806d235a15d7d3) did not kick in....
> 
> Because the worker has not been force pushed yet? @ppigazzini

I updated one of my workers to master now...

@ppigazzini when will we increase the worker version?

**Comment by ppigazzini** [comment]
> > > Hmm I wonder why [fc62910](https://github.com/glinscott/fishtest/commit/fc6291006f4ee315f5844b7448806d235a15d7d3) did not kick in....
> > 
> > 
> > Because the worker has not been force pushed yet? @ppigazzini
> 
> I updated one of my workers to master now...
> 
> @ppigazzini when will we increase the worker version?

https://github.com/glinscott/fishtest/commit/fc6291006f4ee315f5844b7448806d235a15d7d3 works only with linux workers, #722 solves the problem but I'm waiting a review of the PR before force a worker updated.
