### ISSUE TITLE
Wrong bench

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#729]
I saw there are some weird wrong bench errors across multiple tests related to current master.

```
stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4487388
stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4490660
stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4407953
stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4104589
stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4488898
stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4178177
```

I have done these:
Remove all cached compiles
Redeploy fishtest worker
Check GCC & kernel version
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
3.10.0-1127.13.1.el7.x86_64

The binaries on some workers appeared to have different MD5 than others(now I removed all caches again and they are the same). But I already did this earlier.

So... either a GCC bug or worker downloaded the wrong code?

**Comment by ppigazzini** [comment]
@noobpwnftw PGO (`make profile-build` uses now a bench with fixed depth) is "nearly" deterministic wrt the binary code generated, so some different MD5 should be expected.
@vondele any idea?

**Comment by vondele** [comment]
No idea, the code bench should be deterministic also with PGO. (MD5 of binaries might be non-deterministic because the compile date is included (misc.cpp)).

**Comment by tomtor** [comment]
Note that "modify" followed by a "stop" for https://tests.stockfishchess.org/tests/view/5f16a86bc09435d870cb9b51
shows a new

`stop run: Wrong bench in stockfish_d89730d5c8dcf10eb9e1d91a81f903d9fc3c949a Expected: 4578298 Got: 4487388`

in `actions` but that is just the original error message.

@MJZ1977 Is it OK to "delete" this failed test?

**Comment by Vizvezdenec** [comment]
it seems to still be the case sometimes...

**Comment by tomtor** [comment]
Something strange that I noticed earlier two days ago, my 14 thread worker now hangs having worked on https://tests.stockfishchess.org/tests/view/5f188d88c09435d870cb9c0a
```
Score of New-c516bacaa6 vs Base-c516bacaa6: 1 - 3 - 24  [0.464] 28
  Task updated successfully in 0.765014s
Elo difference: -24.9 +/- 48.3, LOS: 15.9 %, DrawRatio: 85.7 %
Finished match
Finished match cleanly
```

pstree:
```
        |-sshd---sshd---sshd---bash---python3-+-cutechess-cli
        |                                     `-{python3}
```

I wonder if it is related...

**Comment by noobpwnftw** [comment]
I still believe the most likely cause is an hardware failure on one of my workers, however, it did compile binaries correctly and it did not cause any segfault system-wide(which is very strange). I collected a few logs from that machine, it successfully ran multiple bench, just with random node count....
Then I prevented it from running any tests since yesterday, now let's wait and see if there is any further similar case from others.

**Comment by noobpwnftw** [comment]
Guess what?
1) I went through the repo commit by commit, for the last 100 commits, all of them produced random bench on this machine.
2) I compared the compiled binaries with those produced on another machine, they are identical.
3) I ran a few old compiles/abrok on the suspected machine, they produce correct bench every single time.
4) I compared the installed GCC version again(including rpm -Va), they are correct(devtoolset-9).
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-9/root/usr --mandir=/opt/rh/devtoolset-9/root/usr/share/man --infodir=/opt/rh/devtoolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.3.1-20200408/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
```
5) CPU info for this machine is as follows:
```
[root@199 src]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
stepping        : 9
microcode       : 0xd6
cpu MHz         : 3999.902
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch invpcid_single intel_pt ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear spec_ctrl intel_stibp flush_l1d
bogomips        : 7200.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```
6) Compiling the code with devtoolset-7 and they work without any problem.
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
```

What do you think?

**Comment by vondele** [comment]
@noobpwnftw still strange... if you have a statically linked devtoolset-9 binary compiled on a 'good' machine, does it yield a good bench, and the other way around (i.e. statically linked on the 'bad' machine, moved to a good worker)? If a static linked binary yields different results on one machine or another, presumably the software stack is not the cause (did you rpm -v all software on the machine, or just gcc?). If it is hardware.... it could be triggered by a sequence of instructions emitted by gcc-9 and not gcc-7... but that would be rather peculiar.

**Comment by noobpwnftw** [comment]
@vondele The compiled binaries on good and bad machines are identical, I have 15 such machines, looks like only one of them is bad. I did system-wide "rpm -Va"(see point 4 above), all installed packages have correct files. I particularly do not understand is that the failure rate is like 2 out of 3, if it is an hardware failure then it would almost certainly crash something else, but it isn't. Just GCC9 compiled stuff doesn't work, nothing else seems to break. I also tried "modern" compiles, they too produce error under GCC9 but not GCC7 on this bad machine. I can send you the logins for you to take a look?

**Comment by vondele** [comment]
@noobpwnftw I'm happy to have a look at logs, but I guess with small chances I see anything. Compiled binaries are identical, but also all dynamically linked libraries (that's why I asked for static)?

Also interesting the failure rate is on 2/3. So, random results for the same binary..... I've seen something like that happen before, when the binary had something conditional on the alignment of malloc'ed memory, with a value larger than the malloc guaranteed number.

**Comment by noobpwnftw** [comment]
@vondele I meant the login information for you to connect to the machine. Yes I have checked all dynamic libraries(via rpm -Va it checks MD5 on all packages).

**Comment by vondele** [comment]
@noobpwnftw you can send me login info on my email address you find in git log. I'll try to reproduce it. I won't spent too much time on it as I want to make some progress on NNUE.

**Comment by noobpwnftw** [comment]
Some exotic hardware failure, issue solved.
