### ISSUE TITLE
Changing test type with test options

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#741]
When rescheduling a test with non-default options, these options are copied. However, when changing the test type (e.g. STC -> LTC), these options are reset to default. This is something which will bite us after the NNUE merge, since `Use NNUE=true` or `Use NNUE=false` will be more commonly changed. Maybe we can make the buttons that change the test type a little smarter (i.e. only change those options that match need to change)

**Comment by tomtor** [comment]
I will add that to my NN fixups PR

**Comment by tomtor** [comment]
See also #704 (duplicate)

**Comment by tomtor** [comment]
Fixed with #742
