### ISSUE TITLE
tickbox for the net upload page

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#744]
We might need a tick box saying
'I am the author of this net, or have obtained it (explicitly) with a CC0 license'
before one can click submit.

See also https://github.com/gogamoga1/Stockfish/commit/0e4243577cee7e214e59a70b6ddf0e94ebc8b008#commitcomment-41269863

**Comment by gekkehenker** [comment]
> @gekkehenker the upload page already mentions that.... but yes, we might need a tick box.
> (Edit: issue [glinscott/fishtest#744](https://github.com/glinscott/fishtest/issues/744))


It does, but the big blue upload button isn't in center with the text. So your focus is naturally drawn away from the text.
https://i.imgur.com/RLHjfsL.png

I think this would already be an improvement:

https://i.imgur.com/ydJsIpc.png

And an extra box to tick can't harm.

**Comment by silversolver1** [comment]
on a somewhat related note, it appears as though yet another one of SV's nets has been uploaded in the interim.

20200808-0049.bin uploaded as nn-5570a3425229.nnue. checked using hxim's nnue tool

**Comment by vondele** [comment]
Really annoying. 
@tomtor if you have a chance to implement a tickbox, would be much appreciated.

**Comment by vondele** [comment]
I've also written the uploader on his personal mail address.

**Comment by tomtor** [comment]
@vondele See #748

**Comment by tomtor** [comment]
Fixed

**Comment by vondele** [comment]
@tomtor many thanks!

**Comment by vondele** [comment]
So, same user uploaded again one of @sergiovieri nets, I have now blocked him. But obviously, if people are willingly infringing copyrights it gets harder to stop them.

![image](https://user-images.githubusercontent.com/4202567/90018525-54e57c00-dcad-11ea-94dd-e5d7537e6c60.png)

**Comment by vondele** [comment]
@Vizvezdenec see above

**Comment by tomtor** [comment]
@vondele @ppigazzini Removed the illegal uploads and the double entry on prod
