### ISSUE TITLE
Question/issue about SPRT.

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#746]
With NNUE introduction and simultaneous removal of contempt draw rate increased by like 10% of LTC and STC on fishtest.
I tried to play with it on SPRT calculator and was surprised that actually increase of draw rate drastically decreases needed number of games to pass/fail for patch.
And I indeed can witness this behavior on fishtest now with a lot of tests converging in no time.
Is this an intended behavior? I always thought that lower draw rate is better for tests for them to pass faster.
@vdbergh can you answer pls if this is how this should work?

**Comment by vondele** [comment]
that's actually correct, high draw rate leads to fewer needed games.

Right now, we might be having other reasons as well for the fast passing of tests :-)

**Comment by sf-x** [comment]
>I always thought that lower draw rate is better for tests for them to pass faster.

If the strength difference is the same, then high draw rate is better. But changing opening position set changes the strength difference, too, not only draw rate.

**Comment by vdbergh** [comment]
Yes. All replies are correct....

**Comment by Vizvezdenec** [comment]
Okay, I see.
Probably addition of contempt is also good for tests because we do decrease draw rate but we also increase elo diff of each patch.
Now it's much more clear for me, thx for your replies!
