### ISSUE TITLE
possible server issue?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#751]
https://groups.google.com/g/fishcooking/c/mIcaW7daom8/m/RlcwnACdBQAJ

also worker count indeed low.

**Comment by tomtor** [comment]
https://tests.stockfishchess.org/tests/view/5f32061a90816720665375a4 has no params causing a / 0

**Comment by vondele** [comment]
thanks, I'll leave a note there. We might have to protect against that server side.
