### ISSUE TITLE
Net downloads not cached

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#753]
Investigating download link:
https://data.stockfishchess.org/nn/nn-112bb1c8cdb5.nnue
It says:
cf-cache-status: DYNAMIC
which indicates that the content is not cached and will not be.

**Comment by vondele** [comment]
@daylen ?

**Comment by noobpwnftw** [comment]
As a quick workaround I enabled GZIP on the file server so that egress bandwidth is reduced.
https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN#h_51422705-42d0-450d-8eb1-5321dcadb5bc

According to this, it should, as we do have an "Expires" header present and set to now plus 30 days.

**Comment by daylen** [comment]
Looking into this now.

**Comment by daylen** [comment]
Apologies for the incorrect configuration earlier. This should be fixed now! (I set up a Page Rule for `data.stockfishchess.org/*` to "Cache Everything")

Tested:
`curl -v -X GET https://data.stockfishchess.org/nn/nn-112bb1c8cdb5.nnue --output /tmp/blah.nnue`

Output:
`< cf-cache-status: HIT`

**Comment by vondele** [comment]
thanks, HIT here as well ...

**Comment by noobpwnftw** [comment]
@daylen Thanks! Problem solved.

**Comment by vondele** [comment]
@daylen thanks for the quick fix!
