### ISSUE TITLE
net server having trouble?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#754]
@noobpwnftw @tomtor looks like the downloads of nets is problematic right now. CI is failling and the counter is increasing by a few downloads a second.... do we have an idea what could be causing this?

**Comment by vondele** [comment]
also https://github.com/glinscott/fishtest/issues/753 

however, how come we have so many downloads?

**Comment by noobpwnftw** [comment]
It is due to "make net".

**Comment by vondele** [comment]
probably, but 10s of people doing that at the same time? Rather not.

But possibly we have an issue where the workers that fail to download get the same test again, and try to download again. So, probably we have to enforce the worker upgrade now to get this stopped?

**Comment by vondele** [comment]
or have you just started the large fleet... in that case it is possible.

**Comment by noobpwnftw** [comment]
I just launched 2000 workers and it will be smoothed out when they made their cached compiles.

**Comment by noobpwnftw** [comment]
But Cloudflare not caching nets is something needs to be fixed.

**Comment by vondele** [comment]
will cloudflare cache between the data server and your workers? I had assumed that would be 'internal'

**Comment by noobpwnftw** [comment]
Workers still download from public URL, which relies on it having cache. I can run my own cache but public downloads still needs to be cached.

**Comment by vondele** [comment]
yes, I agree with the later statement. But let's deal with that in the other issue. At least the sudden surge in downloads is understood.
