### ISSUE TITLE
double net uploads

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#756]
![image](https://user-images.githubusercontent.com/4202567/90035509-2c1bb180-dcc2-11ea-9e09-91f187990985.png)

seems like the same net can be uploaded twice, or at least is displayed twice

**Comment by ppigazzini** [comment]
Trying to upload twice the same net on DEV results in a "Network already exists" error message, either with the same account or a new one.

**Comment by tomtor** [comment]
Weird. It would help if sergiovieri could tell if he encountered strange behaviour from fishtest.

It looks as if the first upload was not visible for a while in MongoDb. Perhaps related to multiple fishtest servers, but there is no caching so that should not be an issue.

**Comment by vondele** [comment]
@sergiovieri did you see anything special when uploading the net. Also, did you indeed do the second upload roughly 10min later than the first one?

**Comment by noobpwnftw** [comment]
It can be explained by the MongoDB entry is added only after transferring the net to the file server, during which another upload is possible and will produce duplicated records.

**Comment by tomtor** [comment]
> It can be explained by the MongoDB entry is added only after transferring the net to the file server, during which another upload is possible and will produce duplicated records.

Yes, that's probably the issue. I didn't want to give a possitive feedback to the user untill the network was really transfered. Transfer normally takes just a few seconds, but the code indeed has a race condition.

**Comment by noobpwnftw** [comment]
So we could just remove duplicated entries when it happens as it doesn't seem to break anything?

**Comment by vondele** [comment]
unless two ongoing transfers of the same file corrupt the end result?

**Comment by noobpwnftw** [comment]
It cannot happen, any transfer has to complete successfully before the actual file is moved to the destination location where public download is reading from, before that, it's 404(for file not found or file being locked for writing).

**Comment by sergiovieri** [comment]
First I tried to upload the net, but I got an error, I think it's 504. A few mins later, I saw the net isn't on NN stats yet, so I uploaded the net again.
