### ISSUE TITLE
feature suggestion for net stats page

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#758]
I realized that it would be possible to implement a feature for the net stats page that is often requested, and that would help us with the illegal uploads. Basically, every uploaded net gets a 'status' field in the database as well which can be 'untested', 'tested', 'recommended' (or 'default'). The stats page shows that status next to the net. 

Benefits: 
* Together with the date, the status would be an indication what the strongest net is ('recommended' of latest date). 
* If 'untested' nets would not be shown to users not logged in, the incentive to upload illegally (and without testing) would be small, since nobody would see the upload. Logged in users would still be able to see the needed info (and act if e.g. downloads are misbehaving). If an illegal upload would be tested, the approver could step in, and furthermore we have the github handle of the illegal uploader (in addition to the email), which would help in case we need to take action.

What I realized is that the implementation should be quite doable. Basically, for every test submitted, we check the resolved repo and download the ucioptions.cpp of that repo, extracting the net as we do in the worker. If that resolved repo is equivalent to official-stockfish/master, it can be marked as 'default', otherwise we can switch to 'tested' from 'untested'

I won't be able to implement this myself easily (since I don't know the server code), but am happy to help.

**Comment by tomtor** [comment]
We could persist as `last_test` attribute the id of each new test in the nn database with the corresponding net. Or would you (also?) like to preserve the first test?

**Comment by vondele** [comment]
interesting, yes, this would make it possible to link to the test. first_test and last_test could be interesting. I think first is maybe more interesting than last, since first will be the actual test of the net against the previous one, but both have a use. The additional columns could just display the date, where a click on the date jumps to the test page.

**Comment by vondele** [comment]
this feature has been merged, thanks @tomtor.
