### ISSUE TITLE
'choco' is not recognized as ....

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#767]
Maybe an issue with the installer?

'choco' is not recognized as an internal or external command, operable program or batch file.

https://groups.google.com/g/fishcooking/c/r34uszLwVPY/m/maZ1RCBvBgAJ

**Comment by ppigazzini** [comment]
The user didn't answer in the forum, not easy to understand what was wrong.

**Comment by vondele** [comment]
we can close and reopen as needed.
