### ISSUE TITLE
Include net used in each test

### ISSUE THREAD

**Issue by crossbr** [glinscott/fishtest#770]
Right now it is difficult to determine which net was used in a test, especially for tests that take place around the time a new net is adopted. It would be helpful to include in the "Details" of each test the net used by base and by the tested patch. Thanks!

**Comment by tomtor** [comment]
That should be easy to add to fishtest.

The data is already retrieved by the server (for updating the "NN-Stats" page), we just need to add it to the stored test data and view.

**Comment by tomtor** [comment]
@vondele I will create a PR the next few days if you think this is a good feature.

**Comment by vondele** [comment]
yes, why not. In principle this can be found by looking at the branch of the test, but I agree it is an easy addition.

**Comment by tomtor** [comment]
Implemented with #771
