### ISSUE TITLE
"Task requested in 0.474s No tasks available at this time, waiting..." What does it mean?

### ISSUE THREAD

**Issue by EterCyber** [glinscott/fishtest#784]
I get the following error message:

Fetch task...
Exception fetching rate_limit:
('Connection aborted.', error(10054, ''))
Worker version checked successfully in 0.714s
Task requested in 0.474s
No tasks available at this time, waiting...

Fetch task...
Exception fetching rate_limit:
('Connection aborted.', error(10054, ''))
Worker version checked successfully in 0.421s
Task requested in 0.409s
No tasks available at this time, waiting...

I don't know what went wrong.

**Comment by vondele** [comment]
Exception fetching rate_limit: 

seems like you can not connect to github with your worker? Can you access this link from the worker: 
https://api.github.com/rate_limit

**Comment by EterCyber** [comment]
Yes, I changed the get_rate() function, but it still doesn't work, and I get the following error message:

Fetch task...
API call rate limits: {u'reset': 1599217876, u'used': 0, u'limit': 60, u'remaining': 60}
Worker version checked successfully in 0.967s
Task requested in 0.579s
No tasks available at this time, waiting...

Fetch task...
API call rate limits: {u'reset': 1599217903, u'used': 0, u'limit': 60, u'remaining': 60}
Worker version checked successfully in 0.645s
Task requested in 1.534s
No tasks available at this time, waiting...

Fetch task...
API call rate limits: {u'reset': 1599217922, u'used': 0, u'limit': 60, u'remaining': 60}
Worker version checked successfully in 0.908s
Task requested in 0.597s
No tasks available at this time, waiting...

...

Fetch task...
Exception fetching rate_limit:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /rate_limit (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004B06EF0>: Failed to establish a new connection: [Errno 10061] ',))
Worker version checked successfully in 0.685s
Task requested in 0.525s
No tasks available at this time, waiting...

**Comment by vondele** [comment]
surprising, obviously there are tasks pending. Do you use any of the options when starting the worker (--min_threads or --max_memory or --concurrency or ...) and if so what's the value?

**Comment by ppigazzini** [comment]
@EterCyber I'm wondering if you have started and stopped the worker some times before the error popped out.

**Comment by EterCyber** [comment]
Below is my configuration, should be the default configuration:
concurrency = 2
max_memory = 2031
min_threads = 1

**Comment by EterCyber** [comment]
@ppigazzini I tried to start worker for many times, but there was still a problem. The error message posted was a complete run.

**Comment by tomtor** [comment]
Issue not recently reproduced
