### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#790]
I seem to get
Exception accessing host:
with no more info

**Comment by vondele** [comment]
```
# curl https://tests.stockfishchess.org/api/request_version
Internal Server Error

The server encountered an unexpected internal server error

```

**Comment by tomtor** [comment]
Site is ok now?

`request_version` requires authentication, which causes the error.

**Comment by vondele** [comment]
Ok. Indeed the server now works. 

It was noob who ran the fleet which did fail to run properly. During that time the website appeared OK, but the workers returned 'no task available', when I connected my worker I got the 'Exception accessing host:'. The curl thing was my (failed) attempt to debug.

**Comment by tomtor** [comment]
Server had a reboot around the time of trouble:

`reboot   system boot  4.15.0           Mon Sep 14 15:58   still running`

Probably a transient provider issue, so I will close this.
