### ISSUE TITLE
Scheduling issue

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#792]
There are exactly 500x fleet workers, however, a lot of them got "no task" response.
This problem only appears whenever there is SPSA and also worker have a chance failing API requests(either to fishtest or github), after they fail, their task "slot" stays and will not get rescheduled until probably an hour later as the script clears them.

**Comment by noobpwnftw** [comment]
This however does not appear to be a problem when there is no SPSA running.

**Comment by vondele** [comment]
let me do a test and set all SPSA to -1 priority. See if this fixes things.

**Comment by vondele** [comment]
@noobpwnftw no SPSA jobs should be running right now.

**Comment by noobpwnftw** [comment]
As you can see more workers appear(although old ones are still stale, and total NPS gets larger indicating workers picked up their task).

**Comment by noobpwnftw** [comment]
I'll double fleet workers and see if the observation holds. If so, then you can restart SPSA and see if it get stuck again.

**Comment by vondele** [comment]
one interesting point, even though I stopped and set priority to -1, some of the SPSA runs are in active state 'spontaneously'.

**Comment by vondele** [comment]
I have now switch 4 SPSA runs to prio 0, see what happens. I can also put a test to prio 1.

**Comment by noobpwnftw** [comment]
If you put SPSA on prio 1, I think all other tests will gradually lose workers and only one SPSA will remain active, with only some hundred cores active :)

**Comment by vondele** [comment]
There is some special handling of SPSA runs:
https://github.com/glinscott/fishtest/blob/41723fc7b6a7f9f5b13caadbdf60c6374a54e90f/fishtest/fishtest/rundb.py#L588-L596
maybe the logic is buggy, blocking all tasks as soon as one SPSA run has reached its limit?

**Comment by vondele** [comment]
should that break be a continue instead? @tomtor ?

**Comment by ppigazzini** [comment]
@vondele that "break" is suspect... I replaced it with a "continue" on PROD by hand, feel free to make some tests.

**Comment by vondele** [comment]
that's maybe a little adventurous, I don't know the code well enough. Now that it has been done, let me again put prio back to 0 for these tests.

**Comment by ppigazzini** [comment]
@vondele already reverted, after a second reading the "break" seems fine.

**Comment by vondele** [comment]
Also, it looks like this limit should not be reached easily. The largest tune has 28 params (if I looked correctly), which would limit the cores for that test to ~7500, and we're not near.

**Comment by FauziAkram** [comment]
The largest tune that i currently have, has 56 parameters to be correct

**Comment by vondele** [comment]
OK, that would be still 5300 cores max.

**Comment by tomtor** [comment]
When a fresh worker hits the API github limit, it will never get a task which needs access to github for compiling.
When it has no old cached jobs it will indeed sit idle by design. We could ignore the github limit for fresh workers, but that would cause other issues?

**Comment by vondele** [comment]
@noobpwnftw said in discord that the workers use the token and were not hitting the limit.

**Comment by ppigazzini** [comment]
I'm trying to trigger the SPSA related problem on DEV, no success at the moment stopping/starting nginx or fishtest.

**Comment by noobpwnftw** [comment]
It's even happening now:
170 active, if you launch a new test, hidden workers may appear...

**Comment by vondele** [comment]
seems this is happening again. I've stopped and prio -1 SPSA jobs.

**Comment by vondele** [comment]
maybe an interesting point, two of those stopped, prio -1 jobs, somehow got back with (a few) workers assigned. I wonder if there is something wrong in the database.

**Comment by vondele** [comment]
https://tests.stockfishchess.org/tests/view/5f70ca403b22d6afa506939f
https://tests.stockfishchess.org/tests/view/5f7085963b22d6afa50692ee

**Comment by noobpwnftw** [comment]
Maybe there is no bug, it is just that server is too busy and unable to sustain load.

**Comment by vondele** [comment]
but in that case the error message could be improved (i.e. no task because of timeout).

**Comment by noobpwnftw** [comment]
Well, looking at the code, it has "multi-tasking", there is one path that gathers available tasks, then the rest read from there, I can see when gathering is slow, then it might not see tasks available.

**Comment by vondele** [comment]
actually, if you say server overloaded, and that in that case 'no available tasks' can be the cause, maybe it is obvious that the small batch size of SPSA is the problem. Time to increase that batch size... ? 

@vdbergh do you agree that one can increase the SPSA batch size pretty significantly without significant accuracy impact ?
Maybe something like
```diff
diff --git a/worker/games.py b/worker/games.py
index 546086d..229201b 100644
--- a/worker/games.py
+++ b/worker/games.py
@@ -1000,13 +1000,13 @@ def run_games(worker_info, password, remote, run, task_id):
 
     while games_remaining > 0:
         if spsa_tuning:
-            games_to_play = min(games_concurrency * 2, games_remaining)
+            games_to_play = min(games_concurrency * 32, games_remaining)
             pgnout = []
         else:
             games_to_play = games_remaining
             pgnout = ["-pgnout", pgn_name]
 
-        batch_size = games_concurrency * 2  # update frequency
+        batch_size = games_concurrency * 32  # update frequency
 
         if "sprt" in run["args"]:
             batch_size = 2 * run["args"]["sprt"].get("batch_size", 1)
```

**Comment by ppigazzini** [comment]
@vondele @noobpwnftw with 2152 machines 17083 cores the busy `pserve `oscillates between 30%-100% CPU load

```
top - 20:17:03 up 2 days,  4:48,  2 users,  load average: 1.38, 1.49, 1.48
Tasks:  31 total,   2 running,  29 sleeping,   0 stopped,   0 zombie
%Cpu0  :  23.3/1.0    24[||||||||||||||||||||||||                                                                            ]
%Cpu1  :  35.3/1.7    37[|||||||||||||||||||||||||||||||||||||                                                               ]
%Cpu2  :  16.3/0.3    17[||||||||||||||||                                                                                    ]
%Cpu3  :  30.2/1.0    31[|||||||||||||||||||||||||||||||                                                                     ]
KiB Mem : 77.3/5242880  [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                       ]
KiB Swap:  0.0/0        [                                                                                                    ]

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20      224808   2520   1204 S        0.0   0:01.58 init -z
   75 root      20      121160   7700   5464 S        0.1   0:13.20  `- /lib/systemd/systemd-journald
  183 root      20       42092    532        S        0.0   0:00.20  `- /lib/systemd/systemd-udevd
  185 systemd+  20       71872     56        S        0.0   0:00.29  `- /lib/systemd/systemd-networkd
  198 message+  20       47620    536        S        0.0   0:00.09  `- /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  199 root      20       62132   1016    352 S        0.0   0:00.34  `- /lib/systemd/systemd-logind
  202 syslog    20      189016    668        S        0.0   0:00.67  `- /usr/sbin/rsyslogd -n
  210 root      20       28344    888    616 S        0.0   0:00.67  `- /usr/sbin/cron -f
  324 mongodb   20     3747560 2.137g   3220 S   6.0 42.7 197:45.81  `- /usr/bin/mongod --config /etc/mongod.conf
  327 fishtest  20     2295348 1.246g   5500 S 101.3 24.9 782:10.44  `- /home/fishtest/fishtest/fishtest/env/bin/python3 /home/fishtest/fishtest/fishtest/env/bin/pserve production.ini http_port=6543
  331 root      20      184292   8600    664 S        0.2   0:00.11  `- /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
  333 fishtest  20     1271544 458940   4644 S   1.0  8.8  49:03.37  `- /home/fishtest/fishtest/fishtest/env/bin/python3 /home/fishtest/fishtest/fishtest/env/bin/pserve production.ini http_port=6544
  391 root      20       72292   1364    616 S        0.0   0:00.49  `- /usr/sbin/sshd -D
17911 root      20       97184   1540    600 S        0.0   0:00.02      `- sshd: fishtest [priv]
17923 fishtest  20       97184    940        S        0.0   0:00.04          `- sshd: fishtest@pts/1
17924 fishtest  20       21432   1660        S        0.0   0:00.09              `- -bash
10706 root      20       97184   6016   5072 S        0.1   0:00.02      `- sshd: fishtest [priv]
10724 fishtest  20       97184   3204   2260 S        0.1                    `- sshd: fishtest@pts/0
10725 fishtest  20       19528   3244   1864 S        0.1   0:00.03              `- -bash
10819 fishtest  20       36752   2732   2296 R   0.3  0.1   0:00.14                  `- top
  584 root      20       24176    828    572 S        0.0            `- /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive -inetd_compat -inetd_ipv6
  593 Debian-+  20       59184   1380    636 S        0.0   0:00.25  `- /usr/sbin/exim4 -bd -q30m
  595 root      20      100968   1604    556 S        0.0            `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  596 root      20      100968   1048        S        0.0                `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  598 root      20      142260   1624        S        0.0            `- nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
  599 www-data  20      146964   9148   2776 R   3.3  0.2  36:55.31      `- nginx: worker process
  600 www-data  20      143576   4164   1512 S        0.1   0:23.21      `- nginx: worker process
  601 www-data  20      143524   4588   2276 S        0.1   0:00.12      `- nginx: worker process
  602 www-data  20      143064   3904   1860 S        0.1   0:00.02      `- nginx: worker process
 9479 root      20       13008    532    396 S        0.0            `- /sbin/agetty -o -p -- \u --noclear tty2 linux
 9481 root      20       13008    512    380 S        0.0            `- /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux

```

**Comment by vondele** [comment]
yes, but without SPSA tests however.

**Comment by noobpwnftw** [comment]
It is getting 502 timeouts occasionally after multicore and LTC tests finish, looks pretty much consistent with the behavior. When SPSA is running, it would be slower.

**Comment by vdbergh** [comment]
@vondele Yes I believe you are correct. The way SPSA is implemented in fishtest, the batch size doesn't matter (within reason).

**Comment by ppigazzini** [comment]
@vondele PROD has been running since last night with the new python 3.8.6 (that seems to use 2/3 of memory wrt the previous releases 3.6.9 and 3.8.5), with a new waitress configuration that save memory, with the mongodb cache raised to 2.25GB (from 1GB).

**Comment by tomtor** [comment]
#810 should fix this
