### ISSUE TITLE
Load average too high - VPS shutdown

### ISSUE THREAD

**Issue by glinscott** [glinscott/fishtest#799]
The VPS shut down the machine for violating the "fair share resource usage", which is not super clear to me.  I'm following up to ask what that means.  The load looks reasonable:
![image](https://user-images.githubusercontent.com/554932/94944423-18a0f180-048e-11eb-8a24-c86e820b3636.png)

It just might be that the VPS provider is not comfortable with this load pattern any more.

**Comment by ppigazzini** [comment]
@glinscott thank you for sharing. After the update to python 3.8.6 the CPU/memory load was even lower than usual :(

**Comment by glinscott** [comment]
I suspect the hourly spikes may be the source of their issues, can we spread the load of those out perhaps?

**Comment by glinscott** [comment]
Perhaps we could use cpulimit or cgroups to avoid spiking the cpu usage?  https://scoutapm.com/blog/restricting-process-cpu-usage-using-nice-cpulimit-and-cgroups

**Comment by ppigazzini** [comment]
@glinscott yes, I could restore the cpulimit tricks already used some months ago.
Anyway the backup.sh is using only one threads except for the s3 upload (10 seconds long):
https://github.com/glinscott/fishtest/blob/2ee43c82d63ce9d19838fe9bd493c2cbe76dbb1f/fishtest/utils/backup.sh#L19

**Comment by glinscott** [comment]
Can we disable the hourly backup?  Perhaps change it to daily for now?

**Comment by ppigazzini** [comment]
Sure

**Comment by glinscott** [comment]
Awesome, thanks!  Hopefully I hear back soon from them.

**Comment by ppigazzini** [comment]
fishtest is pretty stable now (finger crossed...)

**Comment by glinscott** [comment]
Just in case, is there e a backup of the server state?  Worst case is they terminate the VPS, without the ability to restart it.

**Comment by ppigazzini** [comment]
Yes, already up and running with the latest backup loaded.
https://dfts-0.pigazzini.it/tests
Unfortunately same provider, but bigger VPS (I pay €21.35/month).

**Comment by ppigazzini** [comment]
@glinscott with the server setup script we can build a new server in 30 minutes with a new provider
https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup

**Comment by glinscott** [comment]
Wow, that's great!  Ok, I'll update the thread when I hear back.

**Comment by ppigazzini** [comment]
@glinscott fishtest up and running, I scheduled the backup to run daily.

**Comment by glinscott** [comment]
Looks like much lower peaks, thanks!  I didn't hear anything back, so fingers crossed they are happy...

![image](https://user-images.githubusercontent.com/554932/95027204-9a8a4980-064b-11eb-9450-c456b4b7691f.png)

**Comment by ppigazzini** [comment]
@glinscott scheduled every 6 hours.

**Comment by tomtor** [comment]
> scheduled every 6 hours.

@ppigazzini It is now running at 6,12,18 but not at midnight. `*/6` should be `0-23/6`

**Comment by tomtor** [comment]
@ppigazzini Please ignore previous message, I somehow missed some mutt entries....

**Comment by tomtor** [comment]
@ppigazzini Weird, when I do:

```egrep 'scavenge.py$|Date' /var/spool/mail/fishtest```

Missing eg

```11 Oct 2020 09:45/50/55```

I get:

```
Date: Sun, 11 Oct 2020 09:01:16 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 09:15:12 +0000
Date: Sun, 11 Oct 2020 09:16:16 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 09:20:12 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 09:25:11 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 09:30:13 +0000
Date: Sun, 11 Oct 2020 09:31:15 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 09:35:12 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 09:40:12 +0000
Date: Sun, 11 Oct 2020 09:46:16 +0000
Date: Sun, 11 Oct 2020 10:01:16 +0000
Date: Sun, 11 Oct 2020 10:16:16 +0000
Date: Sun, 11 Oct 2020 10:31:15 +0000
Date: Sun, 11 Oct 2020 10:46:16 +0000
Date: Sun, 11 Oct 2020 11:01:15 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 11:15:12 +0000
Date: Sun, 11 Oct 2020 11:16:16 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 11:30:13 +0000
Date: Sun, 11 Oct 2020 11:31:17 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 11:35:13 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 11:45:10 +0000
Date: Sun, 11 Oct 2020 11:46:16 +0000
Date: Sun, 11 Oct 2020 12:01:15 +0000
Date: Sun, 11 Oct 2020 12:12:06 +0000
Date: Sun, 11 Oct 2020 12:16:17 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 12:20:14 +0000
Subject: Cron <fishtest@tests> ${VENV}/bin/python3 ${UPATH}/scavenge.py
Date: Sun, 11 Oct 2020 12:30:14 +0000
Date: Sun, 11 Oct 2020 12:31:15 +0000
Date: Sun, 11 Oct 2020 12:46:16 +0000
```

So we miss entries in the mail, only `delta_update_users.py` are all present?

**Comment by ppigazzini** [comment]
@tomtor I check very rarely the emails, but I always viewed an irregular pattern.
