### ISSUE TITLE
worker FAIL on Core2 DUO

### ISSUE THREAD

**Issue by q-l-p** [glinscott/fishtest#80]
Platform: Windows 7 64-bit (Core2 DUO 4GB)
I have followed very carefully the [instructions for fishtest installation on a Windows machine](https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows)

Worker is launched from batch file:

`@echo on`
`SET PATH=C:\MinGW\mingw64\bin;C:\MinGW\msys\1.0\bin;%PATH%`
`C:\Python27\python.exe -i worker.py --concurrency 1 MyUsername MyPassword`

Cmd.exe outputs the following:

`C:\fishtest-master\worker>SET PATH=C:\MinGW\mingw64\bin;C:\MinGW\msys\1.0\bin;C:`
`\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\Phys`
`X\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Syst`
`em32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Bin`
`n\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Micros`
`oft SQL Server\120\Tools\Binn\;C:\Program Files\AMI\DuOS\;C:\Program Files (x86)`
`\Skype\Phone\;C:\Program Files (x86)\GNU\GnuPG\pub`

`C:\fishtest-master\worker>C:\Python27\python.exe -i worker.py --concurrency 1 My`
`Username MyPassword`
`Worker version 59 connecting to http://tests.stockfishchess.org:80`
`mingw32-make ARCH=x86-64-modern COMP=mingw config-sanity`
`mingw32-make[1]: Entering directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcq`
`f/pb00068-Stockfish-f588826/src'`

`Config:`
`debug: 'no'`
`optimize: 'yes'`
`arch: 'x86_64'`
`bits: '64'`
`prefetch: 'yes'`
`popcnt: 'yes'`
`sse: 'yes'`
`pext: 'no'`

`Flags:`
`CXX: g++`
`CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -Wextra -Wshad`
`ow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT`
`LDFLAGS:  -static`

`Testing config sanity. If this fails, try 'make help' ...`

`mingw32-make[1]: Leaving directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcqf`
`/pb00068-Stockfish-f588826/src'`

`Step 0/4. Preparing for profile build.`
`mingw32-make ARCH=x86-64-modern COMP=mingw gcc-profile-prepare`
`mingw32-make[1]: Entering directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcq`
`f/pb00068-Stockfish-f588826/src'`
`mingw32-make ARCH=x86-64-modern COMP=mingw gcc-profile-clean`
`mingw32-make[2]: Entering directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcq`
`f/pb00068-Stockfish-f588826/src'`
`mingw32-make[2]: Leaving directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcqf`
`/pb00068-Stockfish-f588826/src'`
`mingw32-make[1]: Leaving directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcqf`
`/pb00068-Stockfish-f588826/src'`

`Step 1/4. Building executable for benchmark ...`
`mingw32-make ARCH=x86-64-modern COMP=mingw gcc-profile-make`
`mingw32-make[1]: Entering directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcq`
`f/pb00068-Stockfish-f588826/src'`
`mingw32-make ARCH=x86-64-modern COMP=mingw \`
`EXTRACXXFLAGS='-fprofile-generate' \`
`EXTRALDFLAGS='-lgcov' \`
`all`
`mingw32-make[2]: Entering directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcq`
`f/pb00068-Stockfish-f588826/src'`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o benchmark.o benchmark.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o bitbase.o bitbase.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o bitboard.o bitboard.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o endgame.o endgame.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o evaluate.o evaluate.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o main.o main.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o material.o material.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o misc.o misc.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o movegen.o movegen.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o movepick.o movepick.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o pawns.o pawns.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o position.o position.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o psqt.o psqt.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o search.o search.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o thread.o thread.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o timeman.o timeman.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o tt.o tt.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o uci.o uci.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o ucioption.o ucioption.cpp`
`g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -W`
`extra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -`
`o syzygy/tbprobe.o syzygy/tbprobe.cpp`
`syzygy/tbprobe.cpp: In function 'int probe_ab(Position&, int, int, int*)':`
`syzygy/tbprobe.cpp:205:14: warning: array subscript is above array bounds [-Warr`
`ay-bounds]`
`p[i++] = pop_lsb(&bb) ^ mirror;`
`^`
`syzygy/tbprobe.cpp: In function 'int Tablebases::probe_dtz(Position&, int*)':`
`syzygy/tbprobe.cpp:315:14: warning: array subscript is above array bounds [-Warr`
`ay-bounds]`
`p[i++] = pop_lsb(&bb) ^ mirror;`
`^`
`g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o ma`
`terial.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o`
`timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o -lgcov -static`
`mingw32-make[2]: Leaving directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcqf`
`/pb00068-Stockfish-f588826/src'`
`mingw32-make[1]: Leaving directory 'c:/users/9dec~1/appdata/local/temp/tmpp8rcqf`
`/pb00068-Stockfish-f588826/src'`

`Step 2/4. Running benchmark for pgo-build ...`
`./stockfish bench 16 1 1000 default time > /dev/null`

[THEN disaster window pops up: stockfish.exe has stopped working.](http://imgur.com/t72apt4)
After I close it, the cmd.exe continues with the following output:

`Makefile:403: recipe for target 'profile-build' failed`
`mingw32-make: *** [profile-build] Error 255`

`Exception running games:`
`Traceback (most recent call last):`
`File "worker.py", line 88, in worker`
`run_games(worker_info, password, remote, run, task_id)`
`File "C:\fishtest-master\worker\games.py", line 383, in run_games`
`setup_engine(new_engine, binaries_url, worker_dir, run['args']['resolved_new'], repo_url, worker_info['concurrency'])`
`File "C:\fishtest-master\worker\games.py", line 152, in setup_engine`
`build(worker_dir, sha, repo_url, destination, concurrency)`
`File "C:\fishtest-master\worker\games.py", line 131, in build`
`subprocess.check_call(MAKE_CMD + ' -j %s' % (concurrency), shell=True)`
`File "C:\Python27\lib\subprocess.py", line 540, in check_call`
`raise CalledProcessError(retcode, cmd)`
`CalledProcessError: Command 'mingw32-make profile-build COMP=mingw ARCH=x86-64-modern -j`1' `returned non-zero exit status 2`
`Task exited`

What can I do to start contributing with a little processing power to Stockfish?

**Comment by KassiasGrandiel** [comment]
Follow these instructions https://github.com/ppigazzini/fishtest/wiki/Running-the-worker-on-Windows

**Comment by q-l-p** [comment]
Why?

**Comment by ppigazzini** [comment]
Hi q-l-p, your CPU is a Core2 DUO, the python script of fishtest uses this compiling directive "make profile-build ARCH=x86-64-modern COMP=mingw" so your CPU is not able to run the binary.

Please follow the note on wiki after point 4, you need to write a text file "custom_make.txt" in "fishtest-master\worker" directory, with this text:
make profile-build ARCH=x86-64 COMP=mingw

**Comment by q-l-p** [comment]
Followed your instructions and launched the worker. Cmd.exe keeps outputting stuff. No errors so far.
The program is still running... I assume this is normal... These are some of the latest output lines at the time of this post:
`Started game 28 of 1000 (base vs stockfish)
Finished game 28 (base vs stockfish): 1/2-1/2 {Draw by 3-fold repetition}
Score of stockfish vs base: 4 - 3 - 21  [0.518] 28
Started game 29 of 1000 (stockfish vs base)
Finished game 29 (stockfish vs base): 1/2-1/2 {Draw by 3-fold repetition}
Score of stockfish vs base: 4 - 3 - 22  [0.517] 29
Started game 30 of 1000 (base vs stockfish)
Finished game 30 (base vs stockfish): 0-1 {Black wins by adjudication}
Score of stockfish vs base: 5 - 3 - 22  [0.533] 30
Started game 31 of 1000 (stockfish vs base)
`
Is this normal? Is my CPU helping Stockfish?

**Comment by ppigazzini** [comment]
@q-l-p The worker is running fine :)

When the Stockfish Testing Queue runs empty you get  the message "No tasks available at this time, waiting..." until new tasks will be approved. Check here the Stockfish Testing Queue

http://tests.stockfishchess.org/tests

**Comment by q-l-p** [comment]
@ppigazzini Thank you for the help!!
