### ISSUE TITLE
VPS Migration - Oct. 7th

### ISSUE THREAD

**Issue by glinscott** [glinscott/fishtest#802]
From the provider:
>Date: Wednesday 7th October
Start: 10 AM UTC
End: ~End of Day 
>
>We will be migrating users on AMS7VZ3 to a new node, you are receiving this email as you have one or more VMs on the node. You may check the exact VM from the main control panel.
>
>Your VM will only go down when it is in queue for migration, for users with less than 50GB actively used disk we anticipate less than 30 minutes down time. Users with large space being used may take significantly longer.
>
>As always we recommend clients keep their own backups at all times, however we will aim to retain a copy of your old VM prior to migration on the old node for a couple of days post migration.

**Comment by ppigazzini** [comment]
@glinscott thank you for the information, disk usage 32 GB after compacting mongodb.

**Comment by tomtor** [comment]
The server rebooted around midnight (not 10 AM UTC):

```reboot   system boot  4.15.0           Tue Oct  6 23:33   still running```

and `/var/run/mongodb` was gone, so MongoDb could not restart.

I recreated `/var/run/mongodb` and it is running again.

**Comment by ppigazzini** [comment]
@tomtor my fault. Yesterday I setup logrotate for mongodb, I missed to test the VPS reboot. As soon as I will back to my keyboard I will disable mongodb logrotate on PROD.

**Comment by ppigazzini** [comment]
@tomtor now the server start correctly after a reboot, hopefully at 00 UTC the mongodb log should rotate, finger crossed :)
wiki server setup script updated, this is the code snippet:
```bash
# setup logrotate for mongodb
sed -i '/^  logAppend: true/a\  logRotate: reopen' /etc/mongod.conf
sed -i '/^  timeZoneInfo:*/a\  pidFilePath: /var/run/mongodb/mongod.pid' /etc/mongod.conf

cat << EOF > /etc/tmpfiles.d/mongod.conf
d /run/mongodb 0755 mongodb mongodb -
EOF

systemd-tmpfiles --create /etc/tmpfiles.d/mongod.conf

cat << 'EOF' > /etc/logrotate.d/mongod
/var/log/mongodb/mongod.log
{
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0600 mongodb mongodb
    sharedscripts
    postrotate
        /bin/kill -SIGUSR1 $(cat /var/run/mongodb/mongod.pid 2>/dev/null) 2>/dev/null || true
    endscript
}
EOF
```

**Comment by ppigazzini** [comment]
@tomtor mongodb log rotation works :)

**Comment by ppigazzini** [comment]
I found on PROD some system files/folders with `root:fishtest` ownership (e.g. `/bin`, `/sbin`, `/run` and some file/folders in `/etc/systemd/system`).
Could be a collateral effect of the VM migration
I restored the default `root:root` ownership after a double check on DEV.

**Comment by tomtor** [comment]
```I found on PROD some system files/folders with root:fishtest ownership```

Strange, I would not expect a migration to change ANY filesystem state...

**Comment by ppigazzini** [comment]
DEV was migrated some weeks ago (same provider), no problems.

**Comment by noobpwnftw** [comment]
hmm...probably host is LXC, not KVM? Otherwise migration should have no downtime.

**Comment by glinscott** [comment]
They emailed to say all migrations are complete.  Apparently the new node has SSD disks as well, so we should see a nice perf boost hopefully!

**Comment by ppigazzini** [comment]
@glinscott IMO PROD was already on SSD, DEV finally is on par, see old benches
https://github.com/glinscott/fishtest/issues/391#issuecomment-529411249 

and new benches:
- PROD
```
time (dd if=/dev/zero of=/tmp/test bs=64k count=16k > /dev/null; sync)
16384+0 records in
16384+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.58206 s, 679 MB/s

real    0m1.797s
user    0m0.018s
sys     0m1.605s
```
- DEV
```
time (dd if=/dev/zero of=/tmp/test bs=64k count=16k > /dev/null; sync)
16384+0 records in
16384+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.11714 s, 961 MB/s

real    0m1.595s
user    0m0.014s
sys     0m1.113s
```

**Comment by ppigazzini** [comment]
> hmm...probably host is LXC, not KVM? Otherwise migration should have no downtime.

OpenVZ

**Comment by ppigazzini** [comment]
@tomtor PROD and wiki setup script updated with a simpler process that avoid PIDfile and `tmpfile.d` management, lowering the risk of errors. `logrotate` get the `mongod` PID using `pgrep` (installed by default on Ubuntu 18.04, added anyway `procps` in required packages), see https://aerospike.com/docs/operations/configure/log/logrotate.html#logrotate-policy-on-systemd-environments
Here the snippet:
```bash
# setup logrotate for mongodb
sed -i '/^  logAppend: true/a\  logRotate: reopen' /etc/mongod.conf

cat << 'EOF' > /etc/logrotate.d/mongod
/var/log/mongodb/mongod.log
{
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0600 mongodb mongodb
    sharedscripts
    postrotate
        /bin/kill -SIGUSR1 $(pgrep mongod 2>/dev/null) 2>/dev/null || true
    endscript
}
EOF
```
From the unit file `mongodb` doesn't fork, otherwise we should use `pgrep --oldest mongod`
Alternative way is to read the PID from `/var/lib/mongodb/mongod.lock`, this could silently break with a future `mongodb` update.
