### ISSUE TITLE
Stuck SPSA runs

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#809]
As reported on the forum: https://groups.google.com/d/msg/fishcooking/no-PkdKafpA/4TZhEY-uAwAJ

https://tests.stockfishchess.org/tests/view/5f8744f4dcdad978fe8c51fe
https://tests.stockfishchess.org/tests/view/5f875213dcdad978fe8c5211
https://tests.stockfishchess.org/tests/view/5f8744fadcdad978fe8c5200
 
These seem to be somehow "stuck", indicating a number of active cores in
the main list, while there seem to be no active machines on the respective
test pages. Also, the number of games/iteratations remains absolutely
constant.

EDIT_000: added the right link to the forum post

**Comment by tomtor** [comment]
@ppigazzini  I will add some debugging code to prod.

**Comment by tomtor** [comment]
@ppigazzini Could it be that live changes to the python code in `~/fishtest/fishtest` are no longer picked up (after a restart) in the current deployment with `pip install`? We used to `pip install` in development mode.

Any hints because I don't see my debugging output in the logs...

**Comment by ppigazzini** [comment]
@tomtor try filtering with ` sudo journalctl -u fishtest@6543 --since 10:00`

**Comment by ppigazzini** [comment]
@tomtor on DEV I changed `views.py`, restarted with `sudo systemctl restart fishtest@{6543..6544}` and got "AAAAAAAA Your account has been created."

Also on PROD you can setup fishtest merging a github branch, check `~/x/update_fishtest.sh`

**Comment by ppigazzini** [comment]
@tomtor it works after a reboot ...
```
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Starting server in PID 348.
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Serving on http://localhost:6543
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 120 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 773 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 774 {'unique_key': 'b1f83a87-cc40-48ae-a9b2-5d2673328e0d', 'username': 'dew', 'rate': {'limit': 60, 'reset': 1602849259, 'remaining': 60, 'u
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 775 {'uname': 'Windows 10', 'architecture': ['64bit', 'WindowsPE'], 'concurrency': 32, 'max_memory': 32768, 'min_threads': 1, 'username': 'g
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 812 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 114 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 52 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 53 {'uname': 'Windows 10', 'architecture': ['64bit', 'WindowsPE'], 'concurrency': 15, 'max_memory': 16349, 'min_threads': 1, 'username': 'bc
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 813 {'unique_key': 'b1f83a87-cc40-48ae-a9b2-5d2673328e0d', 'username': 'dew', 'rate': {'limit': 60, 'reset': 1602849283, 'remaining': 60, 'u
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 67 {'uname': 'Linux 4.19.128-microsoft-standard', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 25676, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 504 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 36 {'architecture': ['64bit', 'ELF'], 'rate': {'remaining': 60, 'reset': 1602849306, 'limit': 60, 'used': 0}, 'version': '87:3', 'min_thread
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 505 {'unique_key': 'b1f83a87-cc40-48ae-a9b2-5d2673328e0d', 'username': 'dew', 'rate': {'limit': 60, 'reset': 1602849307, 'remaining': 60, 'u
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 813 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 505 {'architecture': ['64bit', 'ELF'], 'rate': {'remaining': 60, 'reset': 1602849322, 'limit': 60, 'used': 0}, 'version': '87:3', 'min_threa
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 505 {'uname': 'Linux 5.4.0-47-generic', 'architecture': ['64bit', 'ELF'], 'concurrency': 30, 'max_memory': 8028, 'min_threads': 1, 'username
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 502 {'uname': 'Linux 3.10.0-1127.19.1.el7.x86_64', 'architecture': ['64bit', 'ELF'], 'concurrency': 8, 'max_memory': 1834, 'min_threads': 1,
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 594 {'uname': 'Windows 10', 'architecture': ['64bit', 'WindowsPE'], 'concurrency': 16, 'max_memory': 16384, 'min_threads': 1, 'username': 'g
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 595 {'unique_key': 'b1f83a87-cc40-48ae-a9b2-5d2673328e0d', 'username': 'dew', 'rate': {'limit': 60, 'reset': 1602849333, 'remaining': 60, 'u
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 596 {'architecture': ['64bit', 'ELF'], 'rate': {'remaining': 60, 'reset': 1602849338, 'limit': 60, 'used': 0}, 'version': '87:3', 'min_threa
Oct 16 10:55:55 tests.stockfishchess.org pserve[348]: Return task: 595 {'uname': 'Linux 4.15.0-118-generic', 'architecture': ['64bit', 'ELF'], 'concurrency': 14, 'max_memory': 8028, 'min_threads': 1, 'userna
```

**Comment by tomtor** [comment]
It is interesting that one of JojoM workers tries to run a stuck test:

Oct 16 11:12:32 tests.stockfishchess.org pserve[2843]: Return SPSA 5f8744fadcdad978fe8c5200 {'uname': 'Linux 4.19.0-10-amd64', 'architecture': ['64bit', 'ELF'], 'concurrency': 7, 'max_memory': 16084, 'min_threads': 1, 'username': 'JojoM', 'version': '87:3', 'unique_key': '238dbc1b-58e5-426e-83ac-44e80b61851d', 'rate': {'limit': 60, 'remaining': 60, 'reset': 1602850262, 'used': 0}, 'remote_addr': '160.45.42.134', 'country_code': 'DE'}

I expect that one of these  workers shows some errors which might hint at the cause of this issue. Perhaps an old cutechess binary or some missing file(s)?

**Comment by JojoM-sf** [comment]
I will look into it, immediately.

**Comment by JojoM-sf** [comment]
I have identified the worker and the machine. From my perspective, no errors at all. In the terminal, everything is looking ok. Shall I restart the worker or shall I leave everything as it is?

**Comment by ppigazzini** [comment]
> Perhaps an old cutechess binary or some missing file(s)?

We check for the cutechess version:
https://github.com/glinscott/fishtest/blob/b5cf10759ab5f6b7329e6cfadbd25600d8e87178/worker/games.py#L118-L119

**Comment by tomtor** [comment]
> From my perspective, no errors at all. In the terminal, everything is looking ok. Shall I restart the worker or shall I leave everything as it is?

Is it playing SPSA games? If it is it would be interesting to wait until it posts results:
`  Task updated successfully in 0.047783s`

and post the last 30 lines of the worker output.

**Comment by tomtor** [comment]
It might be an issue that it takes more than 30 minutes to post the first results.

**Comment by JojoM-sf** [comment]
Give me a second ...

**Comment by JojoM-sf** [comment]
Thing is, the line "task updated ..." doesn't show up at all, as opposed to the other workers/machines I am running. And as opposed to the same worker/machine when not running SPSA, but SPRT.

**Comment by tomtor** [comment]
> Thing is, the line "task updated ..." doesn't show up at all, as opposed to the other workers/machines I am running. And as opposed to the same worker/machine when not running SPSA, but SPRT.

@vondele @ppigazzini Can you think of a reason?

**Comment by JojoM-sf** [comment]
Also, I am using the latest standard version of Fishtest, including Cutechess 1.2.0. The problem must be SPSA-specific, I think.

**Comment by JojoM-sf** [comment]
From the outside, the test looks like a normal SPRT-test. I.e., no "finished match cleanly" messages and things like that.

Started game 1 of 200 (New-be64bc2b77 vs Base-be64bc2b77)
Started game 2 of 200 (Base-be64bc2b77 vs New-be64bc2b77)
Started game 3 of 200 (New-be64bc2b77 vs Base-be64bc2b77)
Started game 5 of 200 (New-be64bc2b77 vs Base-be64bc2b77)
Started game 6 of 200 (Base-be64bc2b77 vs New-be64bc2b77)
Started game 4 of 200 (Base-be64bc2b77 vs New-be64bc2b77)
Started game 7 of 200 (New-be64bc2b77 vs Base-be64bc2b77)
Finished game 5 (New-be64bc2b77 vs Base-be64bc2b77): 1/2-1/2 {Draw by adjudication}
Score of New-be64bc2b77 vs Base-be64bc2b77: 0 - 0 - 1  [0.500] 1
Started game 8 of 200 (Base-be64bc2b77 vs New-be64bc2b77)
Finished game 4 (Base-be64bc2b77 vs New-be64bc2b77): 1/2-1/2 {Draw by adjudication}
Score of New-be64bc2b77 vs Base-be64bc2b77: 0 - 0 - 2  [0.500] 2
Started game 9 of 200 (New-be64bc2b77 vs Base-be64bc2b77)
Finished game 7 (New-be64bc2b77 vs Base-be64bc2b77): 1-0 {White wins by adjudication}
Score of New-be64bc2b77 vs Base-be64bc2b77: 1 - 0 - 2  [0.667] 3
Started game 10 of 200 (Base-be64bc2b77 vs New-be64bc2b77)
Finished game 6 (Base-be64bc2b77 vs New-be64bc2b77): 1/2-1/2 {Draw by insufficient mating material}
Score of New-be64bc2b77 vs Base-be64bc2b77: 1 - 0 - 3  [0.625] 4
Started game 11 of 200 (New-be64bc2b77 vs Base-be64bc2b77)
Finished game 1 (New-be64bc2b77 vs Base-be64bc2b77): 1-0 {White wins by adjudication}
Score of New-be64bc2b77 vs Base-be64bc2b77: 2 - 0 - 3  [0.700] 5
Started game 12 of 200 (Base-be64bc2b77 vs New-be64bc2b77)
Finished game 3 (New-be64bc2b77 vs Base-be64bc2b77): 0-1 {Black wins by adjudication}
Score of New-be64bc2b77 vs Base-be64bc2b77: 2 - 1 - 3  [0.583] 6

**Comment by JojoM-sf** [comment]
Header of the test:

Running bpf vs bpf
Fetched SPSA parameters successfully in 0.125344s
['/home/mi/joachim70/C5/fishtest/worker/testing/cutechess-cli', '-repeat', '-rounds', '100', '-games', ' 2', '-tournament', 'gauntlet', '-site', 'https://tests.stockfishchess.org/tests/view/5f8744fadcdad978fe8c5200', '-event', 'Batch 136: bpf vs bpf', '-srand', '1004428083', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '7', '-openings', 'file=noob_3moves.epd', 'format=epd', 'order=random', 'plies=16', 'start=13601', '-engine', 'name=New-be64bc2b77', 'cmd=stockfish_be64bc2b77b0b9a8497fb34e5219bed30e32146c', 'option.Hash=64', 'option.Use NNUE=false', 'option.EvalFile=/home/mi/joachim70/C5/fishtest/worker/testing/nn-04cf2b4ed1da.nnue', 'option.mBishopPawns[0]=5', 'option.eBishopPawns[0]=10', 'option.mBishopPawns[1]=5', 'option.eBishopPawns[1]=9', 'option.mBishopPawns[2]=4', 'option.eBishopPawns[2]=10', 'option.mBishopPawns[3]=0', 'option.eBishopPawns[3]=10', '-engine', 'name=Base-be64bc2b77', 'cmd=stockfish_be64bc2b77b0b9a8497fb34e5219bed30e32146c', 'option.Hash=64', 'option.Use NNUE=false', 'option.EvalFile=/home/mi/joachim70/C5/fishtest/worker/testing/nn-04cf2b4ed1da.nnue', 'option.mBishopPawns[0]=0', 'option.eBishopPawns[0]=5', 'option.mBishopPawns[1]=0', 'option.eBishopPawns[1]=4', 'option.mBishopPawns[2]=-1', 'option.eBishopPawns[2]=5', 'option.mBishopPawns[3]=5', 'option.eBishopPawns[3]=5', '-each', 'proto=uci', 'tc=72.696+0.727', 'option.Threads=1']
TC limit 20770.377633591932 End time: 2020-10-16 18:58:04.436855
Indexing opening suite...

**Comment by tomtor** [comment]
@JojoM-sf It will update after 32 played games (this is a recent change)!!!

**Comment by JojoM-sf** [comment]
@tomtor Ok, but obviously without saying so ... no „task updated“ line. Presently, two workers running on „bpf“.

**Comment by tomtor** [comment]
@vondele I believe https://github.com/glinscott/fishtest/commit/2ee43c82d63ce9d19838fe9bd493c2cbe76dbb1f# is broken, it will only update after all 200 games have been played. At that time the active timeout has been triggered and all results are dropped.

**Comment by tomtor** [comment]
This is also the root cause for https://github.com/glinscott/fishtest/issues/792

**Comment by tomtor** [comment]
@ppigazzini I believe merging https://github.com/glinscott/fishtest/pull/810 and reverting https://github.com/glinscott/fishtest/commit/2ee43c82d63ce9d19838fe9bd493c2cbe76dbb1f or changing it to eg *4 instead of *32 would solve this issue.

**Comment by tomtor** [comment]
@JojoM-sf 

```
Oct 16 13:09:13 tests pserve[8955]: Update_task: Non matching username: JojoM
Oct 16 13:09:13 tests pserve[8955]: SPSA dead task
```

Your worker posted its results and these were dropped because of the above mentioned timeout issue.

**Comment by JojoM-sf** [comment]
@tomtor So is it better to switch them off, while the issue is not resolved – or try to have them be assigned to another test?

**Comment by JojoM-sf** [comment]
Logged my workers out for the moment. Their resources shouldn't be wasted entirely.

**Comment by tomtor** [comment]
@JojoM-sf I changed the timeouts on the server to about 3 hours for now, that should work as a quick fix.

**Comment by JojoM-sf** [comment]
@tomtor Yes, thank you. After a worker restart, Fishtest assigned new tasks, anyway ;)

**Comment by tomtor** [comment]
@JojoM-sf Thanks for your assistance in debugging!

**Comment by JojoM-sf** [comment]
@tomtor You are most welcome! I have the greatest respect for what you all are achieving here – and only wish I knew more about programming myself.

**Comment by ppigazzini** [comment]
> @ppigazzini I believe merging #810 and reverting [2ee43c8](https://github.com/glinscott/fishtest/commit/2ee43c82d63ce9d19838fe9bd493c2cbe76dbb1f) or changing it to eg *4 instead of *32 would solve this issue.

My vote for `*4` to keep a bit low the CPU load and avoid problems with the VPS provider.

**Comment by ppigazzini** [comment]
> only wish I knew more about programming myself.

I'm wondering if that is to be only intended in a wishful thinking way :)
Otherwise there are plenty of good tutorials out there:
https://www.programiz.com/python-programming
https://docs.python.org/3.8/tutorial/index.html

**Comment by JojoM-sf** [comment]
;) Thanks ... It's true that words need to be followed by deeds.

**Comment by tomtor** [comment]
> My vote for `*4` to keep a bit low the CPU load and avoid problems with the VPS provider.

@ppigazzini Sure, I added it to #810.

The downside is that eg my worker will only send a first update after 120 games (4*30 and is not visible before that) and finally a second update after 200 games. We could keep * 32 for request_SPSA calls() and batch size, but the worker/server code needs to be changed so that the updates are send more frequently, eg after `concurrency` games.

That could be part of another future PR.

**Comment by JojoM-sf** [comment]
@tomtor 

Will that also provide a more frequent update of the webpages, i.e. the main page and the SPSA test page?

**Comment by tomtor** [comment]
> @tomtor
> 
> Will that also provide a more frequent update of the webpages, i.e. the main page and the SPSA test page?

Yes it will

**Comment by ppigazzini** [comment]
> send a first update after 120 games (4*30 

So updates every 4 games/core, IMO is reasonable, the default was 2 games/core.

**Comment by tomtor** [comment]
@JojoM-sf For test https://tests.stockfishchess.org/tests/view/5f8744fadcdad978fe8c5200
your 1 core worker just showed up with slot 159  ;-)

![image](https://user-images.githubusercontent.com/1104260/96292955-489dd800-0fea-11eb-9dac-f355c582a4de.png)

Looks good.

**Comment by JojoM-sf** [comment]
So, presently, updates only after a 200 games batch. But 3 hours seem to be sufficient so as to not lose the games, at least in the case of 7 cores attached ;)

**Comment by SFisGOD** [comment]
Number of games/iterations remain constant
https://tests.stockfishchess.org/tests/view/5f8dd390bacb75a4f9a47209

**Comment by tomtor** [comment]
@SFisGOD That worker crashed, 2 new workers are now assigned (that takes 120 minutes, but we are working to improve that)

**Comment by tomtor** [comment]
Should be fixed
