### ISSUE TITLE
fishtest server down?

### ISSUE THREAD

**Issue by Def9Infinite** [glinscott/fishtest#814]
timed out when try to connect to fishtest.

> API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1602981316, 'used': 0}
Exception accessing host:
HTTPSConnectionPool(host='tests.stockfishchess.org', port=443): Max retries exceeded with url: /api/request_version (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4fa9a4d700>, 'Connection to tests.stockfishchess.org timed out. (connect timeout=15.0)'))

**Comment by ppigazzini** [comment]
@glinscott the VPS seems down, can you check?

**Comment by glinscott** [comment]
I've rebooted it.  I didn't get any notification, but the RAM usage was in the red at 5GB out of 5GB - perhaps that was it?  It's unfortunate there is no reason though :(.  Perhaps in the VM logs?

![image](https://user-images.githubusercontent.com/554932/96357128-37b59b00-10ac-11eb-93c8-7b8cb4722972.png)

**Comment by ppigazzini** [comment]
Perhaps #810 has raised the memory requirement, I lowered the mongodb cache from 2GB to 1GB.
Thnak you @glinscott

**Comment by tomtor** [comment]
> Perhaps #810 has raised the memory requirement

That is very unlikely.

**Comment by ppigazzini** [comment]
> > Perhaps #810 has raised the memory requirement
> 
> That is very unlikely.

I agree.

* DEV : the Memory ISP panel shows the output of `free`, counting also the buffers/cache:

![image](https://user-images.githubusercontent.com/15718418/96364155-96752600-1139-11eb-9a56-ff01c1b13d71.png)

```
free -h
              total        used        free      shared  buff/cache   available
Mem:           6.0G        2.7G        1.0G         60K        2.3G        3.3G
Swap:          3.0G         94M        2.9G
```


* PROD : we are using now 57.1% memory with mongodb cache set to 1 GiB, so we should got the usual 77.1% with mongodb cache set to 2 GiB.

```
free -h
              total        used        free      shared  buff/cache   available
Mem:           5.0G        2.9G        371M        1.1M        1.8G        2.1G
Swap:            0B          0B          0B
```

```
top

GiB Mem : 57.1/5.000    [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                           ]
GiB Swap:  0.0/0.000    [                                                                                                    ]


 3989 mongodb   20     2866544 1.301g   9528 S   4.3 26.0  24:30.99  `- /usr/bin/mongod --config /etc/mongod.conf
 4029 fishtest  20     2225160 1.163g   9628 S   7.0 23.3  99:30.80  `- /home/fishtest/fishtest/fishtest/env/bin/python3 /home/fishtest/fishtest/fishtest/env/bin/pserve production.ini http_port=6543
 4030 fishtest  20     1204744 386172   9572 S   0.7  7.4   4:32.92  `- /home/fishtest/fishtest/fishtest/env/bin/python3 /home/fishtest/fishtest/fishtest/env/bin/pserve production.ini http_port=6544
```

**Comment by tomtor** [comment]
@glinscott @ppigazzini It crashed again...

**Comment by tomtor** [comment]
Its back. A transient network issue?

**Comment by ppigazzini** [comment]
Perhaps ...
```
uptime -p
up 11 hours, 8 minutes
```
