### ISSUE TITLE
truncated nn stats table?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#815]
looks like the table on the nn stats table is missing older entries:

https://tests.stockfishchess.org/nns

i.e. anything before Sept. 15 is missing for me.

**Comment by tomtor** [comment]
Yes, it shows the 100 most recent networks...

Op zo 18 okt. 2020 08:55 schreef Joost VandeVondele <
notifications@github.com>:

**Comment by tomtor** [comment]
I can raise it (the entries are small) to eg 1000. I do not think paging is needed.

**Comment by vondele** [comment]
yes, let's show all for the time being, that's probably the easiest. Not urgent either.
