### ISSUE TITLE
workers with many cores

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#822]
High core workers (64, 88, etc) can't meaningfully participate in fishtest because cutechess can't deal with that many concurrent processes. The user can fix this manually by running multiple workers with reduced concurrency. The alternative would be we deal with this in the worker code, spawning multiple cutechess runs with reduced concurrency (e.g. 16). This happened with at least 3 users so far.

**Comment by vondele** [comment]
BTW, a simple workaround would be to assign these workers to LTC jobs. At high TC this problem is nearly absent.

**Comment by tomtor** [comment]
> BTW, a simple workaround would be to assign these workers to LTC jobs. At high TC this problem is nearly absent.

@vondele I do not understand why it is no problem at LTC, the number of processes is the same?

Is the cutechess issue too much IO between the master and child processes?

Anyway, is the only file that need to be unique when we start multiple cutechess instances the `.pgn` file?

**Comment by vondele** [comment]
I don't know what the exact cutechess issue is, but I've observed it before locally myself, and now it is clear on fishtest as well. Clearly following 60 games at LTC is easier than at STC (quick IO, but also at STC there will be more often moves that are close to the time limit).

Yes, probably the only file that needs to be unique for starting multiple cutechess instances is the .pgn file, assuming they work on the same test of course.

**Comment by vondele** [comment]
I have also filed this as a cutechess issue, but we should try to fix this in the short term 

https://github.com/cutechess/cutechess/issues/630

**Comment by ppigazzini** [comment]
> I have also filed this as a cutechess issue, but we should try to fix this in the short term
> 
> [cutechess/cutechess#630](https://github.com/cutechess/cutechess/issues/630)

The issue reports cutechess-cli 1.1.0, in fishtest we are using 1.2.0. Typo?

**Comment by vondele** [comment]
happens with both, I happen to pick an older local version in a testing dir.

**Comment by alwey** [comment]
@vondele : Could you please make a local test with the old cutechess-0.6.0 for comparison?
I guess the high rate of PV conversion from LAN to SAN might trigger the problem. The old version does not convert PVs into SAN.

**Comment by vondele** [comment]
@alwey I can test but it would be easiest if there is a linux binary for cutechess-0.6.0 somewhere available. 
I didn't see any on github, do you know if they can be found somewhere ?

**Comment by alwey** [comment]
@vondele: Indeed, there is no binary for version 0.6.0 on the cutechess site.

CLI Version 0.6.0 old and compact binary from the predecessor of my local system : 
[cutechess-cli-0.6.0.zip](https://github.com/glinscott/fishtest/files/5415320/cutechess-cli-0.6.0.zip)

Old Binaries V 0.5.1 from Marco: https://github.com/mcostalba/FishCooking/blob/setup/cutechess-cli-linux-64bit.zip
Version 0.8.2 from official cutechess: https://github.com/cutechess/cutechess/releases/download/cli-0.8.2/cutechess-cli-linux64.tar.gz

**Comment by vondele** [comment]
@alwey I tried the 3 options, but got none to work because missing shared libraries. On a machine with 128cores/256threads I look at timeout stats as a function of cutechess concurrency (threads in the table) and TC.
```
   threads         TC  timed-out /      total
       240   4.0+0.04        940 /       1000 ( 94%)
       128   4.0+0.04        886 /       1000 ( 89%)
       120   4.0+0.04        863 /       1000 ( 87%)
       100   4.0+0.04        559 /       1000 ( 56%)
        80   4.0+0.04         10 /       1000 (  1%)
        64   4.0+0.04          0 /       1000 (  0%)
       240   10.0+0.1        777 /        960 ( 81%)
       128   10.0+0.1        108 /        512 ( 22%)
       120   10.0+0.1         57 /        480 ( 12%)
       100   10.0+0.1         10 /        400 (  3%)
        80   10.0+0.1          0 /        320 (  0%)
        64   10.0+0.1          0 /        256 (  0%)
       240   60.0+0.6          2 /        960 (  1%)
       128   60.0+0.6          0 /        512 (  0%)
       120   60.0+0.6          0 /        480 (  0%)
       100   60.0+0.6          0 /        400 (  0%)
        80   60.0+0.6          0 /        320 (  0%)
        64   60.0+0.6          0 /        256 (  0%)
```
it definitely shows the problem is mostly showing up with relatively short TC games and larger concurrency. The precise values will be hardware/OS dependent, I assume, but the trend is clear.
