### ISSUE TITLE
Big Tuning Run

### ISSUE THREAD

**Issue by SFisGOD** [glinscott/fishtest#823]
@ppigazzini  The limit is currently 800,000 games. Can we increase this for SPSA?

**Comment by xoto10** [comment]
And related to [that SPSA run](https://tests.stockfishchess.org/tests/view/5f8dd390bacb75a4f9a47209), is there any noticeable increase in load on the server?

**Comment by ppigazzini** [comment]
> And related to [that SPSA run](https://tests.stockfishchess.org/tests/view/5f8dd390bacb75a4f9a47209), is there any noticeable increase in load on the server?

No at the moment, but the workers seem to be stuck...
`top - 20:08:42 up 1 day, 17:44,  2 users,  load average: 0.32, 0.31, 0.37`

**Comment by ppigazzini** [comment]
> @ppigazzini The limit is currently 800,000 games. Can we increase this for SPSA?

cc @vondele

**Comment by SFisGOD** [comment]
@ppigazzini What to do with that stuck run?

**Comment by xoto10** [comment]
Maybe the low load average suggests everything is ok ?

**Comment by SFisGOD** [comment]
@xoto10 It's stuck though

**Comment by xoto10** [comment]
What is stuck?

**Comment by xoto10** [comment]
Ah, you mean your tune? Probably the grandphish worker has disconnected and fishtest doesn't know yet. We have been discussing this issue elsewhere. The scavenge will remove the worker 110 mins after last update (5-10 mins from now?) and then fishtest will allocate a new worker(s) ...

**Comment by xoto10** [comment]
Have you noticed the tuned values are moving a lot? I think you have the A parameter set too small, something like 40,000 would be more appropriate than the default 3000 since you have requested a large number of games.

**Comment by tomtor** [comment]
> The limit is currently 800,000 games. Can we increase this for SPSA?

No, that limit is needed to prevent out-of-memory issues.

**Comment by SFisGOD** [comment]
Closing this since tomtor already answered my question.

**Comment by SFisGOD** [comment]
@ppigazzini @tomtor Will fishtest be able to handle the load when tuning 16384 parameters?

**Comment by vondele** [comment]
@SFisGOD probably not, and it makes little sense to try and do it. In the issue discussing SPSA, one can estimate that ~100000 games are needed to converge 1 parameter by SPSA (assuming this parameter contributes 2Elo). Tuning 16k parameter playing games is just out of reach with fishtest. This needs some smarter choice of variables.

**Comment by xoto10** [comment]
Regarding tuning 16k parameters, my concern would be network traffic and load on the server. Even if (say) 400k games was enough to be worth trying, I'm doubtful the server could handle that kind of parameter load.

I wonder about those calculations for number of games required though.

~100000 games seems about right, but I'm not convinced it goes up with the number of parameters as suggested in that thread. I've had success with search tunes several times with 100,000-200,000 games when tuning something like 70-80 parameters. I get the idea that more parameters might need more games (if not the detailed maths), but does this hypothesis match what happens in practice? I'm doubtful.

It seems to me that any changes which are definitely harmful are quickly selected against, so from then on the tune is randomly varying all the parameters in spaces which are neutral / possibly helpful. Having more parameters might improve the chances of finding a gain on this view. Then again, tuning can find useful changes to a combination of parameters, where all of them need to change to get the improvement. I guess this is where the higher number of games is expected to be needed. 

My point is that theorising about this is one thing, but what happens in practice is what really counts. I understand that this kind of optimisation is reasonably well known and studied, and I am likely flat out wrong, but I thought it worth pointing out what I (think I) see in practice.

**Comment by SFisGOD** [comment]
@xoto10 Link to that thread?

**Comment by vondele** [comment]
@SFisGOD https://github.com/glinscott/fishtest/issues/535

@xoto10 that number of games refers to getting to the optimal value (to within 0.5Elo). If one is sufficiently far away from optimum, one might improve over the current parameters by say 1Elo (fishtest success) with less games.

Anyway, many parameters breaks the server by data overload. Probably has improved a bit, but still.

**Comment by xoto10** [comment]
> Anyway, many parameters breaks the server by data overload. Probably has improved a bit, but still.

yes, this is my concern

**Comment by SFisGOD** [comment]
@vondele When I try to tune 1024 parameters (512x32 layer), the values doesn't move https://tests.stockfishchess.org/tests/view/5f99ffad6a2c112b60691c09

128 parameters seems okay
https://tests.stockfishchess.org/tests/view/5f9a0d376a2c112b60691c12

**Comment by SFisGOD** [comment]
There seems to be a problem with this test
https://tests.stockfishchess.org/tests/view/5f9e59226a2c112b60691e1d

Draw by stalled connection
https://github.com/SFisGOD/Stockfish/commit/55da154484aeda335b02bcef3f73ac30c6ef62eb#commitcomment-43772527
