### ISSUE TITLE
Configure number of exec files in .fishtest/worker/testing/

### ISSUE THREAD

**Issue by JojoM-sf** [glinscott/fishtest#825]
(See https://groups.google.com/g/fishcooking/c/ZLU5Ry07HKM/m/BrSxUaJIBAAJ).

Would it be a great effort to add a switch to the worker script enabling it to configure the number or the amount of files being cached in the testing folder?

I have to manually reduce the respective value (50) in line 856 of games.py every time we are getting an update, as I am regularly hitting my assigned hard drive quota since the advent of NNUE.

**Comment by JojoM-sf** [comment]
Can, after update #91, this issue be closed and would I be authorised to do this?

**Comment by ppigazzini** [comment]
@JojoM-sf yes :)

**Comment by JojoM-sf** [comment]
Ok, then ... ;)
