### ISSUE TITLE
02_install_worker.cmd briefly open then closes

### ISSUE THREAD

**Issue by Nordlandia** [glinscott/fishtest#826]
As Fishtest Portable Launcher is phased out. I tried install the new working client. 

But stage 2 in the recipe is not straightforward. It opens for about 200ms then closes. 

What is a possible solution?

**Comment by ppigazzini** [comment]
@Nordlandia some tests to verify if running as administrator `00_install_choco_msys2_admin.cmd` was successful:
- open a cmd or a powershell, write `ming64`, push `enter` key. It should start a mingw64 windows
- run as administrator `04_update_msys2_choco_admin.cmd`

Let me know the result of the tests and your Windows version.

Anyway I just found that a PR merged today broken the stopping process with `fish.exit` used also in the setup script.

**Comment by ppigazzini** [comment]
@Nordlandia another user had the same windows flash problem with the script, solved after a reboot, see https://github.com/glinscott/fishtest/pull/841#issuecomment-716709454

Let me know if you solved the problem.
