### ISSUE TITLE
User statistic stuck?

### ISSUE THREAD

**Issue by JojoM-sf** [glinscott/fishtest#846]
SInce yesterday, figures on `tests.stockfishchess.org/users` haven't budged anymore.
@tomtor @ppigazzini Could you look into it, please?

**Comment by ppigazzini** [comment]
My fault, I forgot to restart `cron` after the VPS maintenance work for https://github.com/glinscott/fishtest/pull/834 .

**Comment by JojoM-sf** [comment]
Thanks, Pasquale.
