### ISSUE TITLE
Test not showing in NN stats

### ISSUE THREAD

**Issue by SFisGOD** [glinscott/fishtest#854]
This test is not showing in NN stats
https://tests.stockfishchess.org/tests/view/5fa29fe9bca9bf35bae7f865

new_net  None?

**Comment by tomtor** [comment]
Looks like a problem with accessing github at the time of the test creation.

**Comment by ppigazzini** [comment]
@SFisGOD please close the issue if solved.

**Comment by SFisGOD** [comment]
@ppigazzini Issue closed :)
