### ISSUE TITLE
Unable to create a working Fishtest in Ubuntu 20.04.

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#871]
I upgraded to Ubuntu 20.04. I reinstalled Fishtest from scratch using Pasquale's script on the Wiki.

I can start the server (with `pserve development.ini` after activating the virtual environment) but I cannot connect to it. The connection hangs for a while and then the server gives an error. Below an attempt with wget so that one can see the server responses.

Is there anyway I can debug this?

```
$ wget localhost:6542 -S

--2020-12-06 09:54:38--  http://localhost:6542/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:6542... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 302 Found
  Content-Length: 564
  Content-Type: text/html; charset=UTF-8
  Date: Sun, 06 Dec 2020 08:54:38 GMT
  Location: http://localhost:6542/tests
  Server: waitress
Location: http://localhost:6542/tests [following]
--2020-12-06 09:54:38--  http://localhost:6542/tests
Reusing existing connection to localhost:6542.
HTTP request sent, awaiting response...

# Nothing happens for some time.... and then:
 
  HTTP/1.1 500 Internal Server Error
  Content-Length: 10621
  Content-Type: text/html; charset=UTF-8
  Date: Sun, 06 Dec 2020 08:54:38 GMT
  Server: waitress
2020-12-06 09:55:06 ERROR 500: Internal Server Error.
```

**Comment by vdbergh** [comment]
Below also part of the console log. I added some newlines for readability. The reference to port 27017 seems strange to me.
```
$ pserve development.ini

Starting server in PID 73364.
Serving on http://0.0.0.0:6542

# After connecting with wget....

Overview exception: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology 
Description: <TopologyDescription id: 5fcc9c357b04e3eb3ba83d2d, topology_type: Single, servers: 
[<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, 
error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
2020-12-06 09:55:06,294 ERROR [pyramid_debugtoolbar][waitress-3] Uncaught TypeError at 
http://localhost:6542/tests
```

**Comment by vdbergh** [comment]
Ok it seems that mongod is not starting....

**Comment by vdbergh** [comment]
This is the mongod error
```
{"t":{"$date":"2020-12-06T10:42:56.765+01:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
```
I do have wiredtiger installed (whatever that could be). Googling didn't help so far.

**Comment by vdbergh** [comment]
Ok WiredTiger is a "storage engine". This is what the manual has to say:
```
If  you  attempt to start a mongod with a --dbpath that contains data files produced by a storage engine other than the one
              specified by --storageEngine, mongod will refuse to start.
```
Retrying with an empty data directory /var/lib/mongodb finally allowed me to start mongod. So I guess the new question becomes:

Can I save my old database somehow (I renamed to old data directory as /var/lib/mongodb_org)?

**Comment by ppigazzini** [comment]
@vdbergh be sure to update the mongodb setup for Ubuntu 20.04
`# install mongodb community edition for Ubuntu 18.04 (bionic), change for other releases`
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

I started a setup in a Ubuntu 20.04 vm.

**Comment by ppigazzini** [comment]
@vdbergh the easier way to save/restore all the mongodb content is:
```
mongodump # save a "dump" folder with dbs and collections, tar and move somewhere
mongorestore --drop # restore dbs and collections from a "dump" folder

```

This is the way used in the backup script to save some space:
```
cd ${HOME}/backup
for db_name in "fishtest_new" "admin" "fishtest" "fishtest_testing"; do
  mongodump --db=${db_name} --numParallelCollections=1 --excludeCollection="pgns" --gzip
done
tar -cv dump | gzip -1 > dump.tar.gz
rm -rf dump
```

```
cd ${HOME}/backup/restore
tar -xzvf dump.tar.gz
mongorestore --gzip --drop
rm -rf dump
```

**Comment by ppigazzini** [comment]
@vdbergh I successfully installed fishtest in a fresh Ubuntu 20.04 VM with that mongodb related one line change in the setup script, also restored the latest mongodb backup.

**Comment by ppigazzini** [comment]
@vdbergh if you have a backup from an old "storage engine" be sure to delete the *.json files from the "dump" folder before importing the backup in mongodb using "WiredTiger". This is the script used to update PROD form the old CentOS config https://github.com/glinscott/fishtest/issues/408

```
#!/bin/bash
# mongodb_restore.sh

bkp_dir=${HOME}/backup/restore
[ ! -d ${bkp_dir} ] && mkdir -p ${bkp_dir}
mv dump.tar.gz ${bkp_dir}
cd ${bkp_dir}
mongo fishtest         --eval 'db.dropDatabase()'
mongo fishtest_new     --eval 'db.dropDatabase()'
mongo fishtest_testing --eval 'db.dropDatabase()'

tar -xzvf dump.tar.gz && rm -f dump/*/*.json && mongorestore --drop
```

**Comment by vdbergh** [comment]
@ppigazzini Thanks! Closing this as the issue has been clarified.
