### ISSUE TITLE
Workflow for nets?

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#872]
On my local fishtest I tried to schedule a test of master vs master. I got...

Net not in repository: nn-62ef826d1a6d.nnue

Is this supposed to be correct? I thought nets were not part of the repository but stored in a separate location.

**Comment by vondele** [comment]
the local fishtest doesn't provide the api or doesn't have the local database needed for downloading the nets. Probably needs to be synced from fishtest master. The nets themselves are in a separate location.

**Comment by vdbergh** [comment]
The local fishtest was installed with Pasquale's script. It is up to date with master....

**Comment by ppigazzini** [comment]
@vdbergh I always take the lazy way to upload in the local fishtest server:
http://172.23.3.112/upload

the required net downloaded from:
https://tests.stockfishchess.org/nns

If I'm not wrong this action simply write the mandatory info in the db without side effects, @tomtor can help here :)

**Comment by vdbergh** [comment]
The net nn-62ef826d1a6d.nnue is present https://tests.stockfishchess.org/nns .

So the error message I get ("Net not in repository: nn-62ef826d1a6d.nnue") is not correct ...

Am I right? If so I can debug it.

**Comment by vondele** [comment]
your local fishtest needs a database of nets so that your local server can provide the redirect for https://my.local.server/api/nn/nn-018430ac30dd.nnue easiest is to upload that net to your local server and populate that database.

**Comment by vdbergh** [comment]
Ok I get it but this is an annoying extra step if one wants to do a quick test.

Is it necessary? The worker will download the net anyway right?

**Comment by vondele** [comment]
Don't recall where this is coming from exactly, but I think it is the server checking that the net required to build the binary is available. If not, it will fail to build and all workers that start that test will fail. It is a reasonable thing for the server to check.

For a quick check, maybe start a test of SF_11, that should circumvent the check.

**Comment by vdbergh** [comment]
@vondele Thanks. At least I now understand the issue. For now I will upload the net to my local Fishtest. The default net doesn't change all that often so it is not too much work.

@Pasquale Maybe this should be documented a bit better? Then the message could also be more illuminating (i.e. if the server detects it is not the official one, it could include a reference to the FishtestWiki).

**Comment by vdbergh** [comment]
So I "uploaded" the net to localhost:6542 but I found out it is not actually stored in the local fishtest since ` wget -S localhost:6542/api/nn/nn-62ef826d1a6d.nnue` shows that the dowload request is redirected to  `https://data.stockfishchess.org/nn/nn-62ef826d1a6d.nnue`. 

I guess that when I uploaded the net I did not really send it to data.stockfishchess.org (that would be a security risk) ... So what if I did a test on my local fishtest with a net that is not stored at data.stockfishchess.org ?

**Comment by ppigazzini** [comment]
@vdbergh the server setup script write an empty `fishtest.upload`, the fake upload simply write the net info in mongodb, at this point the local fishtest server starts working.
I should reverse engineering the upload infrastructure to document that component.

**Comment by vdbergh** [comment]
@ppigazzini Thanks.  That's what I thought. 

If I ever would want to do a local test with a new net then I could first upload it to the official SF site and then upload it again to the local site.

**Comment by ppigazzini** [comment]
@vdbergh I reviewed the NN upload infrastructure for the NN server migration (CentOS 8, SELinux is a nightmare...). In the weekend I should be able to write a setup script for Ubuntu.
By the way I updated PROD, DEV and the server setup script to python 3.9.5 (pyramid raised the compatibility).

**Comment by ppigazzini** [comment]
@vdbergh @vondele wiki server setup script updated with the the net server configuration.
Now it's possible to make local tests uploading and downloading a net on the local DEV.

Changelog:
- update `/etc/nginx/sites-available/fishtest.conf` with the post-server URI/upstream
- write the upload URI in `~/.fishtest.upload`
- write the post-server code/virtual_env in `~/post-server`
- write a systemd unit file for the post-server
- update with the DEV IP to have a local net server: https://github.com/glinscott/fishtest/blob/ef40d92e6daa7945a0e17aa59ce571fe93c179d9/server/fishtest/api.py#L224

Todo:
- document the nets workflow
- find an easy way to switch back and forth DEV between official net server and local net server

**Comment by ppigazzini** [comment]
- nets workflow documented
- the server setup script now writes a script to set the net downloading server

I think that this issue is finally closed :)

**Comment by vdbergh** [comment]
Thanks a lot!
