### ISSUE TITLE
Getting other user's heartbeat

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#878]
Just run fishtest-worker into my old notebook with one core:

![lol](https://user-images.githubusercontent.com/32866346/103907487-62931680-5112-11eb-91f7-32655e7f235b.jpg)

So heartbeat for TueRens 16 core (not for dew with only one core)

Magic and all of the hype?

**Comment by d3vv** [comment]
So, into my all worker-pool I've got "heartbeat" for various users except me..

**Comment by vondele** [comment]
that seems like a bug to me.

**Comment by d3vv** [comment]
@vondele okey-dockey, I will close an issue as well

**Comment by vondele** [comment]
shouldn't you leave the issue open until it is fixed?

**Comment by d3vv** [comment]
Hmm.. Ok - I just thought it was fixed (if I don't see it since your last message)

**Comment by d3vv** [comment]
Also, I never believe that 48 cores from grandphish2 are so faster then 105 cores from dew..

**Comment by d3vv** [comment]
С Рождеством, Православные!!

https://youtube.com./watch?v=7z_MB8EE7HI

**Comment by ppigazzini** [comment]
Another user reported the problem, see https://discord.com/channels/435943710472011776/733545871911813221/875403996095975514

**Comment by ppigazzini** [comment]
If the problem was a side effect of reassigning to another worker of an unfinished task then it has been solved by #1021
