### ISSUE TITLE
Production broke

### ISSUE THREAD

**Issue by NoTeefy** [glinscott/fishtest#880]
Not really a bug/issue but since I didn't really find any contact informations, I thought I'd mention it here.
Seems like the framework broke down, at least the frontend:
![grafik](https://user-images.githubusercontent.com/17280959/104827747-84527300-5861-11eb-9ad9-2645490f2795.png)
Are there any ongoing technical problems?

Best regards

**Comment by NoTeefy** [comment]
@snicolet @ppigazzini  @vondele

**Comment by NoTeefy** [comment]
The logs on all of my systems look like this: 
![grafik](https://user-images.githubusercontent.com/17280959/104827778-edd28180-5861-11eb-8ef2-e6bcd5bc5030.png)

I would be happy to contribute some servers in case you want to build in a loadbalancer/failover in case such a thing happens more regularly. Seems like it's caused by a network issue on the backend side.

**Comment by vondele** [comment]
just no active tests in that period.... nothing wrong as far as I know.

**Comment by NoTeefy** [comment]
That was my bad... was already pretty tired when opening up that issue. Should have double checked the remaining games on the tune job.
Sorry about the disturbance.

Best regards
