### ISSUE TITLE
Using Github with passwords is deprecated

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#881]
Hi all,

I have received the following email from Github, warning about the future deprecation of access with passwords for the git operations in August 2021.

>Hi @snicolet,
>You recently used a password to access the repository at snicolet/Stockfish with git using git/2.13.5 (Apple Git-94). Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
>Thanks, The GitHub Team

Since I suppose that all of us use command-line git commands to keep our master branch in synch with the stockfish-official master branch, we should probably all begin to switch to token authorizations right now, to avoid bad surprises in the summer. 

There is some documentation there: 
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

EDIT: all cross-posted in the fishcooking forum
https://groups.google.com/g/fishcooking/c/s_LkRfMezTE/m/Uqguv64kBQAJ

**Comment by ppigazzini** [comment]
@snicolet with https/token login should still work the `~/.netrc` file simply adding the field `machine github.com` for cli operations, see
https://github.com/glinscott/fishtest/wiki/Running-the-worker%3A-overview#github-api-requests-rate-limit
```
machine github.com
login <personal-access-token>
password x-oauth-basic

machine api.github.com
login <personal-access-token>
password x-oauth-basic
```

Anyway the github ssh authorization is unaffected by this Github policy change:
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/#timeline

To simplify the ssh login I wrote a `~./ssh/config` with:
```
# github git
Host github.com
   HostName github.com
   User git
   IdentityFile ~/.ssh/id_ed25519_gh
```
and configured the git remotes in this way:
```
origin  ssh://github.com/ppigazzini/fishtest.git (fetch)
origin  ssh://github.com/ppigazzini/fishtest.git (push)
upstream        ssh://github.com/glinscott/fishtest.git (fetch)
upstream        ssh://github.com/glinscott/fishtest.git (push)
```

**Comment by snicolet** [comment]
I have just updated the script "synch-with-official.sh" given in the wiki to use an URL with the **https** protocol instead of the **http** protocol for the remote name "official", because as I understand it tokens will only work with **https**.
See https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

To check if your current git remote named "official" uses the right protocol (**https**), run:

`git remote -v`

To change the URL of your remote named "official" to use **https**, run the following command:

`git remote set-url official https://github.com/official-stockfish/Stockfish.git`
