### ISSUE TITLE
Depth problem in STF 12

### ISSUE THREAD

**Issue by Wickdhub** [glinscott/fishtest#882]
Hello!

I don't understand something about depth in STF 12, in fact i thought it was basically the number of anticipated half moves, but when I run it, I sometimes have results with higher depth and less moves, for example:

> info depth 48 seldepth 51 multipv 1 score cp 23 nodes 19440223582 nps 9584151 hashfull 1000 tbhits 0 time 2028372 pv e2e4 e7e6 b1c3 d7d5 d2d4 g8f6 e4e5 f6d7 c3e2 c7c5 c2c3 d8b6 a2a3 b8c6 b2b4 c5d4 c3d4 a7a5 b4b5 b6b5 e2c3 b5b6 g1f3 b6d8 f1d3 f8e7 c3b5 f7f6 e5f6 d7f6 e1g1 e8g8 f1e1 c8d7 c1f4 f6e4 f4c7 d8e8 d3e4 d5e4

 has 40 half moves anticipated while

 

> info depth 43 seldepth 47 multipv 1 score cp 28 nodes 7457369869 nps 9860163 hashfull 1000 tbhits 0 time 756313 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 g8f6 f1d3 c7c5 c2c3 f8e7 e1g1 e8g8 h2h3 b8c6 f1e1 f8e8 c1g5 h7h6 g5f6 e7f6 d4c5 e8e1 d1e1 d5d4 d3e4 d8e7 e4d5 e7e1 f3e1 c8e6 d5e6 f7e6 c3d4 f6d4 b1c3 a8d8 a1d1 d4c5 d1d8 c6d8 e1f3

has exactly 43 half moves anticipated

The opposite can also happen beacause i found on the net (however not in stf12):

> info depth 65 seldepth 97 multipv 1 score cp 8 nodes 17288598093977 nps 9446437 hashfull 999 tbhits 0 time 1830171180 pv c2c4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g8f6 g2g3 e7e5 d4b5 f8b4 c1d2 a7a6 b5c3 d7d5 c4d5 f6d5 f1g2 c8e6 e1g1 d5b6 c3a4 b4d2 g2c6 b7c6 a4b6 d8b6 d1d2 e8g8 d2c2 f7f5 b1c3 f5f4 c3a4 b6a7 a4c5 a7f7 c5e6 f7e6 c2e4 f8f6 b2b3 f6h6 a1c1 e6h3 e4g2 h3e6 c1c4 a8d8 f1c1 f4g3 h2g3 d8d2 c4c6 e6c6 g2c6 h6c6 c1c6 d2a2 g1f1 g8f7 c6c7 f7f6 f2f3 a2b2 c7a7 b2b3 a7a6 f6e7 a6a7 e7f6 f1f2 b3b2 f2e3 f6g6 a7a6 g6g5

which has a 78 half moves anticipated.

Could you explain me where it comes from?

Thanks!

**Comment by ppigazzini** [comment]
Hello @Wickdhub, fishtest issues are about the testing framework :)
Please ask the question in the forum:
https://groups.google.com/g/fishcooking
