### ISSUE TITLE
Switch running workers to python 3.x

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#883]
With all workers running on python 3.x we could clean up the worker codebase dropping the python 2.x compatibility.
I open this issue to inform the few CPU contributors that are still running the workers on python 2.x .

---

@d3vv I'm wondering if , at your convenience, you could update to python 3.x these workers :)
| Machine | Cores | System | Version | UUI |
| - | - | - | - | - |
| dew | 6 | Linux 4.9.0-8-amd64 | 94:2 | e03b3415-c606-4595-9d94-16e2a7cb4750 |
| dew | 10 | Linux 4.1.15-gentoo-r1 | 94:2 | 292446ed-5ec9-4f0b-90bd-36a338fd7f64 |
| dew | 3 | Linux 4.9.76-gentoo-r1 | 94:2 | 510539fb-b601-44bf-a9b0-197a92a80a4d |
| dew | 9 | Linux 4.8.17-hardened-r2 | 94:2 | 88c14173-9f06-4f66-b174-21a3f62d04af |

To keep clean system python I'm using `pyenv` and `python3 -m venv`:
https://github.com/pyenv/pyenv

**Comment by d3vv** [comment]
@ppigazzini Could it possible provide UUIDs for such workers?
Thank You in Advance ;-)

**Comment by ppigazzini** [comment]
@d3vv table updated with UUID extracted from a db daily backup, hoping are correct :)

**Comment by d3vv** [comment]
@ppigazzini You said that need to avoid me and my workers..
Very cute..
Please be advised, I gave all the best and more workers instead, but you keep poking the Slovenian bear with a stick..
But in addition, you impose limits on my workers (all as you like)..
Go ahead and keep shooting at the foot of stockfish community..
But this shit doesn't mean fuck to me anymore.. And That it is.

**Comment by noobpwnftw** [comment]
What exactly is wrong with you? The top post has been updated with UUIDs.

**Comment by d3vv** [comment]
@noobpwnftw just read about avoids for my workers from @ppigazzini

**Comment by d3vv** [comment]
I'm sorry, men.. But if you corrected previous message (not new) - there is no alerts via e-mail and whatever..

**Comment by noobpwnftw** [comment]
It's all cool my friend, next time we let him know to notify you. :)

**Comment by ppigazzini** [comment]
@d3vv I wrote the second post to notify the update of the first post with the UUID :)

**Comment by d3vv** [comment]
@ppigazzini I'm sure You are corrected post about monthly backup and yada-yada..
In any case, please accept my apologies

**Comment by d3vv** [comment]
@ppigazzini Your words below?

@d3vv table updated with UUID extracted from a db daily backup, hoping are correct :)

**Comment by ppigazzini** [comment]
@ppigazzini yes, that is my second post in this thread.
If I'm not wrong the UUID should change with a worker restart, let me know if you need more recent UUIDs.

**Comment by d3vv** [comment]
@ppigazzini  let's be honest with ourselves here - turn off python two workers and problem solved

**Comment by noobpwnftw** [comment]
@ppigazzini I think he is complaining about machine limit.

**Comment by ppigazzini** [comment]
@d3vv the switch to python 3 is a very low priority task.
I helped other users to switch to python 3 writing by email, I wrote this issue only because I got no answer writing to you to im*******@ra*******.ru

At the moment you have a machine_limit = 40, let me know if I must raise it.

**Comment by ppigazzini** [comment]
By the way also the user TueRens has 2 workers (total 10 cores) on python 2, no answer by email.

**Comment by d3vv** [comment]
@ppigazzini I'll take a look about what is wrong.. "machine_limit = 40" - what does it mean? All, per ip or something else?
For some reason, I am glad that you are worried about a dozen workers, but do not worry about mine who have served you faithfully for more than one year..

**Comment by ppigazzini** [comment]
@d3vv at the moment you can start 40 different workers, the default is 16, see
https://github.com/glinscott/fishtest/blob/3362a3db2730be8eee1f58acde257e1d071b0336/server/fishtest/userdb.py#L104-L108

**Comment by d3vv** [comment]
Okey-dockey - I will remember 40..
If you have any suggestions I am ready to consider them or fulfill them

**Comment by ppigazzini** [comment]
I'm using pyenv to build the latest python 3:
- instructions (I use the git clone)
https://github.com/pyenv/pyenv
- prerequisites for some linux:
https://github.com/pyenv/pyenv/wiki#suggested-build-environment

Here my script for ubuntu:
```bash
# setup pyenv and install latest python
# https://github.com/pyenv/pyenv

if ! command -v pyenv &>/dev/null; then
  python_ver="3.9.1"
  sudo apt update; sudo apt install -y --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

  pyenv_dir="${HOME}/.pyenv"
  git clone https://github.com/pyenv/pyenv.git "$pyenv_dir"

  cat << EOF >> ${HOME}/.profile

# pyenv: keep at the end of the file
export PYENV_ROOT="\$HOME/.pyenv"
export PATH="\$PYENV_ROOT/bin:\$PATH"
if command -v pyenv &>/dev/null; then
  eval "\$(pyenv init -)"
fi
EOF

  . ${HOME}/.profile
  pyenv install ${python_ver}
  pyenv global ${python_ver}
fi
```

**Comment by ppigazzini** [comment]
@d3vv it seems to be easy to have several python versions in Gentoo:

https://wiki.gentoo.org/wiki/Python

```
Emerge
Python is slotted, which means there is more than one version Python that can be installed on a Gentoo system at the same time. Select the version to install by using an : (colon) and the package atom followed by one of the slot numbers:

For example, to install Python 3.8:

root #emerge --ask dev-lang/python:3.8
```

**Comment by d3vv** [comment]
@ppigazzini Thanks a lot for your advice. But as far as Gentoo is concerned, sometimes feel like I know more than a common developer of this distro..

**Comment by d3vv** [comment]
Most of my workers for fishtest are running on Gentoo.. But I'm Slackware guy initially as well :))

**Comment by d3vv** [comment]
I apologize for being too emotional earlier, but I think this issue should be closed, because I did everything as well'

**Comment by ppigazzini** [comment]
Thank you so much @d3vv :)

I'm keeping opened this issue for some days, the user TueRens sometimes starts a couple of workers on python 2.x.

**Comment by d3vv** [comment]
> I'm keeping opened this issue for some days, the user TueRens sometimes starts a couple of workers on python 2.x.

I wish TueRens and grandphish2 would repeat the mibere path. Though the numbers I made up mibere, but he was always with you and not variable..

**Comment by JojoM-sf** [comment]
`
![Screen Shot 2021-03-09 at 23 34 43](https://user-images.githubusercontent.com/63949174/110547461-3e62ae80-8130-11eb-92b7-8ba9ea549b9f.png)
`

**Comment by JojoM-sf** [comment]
Congrats, you've been having an emotional discussion 👍  (Haven't been around in a while.) Current standings on Python 2:

Machine | Cores | MNps | System | Version
-- | -- | -- | -- | --
Rudolphous | 8 | 1.46 | Windows 10 | 97:2.7.14
TueRens | 3 | 2.00 | Linux 5.4.0-62-generic | 97:2.7.17
TueRens | 7 | 1.18 | Linux 4.15.0-135-generic | 97:2.7.17

**Comment by zungur** [comment]
All the current workers seem to be running on Python 3.x. Is this a good time to drop 2.x compatibility?

**Comment by ppigazzini** [comment]
TueRens python 2.x workers join from time to time, but TueRens never answered to my emails, so I think that the only way is to drop the compatibility.

**Comment by ppigazzini** [comment]
Switch to python3 completed with #1085
