### ISSUE TITLE
Stuck tests

### ISSUE THREAD

**Issue by mstembera** [glinscott/fishtest#889]
I submitted these two tuning sessions:
https://tests.stockfishchess.org/tests/view/6042f6a3ddcba5f0627bb717
https://tests.stockfishchess.org/tests/view/6042f8eaddcba5f0627bb71a
but even after seeing workers get assigned to them and waiting a long time no tests ever ran.
(Other tuning sessions were running fine at the time.)  It may be that due to the Eigen/SVD library it takes SF a bit longer to start up causing some kind of time out? but that's pure speculation on my part.  I don't know what is preventing these tests from running?  Any help would be appreciated.
Thanks Fisherman

**Comment by ppigazzini** [comment]
@mstembera scheduled on DEV, my worker got this error:

```
Exception running games:
Traceback (most recent call last):
  File "/home/usr00/_git/__test_folder00/fishtest/worker/games.py", line 405, in setup_engine
    net = required_net_from_source()
  File "/home/usr00/_git/__test_folder00/fishtest/worker/games.py", line 127, in required_net_from_source
    with open("evaluate.h", "r") as srcfile:
FileNotFoundError: [Errno 2] No such file or directory: 'evaluate.h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr00/_git/__test_folder00/fishtest/worker/worker.py", line 227, in worker
    pgn_file = run_games(worker_info, password, remote, RUN, TASK_ID)
  File "/home/usr00/_git/__test_folder00/fishtest/worker/games.py", line 887, in run_games
    setup_engine(
  File "/home/usr00/_git/__test_folder00/fishtest/worker/games.py", line 432, in setup_engine
    raise Exception("Failed to setup engine for {}".format(sha))
Exception: Failed to setup engine for 1c4f802ebd8148773e5237eea68c8c15c2dd95fd
```

**Comment by mstembera** [comment]
Thanks.  I have no idea why it would complain about evaluate.h.  The patch has nothing to do with it.

**Comment by ppigazzini** [comment]
@vondele any idea?
https://github.com/glinscott/fishtest/blob/ddbfffe8980f0b304e807476955ae6fe277dd79f/worker/games.py#L122-L133

**Comment by vondele** [comment]
well, I could only guess that the file is not there (maybe git checkout failed?), or maybe that the worker ends up in the wrong directory after git checkout?

**Comment by ppigazzini** [comment]
@vondele ok, firts time I see using the SVD in SPSA, I will debug tonight what happen in the worker with those two tests.

BTW useful trick to get speedup and lower RAM requirement in SVD of matrix with big asymmetry in rows/columns:
```python
import numpy as np
a = np.random.rand(32, 512)

u0, s0, v0 = np.linalg.svd(a, full_matrices=False, compute_uv=True, hermitian=False)
a0 = u0 @ np.diag(s0) @ v0
print(np.allclose(a, a0))

u1, s1, v1 = np.linalg.svd(a @ a.T, full_matrices=False, compute_uv=True, hermitian=True)
s1 = np.diag(np.sqrt(s1))
v1 = np.linalg.inv(s1) @ u1.T @ a
a1 = u1 @ s1 @ v1
print(np.allclose(a, a1))
```

**Comment by ppigazzini** [comment]
@mstembera @vondele the eigen3 lib has a "src" folder, I'm testing the bugfix.

**Comment by ppigazzini** [comment]
@mstembera triggered the workers update

**Comment by ppigazzini** [comment]
@mstembera I lowered tests priority and throughput, now they are in paused mode but still with the workers allocated. Please consider to stop and rescheduled the tests.

**Comment by ppigazzini** [comment]
@mstembera the tests seems running fine now, I restored the default priority and throughput.

**Comment by mstembera** [comment]
@ppigazzini Thank you!
