### ISSUE TITLE
certain tests on fishtest 'unclickable' on firefox

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#893]
that's a weird issue, but 
https://tests.stockfishchess.org/tests/view/60448e3333eb56b2e8566d73

or similar tests with this patch yield a web page where I can't click on the buttons (like approve) using firefox. Something on the page appears to confuse it. Other tests in other tabs are fine. If I open another tab and go back to that tab, firefox doesn't display it. I see no useful error messages at first sight.

I'm on 86.0+build3-0ubuntu0.20.04.1 I assume it is a firefox issue rather than the webpage, but of course I don't know.

**Comment by tomtor** [comment]
I can reproduce it. After displaying the tab my gmail hangs in another tab.

Probably rendering the data in this specific graph causes the issue (hanging JavaScript in Firefox). Could be a JavaScript incompatibility between Chrome and latest Firefox. The graph rendering JavaScript library is a Google library.

**Comment by ppigazzini** [comment]
If I'm not wrong Google suggests a new way to render the graph (just played a bit yesterday to try to fix #884):  
https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code

**Comment by tomtor** [comment]
@ppigazzini Interesting to test if updating that code fixes this issue, but I expect it is not related.

I did not test other finished tests, do they work OK?

**Comment by vondele** [comment]
Others seem fine like https://tests.stockfishchess.org/tests/view/604246e0ddcba5f0627bb6b8

**Comment by dav1312** [comment]
Is this still an issue?

**Comment by vondele** [comment]
seems fixed
