### ISSUE TITLE
Using zip instead of 7z

### ISSUE THREAD

**Issue by cgrandsjo** [glinscott/fishtest#90]
Hi Gary,

Maybe it's better to use zip instead of 7z on this file https://s3-us-west-2.amazonaws.com/stockfish-fishtest/w64-portable/StockfishTesting.7z. Zip doesn't require you to download 7zip since Windows can handle the zip format out of the box.

Cheers,
Christian

**Comment by Stefano80** [comment]
This does not seem to be an issue. But feel free to code the improvement and open a PR if you feel so.
