### ISSUE TITLE
fishtest dead?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#907]
website seems down

**Comment by snicolet** [comment]
not accessible from my machine either

**Comment by tomtor** [comment]
@glinscott @ppigazzini Yes, it's completely dead (no ssh or ping response).

**Comment by ppigazzini** [comment]
No ssh for me too, DEV is up and running with the same ISP.
We must wait that @glinscott will have some free time to check the VPS.

**Comment by ppigazzini** [comment]
I loaded on DEV the latest DB backup saved `2021-04-10 06:14:26 1242410206 dump.tar.gz`

**Comment by ppigazzini** [comment]
@tomtor the fishtest log is full of messages about inactive workers. For example the Dantist workers started to be logged as inactive 5 days ago:

```
 sudo journalctl -u fishtest@6543 --since "5 days ago"

...
Apr 05 14:26:34 tests.stockfishchess.org pserve[24974]: Inactive: https://tests.stockfishchess.org/tests/view/606a99fd2b2df919fd5f0532 147 Dantist-7cores-3
Apr 05 14:26:41 tests.stockfishchess.org pserve[24974]: Inactive: https://tests.stockfishchess.org/tests/view/606a99fd2b2df919fd5f0532 147 Dantist-15cores-4
Apr 05 14:26:50 tests.stockfishchess.org pserve[24974]: Inactive: https://tests.stockfishchess.org/tests/view/6069fc422b2df919fd5f04f9 258 Dantist-7cores-3
...
```

**Comment by crossbr** [comment]
I'm getting a 504 Gateway Time-out.
