### ISSUE TITLE
RMS Bias values inconsistent with draw rate on SPRT calculator.

### ISSUE THREAD

**Issue by chuckstables** [glinscott/fishtest#909]
I was looking at the SPRT test calculator and I noticed an error with the math's. If we use a draw rate of 92.8% (approximately current LTC draw rates), it defaults to an RMS bias of 30 logistic elo. 30 elo for RMS bias is mathematically inconsistent (as far as I'm aware) with a draw rate of 92.8%. The following is a brief argument of why. 

For an RMS bias of B and a draw rate of D, the expected score (S) for engines of equal strength of white vs black is 1/(1+10**(-B/400)). The win rate W for white  is then S-D/2. The loss rate for white is then 1-D-W, which simplifies to 1-S-D/2. Because this is a probability it obviously has to remain positive. This implies that S has to be less than 1-D/2 (otherwise the loss rate is negative). Skipping some tedious algebra I end up rearranging to find that the maximum possible RMS bias is 400/ln(10)*ln(2/D - 1). For a draw rate of 0.928 this works out to be ~ 25 elo, not 30 elo (which is the default for the calculator).

This seems to be reflected in the raw statistics from recent LTC's; https://tests.stockfishchess.org/tests/stats/6070418fde8d5df05f51a2ca has an RMS bias of 21.251 and a draw rate around 92.8%, whereas this classical test https://tests.stockfishchess.org/tests/stats/606a690f2b2df919fd5f051c has an RMS bias of 31.894 and a much lower draw rate of 73.2%. 

If I'm completely wrong feel free to let me know, this is just something I've noticed. Thanks.

**Comment by vdbergh** [comment]
You are correct. I had also observed that the RMSbias is no longer 30 (logistic) Elo at LTC. I assumed that this is just the normal logistic Elo compression that comes with higher draw ratio. But your explanation is much more  explicit.

**Comment by vdbergh** [comment]
Actually. Maybe your explanation is not quite correct.

Note that the draw rate is an aggregate. A draw rate of `0.928` does not  mean that all the positions have such a draw rate between equal strength engines.

Assume that half of the positions have draw rate 1 and the other half has draw rate `0.856`.  Then the maximal scores are `0.5` and `0.572`. If the biases are maximal for each position then the RMS bias is `sqrt((0^2+0.072^2)/2)=0.0509` which converted to Elo is about `35`.

So I do not think that `RMSbias > 25` is mathematically impossible. But it is true that it becomes harder.

**Comment by vdbergh** [comment]
The SPRTCalculator checks that the variance is `>0` which comes down to `b<sqrt((1-d)/2)`. (`d=draw ratio`, `b=RMS bias` in score units). 

The upper bound  `sqrt((1-d)/2)` can be achieved with a book in which a fraction of `d` positions has draw ratio `1` and the other positions have draw ratio `0`, and furthermore all biases are maximal.

In this scenario all games have a predetermined outcome so the variance is `0`. 

So now I think that the SPRT calculator is correct.

**Comment by chuckstables** [comment]
> Actually. Maybe your explanation is not quite correct.
> 
> Note that the draw rate is an aggregate. A draw rate of `0.928` does not mean that all the positions have such a draw rate.
> 
> Assume that half of the positions have draw rate `1` and the other half have draw rate `0.856`. Then the maximal scores are `0.5` and `0.572`. If the biases are maximal for each position then the RMS bias is `sqrt((0^2+0.072^2)/2)=0.0509` which converted to Elo is about `35`.
> 
> So I do not think that `RMSbias > 25` is mathematically impossible. But it is true that it becomes harder.

So if half the positions have a draw rate of 1, then the maximum possible bias for that position is zero, correct? So I'm not sure where the other bias here is coming from.

**Comment by chuckstables** [comment]
I'm going to close this issue, since vdbergh explained the resolution quite convincingly. Thanks vdbergh.

**Comment by vdbergh** [comment]
Update: I edited my last reply since there was a spurious `sqrt(2)` factor.

Update2: It seems that "higher than expected" RMS biases occur for regression tests with the 8 moves book.

https://tests.stockfishchess.org/tests/stats/605c304bfa3cc97981cfaab7

`d=0.88917         b=0.07901` (score units)

So by your observation this means that the positions in that book are not all "equally drawish". Of course this is what you expect. But it is nice to have some kind of proof.
