### ISSUE TITLE
Test stuck. Bug?

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#912]
This test has been doing nothing since yesterday. 

https://tests.stockfishchess.org/tests/view/6075b6818141753378960617

There are two ghost workers.

**Comment by vondele** [comment]
yes, I think there is some bug, this is a recurring problem.

**Comment by vdbergh** [comment]
I gave it priority -10 now. Perhaps that will chase the ghost workers away...

**Comment by vdbergh** [comment]
Doesn't seem to be working. The ghost workers are sending some kind of heart beat. But no games.

**Comment by ppigazzini** [comment]
Stopping the server for 3 minutes didn't helped to clean the ghost workers...

**Comment by ppigazzini** [comment]
Hopefully with the recent big recent worker enhancement this should be solved.
