### ISSUE TITLE
NN upload timeout, corruped net on the list.

### ISSUE THREAD

**Issue by Sopel97** [glinscott/fishtest#913]
I tried uploading the same net twice (with different shas). These are just over 25 MB so it's enough that the upload takes more than 60 seconds (writing this just in case there is a 60s timeout...). Both of the times I got gateway timeout, and both times the net made it corruped onto the list (that's why I had to modify the net, because can't upload a duplicate). 

https://tests.stockfishchess.org/api/nn/nn-c9295d9d8a42.nnue

https://tests.stockfishchess.org/api/nn/nn-e428e2bee99e.nnue

**Comment by Sopel97** [comment]
Looks like the problem was on my side. Firefox has an http response connection timeout. I increased it to 300 seconds and now it went fine. Still, there's something on the server side that allows corrupted nets...

The setting is `network.http.connection-timeout`

**Comment by ppigazzini** [comment]
@Sopel97 those NN are not on the file server, and I don't found them in the "NN stats" page. We should check the DB to view where is the information that stops a second upload attempt.

**Comment by Sopel97** [comment]
![obraz](https://user-images.githubusercontent.com/8037982/115140754-2c323500-a039-11eb-8865-00dab809a07d.png)

**Comment by ppigazzini** [comment]
![image](https://user-images.githubusercontent.com/15718418/115141010-7b2c9a00-a03a-11eb-9b42-77e2999cbd50.png)

**Comment by ppigazzini** [comment]
@Sopel97 mmm, that page show different info after the login...

![image](https://user-images.githubusercontent.com/15718418/115141295-b4193e80-a03b-11eb-8383-4a661d5434d5.png)

**Comment by ppigazzini** [comment]
Fixed by #974
