### ISSUE TITLE
Fishtest installation only works if msys installation is in the C:/tools/msys64 instead of the default C:/msys64 (Windows)

### ISSUE THREAD

**Issue by PandaTobi** [glinscott/fishtest#917]
I spent an embarrassingly long time trying to debug this issue, only to find that when opened the 02_install_worker file with Notepad, it referenced a different directory than the default MSYS installation's. I think that it would be nice to change the installation files just a little bit so that it's easier to install, and won't require tweaking the files by hand.

**Comment by ppigazzini** [comment]
Sorry for the time loss but there is not an easy solution.

Chocolatey installs msys2 in `C:\tools\msys64` as default, an user had a bad update experience when customizing the installation folder, see the comment here
https://community.chocolatey.org/packages/msys2/

The fishtest wiki page reports to change the installation folder when installing msys2 by hand, see
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows
"download and start the one-click installer for MSYS2, change the installation folder to `C:\tools\msys64`"
