### ISSUE TITLE
Booking keeping issue with nets?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#919]
something is strange... 
both 
https://tests.stockfishchess.org/tests/view/608d83b895e7f1852abd2c6d 
and 
https://tests.stockfishchess.org/tests/view/608d2c7a95e7f1852abd2c1f 
mention nn-1a9420c9c1d3.nnue as the new_net.
The git diff on the same page shows only one of the two tests with this net, the first link seemingly being wrong.

https://tests.stockfishchess.org/nns shows I uploaded 6 nets, but only 5 show they have been tested (but hte download numbers are such that it is likely all 6 have actually been tested) https://tests.stockfishchess.org/tests/user/vdv shows I tested 3 standard nets (Elo around -30) and 3 Lc0 data nets (Elo around -60). With one canceled test in between (date: 21-05-01 )

As if the git diff or our book-keeping gets it wrong.

**Comment by TopoIogist** [comment]
There seems to be a race condition in the views.py that fetches the net
https://github.com/glinscott/fishtest/blob/8308edf4e1b245d3f922e4439f221094dae90a3e/server/fishtest/views.py#L416

It uses the git branch name to fetch the net

```
def get_net(branch, repo_url):
    """ Get the net from evaluate.h or ucioption.cpp in the repo """
    api_url = repo_url.replace(
        "https://github.com", "https://raw.githubusercontent.com"
    )
    try:
        net = None

        url1 = api_url + "/" + branch + "/src/evaluate.h"
```

Correct would be to use the sha commit id, as the branch could have changed in the meantime.
