### ISSUE TITLE
more precise identifier on actions

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#923]
For the cases where an action is a machine returning a wrong bench, it would be useful if we would somehow have an identifier that gives us which machine lead to the wrong bench (https://tests.stockfishchess.org/actions). There is some suspicion there is a fault CPU on noob's fleet, but it would be useful if we could pinpoint the machine.

**Comment by ppigazzini** [comment]
Solved by the recent big enhancement of the worker.
