### ISSUE TITLE
Can't Compile Stockfish

### ISSUE THREAD

**Issue by galacticue06** [glinscott/fishtest#926]
> Step 1/4. Building instrumented executable ...
> make ARCH=x86-64 COMP=mingw gcc-profile-make
> make[1]: Entering directory '/C/Users/****/Desktop/Stockfish-master/src'
> make ARCH=x86-64 COMP=mingw \
> EXTRACXXFLAGS='-fprofile-generate' \
> EXTRALDFLAGS='-lgcov' \
> all
> make[2]: Entering directory '/C/Users/****/Desktop/Stockfish-master/src'
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2   -c -o benchmark.o benchmark.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2   -c -o bitbase.o bitbase.cpp
> make[2]: g++: No such file or directory
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2   -c -o bitboard.o bitboard.cpp
> make[2]: g++: No such file or directory
> make[2]: *** [<builtin>: benchmark.o] Error 127
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [<builtin>: bitbase.o] Error 127
> make[2]: g++: No such file or directory
> make[2]: *** [<builtin>: bitboard.o] Error 127
> make[2]: Leaving directory '/C/Users/****/Desktop/Stockfish-master/src'
> make[1]: *** [Makefile:880: gcc-profile-make] Error 2
> make[1]: Leaving directory '/C/Users/****/Desktop/Stockfish-master/src'
> make: *** [Makefile:740: profile-build] Error 2
> Makefile.sh: line 38: strip: command not found
> mv: cannot stat 'stockfish.exe': No such file or directory
> make: g++: No such file or directory
> make: g++: No such file or directory
>

I'm pretty sure that I'm following building steps as I'm supposed to but I get this error no matter what. I have tried compiling it with gcc too, but it says that gcc is not recognised as a command, even if I have installed it.

I'm using Windows 8.1 OEM version(64-bit) and MSYS2

Thanks in advance.

**Comment by vondele** [comment]
well it clearly can't use the compiler g++ so something is not setup correctly in your compiler/tools

**Comment by galacticue06** [comment]
What can be done about it? 
(Sorry, I'm new to these things)

**Comment by galacticue06** [comment]
Thanks for your help. It turns out that the issue I was facing with was caused by a 3rd party installation of MinGW. Deleted the MinGW and MSYS2 installation and reinstalled MSYS2. The issue seems to be solved
