### ISSUE TITLE
Can't seem to run more then 16 clients

### ISSUE THREAD

**Issue by mlang** [glinscott/fishtest#934]
It looks like I can't run more then 16 clients at a time.
I grabbed a personal access token from github and put it in ~/.netrc to
work around the rate limit of 60/hour.  However, if I start more
then 16 clients I get a "No tasks available at this time" message.
Given the queue, I am suspecting I am hitting another limit.
I could run up to 100 clients, although not on a regular basis.
My fishtest account is mlang.  Maybe you could raise the account-specific limit
to 100?

**Comment by ppigazzini** [comment]
@mlang Limit raised to 100 :)

**Comment by mlang** [comment]
Thanks!

**Comment by SFisGOD** [comment]
@mlang Thank you so much for your generous contribution. I think mlang should be recognized @vondele @ppigazzini

**Comment by ppigazzini** [comment]
We update from time to time the "Top CPU Contributors.txt", see

https://github.com/official-stockfish/Stockfish/blob/master/Top%20CPU%20Contributors.txt

I will glad to update the file as soon as @mlang will overtake @d3vv for the second place ;)

By the way, thank you @mlang @d3vv for your extraordinary contribution :)
