### ISSUE TITLE
Worker failing to setup

### ISSUE THREAD

**Issue by armo9494** [glinscott/fishtest#939]
I had problems today with setting up fishtest. The worker was setup and working yesterday at number of cores set on 20x. Tried to change today from 20x to 30x today and as usual the install cmd asked for username/password and number of cores. Tapped in and cmd could read trough everything and closed. Then went to the fishtest worker and started as usual, but the cmd says incorrect password or username for some reason.
Im 100 percent sure my username and password is right because i tried to login on fishtest to see if maybe the password was incorrect.
I also tried to delete the worker and redownload and now nothing is working.
I run 00_install_choco_msys2_admin.cmd as an admin and nothing happens other than a cmd flashing for a brief second and closing. 
Then i run 02_install_worker.cmd as admin and nothing happens. Fishtest worker is not being created...
Tried redownloading few times, restarted the computer etc. Still not working. 

this is the error message 
![Skärmbild (7)](https://user-images.githubusercontent.com/85809973/121807584-0ac68180-cc55-11eb-9b8a-2e5f7b209c6a.png)

EDIT: Managed to fix netsh.exe error by creating env variable path.

then i get a new error this is it. Couldnt find any fixes to this.

![Skärmbild (11)](https://user-images.githubusercontent.com/85809973/121809039-89beb880-cc5b-11eb-8ce0-5297cf7b8404.png)

**Comment by ppigazzini** [comment]
@armo9494 The worker setup script is working fine for me in a clean windows 10 virtual machine.
Running `00_install_choco_msys2_admin.cmd` seems to have broke your msys2 setup.
Try this fix:
 - uninstall msys2
   - open a powershell admin prompt and write `choco uninstall msys2 -y`
   - delete the `c:\tools\msys64` folder
   - revert your custom changes (if any) 
 - run `00_install_choco_msys2_admin.cmd` as admin
 - run `02_install_worker.cmd` as normal user

**Comment by armo9494** [comment]
@ppigazzini 
Since my computer was just 1 day old i just formated everything and that seems to have solved the issue. Maybe something went wrong with msys. Its solved regardless. Maybe if the issue re appears i can try your suggested method. Ill close this for now.
