### ISSUE TITLE
fishtest down

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#943]
right now seems not reachable.

**Comment by ppigazzini** [comment]
@glinscott the VPS it's unreachable for me. Can you check please?

**Comment by vondele** [comment]
back up

**Comment by vondele** [comment]
hmm back down

**Comment by ppigazzini** [comment]
VPS down. The syslog had some strange entry for a couple of hours ago. If @glinscott didn't restarted the VPS, then could be a problem of the US node. DEV is on Nederland node.

**Comment by glinscott** [comment]
This was some unplanned downtime at the VPS host, they resolved it this morning.
