### ISSUE TITLE
Time losses in tunes

### ISSUE THREAD

**Issue by SFisGOD** [glinscott/fishtest#961]
@ppigazzini It seems that @JojoM-sf workers have consistent time losses in my tunes.
Https://tests.stockfishchess.org/tests/view/60d5510642a522cc50282ef3

![image](https://user-images.githubusercontent.com/38142170/123742063-ac003980-d8dd-11eb-87e5-ffbe3a320314.png)

I purged them but I think it doesn't undo the iterations in those losses.

Is there a way for these workers to avoid my tuning runs?

**Comment by ppigazzini** [comment]
@SFisGOD there is no way to associate/ban workers for a test. IMO purging in SPSA has no effect. The "mad" worker results have already shifted the search path.

**Comment by ppigazzini** [comment]
@JojoM-sf please check your workers, thank you :)
