### ISSUE TITLE
Using cloud servers to boost fishtest

### ISSUE THREAD

**Issue by xoto10** [glinscott/fishtest#965]
There's a wiki page [Running the worker in the Amazon AWS EC2 cloud](https://github.com/glinscott/fishtest/wiki/Running-the-worker-in-the-Amazon-AWS-EC2-cloud) but it's quite old now, does anyone know if these instructions still work / if there are other cloud servers that can provide high-quality cpu at a good price?

**Comment by vondele** [comment]
I think the instructions are now outdated, but the principle still applies.

**Comment by xoto10** [comment]
Yes, that was my guess. I looked at the aws website and the c4.8xlarge machines are still available, so that bit still applies. The Ubuntu version will presumably be more modern now, but maybe that doesn't make any difference anyway. I imagine there are decent alternatives nowadays, but I don't suppose anyone does this so it would take some investigation. It's too expensive (for me) to use on any scale, but I thought maybe it would be interesting to investigate again ...

**Comment by candirufish** [comment]
Google cloud offers free $300, no guide on how to run fishtest there though. Same for linode or digital ocean they offer $100 free if you know where to look. If you like to build one yourself 2x 2650l v4 14c 28t at 145 usd is probably best for fishtest price wise, or 2682 v4 if you play engine chess and ghz matters.
