### ISSUE TITLE
Fishtest only using 1 x Xeon on multi Xeon server

### ISSUE THREAD

**Issue by pjdouillard** [glinscott/fishtest#97]
I have access to some multi Xeon servers, and I would like to know how to setup Fishtest to use all the nodes (socket) and not just 1 node ?

I am using the Fishtest-Portable-Worker but when I run the RUN_FIRST_PROFILER, it only detects 1 Xeon and I can only set concurrency to Max-1 core of that single Xeon.

Anyone can help with this?
Thx!

**Comment by ppigazzini** [comment]
Hi pjdouillard, this post in the forum should help you 

https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/tuhee1WDOTY

Anyway I suggest to post this type of problems in the forum.

Regards

**Comment by pjdouillard** [comment]
Thank you!  I had found that I could change it that parameter and spread the load on multiple core, but that you would also need to turn off HT.  I would like to know more about how to set the Affinity parameter if possible.

Regards
