### ISSUE TITLE
Net downloads failing?

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#973]
$ wget https://tests.stockfishchess.org/api/nn/nn-59cf1ac2e4fa.nnue
--2021-07-26 20:34:29--  https://tests.stockfishchess.org/api/nn/nn-59cf1ac2e4fa.nnue
Resolving tests.stockfishchess.org (tests.stockfishchess.org)... 185.83.217.134
Connecting to tests.stockfishchess.org (tests.stockfishchess.org)|185.83.217.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://data.stockfishchess.org/nn/nn-59cf1ac2e4fa.nnue [following]
--2021-07-26 20:34:29--  https://data.stockfishchess.org/nn/nn-59cf1ac2e4fa.nnue
Resolving data.stockfishchess.org (data.stockfishchess.org)... 104.25.158.9, 172.67.80.249, 104.25.159.9, ...
Connecting to data.stockfishchess.org (data.stockfishchess.org)|104.25.158.9|:443... connected.
HTTP request sent, awaiting response... 521 
2021-07-26 20:34:30 ERROR 521: (no description).

**Comment by ppigazzini** [comment]
I will be at the keyboard in 45 minutes.

**Comment by vondele** [comment]
this could be something cloudflare related? https://support.cloudflare.com/hc/en-us/articles/115003011431-Error-521#521error 
and maybe depending on the location. See also https://discord.com/channels/435943710472011776/813919248455827515/869294639541256242

**Comment by vondele** [comment]
thanks working now :-)

**Comment by vondele** [comment]
hmm not yet, different error:
```
$ wget https://tests.stockfishchess.org/api/nn/nn-3961e59d8d07.nnue
--2021-07-26 22:10:18--  https://tests.stockfishchess.org/api/nn/nn-3961e59d8d07.nnue
Resolving tests.stockfishchess.org (tests.stockfishchess.org)... 185.83.217.134
Connecting to tests.stockfishchess.org (tests.stockfishchess.org)|185.83.217.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://data.stockfishchess.org/nn/nn-3961e59d8d07.nnue [following]
--2021-07-26 22:10:19--  https://data.stockfishchess.org/nn/nn-3961e59d8d07.nnue
Resolving data.stockfishchess.org (data.stockfishchess.org)... 172.67.80.249, 104.25.158.9, 104.25.159.9, ...
Connecting to data.stockfishchess.org (data.stockfishchess.org)|172.67.80.249|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 22:10:19 ERROR 404: Not Found.
```

**Comment by vondele** [comment]
only for that one net, however.

**Comment by ppigazzini** [comment]
```
ls -la nn-3961e59d8d07.nnue
ls: cannot access 'nn-3961e59d8d07.nnue': No such file or directory
```

**Comment by vondele** [comment]
yeah, seems to be missing on the server: nn-3961e59d8d07.nnue

**Comment by ppigazzini** [comment]
We can copy manually: do you have a copy?

**Comment by vondele** [comment]
I don't be I can ask in discord or @MichaelB7

**Comment by vondele** [comment]
I wonder if we can avoid adding it to the db if the upload to the server fails one way or another.

**Comment by ppigazzini** [comment]
The DEV server setup script now install also the net upload server, so that check can be added.

**Comment by ppigazzini** [comment]
net uploaded, I'm able to download it using the IP or the FQDN, but form the CDN I still got "404 file not found"
```
wget http://156.248.75.97/nn/nn-3961e59d8d07.nnue
wget https://fishnet-new.v7f.eu/nn/nn-3961e59d8d07.nnue
wget https://tests.stockfishchess.org/api/nn/nn-3961e59d8d07.nnue
```

**Comment by vondele** [comment]
a trick download the latter via a browser:
```
https://data.stockfishchess.org/nn/nn-3961e59d8d07.nnue?test=0
```
works for me.

**Comment by ppigazzini** [comment]
So it's should be an answer cached by the CDN. @MichaelB7 has already uploaded a functional copy of the net with different sha256, see https://discord.com/channels/435943710472011776/813919248455827515/869395885136678932

**Comment by vondele** [comment]
ok, so let's consider this solved for now.

**Comment by ppigazzini** [comment]
Some references.

Cloudflare requires a good nginx cache configuration to avoid problems:
https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN
https://support.cloudflare.com/hc/en-us/articles/115003206852-Understanding-Origin-Cache-Control

I deleted `cache-control` directive and `expires` response header from the nginx configuration to use the Cloudflare default cache ttl.

```
curl -skI https://fishnet-new.v7f.eu/nn/nn-3961e59d8d07.nnue
HTTP/2 200
server: nginx/1.14.1
date: Tue, 27 Jul 2021 09:47:54 GMT
content-type: application/octet-stream
content-length: 47721371
last-modified: Tue, 27 Jul 2021 01:22:36 GMT
etag: "60ff5fdc-2d82b9b"
strict-transport-security: max-age=31536000; includeSubDomains
accept-ranges: bytes
```

Unfortunately now the CDN has that "404" page cached for 1 year, IMO only @daylen could clear the cache.
```
curl -skI https://data.stockfishchess.org/nn/nn-3961e59d8d07.nnue
HTTP/2 200
date: Tue, 27 Jul 2021 09:50:56 GMT
content-type: application/octet-stream
last-modified: Tue, 27 Jul 2021 01:22:36 GMT
etag: W/"60ff5fdc-2d82b9b"
expires: Wed, 27 Jul 2022 01:45:11 GMT
cache-control: max-age=31536000
strict-transport-security: max-age=31536000; includeSubDomains
cf-cache-status: HIT
age: 29144
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=zOjcF%2Bx2O52eoJiJbdD6Mpl6jWB13sRbls2KvPc4EPj8miCUTjGViqKxglAXtgjHKT40Q6XBD8qSrCkebR%2FQh%2BeFI8kczwUQ73kCriwGCB9Z3P5DW%2F1j8gnhTGKSXDrLj328ImPDM9uy"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6754f7642904fc8d-FCO
```

**Comment by daylen** [comment]
Purged https://data.stockfishchess.org/nn/nn-3961e59d8d07.nnue from the CloudFlare cache; it downloads for me now.

**Comment by ppigazzini** [comment]
Thanks!
This is the new info from `curl`:
```
curl -skI https://data.stockfishchess.org/nn/nn-3961e59d8d07.nnue
HTTP/2 200
date: Tue, 27 Jul 2021 13:41:03 GMT
content-type: application/octet-stream
last-modified: Tue, 27 Jul 2021 01:22:36 GMT
etag: W/"60ff5fdc-2d82b9b"
strict-transport-security: max-age=31536000; includeSubDomains
cache-control: max-age=14400
cf-cache-status: HIT
age: 153
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=FRIE1jemI25P2KYHP3%2BzuxpWSsrg%2Bhu5OUqrsY7n%2FFi7TduV7RK3cxdLA8uf%2Bakn79bBlbuXtxrI%2FuGjh1OeTBV%2FhW%2Bvlc%2FW7R9JHdC0OPOtPaoRFH1Ms4Qqr%2BHT97FLNwQYiNsy3Va%2B"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6756487bbb43fc89-FCO
```

**Comment by ppigazzini** [comment]
> I wonder if we can avoid adding it to the db if the upload to the server fails one way or another.

@vondele if I'm not wrong adding a `return {}` for the `exception` should do the trick: 
https://github.com/glinscott/fishtest/blob/b8d34874bbcdc730010012619049d57146da6f12/server/fishtest/views.py#L124-L141

**Comment by ppigazzini** [comment]
fixed by #974

**Comment by ppigazzini** [comment]
@daylen sorry to bother you but it seems that Cloudflare is caching the "404" for these 3 files past the `cache-control max-age`. Could you clear them with the control panel?

https://data.stockfishchess.org/nn/nn-f31e5e1cd71f.nnue
https://data.stockfishchess.org/nn/nn-79c03ba207ef.nnue
https://data.stockfishchess.org/nn/nn-3c0aa92af1da.nnue

```
~$ curl -skI https://data.stockfishchess.org/nn/nn-f31e5e1cd71f.nnue
HTTP/2 404
date: Fri, 13 May 2022 21:32:34 GMT
content-type: text/html
strict-transport-security: max-age=31536000; includeSubDomains
cache-control: max-age=14400
cf-cache-status: HIT
age: 14870
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=GNOgqS9afGXaJaMPBYmIFI7kEEJ%2B4kxN9n7tM0DK7j1NgcxmOZOo13mVJxsIXSo0WtA6bCyBh2crXqprYTRaIlEO8koy0Xbei62lkoE7mwobPRGz19%2FhQtWlQMMZ7xeTIA1c8VHVOtFb"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 70ae81ed1b570f86-MXP
```

**Comment by daylen** [comment]
Purged those 3 urls. Should take effect within a minute.

**Comment by ppigazzini** [comment]
Cleared, thank you!
