### ISSUE TITLE
cloning wiki

### ISSUE THREAD

**Issue by Dboingue** [glinscott/fishtest#975]
Hi, this probably a github issue, and if so please, kindly help me ask in a better context, if within your knowledge.  

Motivation: I would like to use my desktop search tools and other meaning oriented tools to start digest the wiki here.  And I use windows (I have had problems in the past with entries containing :, for example, which would prevent cloning the whole wiki for just one page with a windows non-legit filename).  There is not the same fork, and modification tool I think with wikis (unless there is).  And my error message in this repository is not as precise.

Problem: here is the verbatim of the error.
`fatal: unable to update url base from redirection:
  asked for: https://github.com/glinscott/fishtest/wiki/Regression-Tests/info/refs?service=git-upload-pack
   redirect: https://github.com/glinscott/fishtest/wiki/Regression-Tests`
I ommitted the first line referring to my file management structure.  I am using Github desktop using the URL from the wiki page.

1. Are you aware of this problem?. 
2. Is this specific to this repo. wiki?
3. I there a quick fix?
4. I there any compressed source anywhere I could work with meanwhile?
5. any hints where to look next. (obviously searching google with clone wiki errors of the sort above, but more useful?)

Thanks for reading. 
I know, only about documentation.  But hey, I might get more interested in the code with better exposure.  I might even understand the whole information flow between the Development SF pipeline of testing and all the values in the SF executable, and live to tell the tale afterward.

**Comment by ppigazzini** [comment]
After forking on GitHub the fishtest repo I setup the local wiki repo in the usual way with the `git` command line:
```
git clone https://github.com/ppigazzini/fishtest.wiki.git
cd fishtest.wiki
git remote add upstream https://github.com/glinscott/fishtest.wiki.git
```

But I use this only to keep up to date the wiki on my fork.
