### ISSUE TITLE
Serverside-logging ... which of my servers under-perform..?

### ISSUE THREAD

**Issue by Technologov** [glinscott/fishtest#979]
Server-side , it assigns jobs to workers per amount of cores. Therefore it can estimate the amount of results (games played) per hour of time.
The results should be actual results and expected results (expected work completed)

my goal here is to minimize CPU under-utilization (and wasted CPU cycles) and monitoring entire fleet of servers at once, rather than on a one-by-one basis.

So I would like to know which of my servers perform well, and which do not (including server host-names).
Workers must allow to report host-names to the fishtest server (Leela training client has a parameter like --report-hostname )... so Fishtest should have similar 

-Alexey "Technologov ", 1.8.2021

**Comment by Vizvezdenec** [comment]
I honestly don't remember why we even have such a small batches like 200.
With current fishtest mostly being run on 8+ core machines and also now some massive 50+ cores servers it would make a lot of sense to make batches bigger, like 1000-2000 games easily.

**Comment by Sopel97** [comment]
Other things that could be displayed for each worker:

- residual
- number of completed games
- time spent on downloading the nets
- time spent on compilation
- time spent on running cutechess
- effective time control scaling factor
- list of (last N) completed batches
- bench variance (if we measure it many times for the same configuration)
- CPU arch (the arch defines and ARCH=...)
- ip (possibly for logged users only)
- cpuid/lscpu (would also show any vulnerability mitigations if applied)
- OS

**Comment by Technologov** [comment]
* number of expected games to be completed (time x amount of cores)

**Comment by ppigazzini** [comment]
@Technologov added in the machines/tasks tables the first 8 hex digits from the worker "uuid.txt" (this change at any worker start)
Some info about the CPU idle time:
 - the worker keeps the last 50 engine binaries to lower the building time
 - the worker keeps the last 10 nets to lower the download time
 - a recent CPU is working fine with virtual cores from HT (IIRC the noob's fleet always used the virtual cores and IMO also other fleets are using virtual cores)

**Comment by Technologov** [comment]
Can I, the user, see everything mentioned above per worker, from the server? How?

**Comment by ppigazzini** [comment]
> Can I, the user, see everything mentioned above per worker, from the server? How?

No, the server collect only some information of the worker (e.g. CPU ARCH and OS).

Please consider that some users have dynamic/private IP, on the same PC an user can run several workers, sometimes with only physicals cores sometimes with virtual cores, an user can change from time to time the `concurrency` of the workers, some workers fleet are VMs/containers.

So we are identifying a worker generating a random UUID at any start of the worker, check the `fishtest/worker/uuid.txt` file.

The list from @Sopel97 makes sense only for PC dedicated full time to fishtest, otherwise some of those indicators will be pure garbage.

**Comment by Technologov** [comment]
Then it doesn't solve the problem

**Comment by ppigazzini** [comment]
You could collect the workers output (we can add some output if needed) and servers info on your side with a dashbord, eg https://grafana.com

Please mind that the fishtest server is running on a very little VPS, so not easy to add load:
 - 4 cores but we can use only 2 cores at 100% or the IPS will power off the VPS for abuse
 - 4 GB ram no swap disk
 - 100 GB hard disk (only 31 GB free now...)

**Comment by ppigazzini** [comment]
@Technologov please mind that is normal to read sometimes `MNps = 0.0` for a worker in home page:
 - the worker is added in the machines table (home page) after receiving a task from the server. At that moment the MNps is unknown, so `MNps = 0.0`
 - the server gets the MNps information only when the worker posts the first `batch_size` of finished games (IIRC 8 games for SPRT test)
 - the home page information is updated every N seconds to keep the load low

| Machine | Cores | UUID | Mnps | System | Version | Running on | Last updated |
| -- | -- | -- | -- | -- | -- | -- | -- |
| technologov | 8 | b5462690 | 0.00 | Linux 4.15.0-143-generic | 102:3.6.9 | d1CaptP2 | seconds ago |
