### ISSUE TITLE
Minimum Nps?

### ISSUE THREAD

**Issue by pjdouillard** [glinscott/fishtest#98]
I am just starting to help on Fishtest, but the more I look into how it is done, the less I understand why you need to calculate the speed of the processor (core) before allowing it to run.  

Now I don't know much about chess programming, but I would like to understand why I read stuff like 'game quality' being less on slower processor vs faster ones (or also in the case of HT being On or Off).  

Isn't the tests run on our machines there to validate that new committed code hasn't broke anything, and that those tests' results are already known in advance?

Thanks to clarify this for me.  And if this is not the right place to ask this, please tell me where.

Regards

**Comment by ppigazzini** [comment]
Without time normalization, during a STC game (10 + 0.1) a very slow CPU could reach a depth of 2-3 ply for each move: the move should be nearly random. A very fast CPU could reach a depth of 12 ply, with a more accurate play.

Fishtest benches the CPU speed to normalize the time control of the game: for a slow CPU the time is increased, for a fast CPU the time control is reduced. In this way two workers, the first with a slow CPU and the second with a fast CPU, reach similar depths during a move: comparable game quality and comparable test results.

HT on old CPU was not efficient and introduced slow down and statistical noise in test, so in the past was better to switch off the HT in the BIOS.

On modern CPU HT is very efficient, so (IMO) is better to keep the HT switched on: Kai Laskos measured the ELO gained using the virtual cores on a modern CPU

http://talkchess.com/forum/viewtopic.php?t=61408

Regards

ps: I suggest to post these questions on the forum

https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

**Comment by pjdouillard** [comment]
I tend to agree with you and others that HT does help the engines more often then not, and that's why I don't understand (and question) the argument about game quality being worse when done on HT machine that uses more than the CPU nb of cores (e.g, 10 threads on a 6-core CPU).  I have done countless of tests (on different CPU architecture) about this and the result is that HT (in the current era) does improve the calculations AND precision of an engine. The few cycles that are wasted for HT handling is way more than compensated by the largeness of position evaluated and less pruning of good 'lines' that 'looked' bad but were in fact very good and often the best line to follow.

I say this also because the whole "HT is bad" argument is easily defeated when you take 2 identical CPUs, one running on its stock clock no HT enbled vs a 2nd one being overclocked and using HT.  The OC'd cpu DOES perform better in all aspects (plies AND Nps) vs the non-HT enable CPU but strangely it gets bugged down in some speed evaluation.  So limiting CPU based on it's speed vs the number of 'core' is very strange way to have processing power when the limitation is so high.

I will close this thread then, but first, let me finish with thiss. 

Taking into account the speed of a CPU to perform test is a strange way to validate the tests.  Maybe tests should be separated between 'performance' oriented one (where the speed of the CPU is required to show improvement in the 'time limited constraint') vs 'precision' oriented test (where the rightness of calculations are validated, because time is not an issue, and see if they are more precises (the evaluations) than before).  IMO you can't mix both of these tests as they are not relevant to the same situation.

**Comment by ppigazzini** [comment]
I'm not an expert on SPRT tests, search the forum ("Draw ratio", "SPRT" etc.) for more information on exact formulas. 
Anyway a SPRT test should work using the W/D/L ratios, so the time control must be normalized with the CPU in order to be able to compare the workers' results. With a not normalized time control a very fast CPU will have a Draw number higher than a very slow CPU.

Regarding HT, the problem is if the virtual cores introduce noise during a test in fishtest.

HT was historically bad for fishtest because a bug with the time control normalization with HT. The bug was fixed with this PR
https://github.com/glinscott/fishtest/pull/73

Users (and also maintainers) are not always updated with all stockfish/fishtest improvements and tests, some changes are accepted slowly, so HT in fishtest is still reported as bad.

Anyway I measured the noise introduced using virtual cores:
https://groups.google.com/d/msg/fishcooking/2gswm_us0bs/IR1hTILSCwAJ

**Comment by pjdouillard** [comment]
I am too new in the FishTest ecosystem to understand what you said.  I don't know what SPRT is nor what noise really is in the context.  How can I contact you privately so we can take this conversation offline?

**Comment by ppigazzini** [comment]
1. read all the wiki's pages starting with the FAQ :)
https://github.com/glinscott/fishtest/wiki/Fishtest-faq

2. search the fishcooking forum for key words
https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

3. post your questions in fishcooking forum: you will have support from different type of users (developers, testers, statistical etc.) and you will be able to view the e-mail addresses for offline conversations
