### ISSUE TITLE
Chi square test no longer valid with unbalanced book

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#998]
The p-values of the chi square test are now unrealistically high (under the null hypothesis they should be uniformly distributed). This is because the basic assumption of the chi square test, that the game outcomes are independently drawn from a trinomial distribution, is no longer valid. 

The solution is simple in principle, we should use the pentanomial frequencies instead.

**Comment by vdbergh** [comment]
But… with the small chunk size of 200 that would mean that the ww and ll cells would get too few hits. So it seems reasonable to coalesce ww+wd and ll+ld. This has the added advantage that we can keep the current layout of the page.

**Comment by NightlyKing** [comment]
In PR #988 the chunk size is set to a thousand games. Would that cause enough hits for ww and ll cells?

**Comment by ppigazzini** [comment]
The auto purge was disabled after the NNUE introduction (hypothesis: outcomes dependent from ARCH), see #760

**Comment by vdbergh** [comment]
I didn't think of the fact that the chi2 test is done per worker. But even so the ll and ww frequencies are currently very low, especially for LTC. See e.g. here https://tests.stockfishchess.org/tests/stats/6124735e5318138ee120481a

About the ww frequency is 0.1%. So a worker must contribute at least 10000 games for its cell count to be >= 5.

**Comment by vdbergh** [comment]
This is now fixed.

**Comment by ppigazzini** [comment]
@vondele @vdbergh DEV updated with a recent DB backup and fixed by hand to show the old chi2/residuals to check if we could revert #760 (perhaps the code now behave better with different ARCHs):

This is one of the tests that one year ago triggered that PR:
https://tests.stockfishchess.org/tests/view/5f01a78059f6f0353289439b
https://dfts-0.pigazzini.it/tests/view/5f01a78059f6f0353289439b

**Comment by vondele** [comment]
not sure that we can fix the fundamental reason that a net arch change, or arch specific optimizations, will be noticed by the chi-square test... not all machines are equal.

**Comment by vdbergh** [comment]
@vondele I agree. However for some reason the issue seems to have become less pressing again. I looked at the last 10 tests or so and the p-values were reasonable. Also for this net change https://tests.stockfishchess.org/tests/view/612ce5b9bb4956d8b78eb5b3. 

Maybe this is just SSS. 

In principle this is testable (if everything is ok then the p-values should be uniformly distributed).

@ppigazzini I do not know if the new way of computing chi2 has anything to do with this. In principle the previous chi2 test was correct for a perfectly balanced book. Of course the noob book wasn't really perfectly balanced but it came close to it. It could also be that the new chi2 test has a bit less power to detect deviations from the null hypothesis since the sample size is only half as big as we are tabulating game pairs instead of games (this is a basic statistical question and I am confused by it).

**Comment by ppigazzini** [comment]
I'm wondering why the TC adjustment according to the bench nps should fail with NNUE (with the hypothesis of positions scored the same by different ARCHs).

In these tests
https://tests.stockfishchess.org/tests/view/5f01a78059f6f0353289439b
https://dfts-0.pigazzini.it/tests/view/5f01a78059f6f0353289439b

many noob workers (that share the same 2 HW configurations) have red/yellow residuals but the p-value is still acceptable (and it's way better with the chi2 pentanomial based).
IIRC once fixed a `p-value-threshold`, exactly `p-value-threshold` normal tests will fail the chi2 test.

**Comment by vdbergh** [comment]
In principle one should only look at the p-value. Only if it is below a certain threshold should one look at residuals. 

This being said, I also have the feeling that there are "too many" residuals > 3, but I have never tried to quantify this.

I had a look at the tests with the noob book and for those the p-value seems to be generally very low. So maybe the new book is just much less sensitive to hardware differences? I guess that's a good thing. 

Note that all this is very unscientific right now.

**Comment by vondele** [comment]
I doubt the book can hide the hardware differences... at least that would be surprising to me.

**Comment by ppigazzini** [comment]
I'm missing:
- the HW difference in that test. noob fleet biased the test (2002 on 2463 total batches), it has only 2 HW configurations (1106 and 896 batches for 8 and 16 threads configurations), and it has a high standard deviation for residual values (with 54 on 88 total red, 130 on 195 total yellow)
- why the bench nps should be a bad figure to adjust HW difference after the switch to NNUE

---

The noob/mlang worker could be a vm/container with 8/16 virtual threads potentially running on a multi CPU server. In that case the total CPU load could be a bit random during the bench of one instance, adding noise to the bench nps.

Here you find my old measurement of nps bench noise for an AWS c4.8xlarge instance (Intel Xeon E5-2666 v3, 18 cores 36 threads) with respect to my desktop CPU:
https://groups.google.com/g/fishcooking/c/2gswm_us0bs/m/IR1hTILSCwAJ

**Comment by vondele** [comment]
I think noob's machines are VMs/containers on a larger node. 

The bench nps can only measure one of the two (base / test) and so the rescaling for nps (which adjusts for the CPU) can make the machines look very similar for the base net architecture, but if the net architecture changes, the machine dependence of that change can not be captures. E.g. new change is effectively an optimization for, say, VNNI (or those machines with large L2 cache) the outcome of the test will be quite different for the different machines, even though base nps has been rescaled.

**Comment by ppigazzini** [comment]
This is valid argument but only for a test about a change of net architecture, if I'm not wrong this type of test is very rare. IMO the optimization for a specific HW instruction should be tested only for speedup. All other tests should work fine with the TC normalization based on base nps.

@noobpwnftw could be so nice to provide some information about the HW that runs the fleet :)

**Comment by vdbergh** [comment]
The distinction between the UHO and the noob book seems to be more systemic. E.g. for the ongoing time odds tests we have p=0.62% for the noob book and p=57.77% for the UHO book. There are no noob machines participating. 

It is not obvious to me what the explanation could be.

**Comment by vondele** [comment]
I don't know exactly what our test measures, but could it be that with noob's book 'all tests are draw' (so all machines are roughly the same), while the UHO book naturally shows large variation in test outcome?

**Comment by ppigazzini** [comment]
Perhaps the NNUE bias on chi2 test is to have increased the % of draws.

**Comment by vdbergh** [comment]
The last RT also has a very low p-value. It seems to be correlated with the draw ratio. I looked at old pre NNUE tests (draw ratio 75%) and there the p values seemed to be fine.

@vondele About what is actually tested: internally a table is made with the rows being the participating workers and the columns giving the frequencies of WW+WD, WL+DD, LL+LD (so 3 columns). Then a chi2 test is done for this table (see the section “Example chi-squared test for categorical data” in https://en.wikipedia.org/wiki/Chi-squared_test ).

Perhaps when the middle column of this table is “fatter” (higher draw ratio) the test becomes more sensitive to deviations from the null hypothesis…. ? I could do some simulations.

**Comment by vondele** [comment]
> Perhaps when the middle column of this table is “fatter” (higher draw ratio) the test becomes more sensitive to deviations from the null hypothesis…. ? I could do some simulations.

yes, something along these lines is what I was suggesting. The same 'different worker' might have quite different p-values depending on how this difference is actually measured.
